import EvmAsm.Codegen.Dispatch
import EvmAsm.Codegen.Programs.Account
import EvmAsm.Codegen.Programs.AccountApplyStorage
import EvmAsm.Codegen.Programs.AccountBalance
import EvmAsm.Codegen.Programs.AccountFieldExtract
import EvmAsm.Codegen.Programs.AccountFieldGetters
import EvmAsm.Codegen.Programs.AccountFields
import EvmAsm.Codegen.Programs.Address
import EvmAsm.Codegen.Programs.AssembleExecutionRequests
import EvmAsm.Codegen.Programs.BalAccountAccessDescriptors
import EvmAsm.Codegen.Programs.BalAccountApplyPostFields
import EvmAsm.Codegen.Programs.BalAccountChangeDescriptor
import EvmAsm.Codegen.Programs.BalAccountChangeValue
import EvmAsm.Codegen.Programs.BalAccountCodeConsistent
import EvmAsm.Codegen.Programs.BalAccountHasStateChange
import EvmAsm.Codegen.Programs.BalAccountNonstorageFinals
import EvmAsm.Codegen.Programs.BalAccountPath
import EvmAsm.Codegen.Programs.BalAccountPostFields
import EvmAsm.Codegen.Programs.BalAccountRecordArray
import EvmAsm.Codegen.Programs.BalAllAccountsCode
import EvmAsm.Codegen.Programs.BalAllAccountsCodeCovers
import EvmAsm.Codegen.Programs.BalCanonicalSort
import EvmAsm.Codegen.Programs.BalGasValid
import EvmAsm.Codegen.Programs.BalModeledSystem
import EvmAsm.Codegen.Programs.BalStorageAccessDescriptors
import EvmAsm.Codegen.Programs.BalStorageReadsExecLog
import EvmAsm.Codegen.Programs.Blake2f
import EvmAsm.Codegen.Programs.BlockAccessListHash
import EvmAsm.Codegen.Programs.BlockGasRemaining
import EvmAsm.Codegen.Programs.BlockHashPredicates
import EvmAsm.Codegen.Programs.BlockHeaderSszToRlp
import EvmAsm.Codegen.Programs.BlockRlpSize
import EvmAsm.Codegen.Programs.BlockVerdictBalFindAccount
import EvmAsm.Codegen.Programs.BlockVerdictGasGate
import EvmAsm.Codegen.Programs.BlockVerdictGasResultArena
import EvmAsm.Codegen.Programs.BlockVerdictModeledSystem
import EvmAsm.Codegen.Programs.BlockVerdictSenderCounts
import EvmAsm.Codegen.Programs.BlockVerdictSimpleTransfer
import EvmAsm.Codegen.Programs.BlockVerdictTxGasLimits
import EvmAsm.Codegen.Programs.Bloom
import EvmAsm.Codegen.Programs.BloomAddValue
import EvmAsm.Codegen.Programs.BloomBlock
import EvmAsm.Codegen.Programs.Bls12Field
import EvmAsm.Codegen.Programs.Bls12Fq12
import EvmAsm.Codegen.Programs.Bls12G1
import EvmAsm.Codegen.Programs.Bls12G2
import EvmAsm.Codegen.Programs.Bls12Kzg
import EvmAsm.Codegen.Programs.Bls12Map
import EvmAsm.Codegen.Programs.Bls12Pairing
import EvmAsm.Codegen.Programs.Bn254Curve
import EvmAsm.Codegen.Programs.Bn254Field
import EvmAsm.Codegen.Programs.Bn254Fp2
import EvmAsm.Codegen.Programs.Bn254Fq12
import EvmAsm.Codegen.Programs.Bn254Pairing
import EvmAsm.Codegen.Programs.CallFrameBase
import EvmAsm.Codegen.Programs.CallFrameDescend
import EvmAsm.Codegen.Programs.CallFrameSwitch
import EvmAsm.Codegen.Programs.ChainValidate
import EvmAsm.Codegen.Programs.ChainValidateBlob
import EvmAsm.Codegen.Programs.ChainValidatePostMerge
import EvmAsm.Codegen.Programs.ChainValidateProgs
import EvmAsm.Codegen.Programs.CreateCodeEffectLog
import EvmAsm.Codegen.Programs.DispatcherExecStateGas
import EvmAsm.Codegen.Programs.DynamicOpcodeGas
import EvmAsm.Codegen.Programs.Eip7702Authority
import EvmAsm.Codegen.Programs.Eip7702NonceReuseGuard
import EvmAsm.Codegen.Programs.EvmCodes
import EvmAsm.Codegen.Programs.EvmMessageCallGas
import EvmAsm.Codegen.Programs.EvmNonce
import EvmAsm.Codegen.Programs.EvmOpcodes
import EvmAsm.Codegen.Programs.EvmOpcodesExtcodecopy
import EvmAsm.Codegen.Programs.ExecLogLatestValue
import EvmAsm.Codegen.Programs.HashBridge
import EvmAsm.Codegen.Programs.Header
import EvmAsm.Codegen.Programs.HeaderBaseFee
import EvmAsm.Codegen.Programs.HeaderChain
import EvmAsm.Codegen.Programs.HeaderDecode
import EvmAsm.Codegen.Programs.HeaderFields
import EvmAsm.Codegen.Programs.HeaderU64
import EvmAsm.Codegen.Programs.HeadersKeccak
import EvmAsm.Codegen.Programs.IntrinsicGas
import EvmAsm.Codegen.Programs.MemoryExpansionGas
import EvmAsm.Codegen.Programs.Mpt
import EvmAsm.Codegen.Programs.MptDeleteAcc
import EvmAsm.Codegen.Programs.MptDeleteWalkDb
import EvmAsm.Codegen.Programs.MptEncode
import EvmAsm.Codegen.Programs.MptIndexedTrieRoot
import EvmAsm.Codegen.Programs.MptInsertAcc
import EvmAsm.Codegen.Programs.MptInsertWalkDb
import EvmAsm.Codegen.Programs.MptInternal
import EvmAsm.Codegen.Programs.MptNibbles
import EvmAsm.Codegen.Programs.MptSet
import EvmAsm.Codegen.Programs.MptSetAcc
import EvmAsm.Codegen.Programs.MptStateRootIns
import EvmAsm.Codegen.Programs.NonstorageEffectLog
import EvmAsm.Codegen.Programs.P256Verify
import EvmAsm.Codegen.Programs.Receipt
import EvmAsm.Codegen.Programs.ReceiptsRootIndexed
import EvmAsm.Codegen.Programs.RequestsHash
import EvmAsm.Codegen.Programs.RlpRead
import EvmAsm.Codegen.Programs.RuntimeSameBlockCode
import EvmAsm.Codegen.Programs.Secp256k1Curve
import EvmAsm.Codegen.Programs.Secp256k1Field
import EvmAsm.Codegen.Programs.Secp256k1Recover
import EvmAsm.Codegen.Programs.SeedTxAccessList
import EvmAsm.Codegen.Programs.SenderPostNonceConsistent
import EvmAsm.Codegen.Programs.Ssz
import EvmAsm.Codegen.Programs.SszParentHeader
import EvmAsm.Codegen.Programs.SszPayloadWithdrawals
import EvmAsm.Codegen.Programs.SszWithdrawal
import EvmAsm.Codegen.Programs.SszWitnessState
import EvmAsm.Codegen.Programs.State
import EvmAsm.Codegen.Programs.StateCompose
import EvmAsm.Codegen.Programs.StatePredicates
import EvmAsm.Codegen.Programs.StatelessVerdict
import EvmAsm.Codegen.Programs.Step2Verdict
import EvmAsm.Codegen.Programs.StorageWrite
import EvmAsm.Codegen.Programs.SystemCallStaging
import EvmAsm.Codegen.Programs.Tx
import EvmAsm.Codegen.Programs.TxBlobGas
import EvmAsm.Codegen.Programs.TxDecode1559
import EvmAsm.Codegen.Programs.TxDecode2930
import EvmAsm.Codegen.Programs.TxDecode4844
import EvmAsm.Codegen.Programs.TxDecode7702
import EvmAsm.Codegen.Programs.TxExtract
import EvmAsm.Codegen.Programs.TxGasSenderBalLookup
import EvmAsm.Codegen.Programs.TxIntrinsicStateGasProg
import EvmAsm.Codegen.Programs.TxPubkey
import EvmAsm.Codegen.Programs.TxRefund
import EvmAsm.Codegen.Programs.TxRoot
import EvmAsm.Codegen.Programs.TxSigningHash
import EvmAsm.Codegen.Programs.U256
import EvmAsm.Codegen.Programs.U256GasPricing
import EvmAsm.Codegen.Programs.ValidateHeaderPair
import EvmAsm.Codegen.Programs.VerifyPublicKeysSenders
import EvmAsm.Codegen.Programs.Withdrawal
import EvmAsm.Codegen.Programs.WithdrawalPath
import EvmAsm.Codegen.Programs.WithdrawalsRootIndexed
import EvmAsm.Codegen.Programs.WithdrawalsStateRoot
import EvmAsm.Codegen.Programs.WitnessValidation
open EvmAsm.Codegen
def _renderItems : List (String × String) :=
  [ ("accessListCountFunction", accessListCountFunction),
    ("accountAddBalanceFunction", accountAddBalanceFunction),
    ("accountApplyStorageSlotAccFunction", accountApplyStorageSlotAccFunction),
    ("accountApplyStorageSlotFunction", accountApplyStorageSlotFunction),
    ("accountAtAddressFunction", accountAtAddressFunction),
    ("accountAtHeaderStateRootFunction", accountAtHeaderStateRootFunction),
    ("accountChargeGasPreExecFunction", accountChargeGasPreExecFunction),
    ("accountDecodeFunction", accountDecodeFunction),
    ("accountExistsAtHeaderStateRootFunction", accountExistsAtHeaderStateRootFunction),
    ("accountExtractBalanceFunction", accountExtractBalanceFunction),
    ("accountExtractNonceFunction", accountExtractNonceFunction),
    ("accountIsEip161EmptyFunction", accountIsEip161EmptyFunction),
    ("accountIsEmptyAtHeaderStateRootFunction", accountIsEmptyAtHeaderStateRootFunction),
    ("accountSetStorageRootFunction", accountSetStorageRootFunction),
    ("accountSetUintFieldFunction", accountSetUintFieldFunction),
    ("addressComputeCreate2Function", addressComputeCreate2Function),
    ("addressComputeCreateFunction", addressComputeCreateFunction),
    ("addressFromPubkeyFunction", addressFromPubkeyFunction),
    ("amsterdamBlobGasPriceU256Function", amsterdamBlobGasPriceU256Function),
    ("b1SenderTableFindFunction", b1SenderTableFindFunction),
    ("baapDeleteSingleLeafStorageFunction", baapDeleteSingleLeafStorageFunction),
    ("bahU32leFunction", bahU32leFunction),
    ("balAccountAccessOutcomeDescriptorsFunction", balAccountAccessOutcomeDescriptorsFunction),
    ("balAccountChangeDescriptorFunction", balAccountChangeDescriptorFunction),
    ("balAccountCodeConsistentFunction", balAccountCodeConsistentFunction),
    ("balAccountHasStateChangeFunction", balAccountHasStateChangeFunction),
    ("balAccountIsModeledSystemFunction", balAccountIsModeledSystemFunction),
    ("balAccountNonstorageFinalsFunction", balAccountNonstorageFinalsFunction),
    ("balAccountPathFunction", balAccountPathFunction),
    ("balAccountPostFieldsFunction", balAccountPostFieldsFunction),
    ("balAccountRecordArrayFunction", balAccountRecordArrayFunction),
    ("balAllAccountsCodeConsistentFunction", balAllAccountsCodeConsistentFunction),
    ("balAllAccountsCodeCoversFunction", balAllAccountsCodeCoversFunction),
    ("balCanonicalSortFunction", balCanonicalSortFunction),
    ("balCanonicalSortSelftestFunction", balCanonicalSortSelftestFunction),
    ("balFindAccountByAddressFunction", balFindAccountByAddressFunction),
    ("balGasValidFunction", balGasValidFunction),
    ("balSectionInfoFunction", balSectionInfoFunction),
    ("balStorageAccessOutcomeDescriptorsFunction", balStorageAccessOutcomeDescriptorsFunction),
    ("balStorageReadsInExecLogFunction", balStorageReadsInExecLogFunction),
    ("bgvU32leFunction", bgvU32leFunction),
    ("bgvU64leFunction", bgvU64leFunction),
    ("bhrRevLeBeFunction", bhrRevLeBeFunction),
    ("blake2fLdLe64Function", blake2fLdLe64Function),
    ("blake2fStLe64Function", blake2fStLe64Function),
    ("blockAccessListHashCoreFunction", blockAccessListHashCoreFunction),
    ("blockAccessListHashFunction", blockAccessListHashFunction),
    ("blockHashFromHeaderFunction", blockHashFromHeaderFunction),
    ("blockLogsBloomFromReceiptsListFunction", blockLogsBloomFromReceiptsListFunction),
    ("blockRlpRebuiltSizeFunction", blockRlpRebuiltSizeFunction),
    ("blockValidateLogsBloomFunction", blockValidateLogsBloomFunction),
    ("blockValidateReceiptsRootIndexedFunction", blockValidateReceiptsRootIndexedFunction),
    ("blockValidateWithdrawalsRootIndexedFunction", blockValidateWithdrawalsRootIndexedFunction),
    ("blockVerdictChainIdGateFunction", blockVerdictChainIdGateFunction),
    ("blockVerdictEip8037TxStateGasNetArrayFunction", blockVerdictEip8037TxStateGasNetArrayFunction),
    ("blockVerdictGasResultArenaPrepareFunction", blockVerdictGasResultArenaPrepareFunction),
    ("blockVerdictTxGasLimitsFunction", blockVerdictTxGasLimitsFunction),
    ("blockhashFromWitnessHeadersFunction", blockhashFromWitnessHeadersFunction),
    ("bloomAddValueFunction", bloomAddValueFunction),
    ("bloomEqFunction", bloomEqFunction),
    ("bloomOrIntoFunction", bloomOrIntoFunction),
    ("bls12CopyQuadsFunction", bls12CopyQuadsFunction),
    ("bls12Fq12CopyFunction", bls12Fq12CopyFunction),
    ("bls12Fq12EqFunction", bls12Fq12EqFunction),
    ("bls12Fq12IsZeroFunction", bls12Fq12IsZeroFunction),
    ("bls12Fq12PowFunction", bls12Fq12PowFunction),
    ("bls12Fq12SMulFunction", bls12Fq12SMulFunction),
    ("bls12Fq12SetOneFunction", bls12Fq12SetOneFunction),
    ("bls12Fq12ZeroFunction", bls12Fq12ZeroFunction),
    ("bls12G1AddModPFunction", bls12G1AddModPFunction),
    ("bls12G1BeToLeFunction", bls12G1BeToLeFunction),
    ("bls12G1Copy96Function", bls12G1Copy96Function),
    ("bls12G1Eq48Function", bls12G1Eq48Function),
    ("bls12G1IsZeroFunction", bls12G1IsZeroFunction),
    ("bls12G1LeAddFunction", bls12G1LeAddFunction),
    ("bls12G1LeDblFunction", bls12G1LeDblFunction),
    ("bls12G1LeToBeFunction", bls12G1LeToBeFunction),
    ("bls12G1LtPFunction", bls12G1LtPFunction),
    ("bls12G1MulModPFunction", bls12G1MulModPFunction),
    ("bls12G1OnCurveFunction", bls12G1OnCurveFunction),
    ("bls12G1PointAddFunction", bls12G1PointAddFunction),
    ("bls12G1PointDblFunction", bls12G1PointDblFunction),
    ("bls12G1SubgroupFunction", bls12G1SubgroupFunction),
    ("bls12G1Zero96Function", bls12G1Zero96Function),
    ("bls12G2ChordTailFunction", bls12G2ChordTailFunction),
    ("bls12G2Copy192Function", bls12G2Copy192Function),
    ("bls12G2EncodeFunction", bls12G2EncodeFunction),
    ("bls12G2EqNFunction", bls12G2EqNFunction),
    ("bls12G2Fp2AddFunction", bls12G2Fp2AddFunction),
    ("bls12G2Fp2InvFunction", bls12G2Fp2InvFunction),
    ("bls12G2Fp2MulFunction", bls12G2Fp2MulFunction),
    ("bls12G2Fp2SubFunction", bls12G2Fp2SubFunction),
    ("bls12G2FpAddLeFunction", bls12G2FpAddLeFunction),
    ("bls12G2FpInvFunction", bls12G2FpInvFunction),
    ("bls12G2FpMulLeFunction", bls12G2FpMulLeFunction),
    ("bls12G2ScalarMulFunction", bls12G2ScalarMulFunction),
    ("bls12G2SubgroupFunction", bls12G2SubgroupFunction),
    ("bls12G2Zero192Function", bls12G2Zero192Function),
    ("bls12KzgFpPowQ14Function", bls12KzgFpPowQ14Function),
    ("bls12KzgG1WireFunction", bls12KzgG1WireFunction),
    ("bls12KzgG2WireFunction", bls12KzgG2WireFunction),
    ("bls12KzgLtBeFunction", bls12KzgLtBeFunction),
    ("bls12KzgNegScalarFunction", bls12KzgNegScalarFunction),
    ("bls12MapFp2PowFunction", bls12MapFp2PowFunction),
    ("bls12MapFpPowFunction", bls12MapFpPowFunction),
    ("bls12PtCopyFunction", bls12PtCopyFunction),
    ("bn254CallAllotmentFunction", bn254CallAllotmentFunction),
    ("bn254FieldAddFunction", bn254FieldAddFunction),
    ("bn254FieldBeToLeFunction", bn254FieldBeToLeFunction),
    ("bn254FieldEq32Function", bn254FieldEq32Function),
    ("bn254FieldIsZeroFunction", bn254FieldIsZeroFunction),
    ("bn254FieldLeToBeFunction", bn254FieldLeToBeFunction),
    ("bn254FieldLtPFunction", bn254FieldLtPFunction),
    ("bn254FieldMulFunction", bn254FieldMulFunction),
    ("bn254Fp2AddFunction", bn254Fp2AddFunction),
    ("bn254Fp2CopyFunction", bn254Fp2CopyFunction),
    ("bn254Fp2EqFunction", bn254Fp2EqFunction),
    ("bn254Fp2InvFunction", bn254Fp2InvFunction),
    ("bn254Fp2IsZeroFunction", bn254Fp2IsZeroFunction),
    ("bn254Fp2MulFunction", bn254Fp2MulFunction),
    ("bn254Fp2SubFunction", bn254Fp2SubFunction),
    ("bn254Fp2ZeroFunction", bn254Fp2ZeroFunction),
    ("bn254FpAddLeFunction", bn254FpAddLeFunction),
    ("bn254FpMulLeFunction", bn254FpMulLeFunction),
    ("bn254FpPowLeFunction", bn254FpPowLeFunction),
    ("bn254Fq12CopyFunction", bn254Fq12CopyFunction),
    ("bn254Fq12EqFunction", bn254Fq12EqFunction),
    ("bn254Fq12IsZeroFunction", bn254Fq12IsZeroFunction),
    ("bn254Fq12PowFunction", bn254Fq12PowFunction),
    ("bn254Fq12SMulFunction", bn254Fq12SMulFunction),
    ("bn254Fq12SetOneFunction", bn254Fq12SetOneFunction),
    ("bn254Fq12ZeroFunction", bn254Fq12ZeroFunction),
    ("bn254OnCurveFunction", bn254OnCurveFunction),
    ("bn254PointAddFunction", bn254PointAddFunction),
    ("bn254PointCopy64Function", bn254PointCopy64Function),
    ("bn254PointDblFunction", bn254PointDblFunction),
    ("bn254PointIsInfFunction", bn254PointIsInfFunction),
    ("bn254PointZero64Function", bn254PointZero64Function),
    ("bn254PtCopyFunction", bn254PtCopyFunction),
    ("bn254ScalarMulFunction", bn254ScalarMulFunction),
    ("bn254ValidateG1Function", bn254ValidateG1Function),
    ("bsrApplyModeledSystemPostFieldsFunction", bsrApplyModeledSystemPostFieldsFunction),
    ("bvSumWithdrawalsToAddressFunction", bvSumWithdrawalsToAddressFunction),
    ("bytesToNibblesFunction", bytesToNibblesFunction),
    ("calcExcessBlobGasFunction", calcExcessBlobGasFunction),
    ("callFrameSetCalldataFunction", callFrameSetCalldataFunction),
    ("calldataByteCountsFunction", calldataByteCountsFunction),
    ("chainValidateBlobGasUsedMultipleFunction", chainValidateBlobGasUsedMultipleFunction),
    ("chainValidateBlobGasUsedUnderMaxFunction", chainValidateBlobGasUsedUnderMaxFunction),
    ("chainValidateConsecutiveNumbersFunction", chainValidateConsecutiveNumbersFunction),
    ("chainValidateExtraDataLengthFunction", chainValidateExtraDataLengthFunction),
    ("chainValidateGasUsedUnderLimitFunction", chainValidateGasUsedUnderLimitFunction),
    ("chainValidateIncreasingTimestampsFunction", chainValidateIncreasingTimestampsFunction),
    ("chainValidatePostMergeFullFunction", chainValidatePostMergeFullFunction),
    ("checkGasLimitFunction", checkGasLimitFunction),
    ("codeAtHeaderStateRootFunction", codeAtHeaderStateRootFunction),
    ("codeHashAtHeaderStateRootFunction", codeHashAtHeaderStateRootFunction),
    ("copyWordGasFunction", copyWordGasFunction),
    ("createExecuteInitcodeFrameRuntimeFunction", createExecuteInitcodeFrameRuntimeFunction),
    ("createStageInitcodeFrameRuntimeFunction", createStageInitcodeFrameRuntimeFunction),
    ("deriveChainIdFromVFunction", deriveChainIdFromVFunction),
    ("deriveConsolidationRequestsFunction", deriveConsolidationRequestsFunction),
    ("deriveWithdrawalRequestsFunction", deriveWithdrawalRequestsFunction),
    ("dispatcherCaptureExecStateGasFunction", dispatcherCaptureExecStateGasFunction),
    ("dispatcherTxGasSettleFunction", dispatcherTxGasSettleFunction),
    ("eip1559CalcBaseFeePerGasFunction", eip1559CalcBaseFeePerGasFunction),
    ("eip7702AuthorizationRecoverAddressFunction", eip7702AuthorizationRecoverAddressFunction),
    ("eip7702AuthorizationSigningHashFunction", eip7702AuthorizationSigningHashFunction),
    ("eip7778RemainingBlockGasFromResultsFunction", eip7778RemainingBlockGasFromResultsFunction),
    ("eip8037BlockGasUsedFunction", eip8037BlockGasUsedFunction),
    ("eip8037PriorStateUsedExactFunction", eip8037PriorStateUsedExactFunction),
    ("eip8037ReservoirSplitFunction", eip8037ReservoirSplitFunction),
    ("eip8037TxGasGateFunction", eip8037TxGasGateFunction),
    ("enrgU32leFunction", enrgU32leFunction),
    ("ephU32leFunction", ephU32leFunction),
    ("erhHashOneFunction", erhHashOneFunction),
    ("execLogLatestValueFunction", execLogLatestValueFunction),
    ("executionRequestsHashFunction", executionRequestsHashFunction),
    ("expGasFunction", expGasFunction),
    ("extcodecopyAtHeaderStateRootFunction", extcodecopyAtHeaderStateRootFunction),
    ("extcodehashAtHeaderStateRootFunction", extcodehashAtHeaderStateRootFunction),
    ("extcodesizeAtHeaderStateRootFunction", extcodesizeAtHeaderStateRootFunction),
    ("extractParentHeaderAndStateRootFunction", extractParentHeaderAndStateRootFunction),
    ("extractPayloadAndWithdrawalsFunction", extractPayloadAndWithdrawalsFunction),
    ("extractWitnessStateSectionFunction", extractWitnessStateSectionFunction),
    ("findCodeEffectByAddressFunction", findCodeEffectByAddressFunction),
    ("frameBaseFunction", frameBaseFunction),
    ("frameDepthPopFunction", frameDepthPopFunction),
    ("frameDepthPushFunction", frameDepthPushFunction),
    ("frameLoadRegsFunction", frameLoadRegsFunction),
    ("frameSaveRegsFunction", frameSaveRegsFunction),
    ("hasCodeOrNonceAtHeaderStateRootFunction", hasCodeOrNonceAtHeaderStateRootFunction),
    ("headerExtendedDecodeFunction", headerExtendedDecodeFunction),
    ("headerExtractLogsBloomFunction", headerExtractLogsBloomFunction),
    ("headerExtractNumberFunction", headerExtractNumberFunction),
    ("headerExtractReceiptsRootFunction", headerExtractReceiptsRootFunction),
    ("headerExtractStateRootFunction", headerExtractStateRootFunction),
    ("headerExtractWithdrawalsRootFunction", headerExtractWithdrawalsRootFunction),
    ("headerValidateBaseFeeFunction", headerValidateBaseFeeFunction),
    ("headerValidateExcessBlobGasFunction", headerValidateExcessBlobGasFunction),
    ("headerValidateExtraDataLengthFunction", headerValidateExtraDataLengthFunction),
    ("headerValidateParentHashFunction", headerValidateParentHashFunction),
    ("headerValidatePostMergeFunction", headerValidatePostMergeFunction),
    ("headersKeccakArrayFunction", headersKeccakArrayFunction),
    ("headersParentHashFunction", headersParentHashFunction),
    ("headersValidateChainFunction", headersValidateChainFunction),
    ("hpDecodeNibblesFunction", hpDecodeNibblesFunction),
    ("hpEncodeNibblesFunction", hpEncodeNibblesFunction),
    ("initCodeCostFunction", initCodeCostFunction),
    ("intrinsicGasAmsterdamCountsFunction", intrinsicGasAmsterdamCountsFunction),
    ("intrinsicGasCalldataFloorEip7623Function", intrinsicGasCalldataFloorEip7623Function),
    ("intrinsicGasLegacyFunction", intrinsicGasLegacyFunction),
    ("keccak256WordGasFunction", keccak256WordGasFunction),
    ("logBloomAddFunction", logBloomAddFunction),
    ("logDataGasFunction", logDataGasFunction),
    ("logsListBloomAddFunction", logsListBloomAddFunction),
    ("mapAccountChangeValueFunction", mapAccountChangeValueFunction),
    ("memoryExpansionGasFunction", memoryExpansionGasFunction),
    ("messageCallGasFunction", messageCallGasFunction),
    ("mptBranchChildFunction", mptBranchChildFunction),
    ("mptBranchPayloadTwoSlotsFunction", mptBranchPayloadTwoSlotsFunction),
    ("mptCompactToNibblesFunction", mptCompactToNibblesFunction),
    ("mptDeleteAccFunction", mptDeleteAccFunction),
    ("mptDeleteWalkDbFunction", mptDeleteWalkDbFunction),
    ("mptExtensionExtractFunction", mptExtensionExtractFunction),
    ("mptExtensionNodeEncodeFunction", mptExtensionNodeEncodeFunction),
    ("mptIndexedLargeLeafHashFunction", mptIndexedLargeLeafHashFunction),
    ("mptIndexedTrieRootLargeFunction", mptIndexedTrieRootLargeFunction),
    ("mptIndexedTrieRootSmallFunction", mptIndexedTrieRootSmallFunction),
    ("mptInsertAccFunction", mptInsertAccFunction),
    ("mptInsertWalkDbFunction", mptInsertWalkDbFunction),
    ("mptLeafExtractFunction", mptLeafExtractFunction),
    ("mptLookupByKeyFunction", mptLookupByKeyFunction),
    ("mptNibblesToCompactFunction", mptNibblesToCompactFunction),
    ("mptNodeKindFunction", mptNodeKindFunction),
    ("mptNodeResolveFunction", mptNodeResolveFunction),
    ("mptNodeSlotEncodeFunction", mptNodeSlotEncodeFunction),
    ("mptOneLeafRootIndexedFunction", mptOneLeafRootIndexedFunction),
    ("mptResolveCacheResetFunction", mptResolveCacheResetFunction),
    ("mptSetAccFunction", mptSetAccFunction),
    ("mptSetRecordWalkDbFunction", mptSetRecordWalkDbFunction),
    ("mptSpliceSlotFunction", mptSpliceSlotFunction),
    ("mptStateRootFunction", mptStateRootFunction),
    ("mptStateRootInsFunction", mptStateRootInsFunction),
    ("mptWalkFunction", mptWalkFunction),
    ("msetMemcpyFunction", msetMemcpyFunction),
    ("nibblesCommonPrefixLenFunction", nibblesCommonPrefixLenFunction),
    ("nodeDbAppendFunction", nodeDbAppendFunction),
    ("nodeDbLookupFunction", nodeDbLookupFunction),
    ("nonceAtHeaderStateRootFunction", nonceAtHeaderStateRootFunction),
    ("nonstorageEffectLatestBalanceFunction", nonstorageEffectLatestBalanceFunction),
    ("p256BeToLeFunction", p256BeToLeFunction),
    ("p256ChordTailFunction", p256ChordTailFunction),
    ("p256CopyNFunction", p256CopyNFunction),
    ("p256Eq32Function", p256Eq32Function),
    ("p256IsZeroNFunction", p256IsZeroNFunction),
    ("p256LeToBeFunction", p256LeToBeFunction),
    ("p256LtBeFunction", p256LtBeFunction),
    ("p256OpWithFunction", p256OpWithFunction),
    ("p256PointAddFunction", p256PointAddFunction),
    ("p256PointDblFunction", p256PointDblFunction),
    ("p256PowFunction", p256PowFunction),
    ("p256ScalarMulFunction", p256ScalarMulFunction),
    ("parentHeaderMatchesWitnessFirstFunction", parentHeaderMatchesWitnessFirstFunction),
    ("priorityFeePerGasEip1559Function", priorityFeePerGasEip1559Function),
    ("receiptEncodeFunction", receiptEncodeFunction),
    ("receiptExtractLogsBloomFunction", receiptExtractLogsBloomFunction),
    ("requestsHashVerifyFunction", requestsHashVerifyFunction),
    ("rlpBytesEncodedSizeFunction", rlpBytesEncodedSizeFunction),
    ("rlpEncodeBytesFunction", rlpEncodeBytesFunction),
    ("rlpEncodeListPrefixFunction", rlpEncodeListPrefixFunction),
    ("rlpEncodeU64Function", rlpEncodeU64Function),
    ("rlpEncodeUintBeFunction", rlpEncodeUintBeFunction),
    ("rlpFieldToU256BeFunction", rlpFieldToU256BeFunction),
    ("rlpFieldToU64Function", rlpFieldToU64Function),
    ("rlpListCountItemsFunction", rlpListCountItemsFunction),
    ("rlpListEncodedSizeFunction", rlpListEncodedSizeFunction),
    ("rlpListNthItemFunction", rlpListNthItemFunction),
    ("rlpListTruncateToNFieldsFunction", rlpListTruncateToNFieldsFunction),
    ("runningBloomCopyFunction", runningBloomCopyFunction),
    ("runningBloomZeroFunction", runningBloomZeroFunction),
    ("runtimeSameBlockDelegationCodeFunction", runtimeSameBlockDelegationCodeFunction),
    ("secp256k1FieldAddFunction", secp256k1FieldAddFunction),
    ("secp256k1FieldBeToLeFunction", secp256k1FieldBeToLeFunction),
    ("secp256k1FieldCmpPFunction", secp256k1FieldCmpPFunction),
    ("secp256k1FieldCopy32Function", secp256k1FieldCopy32Function),
    ("secp256k1FieldEq32Function", secp256k1FieldEq32Function),
    ("secp256k1FieldGetBitFunction", secp256k1FieldGetBitFunction),
    ("secp256k1FieldInvFunction", secp256k1FieldInvFunction),
    ("secp256k1FieldIsZeroFunction", secp256k1FieldIsZeroFunction),
    ("secp256k1FieldLeToBeFunction", secp256k1FieldLeToBeFunction),
    ("secp256k1FieldMulFunction", secp256k1FieldMulFunction),
    ("secp256k1FieldPowFunction", secp256k1FieldPowFunction),
    ("secp256k1FieldReduceOnceFunction", secp256k1FieldReduceOnceFunction),
    ("secp256k1FieldSqrtFunction", secp256k1FieldSqrtFunction),
    ("secp256k1FieldSquareFunction", secp256k1FieldSquareFunction),
    ("secp256k1FieldSubFunction", secp256k1FieldSubFunction),
    ("secp256k1FieldZero32Function", secp256k1FieldZero32Function),
    ("secp256k1PointCopy64Function", secp256k1PointCopy64Function),
    ("secp256k1PointDoubleFunction", secp256k1PointDoubleFunction),
    ("secp256k1PointZero64Function", secp256k1PointZero64Function),
    ("secp256k1RecoverPubkeyStagedFunction", secp256k1RecoverPubkeyStagedFunction),
    ("secp256k1RecoverRFunction", secp256k1RecoverRFunction),
    ("secp256k1ScalarFieldAddFunction", secp256k1ScalarFieldAddFunction),
    ("secp256k1ScalarFieldInvFunction", secp256k1ScalarFieldInvFunction),
    ("secp256k1ScalarFieldMulFunction", secp256k1ScalarFieldMulFunction),
    ("secp256k1ScalarFieldPowFunction", secp256k1ScalarFieldPowFunction),
    ("secp256k1ScalarFieldReduceOnceFunction", secp256k1ScalarFieldReduceOnceFunction),
    ("secp256k1ScalarFieldSquareFunction", secp256k1ScalarFieldSquareFunction),
    ("secp256k1ScalarMulFunction", secp256k1ScalarMulFunction),
    ("selfdestructBalanceTransferFunction", selfdestructBalanceTransferFunction),
    ("senderPostNonceConsistentFunction", senderPostNonceConsistentFunction),
    ("simpleTransferTxContextFunction", simpleTransferTxContextFunction),
    ("singleLeafTrieRootFunction", singleLeafTrieRootFunction),
    ("slotAtHeaderStateRootFunction", slotAtHeaderStateRootFunction),
    ("slotAtIndexFunction", slotAtIndexFunction),
    ("slotDecodeU256Function", slotDecodeU256Function),
    ("spwU32leFunction", spwU32leFunction),
    ("sszHashTreeRootBytesFunction", sszHashTreeRootBytesFunction),
    ("sszHashTreeRootListByteListFunction", sszHashTreeRootListByteListFunction),
    ("sszMerkleizeFunction", sszMerkleizeFunction),
    ("sszMerkleizePow2Function", sszMerkleizePow2Function),
    ("sszPackBytesFunction", sszPackBytesFunction),
    ("sszTxListVersionedHashesMatchFunction", sszTxListVersionedHashesMatchFunction),
    ("sszWithdrawalToRlpFunction", sszWithdrawalToRlpFunction),
    ("statelessVerdictFromSszFunction", statelessVerdictFromSszFunction),
    ("step2VerdictFunction", step2VerdictFunction),
    ("storageRootSingleSlotFunction", storageRootSingleSlotFunction),
    ("swrRevLeBeFunction", swrRevLeBeFunction),
    ("swsU32leFunction", swsU32leFunction),
    ("txAccessListSpanFunction", txAccessListSpanFunction),
    ("txEffectiveGasPricingFunction", txEffectiveGasPricingFunction),
    ("txEip1559DecodeFunction", txEip1559DecodeFunction),
    ("txEip2930DecodeFunction", txEip2930DecodeFunction),
    ("txEip4844DecodeFunction", txEip4844DecodeFunction),
    ("txEip4844ValidateBlobHashesFunction", txEip4844ValidateBlobHashesFunction),
    ("txEip7702DecodeFunction", txEip7702DecodeFunction),
    ("txGasResultIncrementsFunction", txGasResultIncrementsFunction),
    ("txGasSenderBalLookupFunction", txGasSenderBalLookupFunction),
    ("txIntrinsicStateGasFunction", txIntrinsicStateGasFunction),
    ("txPubkeyEcrecoverStageMaterialFunction", txPubkeyEcrecoverStageMaterialFunction),
    ("txPubkeyPublicKeyMatchesFunction", txPubkeyPublicKeyMatchesFunction),
    ("txPubkeyRecoverRawFunction", txPubkeyRecoverRawFunction),
    ("txPubkeySignatureMaterialFunction", txPubkeySignatureMaterialFunction),
    ("txRefundCapFunction", txRefundCapFunction),
    ("txSigningHashFunction", txSigningHashFunction),
    ("txSigningHashLegacyEip155Function", txSigningHashLegacyEip155Function),
    ("txTypeDispatchFunction", txTypeDispatchFunction),
    ("txUpfrontPrechargeFunction", txUpfrontPrechargeFunction),
    ("txValidateAgainstBlockFunction", txValidateAgainstBlockFunction),
    ("u256AddBeFunction", u256AddBeFunction),
    ("u256DivU64BeFunction", u256DivU64BeFunction),
    ("u256EqFunction", u256EqFunction),
    ("u256FromU64BeFunction", u256FromU64BeFunction),
    ("u256IsZeroFunction", u256IsZeroFunction),
    ("u256LtBeFunction", u256LtBeFunction),
    ("u256MaxFunction", u256MaxFunction),
    ("u256MinFunction", u256MinFunction),
    ("u256MulU64BeFunction", u256MulU64BeFunction),
    ("u256SubBeFunction", u256SubBeFunction),
    ("u256ToU64BeFunction", u256ToU64BeFunction),
    ("validateHeaderBasicFunction", validateHeaderBasicFunction),
    ("validateHeaderFullFunction", validateHeaderFullFunction),
    ("validateHeaderRlpPairFunction", validateHeaderRlpPairFunction),
    ("validateParentHashLinkFunction", validateParentHashLinkFunction),
    ("verifyPublicKeysMatchSendersFunction", verifyPublicKeysMatchSendersFunction),
    ("withdrawalDecodeFunction", withdrawalDecodeFunction),
    ("withdrawalToPathDeltaFunction", withdrawalToPathDeltaFunction),
    ("withdrawalsStateRootFunction", withdrawalsStateRootFunction),
    ("witnessCodesValidateLengthsFunction", witnessCodesValidateLengthsFunction),
    ("zkvmKeccak256Function", zkvmKeccak256Function),
    ("zkvmKeccak256SegmentsFunction", zkvmKeccak256SegmentsFunction),
    ("zkvmSha256Function", zkvmSha256Function),
    ("accessListCountFunction#c", emitProgram accessListCount_prog),
    ("accountAddBalanceFunction#c", emitProgram accountAddBalance_prog),
    ("accountApplyStorageSlotAccFunction#c", emitProgram accountApplyStorageSlotAcc_prog),
    ("accountApplyStorageSlotFunction#c", emitProgram accountApplyStorageSlot_prog),
    ("accountAtAddressFunction#c", emitProgram accountAtAddress_prog),
    ("accountAtHeaderStateRootFunction#c", emitProgram accountAtHeaderStateRoot_prog),
    ("accountChargeGasPreExecFunction#c", emitProgram accountChargeGasPreExec_prog),
    ("accountDecodeFunction#c", emitProgram accountDecode_prog),
    ("accountExistsAtHeaderStateRootFunction#c", emitProgram accountExistsAtHeaderStateRoot_prog),
    ("accountExtractBalanceFunction#c", emitProgram accountExtractBalance_prog),
    ("accountExtractNonceFunction#c", emitProgram accountExtractNonce_prog),
    ("accountIsEip161EmptyFunction#c", emitProgram accountIsEip161Empty_prog),
    ("accountIsEmptyAtHeaderStateRootFunction#c", emitProgram accountIsEmptyAtHeaderStateRoot_prog),
    ("accountSetStorageRootFunction#c", emitProgram accountSetStorageRoot_prog),
    ("accountSetUintFieldFunction#c", emitProgram accountSetUintField_prog),
    ("addressComputeCreate2Function#c", emitProgram addressComputeCreate2_prog),
    ("addressComputeCreateFunction#c", emitProgram addressComputeCreate_prog),
    ("addressFromPubkeyFunction#c", emitProgram addressFromPubkey_prog),
    ("amsterdamBlobGasPriceU256Function#c", emitProgram amsterdamBlobGasPriceU256_prog),
    ("baapDeleteSingleLeafStorageFunction#c", emitProgram baapDeleteSingleLeafStorage_prog),
    ("balAccountAccessOutcomeDescriptorsFunction#c", emitProgram balAccountAccessOutcomeDescriptors_prog),
    ("balAccountChangeDescriptorFunction#c", emitProgram balAccountChangeDescriptor_prog),
    ("balAccountCodeConsistentFunction#c", emitProgram balAccountCodeConsistent_prog),
    ("balAccountHasStateChangeFunction#c", emitProgram balAccountHasStateChange_prog),
    ("balAccountNonstorageFinalsFunction#c", emitProgram balAccountNonstorageFinals_prog),
    ("balAccountPathFunction#c", emitProgram balAccountPath_prog),
    ("balAccountPostFieldsFunction#c", emitProgram balAccountPostFields_prog),
    ("balAccountRecordArrayFunction#c", emitProgram balAccountRecordArray_prog),
    ("balAllAccountsCodeCoversFunction#c", emitProgram balAllAccountsCodeCovers_prog),
    ("balCanonicalSortFunction#c", emitProgram balCanonicalSort_prog),
    ("balCanonicalSortSelftestFunction#c", emitProgram balCanonicalSortSelftest_prog),
    ("balFindAccountByAddressFunction#c", emitProgram balFindAccountByAddress_prog),
    ("balGasValidFunction#c", emitProgram balGasValid_prog),
    ("balSectionInfoFunction#c", emitProgram balSectionInfo_prog),
    ("balStorageAccessOutcomeDescriptorsFunction#c", emitProgram balStorageAccessOutcomeDescriptors_prog),
    ("blockAccessListHashCoreFunction#c", emitProgram blockAccessListHashCore_prog),
    ("blockAccessListHashFunction#c", emitProgram blockAccessListHash_prog),
    ("blockHashFromHeaderFunction#c", emitProgram blockHashFromHeader_prog),
    ("blockLogsBloomFromReceiptsListFunction#c", emitProgram blockLogsBloomFromReceiptsList_prog),
    ("blockRlpRebuiltSizeFunction#c", emitProgram blockRlpRebuiltSize_prog),
    ("blockValidateLogsBloomFunction#c", emitProgram blockValidateLogsBloom_prog),
    ("blockValidateReceiptsRootIndexedFunction#c", emitProgram blockValidateReceiptsRootIndexed_prog),
    ("blockValidateWithdrawalsRootIndexedFunction#c", emitProgram blockValidateWithdrawalsRootIndexed_prog),
    ("blockVerdictChainIdGateFunction#c", emitProgram blockVerdictChainIdGate_prog),
    ("blockVerdictEip8037TxStateGasNetArrayFunction#c", emitProgram blockVerdictEip8037TxStateGasNetArray_prog),
    ("blockVerdictGasResultArenaPrepareFunction#c", emitProgram blockVerdictGasResultArenaPrepare_prog),
    ("blockVerdictTxGasLimitsFunction#c", emitProgram blockVerdictTxGasLimits_prog),
    ("blockhashFromWitnessHeadersFunction#c", emitProgram blockhashFromWitnessHeaders_prog),
    ("bloomAddValueFunction#c", emitProgram bloomAddValue_prog),
    ("bls12Fq12PowFunction#c", emitProgram blqPow_prog),
    ("bls12Fq12SMulFunction#c", emitProgram blqSmul_prog),
    ("bls12Fq12SetOneFunction#c", emitProgram blqSetOne_prog),
    ("bls12G1AddModPFunction#c", emitProgram blsgAddModP_prog),
    ("bls12G1LeAddFunction#c", emitProgram blsgLeAdd_prog),
    ("bls12G1LeDblFunction#c", emitProgram blsgLeDbl_prog),
    ("bls12G1LtPFunction#c", emitProgram blsgLtP_prog),
    ("bls12G1MulModPFunction#c", emitProgram blsgMulModP_prog),
    ("bls12G1OnCurveFunction#c", emitProgram blsgOnCurve_prog),
    ("bls12G1PointAddFunction#c", emitProgram blsgPointAdd_prog),
    ("bls12G1PointDblFunction#c", emitProgram blsgPointDbl_prog),
    ("bls12G1SubgroupFunction#c", emitProgram blsgSubgroupG1_prog),
    ("bls12G2ChordTailFunction#c", emitProgram blsg2ChordTail_prog),
    ("bls12G2Copy192Function#c", emitProgram blsg2Copy192_prog),
    ("bls12G2EncodeFunction#c", emitProgram blsg2Encode_prog),
    ("bls12G2Fp2AddFunction#c", emitProgram blsg2Fp2Add_prog),
    ("bls12G2Fp2InvFunction#c", emitProgram blsg2Fp2Inv_prog),
    ("bls12G2Fp2MulFunction#c", emitProgram blsg2Fp2Mul_prog),
    ("bls12G2Fp2SubFunction#c", emitProgram blsg2Fp2Sub_prog),
    ("bls12G2FpAddLeFunction#c", emitProgram blsg2FpAdd_prog),
    ("bls12G2FpInvFunction#c", emitProgram blsg2FpInv_prog),
    ("bls12G2FpMulLeFunction#c", emitProgram blsg2FpMul_prog),
    ("bls12G2ScalarMulFunction#c", emitProgram blsg2ScalarMul_prog),
    ("bls12G2SubgroupFunction#c", emitProgram blsg2SubgroupG2_prog),
    ("bls12KzgFpPowQ14Function#c", emitProgram blskFpPowQ14_prog),
    ("bls12KzgG2WireFunction#c", emitProgram blskG2Wire_prog),
    ("bls12KzgNegScalarFunction#c", emitProgram blskNegScalar_prog),
    ("bls12MapFp2PowFunction#c", emitProgram blmFp2Pow_prog),
    ("bls12MapFpPowFunction#c", emitProgram blmFpPow_prog),
    ("bn254FieldAddFunction#c", emitProgram bnfAddModP_prog),
    ("bn254FieldLtPFunction#c", emitProgram bnfLtP_prog),
    ("bn254FieldMulFunction#c", emitProgram bnfMulModP_prog),
    ("bn254Fp2AddFunction#c", emitProgram bnpFp2Add_prog),
    ("bn254Fp2InvFunction#c", emitProgram bnpFp2Inv_prog),
    ("bn254Fp2MulFunction#c", emitProgram bnpFp2Mul_prog),
    ("bn254Fp2SubFunction#c", emitProgram bnpFp2Sub_prog),
    ("bn254FpAddLeFunction#c", emitProgram bnpFpAdd_prog),
    ("bn254FpMulLeFunction#c", emitProgram bnpFpMul_prog),
    ("bn254FpPowLeFunction#c", emitProgram bnpFpPow_prog),
    ("bn254Fq12PowFunction#c", emitProgram bnqPow_prog),
    ("bn254Fq12SMulFunction#c", emitProgram bnqSmul_prog),
    ("bn254Fq12SetOneFunction#c", emitProgram bnqSetOne_prog),
    ("bn254OnCurveFunction#c", emitProgram bncOnCurve_prog),
    ("bn254PointAddFunction#c", emitProgram bncPointAdd_prog),
    ("bn254PointDblFunction#c", emitProgram bncPointDbl_prog),
    ("bn254ScalarMulFunction#c", emitProgram bncScalarMul_prog),
    ("bn254ValidateG1Function#c", emitProgram bncValidateG1_prog),
    ("bsrApplyModeledSystemPostFieldsFunction#c", emitProgram bsrApplyModeledSystemPostFields_prog),
    ("bvSumWithdrawalsToAddressFunction#c", emitProgram bvSumWithdrawalsToAddress_prog),
    ("chainValidateBlobGasUsedMultipleFunction#c", emitProgram chainValidateBlobGasUsedMultiple_prog),
    ("chainValidateBlobGasUsedUnderMaxFunction#c", emitProgram chainValidateBlobGasUsedUnderMax_prog),
    ("chainValidateConsecutiveNumbersFunction#c", emitProgram chainValidateConsecutiveNumbers_prog),
    ("chainValidateExtraDataLengthFunction#c", emitProgram chainValidateExtraDataLength_prog),
    ("chainValidateGasUsedUnderLimitFunction#c", emitProgram chainValidateGasUsedUnderLimit_prog),
    ("chainValidateIncreasingTimestampsFunction#c", emitProgram chainValidateIncreasingTimestamps_prog),
    ("chainValidatePostMergeFullFunction#c", emitProgram chainValidatePostMergeFull_prog),
    ("codeAtHeaderStateRootFunction#c", emitProgram codeAtHeaderStateRoot_prog),
    ("codeHashAtHeaderStateRootFunction#c", emitProgram codeHashAtHeaderStateRoot_prog),
    ("createExecuteInitcodeFrameRuntimeFunction#c", emitProgram createExecuteInitcodeFrame_prog),
    ("createStageInitcodeFrameRuntimeFunction#c", emitProgram createStageInitcodeFrame_prog),
    ("deriveConsolidationRequestsFunction#c", emitProgram deriveConsolidationRequests_prog),
    ("deriveWithdrawalRequestsFunction#c", emitProgram deriveWithdrawalRequests_prog),
    ("dispatcherCaptureExecStateGasFunction#c", emitProgram dispatcherCaptureExecStateGas_prog),
    ("dispatcherTxGasSettleFunction#c", emitProgram dispatcherTxGasSettle_prog),
    ("eip1559CalcBaseFeePerGasFunction#c", emitProgram eip1559CalcBaseFeePerGas_prog),
    ("eip7702AuthorizationRecoverAddressFunction#c", emitProgram eip7702AuthorizationRecoverAddress_prog),
    ("eip7702AuthorizationSigningHashFunction#c", emitProgram eip7702AuthorizationSigningHash_prog),
    ("eip7778RemainingBlockGasFromResultsFunction#c", emitProgram eip7778RemainingBlockGasFromResults_prog),
    ("eip8037PriorStateUsedExactFunction#c", emitProgram eip8037PriorStateUsedExact_prog),
    ("eip8037TxGasGateFunction#c", emitProgram eip8037TxGasGate_prog),
    ("erhHashOneFunction#c", emitProgram erhHashOne_prog),
    ("executionRequestsHashFunction#c", emitProgram executionRequestsHash_prog),
    ("extcodecopyAtHeaderStateRootFunction#c", emitProgram extcodecopyAtHeaderStateRoot_prog),
    ("extcodehashAtHeaderStateRootFunction#c", emitProgram extcodehashAtHeaderStateRoot_prog),
    ("extcodesizeAtHeaderStateRootFunction#c", emitProgram extcodesizeAtHeaderStateRoot_prog),
    ("extractParentHeaderAndStateRootFunction#c", emitProgram extractParentHeaderAndStateRoot_prog),
    ("extractPayloadAndWithdrawalsFunction#c", emitProgram extractPayloadAndWithdrawals_prog),
    ("extractWitnessStateSectionFunction#c", emitProgram extractWitnessStateSection_prog),
    ("frameBaseFunction#c", emitProgram frameBase_prog),
    ("frameDepthPopFunction#c", emitProgram frameDepthPop_prog),
    ("frameDepthPushFunction#c", emitProgram frameDepthPush_prog),
    ("frameLoadRegsFunction#c", emitProgram frameLoadRegs_prog),
    ("frameSaveRegsFunction#c", emitProgram frameSaveRegs_prog),
    ("hasCodeOrNonceAtHeaderStateRootFunction#c", emitProgram hasCodeOrNonceAtHeaderStateRoot_prog),
    ("headerExtendedDecodeFunction#c", emitProgram headerExtendedDecode_prog),
    ("headerExtractLogsBloomFunction#c", emitProgram headerExtractLogsBloom_prog),
    ("headerExtractNumberFunction#c", emitProgram headerExtractNumber_prog),
    ("headerExtractReceiptsRootFunction#c", emitProgram headerExtractReceiptsRoot_prog),
    ("headerExtractStateRootFunction#c", emitProgram headerExtractStateRoot_prog),
    ("headerExtractWithdrawalsRootFunction#c", emitProgram headerExtractWithdrawalsRoot_prog),
    ("headerValidateBaseFeeFunction#c", emitProgram headerValidateBaseFee_prog),
    ("headerValidateExcessBlobGasFunction#c", emitProgram headerValidateExcessBlobGas_prog),
    ("headerValidateExtraDataLengthFunction#c", emitProgram headerValidateExtraDataLength_prog),
    ("headerValidateParentHashFunction#c", emitProgram headerValidateParentHash_prog),
    ("headerValidatePostMergeFunction#c", emitProgram headerValidatePostMerge_prog),
    ("headersKeccakArrayFunction#c", emitProgram headersKeccakArray_prog),
    ("headersValidateChainFunction#c", emitProgram headersValidateChain_prog),
    ("logBloomAddFunction#c", emitProgram logBloomAdd_prog),
    ("logsListBloomAddFunction#c", emitProgram logsListBloomAdd_prog),
    ("mapAccountChangeValueFunction#c", emitProgram mapAccountChangeValue_prog),
    ("mptBranchChildFunction#c", emitProgram mptBranchChild_prog),
    ("mptDeleteAccFunction#c", emitProgram mptDeleteAcc_prog),
    ("mptDeleteWalkDbFunction#c", emitProgram mptDeleteWalkDb_prog),
    ("mptExtensionExtractFunction#c", emitProgram mptExtensionExtract_prog),
    ("mptExtensionNodeEncodeFunction#c", emitProgram mptExtensionNodeEncode_prog),
    ("mptIndexedLargeLeafHashFunction#c", emitProgram mptIndexedLargeLeafHash_prog),
    ("mptIndexedTrieRootLargeFunction#c", emitProgram mptIndexedTrieRootLarge_prog),
    ("mptIndexedTrieRootSmallFunction#c", emitProgram mptIndexedTrieRootSmall_prog),
    ("mptInsertAccFunction#c", emitProgram mptInsertAcc_prog),
    ("mptInsertWalkDbFunction#c", emitProgram mptInsertWalkDb_prog),
    ("mptLeafExtractFunction#c", emitProgram mptLeafExtract_prog),
    ("mptLookupByKeyFunction#c", emitProgram mptLookupByKey_prog),
    ("mptNodeKindFunction#c", emitProgram mptNodeKind_prog),
    ("mptNodeResolveFunction#c", emitProgram mptNodeResolve_prog),
    ("mptNodeSlotEncodeFunction#c", emitProgram mptNodeSlotEncode_prog),
    ("mptOneLeafRootIndexedFunction#c", emitProgram mptOneLeafRootIndexed_prog),
    ("mptResolveCacheResetFunction#c", emitProgram mptResolveCacheReset_prog),
    ("mptSetAccFunction#c", emitProgram mptSetAcc_prog),
    ("mptSetRecordWalkDbFunction#c", emitProgram mptSetRecordWalkDb_prog),
    ("mptSpliceSlotFunction#c", emitProgram mptSpliceSlot_prog),
    ("mptStateRootFunction#c", emitProgram mptStateRoot_prog),
    ("mptStateRootInsFunction#c", emitProgram mptStateRootIns_prog),
    ("mptWalkFunction#c", emitProgram mptWalk_prog),
    ("nodeDbAppendFunction#c", emitProgram nodeDbAppend_prog),
    ("nodeDbLookupFunction#c", emitProgram nodeDbLookup_prog),
    ("nonceAtHeaderStateRootFunction#c", emitProgram nonceAtHeaderStateRoot_prog),
    ("nonstorageEffectLatestBalanceFunction#c", emitProgram nonstorageEffectLatestBalance_prog),
    ("p256ChordTailFunction#c", emitProgram p256ChordTail_prog),
    ("p256OpWithFunction#c", emitProgram p256OpWith_prog),
    ("p256PointAddFunction#c", emitProgram p256PointAdd_prog),
    ("p256PointDblFunction#c", emitProgram p256PointDbl_prog),
    ("p256PowFunction#c", emitProgram p256Pow_prog),
    ("p256ScalarMulFunction#c", emitProgram p256ScalarMul_prog),
    ("priorityFeePerGasEip1559Function#c", emitProgram priorityFeePerGasEip1559_prog),
    ("receiptEncodeFunction#c", emitProgram receiptEncode_prog),
    ("receiptExtractLogsBloomFunction#c", emitProgram receiptExtractLogsBloom_prog),
    ("requestsHashVerifyFunction#c", emitProgram requestsHashVerify_prog),
    ("rlpFieldToU256BeFunction#c", emitProgram rlpFieldToU256Be_prog),
    ("rlpFieldToU64Function#c", emitProgram rlpFieldToU64_prog),
    ("rlpListTruncateToNFieldsFunction#c", emitProgram rlpListTruncateToNFields_prog),
    ("runtimeSameBlockDelegationCodeFunction#c", emitProgram runtimeSameBlockDelegationCode_prog),
    ("secp256k1FieldAddFunction#c", emitProgram secfAddModP_prog),
    ("secp256k1FieldCmpPFunction#c", emitProgram secfCmpP_prog),
    ("secp256k1FieldInvFunction#c", emitProgram secfInvModP_prog),
    ("secp256k1FieldMulFunction#c", emitProgram secfMulModP_prog),
    ("secp256k1FieldPowFunction#c", emitProgram secfPowModP_prog),
    ("secp256k1FieldReduceOnceFunction#c", emitProgram secfReduceOnce_prog),
    ("secp256k1FieldSqrtFunction#c", emitProgram secfSqrtModP_prog),
    ("secp256k1FieldSquareFunction#c", emitProgram secfSquareModP_prog),
    ("secp256k1FieldSubFunction#c", emitProgram secfSubModP_prog),
    ("secp256k1PointDoubleFunction#c", emitProgram secp256k1PointDouble_prog),
    ("secp256k1RecoverPubkeyStagedFunction#c", emitProgram secp256k1RecoverPubkeyStaged_prog),
    ("secp256k1RecoverRFunction#c", emitProgram secp256k1RecoverR_prog),
    ("secp256k1ScalarFieldAddFunction#c", emitProgram secfAddModN_prog),
    ("secp256k1ScalarFieldInvFunction#c", emitProgram secfInvModN_prog),
    ("secp256k1ScalarFieldMulFunction#c", emitProgram secfMulModN_prog),
    ("secp256k1ScalarFieldPowFunction#c", emitProgram secfPowModN_prog),
    ("secp256k1ScalarFieldReduceOnceFunction#c", emitProgram secfReduceOnceN_prog),
    ("secp256k1ScalarFieldSquareFunction#c", emitProgram secfSquareModN_prog),
    ("secp256k1ScalarMulFunction#c", emitProgram secp256k1ScalarMul_prog),
    ("selfdestructBalanceTransferFunction#c", emitProgram selfdestructBalanceTransfer_prog),
    ("simpleTransferTxContextFunction#c", emitProgram simpleTransferTxContext_prog),
    ("singleLeafTrieRootFunction#c", emitProgram singleLeafTrieRoot_prog),
    ("slotAtHeaderStateRootFunction#c", emitProgram slotAtHeaderStateRoot_prog),
    ("slotAtIndexFunction#c", emitProgram slotAtIndex_prog),
    ("sszHashTreeRootBytesFunction#c", emitProgram sszHashTreeRootBytes_prog),
    ("sszHashTreeRootListByteListFunction#c", emitProgram sszHashTreeRootListBytelist_prog),
    ("sszMerkleizeFunction#c", emitProgram sszMerkleize_prog),
    ("sszMerkleizePow2Function#c", emitProgram sszMerkleizePow2_prog),
    ("sszTxListVersionedHashesMatchFunction#c", emitProgram sszTxListVersionedHashesMatch_prog),
    ("sszWithdrawalToRlpFunction#c", emitProgram sszWithdrawalToRlp_prog),
    ("statelessVerdictFromSszFunction#c", emitProgram statelessVerdictFromSsz_prog),
    ("step2VerdictFunction#c", emitProgram step2Verdict_prog),
    ("storageRootSingleSlotFunction#c", emitProgram storageRootSingleSlot_prog),
    ("txAccessListSpanFunction#c", emitProgram txAccessListSpan_prog),
    ("txEffectiveGasPricingFunction#c", emitProgram txEffectiveGasPricing_prog),
    ("txEip1559DecodeFunction#c", emitProgram txEip1559Decode_prog),
    ("txEip2930DecodeFunction#c", emitProgram txEip2930Decode_prog),
    ("txEip4844DecodeFunction#c", emitProgram txEip4844Decode_prog),
    ("txEip4844ValidateBlobHashesFunction#c", emitProgram txEip4844ValidateBlobHashes_prog),
    ("txEip7702DecodeFunction#c", emitProgram txEip7702Decode_prog),
    ("txGasSenderBalLookupFunction#c", emitProgram txGasSenderBalLookup_prog),
    ("txIntrinsicStateGasFunction#c", emitProgram txIntrinsicStateGas_prog),
    ("txPubkeyPublicKeyMatchesFunction#c", emitProgram txPubkeyPublicKeyMatches_prog),
    ("txPubkeyRecoverRawFunction#c", emitProgram txPubkeyRecoverRaw_prog),
    ("txPubkeySignatureMaterialFunction#c", emitProgram txPubkeySignatureMaterial_prog),
    ("txSigningHashFunction#c", emitProgram txSigningHash_prog),
    ("txSigningHashLegacyEip155Function#c", emitProgram txSigningHashLegacyEip155_prog),
    ("txUpfrontPrechargeFunction#c", emitProgram txUpfrontPrecharge_prog),
    ("u256MulU64BeFunction#c", emitProgram u256MulU64Be_prog),
    ("validateHeaderFullFunction#c", emitProgram validateHeaderFull_prog),
    ("validateHeaderRlpPairFunction#c", emitProgram validateHeaderRlpPair_prog),
    ("validateParentHashLinkFunction#c", emitProgram validateParentHashLink_prog),
    ("verifyPublicKeysMatchSendersFunction#c", emitProgram verifyPublicKeysMatchSenders_prog),
    ("withdrawalDecodeFunction#c", emitProgram withdrawalDecode_prog),
    ("withdrawalToPathDeltaFunction#c", emitProgram withdrawalToPathDelta_prog),
    ("withdrawalsStateRootFunction#c", emitProgram withdrawalsStateRoot_prog),
    ("zkvmKeccak256Function#c", emitProgram zkvmKeccak256_prog),
    ("zkvmKeccak256SegmentsFunction#c", emitProgram zkvmKeccak256Segments_prog),
    ("zkvmSha256Function#c", emitProgram zkvmSha256_prog) ]
def main : IO Unit :=
  _renderItems.forM fun (nm, s) => do
    IO.print ("-=-=-=BEGIN " ++ nm ++ "=-=-=-
")
    IO.print s
    IO.print "
-=-=-=END=-=-=-"
