-- GENERATED by scripts/gen-rv64-shims.py -- do not edit by hand.
--
-- `WP.Call` now lives in the riscv-zkvm dependency, prebuilt.
-- This shim re-exports it so evm-asm's existing references keep resolving;
-- `export` aliases the SAME constants, so no statement changes meaning.
--
-- Only the export block below is regenerated. The prelude between the
-- markers is preserved verbatim and is the source of truth -- aliases do not
-- propagate transitively, so those import edges are what let downstream files
-- still see the names they used to. Edit it here if the imports must change.
--
-- Regenerate with `scripts/gen-rv64-shims.py`; `--check` gates it in CI.
-- BEGIN shim prelude (preserved from the original module)
/-
  EvmAsm.Rv64.WP.Call

  Call/return combinators for the WP certificate layer.  This packages the
  common `jal ra, callee` shape as a backward calculator step: after the JAL,
  the callee sees `ra = callerPC + 4`, and a normal RISC-V return reaches the
  aligned caller continuation.
-/

module

public import EvmAsm.Rv64.WP.CFG
public import EvmAsm.Rv64.GenericSpecs
public import EvmAsm.Rv64.Tactics.XSimp
public import RiscvZkvm.Rv64.Logic.WP.Call

@[expose] public section
-- END shim prelude

namespace EvmAsm.Rv64

export RiscvZkvm.Rv64 (WP.CFG.callWithin WP.Triple.callWithin WP.cpsCallWithin)

-- Namespaces downstream files `open`; see render() for why these
-- cannot come from `export`.
namespace WP end WP
namespace WP.CFG end WP.CFG
namespace WP.Triple end WP.Triple

end EvmAsm.Rv64
