-- GENERATED by scripts/gen-rv64-shims.py -- do not edit by hand.
--
-- `WP.CFG` now lives in the riscv-zkvm dependency, prebuilt.
-- This shim re-exports it so evm-asm's existing references keep resolving;
-- `export` aliases the SAME constants, so no statement changes meaning.
--
-- Only the export block below is regenerated. The prelude between the
-- markers is preserved verbatim and is the source of truth -- aliases do not
-- propagate transitively, so those import edges are what let downstream files
-- still see the names they used to. Edit it here if the imports must change.
--
-- Regenerate with `scripts/gen-rv64-shims.py`; `--check` gates it in CI.
-- BEGIN shim prelude (preserved from the original module)
/-
  EvmAsm.Rv64.WP.CFG

  User-facing constructors for structured control-flow certificates.  The
  certificate itself is a `WP.Triple`; this file gives stable names for the
  CFG operations that a proof-producing agent should emit.
-/

module

public import EvmAsm.Rv64.WP.Loop
public import RiscvZkvm.Rv64.Logic.WP.CFG

@[expose] public section
-- END shim prelude

namespace EvmAsm.Rv64

export RiscvZkvm.Rv64 (WP.CFG.Cert WP.CFG.block WP.CFG.block_pre WP.CFG.branch)
export RiscvZkvm.Rv64 (WP.CFG.branchFrameR WP.CFG.branchSeqNotTakenBlockDisjoint WP.CFG.branchSeqNotTakenDisjoint WP.CFG.branchSeqNotTakenNBranchDisjoint)
export RiscvZkvm.Rv64 (WP.CFG.branchSeqTakenBlockDisjoint WP.CFG.branchSeqTakenBlockNBranchDisjoint WP.CFG.branchSeqTakenBranchConvergeDisjoint WP.CFG.branchSeqTakenDisjoint)
export RiscvZkvm.Rv64 (WP.CFG.branchSeqTakenNBranchDisjoint WP.CFG.changeEntry WP.CFG.changeEntry_pre WP.CFG.changeExit)
export RiscvZkvm.Rv64 (WP.CFG.changeExit_pre WP.CFG.exit WP.CFG.exitRefl WP.CFG.exitRefl_pre)
export RiscvZkvm.Rv64 (WP.CFG.extendCode WP.CFG.extendCode_pre WP.CFG.frameR WP.CFG.frameR_pre)
export RiscvZkvm.Rv64 (WP.CFG.leaf WP.CFG.leaf_pre WP.CFG.loopNat WP.CFG.monoSteps)
export RiscvZkvm.Rv64 (WP.CFG.monoSteps_pre WP.CFG.nbranch WP.CFG.nbranchFrameR WP.CFG.nbranchJoin2ResolveFirst)
export RiscvZkvm.Rv64 (WP.CFG.nbranchJoin2ResolveSecond WP.CFG.nbranchJoin3ResolveSecond WP.CFG.nbranchJoin4 WP.CFG.nbranchJoin4Max)
export RiscvZkvm.Rv64 (WP.CFG.nbranchJoin4ResolveThird WP.CFG.nbranchOfBranch WP.CFG.nbranchSeqExitCertDisjoint WP.CFG.nbranchSeqExitNBranchDisjoint)
export RiscvZkvm.Rv64 (WP.CFG.nbranchSeqHead WP.CFG.nbranchSeqHeadBlock WP.CFG.nbranchSeqHeadBlockDisjoint WP.CFG.nbranchSeqHeadDisjoint)
export RiscvZkvm.Rv64 (WP.CFG.nbranchSeqHeadNBranch WP.CFG.nbranchSeqHeadNBranchDisjoint WP.CFG.nbranchSeqSecondNBranchDisjoint WP.CFG.nbranchSeqThirdCertDisjoint)
export RiscvZkvm.Rv64 (WP.CFG.nbranchSeqThirdNBranchDisjoint WP.CFG.nbranchWeakenHeadPost WP.CFG.nbranchWeakenPosts WP.CFG.nbranchWeakenPosts2)
export RiscvZkvm.Rv64 (WP.CFG.nbranchWeakenPosts3 WP.CFG.nbranchWeakenPosts4 WP.CFG.nbranchWeakenPosts4MergeFirstTwo WP.CFG.nbranchWeakenPostsCons)
export RiscvZkvm.Rv64 (WP.CFG.pre WP.CFG.seq WP.CFG.seqBlock WP.CFG.seqBlockDisjoint)
export RiscvZkvm.Rv64 (WP.CFG.seqBlockDisjointExact WP.CFG.seqBlockExact WP.CFG.seqBlockNBranchDisjoint WP.CFG.seqDisjoint)
export RiscvZkvm.Rv64 (WP.CFG.seqDisjointExact WP.CFG.seqExact WP.CFG.unreachable WP.CFG.weakenPost)
export RiscvZkvm.Rv64 (WP.CFG.weakenPost_pre WP.CFG.weakenPre WP.CFG.weakenPre_pre)

-- Namespaces downstream files `open`; see render() for why these
-- cannot come from `export`.
namespace WP end WP
namespace WP.CFG end WP.CFG

end EvmAsm.Rv64
