-- GENERATED by scripts/gen-rv64-shims.py -- do not edit by hand.
--
-- `WP.Core` now lives in the riscv-zkvm dependency, prebuilt.
-- This shim re-exports it so evm-asm's existing references keep resolving;
-- `export` aliases the SAME constants, so no statement changes meaning.
--
-- The original prelude is preserved deliberately -- aliases do not propagate
-- transitively, so those import edges are what let downstream files still see
-- the names they used to.  See original_prelude() for the full reasoning.
--
-- Regenerate with `scripts/gen-rv64-shims.py`; `--check` gates it in CI.
/-
  EvmAsm.Rv64.WP.Core

  A small weakest-precondition style layer over the existing bounded CPS
  Hoare triples.  The layer is intentionally soundness-first: each calculator
  result exposes a precondition together with a proof that the existing
  `cpsTripleWithin`/`cpsNBranchWithin` contract follows.
-/

module

public import EvmAsm.Rv64.CPSSpec
public import RiscvZkvm.Rv64.Logic.WP.Core

@[expose] public section

namespace EvmAsm.Rv64

export RiscvZkvm.Rv64 (WP.Branch WP.Branch.casesOn WP.Branch.ctorIdx WP.Branch.exit_f)
export RiscvZkvm.Rv64 (WP.Branch.exit_t WP.Branch.frameR WP.Branch.frameR_exit_f WP.Branch.frameR_exit_t)
export RiscvZkvm.Rv64 (WP.Branch.frameR_post_f WP.Branch.frameR_post_t WP.Branch.frameR_pre WP.Branch.join)
export RiscvZkvm.Rv64 (WP.Branch.join_pre WP.Branch.mk WP.Branch.mk.inj WP.Branch.mk.injEq)
export RiscvZkvm.Rv64 (WP.Branch.mk.noConfusion WP.Branch.mk.sizeOf_spec WP.Branch.nSteps WP.Branch.noConfusion)
export RiscvZkvm.Rv64 (WP.Branch.noConfusionType WP.Branch.ofSpec WP.Branch.ofSpec_exit_f WP.Branch.ofSpec_exit_t)
export RiscvZkvm.Rv64 (WP.Branch.ofSpec_post_f WP.Branch.ofSpec_post_t WP.Branch.ofSpec_pre WP.Branch.post_f)
export RiscvZkvm.Rv64 (WP.Branch.post_t WP.Branch.pre WP.Branch.rec WP.Branch.recOn)
export RiscvZkvm.Rv64 (WP.Branch.seqNotTakenDisjoint WP.Branch.seqNotTakenDisjoint_pre WP.Branch.seqNotTakenNBranchDisjoint WP.Branch.seqTakenAsNBranchDisjoint)
export RiscvZkvm.Rv64 (WP.Branch.seqTakenBranchConvergeDisjoint WP.Branch.seqTakenBranchConvergeDisjoint_pre WP.Branch.seqTakenDisjoint WP.Branch.seqTakenDisjoint_pre)
export RiscvZkvm.Rv64 (WP.Branch.sound WP.Entails WP.Entails.refl WP.Entails.trans)
export RiscvZkvm.Rv64 (WP.NBranch WP.NBranch.casesOn WP.NBranch.ctorIdx WP.NBranch.exits)
export RiscvZkvm.Rv64 (WP.NBranch.extendCode WP.NBranch.frameR WP.NBranch.join WP.NBranch.join2ResolveFirst)
export RiscvZkvm.Rv64 (WP.NBranch.join2ResolveSecond WP.NBranch.join3ResolveSecond WP.NBranch.join4 WP.NBranch.join4Max)
export RiscvZkvm.Rv64 (WP.NBranch.join4ResolveThird WP.NBranch.mk WP.NBranch.mk.inj WP.NBranch.mk.injEq)
export RiscvZkvm.Rv64 (WP.NBranch.mk.noConfusion WP.NBranch.mk.sizeOf_spec WP.NBranch.nSteps WP.NBranch.noConfusion)
export RiscvZkvm.Rv64 (WP.NBranch.noConfusionType WP.NBranch.ofBranch WP.NBranch.ofSpec WP.NBranch.ofTriple)
export RiscvZkvm.Rv64 (WP.NBranch.ofTriple_exits WP.NBranch.ofTriple_pre WP.NBranch.pre WP.NBranch.rec)
export RiscvZkvm.Rv64 (WP.NBranch.recOn WP.NBranch.seqExitNBranchDisjoint WP.NBranch.seqHead WP.NBranch.seqHeadDisjoint)
export RiscvZkvm.Rv64 (WP.NBranch.seqHeadNBranch WP.NBranch.seqHeadNBranchDisjoint WP.NBranch.seqSecondNBranchDisjoint WP.NBranch.seqThirdCertDisjoint)
export RiscvZkvm.Rv64 (WP.NBranch.seqThirdNBranchDisjoint WP.NBranch.sound WP.NBranch.weakenHeadPost WP.NBranch.weakenPosts)
export RiscvZkvm.Rv64 (WP.NBranch.weakenPosts2 WP.NBranch.weakenPosts3 WP.NBranch.weakenPosts4 WP.NBranch.weakenPosts4MergeFirstTwo)
export RiscvZkvm.Rv64 (WP.NBranch.weakenPostsCons WP.NBranch.weakenPre WP.Triple WP.Triple.casesOn)
export RiscvZkvm.Rv64 (WP.Triple.changeEntry WP.Triple.changeEntry_pre WP.Triple.changeExit WP.Triple.changeExit_pre)
export RiscvZkvm.Rv64 (WP.Triple.ctorIdx WP.Triple.extendCode WP.Triple.extendCode_pre WP.Triple.frameR)
export RiscvZkvm.Rv64 (WP.Triple.frameR_pre WP.Triple.mk WP.Triple.mk.inj WP.Triple.mk.injEq)
export RiscvZkvm.Rv64 (WP.Triple.mk.noConfusion WP.Triple.mk.sizeOf_spec WP.Triple.monoSteps WP.Triple.monoSteps_pre)
export RiscvZkvm.Rv64 (WP.Triple.nSteps WP.Triple.noConfusion WP.Triple.noConfusionType WP.Triple.ofSpec)
export RiscvZkvm.Rv64 (WP.Triple.ofSpec_pre WP.Triple.pre WP.Triple.rec WP.Triple.recOn)
export RiscvZkvm.Rv64 (WP.Triple.refl WP.Triple.refl_pre WP.Triple.seq WP.Triple.seqDisjoint)
export RiscvZkvm.Rv64 (WP.Triple.seqDisjoint_pre WP.Triple.seq_pre WP.Triple.sound WP.Triple.unreachable)
export RiscvZkvm.Rv64 (WP.Triple.unreachable_pre WP.Triple.weakenPost WP.Triple.weakenPost_pre WP.Triple.weakenPre)
export RiscvZkvm.Rv64 (WP.Triple.weakenPre_pre WP.Triple.wp)

-- Namespaces downstream files `open`; see render() for why these
-- cannot come from `export`.
namespace WP end WP
namespace WP.Branch end WP.Branch
namespace WP.Branch.mk end WP.Branch.mk
namespace WP.Entails end WP.Entails
namespace WP.NBranch end WP.NBranch
namespace WP.NBranch.mk end WP.NBranch.mk
namespace WP.Triple end WP.Triple
namespace WP.Triple.mk end WP.Triple.mk

end EvmAsm.Rv64
