-- GENERATED by scripts/gen-rv64-shims.py -- do not edit by hand.
--
-- `WP.Examples` now lives in the riscv-zkvm dependency, prebuilt.
-- This shim re-exports it so evm-asm's existing references keep resolving;
-- `export` aliases the SAME constants, so no statement changes meaning.
--
-- Only the export block below is regenerated. The prelude between the
-- markers is preserved verbatim and is the source of truth -- aliases do not
-- propagate transitively, so those import edges are what let downstream files
-- still see the names they used to. Edit it here if the imports must change.
--
-- Regenerate with `scripts/gen-rv64-shims.py`; `--check` gates it in CI.
-- BEGIN shim prelude (preserved from the original module)
/-
  EvmAsm.Rv64.WP.Examples

  Small kernel-checked examples for the WP layer.
-/

import EvmAsm.Rv64.InstructionSpecs
import EvmAsm.Rv64.WP.CFG
import EvmAsm.Rv64.Tactics.WP
import RiscvZkvm.Rv64.Logic.WP.Examples
-- END shim prelude

namespace EvmAsm.Rv64

export RiscvZkvm.Rv64 (WP.Examples.addiTwiceCfg WP.Examples.oneIterationLoopCfg WP.Examples.twoIterationLoopCfg)

-- Namespaces downstream files `open`; see render() for why these
-- cannot come from `export`.
namespace WP end WP
namespace WP.Examples end WP.Examples

end EvmAsm.Rv64
