-- GENERATED by scripts/gen-rv64-shims.py -- do not edit by hand.
--
-- `WP.GeneratedCFG` now lives in the riscv-zkvm dependency, prebuilt.
-- This shim re-exports it so evm-asm's existing references keep resolving;
-- `export` aliases the SAME constants, so no statement changes meaning.
--
-- Only the export block below is regenerated. The prelude between the
-- markers is preserved verbatim and is the source of truth -- aliases do not
-- propagate transitively, so those import edges are what let downstream files
-- still see the names they used to. Edit it here if the imports must change.
--
-- Regenerate with `scripts/gen-rv64-shims.py`; `--check` gates it in CI.
-- BEGIN shim prelude (preserved from the original module)
/-
  EvmAsm.Rv64.WP.GeneratedCFG

  Typed shape helpers for generated control-flow proofs. The generator supplies
  labels and local postconditions as an explicit exit list; these helpers keep
  that list attached to the underlying WP.NBranch certificate while composing
  or joining exits.
-/

module

public import EvmAsm.Rv64.WP.CFG
public import RiscvZkvm.Rv64.Logic.WP.GeneratedCFG

@[expose] public section
-- END shim prelude

namespace EvmAsm.Rv64

export RiscvZkvm.Rv64 (WP.CFG.nbranchSeqExitNBranchDisjoint.eq_1 WP.CFG.nbranchSeqHeadNBranchDisjoint.eq_1 WP.GeneratedCFG.Branch2Spec WP.GeneratedCFG.Branch2Spec.Matches)
export RiscvZkvm.Rv64 (WP.GeneratedCFG.Branch2Spec.casesOn WP.GeneratedCFG.Branch2Spec.ctorIdx WP.GeneratedCFG.Branch2Spec.exits WP.GeneratedCFG.Branch2Spec.exits.eq_1)
export RiscvZkvm.Rv64 (WP.GeneratedCFG.Branch2Spec.exits_eq_of_matches WP.GeneratedCFG.Branch2Spec.fallthrough WP.GeneratedCFG.Branch2Spec.joinFallthrough WP.GeneratedCFG.Branch2Spec.joinTaken)
export RiscvZkvm.Rv64 (WP.GeneratedCFG.Branch2Spec.mk WP.GeneratedCFG.Branch2Spec.mk.inj WP.GeneratedCFG.Branch2Spec.mk.injEq WP.GeneratedCFG.Branch2Spec.mk.noConfusion)
export RiscvZkvm.Rv64 (WP.GeneratedCFG.Branch2Spec.mk.sizeOf_spec WP.GeneratedCFG.Branch2Spec.noConfusion WP.GeneratedCFG.Branch2Spec.noConfusionType WP.GeneratedCFG.Branch2Spec.rec)
export RiscvZkvm.Rv64 (WP.GeneratedCFG.Branch2Spec.recOn WP.GeneratedCFG.Branch2Spec.taken WP.GeneratedCFG.Branch2Spec.toOpenCFG WP.GeneratedCFG.ExitSpec)
export RiscvZkvm.Rv64 (WP.GeneratedCFG.ExitSpec.casesOn WP.GeneratedCFG.ExitSpec.ctorIdx WP.GeneratedCFG.ExitSpec.label WP.GeneratedCFG.ExitSpec.mk)
export RiscvZkvm.Rv64 (WP.GeneratedCFG.ExitSpec.mk.inj WP.GeneratedCFG.ExitSpec.mk.injEq WP.GeneratedCFG.ExitSpec.mk.noConfusion WP.GeneratedCFG.ExitSpec.mk.sizeOf_spec)
export RiscvZkvm.Rv64 (WP.GeneratedCFG.ExitSpec.noConfusion WP.GeneratedCFG.ExitSpec.noConfusionType WP.GeneratedCFG.ExitSpec.post WP.GeneratedCFG.ExitSpec.rec)
export RiscvZkvm.Rv64 (WP.GeneratedCFG.ExitSpec.recOn WP.GeneratedCFG.LoopNatSpec WP.GeneratedCFG.LoopNatSpec.bodyEntry WP.GeneratedCFG.LoopNatSpec.bodyPre)
export RiscvZkvm.Rv64 (WP.GeneratedCFG.LoopNatSpec.bound WP.GeneratedCFG.LoopNatSpec.casesOn WP.GeneratedCFG.LoopNatSpec.ctorIdx WP.GeneratedCFG.LoopNatSpec.exitLabel)
export RiscvZkvm.Rv64 (WP.GeneratedCFG.LoopNatSpec.exitPost WP.GeneratedCFG.LoopNatSpec.fuel WP.GeneratedCFG.LoopNatSpec.header WP.GeneratedCFG.LoopNatSpec.inv)
export RiscvZkvm.Rv64 (WP.GeneratedCFG.LoopNatSpec.mk WP.GeneratedCFG.LoopNatSpec.mk.inj WP.GeneratedCFG.LoopNatSpec.mk.injEq WP.GeneratedCFG.LoopNatSpec.mk.noConfusion)
export RiscvZkvm.Rv64 (WP.GeneratedCFG.LoopNatSpec.mk.sizeOf_spec WP.GeneratedCFG.LoopNatSpec.nBody WP.GeneratedCFG.LoopNatSpec.nExit WP.GeneratedCFG.LoopNatSpec.nHeader)
export RiscvZkvm.Rv64 (WP.GeneratedCFG.LoopNatSpec.noConfusion WP.GeneratedCFG.LoopNatSpec.noConfusionType WP.GeneratedCFG.LoopNatSpec.post WP.GeneratedCFG.LoopNatSpec.pre)
export RiscvZkvm.Rv64 (WP.GeneratedCFG.LoopNatSpec.rec WP.GeneratedCFG.LoopNatSpec.recOn WP.GeneratedCFG.LoopNatSpec.toCert WP.GeneratedCFG.LoopNatSpec.toCert_nSteps)
export RiscvZkvm.Rv64 (WP.GeneratedCFG.LoopNatSpec.toCert_pre WP.GeneratedCFG.LoopNatSpec.toOpenCFG WP.GeneratedCFG.LoopNatSpec.toOpenCFG_exits WP.GeneratedCFG.OpenCFG)
export RiscvZkvm.Rv64 (WP.GeneratedCFG.OpenCFG.casesOn WP.GeneratedCFG.OpenCFG.cfg WP.GeneratedCFG.OpenCFG.ctorIdx WP.GeneratedCFG.OpenCFG.exits)
export RiscvZkvm.Rv64 (WP.GeneratedCFG.OpenCFG.exits_eq WP.GeneratedCFG.OpenCFG.join WP.GeneratedCFG.OpenCFG.join2ResolveFirst WP.GeneratedCFG.OpenCFG.join2ResolveSecond)
export RiscvZkvm.Rv64 (WP.GeneratedCFG.OpenCFG.join3ResolveSecond WP.GeneratedCFG.OpenCFG.join4ResolveThird WP.GeneratedCFG.OpenCFG.labels WP.GeneratedCFG.OpenCFG.mk)
export RiscvZkvm.Rv64 (WP.GeneratedCFG.OpenCFG.mk.inj WP.GeneratedCFG.OpenCFG.mk.injEq WP.GeneratedCFG.OpenCFG.mk.noConfusion WP.GeneratedCFG.OpenCFG.mk.sizeOf_spec)
export RiscvZkvm.Rv64 (WP.GeneratedCFG.OpenCFG.nSteps WP.GeneratedCFG.OpenCFG.nSteps.eq_1 WP.GeneratedCFG.OpenCFG.noConfusion WP.GeneratedCFG.OpenCFG.noConfusionType)
export RiscvZkvm.Rv64 (WP.GeneratedCFG.OpenCFG.ofBranch WP.GeneratedCFG.OpenCFG.ofBranchSpec WP.GeneratedCFG.OpenCFG.ofBranch_exits WP.GeneratedCFG.OpenCFG.ofCert)
export RiscvZkvm.Rv64 (WP.GeneratedCFG.OpenCFG.ofCert_exits WP.GeneratedCFG.OpenCFG.ofNBranch WP.GeneratedCFG.OpenCFG.ofNBranch_exits WP.GeneratedCFG.OpenCFG.pre)
export RiscvZkvm.Rv64 (WP.GeneratedCFG.OpenCFG.pre.eq_1 WP.GeneratedCFG.OpenCFG.rec WP.GeneratedCFG.OpenCFG.recOn WP.GeneratedCFG.OpenCFG.seqExitCertDisjoint)
export RiscvZkvm.Rv64 (WP.GeneratedCFG.OpenCFG.seqExitNBranchDisjoint WP.GeneratedCFG.OpenCFG.seqHeadCertDisjoint WP.GeneratedCFG.OpenCFG.seqHeadNBranchDisjoint WP.GeneratedCFG.OpenCFG.sound)
export RiscvZkvm.Rv64 (WP.GeneratedCFG.OpenCFG.weakenPosts WP.GeneratedCFG.OpenCFG.weakenPosts2 WP.GeneratedCFG.OpenCFG.weakenPosts3 WP.GeneratedCFG.OpenCFG.weakenPosts4)
export RiscvZkvm.Rv64 (WP.NBranch.mk.congr_simp WP.NBranch.seqExitNBranchDisjoint.eq_1 WP.NBranch.seqHeadNBranchDisjoint.eq_1)

-- Namespaces downstream files `open`; see render() for why these
-- cannot come from `export`.
namespace WP end WP
namespace WP.CFG end WP.CFG
namespace WP.CFG.nbranchSeqExitNBranchDisjoint end WP.CFG.nbranchSeqExitNBranchDisjoint
namespace WP.CFG.nbranchSeqHeadNBranchDisjoint end WP.CFG.nbranchSeqHeadNBranchDisjoint
namespace WP.GeneratedCFG end WP.GeneratedCFG
namespace WP.GeneratedCFG.Branch2Spec end WP.GeneratedCFG.Branch2Spec
namespace WP.GeneratedCFG.Branch2Spec.exits end WP.GeneratedCFG.Branch2Spec.exits
namespace WP.GeneratedCFG.Branch2Spec.mk end WP.GeneratedCFG.Branch2Spec.mk
namespace WP.GeneratedCFG.ExitSpec end WP.GeneratedCFG.ExitSpec
namespace WP.GeneratedCFG.ExitSpec.mk end WP.GeneratedCFG.ExitSpec.mk
namespace WP.GeneratedCFG.LoopNatSpec end WP.GeneratedCFG.LoopNatSpec
namespace WP.GeneratedCFG.LoopNatSpec.mk end WP.GeneratedCFG.LoopNatSpec.mk
namespace WP.GeneratedCFG.OpenCFG end WP.GeneratedCFG.OpenCFG
namespace WP.GeneratedCFG.OpenCFG.mk end WP.GeneratedCFG.OpenCFG.mk
namespace WP.GeneratedCFG.OpenCFG.nSteps end WP.GeneratedCFG.OpenCFG.nSteps
namespace WP.GeneratedCFG.OpenCFG.pre end WP.GeneratedCFG.OpenCFG.pre
namespace WP.NBranch end WP.NBranch
namespace WP.NBranch.mk end WP.NBranch.mk
namespace WP.NBranch.seqExitNBranchDisjoint end WP.NBranch.seqExitNBranchDisjoint
namespace WP.NBranch.seqHeadNBranchDisjoint end WP.NBranch.seqHeadNBranchDisjoint

end EvmAsm.Rv64
