-- GENERATED by scripts/gen-rv64-shims.py -- do not edit by hand.
--
-- `WP.Loop` now lives in the riscv-zkvm dependency, prebuilt.
-- This shim re-exports it so evm-asm's existing references keep resolving;
-- `export` aliases the SAME constants, so no statement changes meaning.
--
-- The original prelude is preserved deliberately -- aliases do not propagate
-- transitively, so those import edges are what let downstream files still see
-- the names they used to.  See original_prelude() for the full reasoning.
--
-- Regenerate with `scripts/gen-rv64-shims.py`; `--check` gates it in CI.
/-
  EvmAsm.Rv64.WP.Loop

  Bounded invariant/variant loop rule for the WP layer.  The rule does not
  infer control flow: callers provide the loop header branch, body triple,
  early-exit postcondition entailment, and final forced-exit triple.
-/

module

public import EvmAsm.Rv64.WP.Core
public import RiscvZkvm.Rv64.Logic.WP.Loop

@[expose] public section

namespace EvmAsm.Rv64

export RiscvZkvm.Rv64 (WP.Triple.ofLoopNatCert WP.loopBound WP.loopBound.eq_1 WP.loopBound.eq_2)
export RiscvZkvm.Rv64 (WP.loopBound.eq_def WP.loopBreakNatCert WP.loopBreakNatCert.eq_1 WP.loopBreakNatCert.eq_2)
export RiscvZkvm.Rv64 (WP.loopBreakNatCert.eq_def WP.loopBreakNatCert_sound WP.loopNatCert WP.loopNatCert.eq_1)
export RiscvZkvm.Rv64 (WP.loopNatCert.eq_2 WP.loopNatCert.eq_def WP.loopNatCert_sound)

-- Namespaces downstream files `open`; see render() for why these
-- cannot come from `export`.
namespace WP end WP
namespace WP.Triple end WP.Triple
namespace WP.loopBound end WP.loopBound
namespace WP.loopBreakNatCert end WP.loopBreakNatCert
namespace WP.loopNatCert end WP.loopNatCert

end EvmAsm.Rv64
