/-
  Axiom witnesses for `scripts/check-axioms.sh` (GH #10601, GH #11042).

  GENERATED by `scripts/gen-axiom-witnesses.py` from the witness abbrevs
  referenced in `EvmAsm/Progress.lean` (the `OpcodeEntry` registry) and
  `EvmAsm/Progress/Routines.lean` (the `RoutineEntry` registry of verified
  guest routines) — do not edit by hand; regenerate with
  `python3 scripts/gen-axiom-witnesses.py --write`.  The gate regenerates and
  diffs, so a stale file fails CI.

  This module exists so the axiom gate runs under `lake build` instead of
  a `lake env lean` scratch file: under the lake artifact cache,
  cache-satisfied modules have no materialized `.olean` on disk and
  `lake env lean` cannot resolve them (issue #10601, in the #10537
  family).  Building this module prints one `#print axioms` report per
  registry witness into the build log; lake replays messages on
  repeat (fully cached) builds, so the gate stays meaningful in cache
  mode and pays zero re-elaboration.

  Coverage note (#11042): the guest-routine half is a **partial** enumeration
  of the verified guest surface, not a complete one.  `EvmAsm/**` carries on
  the order of 1800 distinct `*_spec_within` names, most of them block-level
  rather than whole-routine, so populating every one is not a single change.
  What is registered is witnessed; what is not registered is still outside the
  gate.  Stated here rather than left implicit, because the assumption this
  file exists to break is "covered by CI".  #11290 tracks turning that residual
  into a measured coverage number rather than prose.  As of #11289 all three
  registries are strict, so within a *registered* file an unwitnessed row is a
  build error — the gap is only in what has not been registered yet.
-/
import EvmAsm.Progress
import EvmAsm.Progress.Routines
import EvmAsm.Progress.Correspondence

#print axioms EvmAsm.Codegen.AccountDecodeCompose.decoded_matches_specRef

#print axioms EvmAsm.Codegen.AccountDecodeCompose.outputSuccess_eq_accountDecodedIs

#print axioms EvmAsm.Codegen.AccountDecodeCorrespondence.adEmptyCodeHashBytes_eq_aie

#print axioms EvmAsm.Codegen.AccountDecodeCorrespondence.adEmptyCodeHashBytes_eq_spec

#print axioms EvmAsm.Codegen.AccountDecodeCorrespondence.adEmptyCodeHashBytes_value

#print axioms EvmAsm.Codegen.AccountDecodeCorrespondence.adEmptyTrieRootBytes_eq_spec

#print axioms EvmAsm.Codegen.AccountDecodeCorrespondence.adEmptyTrieRootBytes_value

#print axioms EvmAsm.Codegen.AccountDecodeCorrespondence.aieEmptyCodeHashBytes_value

#print axioms EvmAsm.Codegen.AccountDecodeSpec.account_decode_spec_within

#print axioms EvmAsm.Codegen.AccountIsEip161EmptySpec.account_is_eip161_empty_spec_within

#print axioms EvmAsm.Codegen.AccountIsEip161EmptySpec.leniency_agrees

#print axioms EvmAsm.Codegen.AccountNonceGateCover.account_nonce_is_an_unbounded_nat

#print axioms EvmAsm.Codegen.AccountNonceGateCover.nonce_gate_admits_ordinary

#print axioms EvmAsm.Codegen.AccountNonceGateCover.nonce_gate_boundary

#print axioms EvmAsm.Codegen.AccountNonceGateCover.nonce_gate_middle_band_is_inhabited

#print axioms EvmAsm.Codegen.AccountNonceGateCover.nonce_regimes_exhaustive

#print axioms EvmAsm.Codegen.AccountWalkGateCover.scalarGate_admits_ordinary

#print axioms EvmAsm.Codegen.AccountWalkGateCover.scalarGate_boundary

#print axioms EvmAsm.Codegen.AccountWalkGateCover.scalarGate_iff

#print axioms EvmAsm.Codegen.AccountWalkGateCover.walkInitLong1_band

#print axioms EvmAsm.Codegen.AccountWalkGateCover.walkInitLong1_band_ends_inhabited

#print axioms EvmAsm.Codegen.AccountWalkGateCover.walkInitLong1_excludes_256

#print axioms EvmAsm.Codegen.AccountWalkGateCover.walkInitLong1_excludes_55

#print axioms EvmAsm.Codegen.AccountWalkGateCover.walkInitLong1_upper_bound_is_implicit

#print axioms EvmAsm.Codegen.AddressFromPubkeySpec.addressFromPubkey_spec_within

#print axioms EvmAsm.Codegen.AmbientFree.bncIsInf64FlatEntry_spec

#print axioms EvmAsm.Codegen.AmbientFree.bnfIsZero32FlatEntry_spec

#print axioms EvmAsm.Codegen.AmbientFree.secfIsZero32FlatEntry_spec

#print axioms EvmAsm.Codegen.AmbientFree.secfZero32FlatEntry_spec

#print axioms EvmAsm.Codegen.AmbientLifted.blsgEq48Flat_instance

#print axioms EvmAsm.Codegen.AmbientLifted.blsgEq48Flat_spec

#print axioms EvmAsm.Codegen.AmbientLifted.bnfEq32Flat_spec

#print axioms EvmAsm.Codegen.AmbientLifted.p256Eq32Flat_spec

#print axioms EvmAsm.Codegen.AmbientLifted.secfEq32Flat_spec

#print axioms EvmAsm.Codegen.AmsterdamBlobGasPriceAbiShell.amsterdam_blob_gas_price_abi_from_body

#print axioms EvmAsm.Codegen.AmsterdamBlobGasPriceAbiShell.amsterdam_blob_gas_price_prog_eq_abiFrameProg

#print axioms EvmAsm.Codegen.AmsterdamBlobGasPriceBody14Spec.taylor_round

#print axioms EvmAsm.Codegen.AmsterdamBlobGasPriceBody2Spec.mul6_core

#print axioms EvmAsm.Codegen.AmsterdamBlobGasPriceBody4Spec.swapdiv_core

#print axioms EvmAsm.Codegen.AmsterdamBlobGasPriceBody6Spec.exitdiv_core

#print axioms EvmAsm.Codegen.AmsterdamBlobGasPriceBody7Spec.tail_copyarm

#print axioms EvmAsm.Codegen.AmsterdamBlobGasPriceBody7Spec.tail_core

#print axioms EvmAsm.Codegen.AmsterdamBlobGasPriceBodySpec.add6_carry_branch

#print axioms EvmAsm.Codegen.AmsterdamBlobGasPriceBodySpec.add6_core

#print axioms EvmAsm.Codegen.AmsterdamBlobGasPriceBodySpec.loop_test_beqz_branch

#print axioms EvmAsm.Codegen.AmsterdamBlobGasPriceBodySpec.loop_test_bgeu_branch

#print axioms EvmAsm.Codegen.AmsterdamBlobGasPriceBodySpec.loop_test_or_chain_spec

#print axioms EvmAsm.Codegen.AmsterdamBlobGasPriceBodySpec.price_setup_spec

#print axioms EvmAsm.Codegen.AmsterdamBlobGasPriceDivisionBridge.divst384by64_eq_div384by64

#print axioms EvmAsm.Codegen.AmsterdamBlobGasPriceDivisionBridge.divstLimbFrom_eq_divLimbFrom

#print axioms EvmAsm.Codegen.AmsterdamBlobGasPriceDivisionBridge.divstSix_eq_div384by64

#print axioms EvmAsm.Codegen.AmsterdamBlobGasPriceDivisionBridge.divst_eq_divBitRun

#print axioms EvmAsm.Codegen.AmsterdamBlobGasPricePriceContractWitness.priceContract_ex0_inhabited

#print axioms EvmAsm.Codegen.AmsterdamBlobGasPricePriceContractWitness.taylor_price_contract_excess0_inhabited

#print axioms EvmAsm.Codegen.AmsterdamBlobGasPriceTaylorTie.taylor_price_entry_inhabited

#print axioms EvmAsm.Codegen.AmsterdamBlobGasPriceTaylorTie.taylor_price_outcome_zero

#print axioms EvmAsm.Codegen.AmsterdamBlobGasPriceTaylorTie.taylor_price_outcome_zero_bytes_length

#print axioms EvmAsm.Codegen.AmsterdamBlobGasPriceTaylorTie.taylor_price_outcomes_discriminate

#print axioms EvmAsm.Codegen.AssembleExecutionRequestsTop.aer_gate_buffer_too_short

#print axioms EvmAsm.Codegen.AssembleExecutionRequestsTop.aer_gate_not_8aligned

#print axioms EvmAsm.Codegen.AssembleExecutionRequestsTop.aer_gate_reachable

#print axioms EvmAsm.Codegen.AssembleExecutionRequestsTop.assemble_execution_requests_spec_within

#print axioms EvmAsm.Codegen.BalCanonicalSortDigitSpec.balCanonicalKey_getD_head

#print axioms EvmAsm.Codegen.BalCanonicalSortDigitSpec.balCanonicalKey_getD_tail

#print axioms EvmAsm.Codegen.BalCanonicalSortDigitSpec.balDigitAgree_1seg

#print axioms EvmAsm.Codegen.BalCanonicalSortDigitSpec.balDigitAgree_2seg

#print axioms EvmAsm.Codegen.BalCanonicalSortDigitSpec.balDigitAgree_2seg_live

#print axioms EvmAsm.Codegen.BalCanonicalSortDigitSpec.balDigit_at_67

#print axioms EvmAsm.Codegen.BalGasValidU64SAsm.bgvU64leFlat_spec

#print axioms EvmAsm.Codegen.BalSerializerLeFlatEntry.balSerializerBalanceToLeFlat_spec

#print axioms EvmAsm.Codegen.BalSerializerLeFlatEntry.balSerializerSlotToLeFlat_spec

#print axioms EvmAsm.Codegen.Blake2fLoadLe64SAsm.blk2LdLe64Flat_spec

#print axioms EvmAsm.Codegen.Blake2fStoreLe64SAsm.blk2StLe64Flat_spec

#print axioms EvmAsm.Codegen.BlockAccessListHashBahOffset.bahCr_eq_flatCr

#print axioms EvmAsm.Codegen.BlockAccessListHashBahOffset.bah_u32le_call_site_pointers_unaligned

#print axioms EvmAsm.Codegen.BlockAccessListHashBahOffset.bah_u32le_offset_align_bites

#print axioms EvmAsm.Codegen.BlockAccessListHashBahOffset.bah_u32le_offset_precondition_reachable

#print axioms EvmAsm.Codegen.BlockAccessListHashBahOffset.bah_u32le_offset_spec_within

#print axioms EvmAsm.Codegen.BlockAccessListHashCoreSpec.blockAccessListHashCore_precondition_negative_control

#print axioms EvmAsm.Codegen.BlockAccessListHashCoreSpec.blockAccessListHashCore_precondition_reachable

#print axioms EvmAsm.Codegen.BlockAccessListHashCoreSpec.block_access_list_hash_core_spec_within

#print axioms EvmAsm.Codegen.BlockAccessListHashSAsm.bahU32leFlat_spec

#print axioms EvmAsm.Codegen.BlockHashFromHeaderSpec.block_hash_from_header_headerHash_within

#print axioms EvmAsm.Codegen.BlockHashFromHeaderSpec.block_hash_from_header_spec_within

#print axioms EvmAsm.Codegen.BlockHashFromHeaderSpec.keccakBodyDigest_encode_eq_headerHash

#print axioms EvmAsm.Codegen.BlockHashFromHeaderSpec.keccakBodyDigest_eq_headerHash_of_decode

#print axioms EvmAsm.Codegen.BlockHashFromWitnessHeadersSpec.blockhash_from_witness_headers_spec_within_empty_section

#print axioms EvmAsm.Codegen.BloomEqSAsm.bloomEq_spec

#print axioms EvmAsm.Codegen.BloomOrIntoSAsm.bloomOrIntoFlat_spec

#print axioms EvmAsm.Codegen.BloomOrIntoSAsm.bloomOrIntoFn_spec

#print axioms EvmAsm.Codegen.BloomOrIntoSAsm.bloomOrInto_fold_eq_logs_bloom

#print axioms EvmAsm.Codegen.Bls12FieldCopyQuadsSAsm.blsfCopyQuadsFlat_spec

#print axioms EvmAsm.Codegen.Bls12Fq12CopySAsm.blqCopyFlat_spec

#print axioms EvmAsm.Codegen.Bls12Fq12EqSAsm.blqEq_spec

#print axioms EvmAsm.Codegen.Bls12Fq12IsZeroSAsm.blqIsZeroFlat_spec

#print axioms EvmAsm.Codegen.Bls12Fq12SetOneSAsm.blqSetOneFrame_spec

#print axioms EvmAsm.Codegen.Bls12Fq12Zero576SAsm.blqZeroFlat_spec

#print axioms EvmAsm.Codegen.Bls12G1BeToLeSAsm.blsgBeToLeFlat_spec

#print axioms EvmAsm.Codegen.Bls12G1Copy96SAsm.blsgCopy96Flat_spec

#print axioms EvmAsm.Codegen.Bls12G1IsZeroNSAsm.blsgIsZeroNFlat_spec

#print axioms EvmAsm.Codegen.Bls12G1LeToBeSAsm.blsgLeToBeFlat_spec

#print axioms EvmAsm.Codegen.Bls12G1LtPSAsm.blsgLtP_spec

#print axioms EvmAsm.Codegen.Bls12G1Zero96SAsm.blsgZero96Flat_spec

#print axioms EvmAsm.Codegen.Bls12G2Copy192SAsm.blsg2Copy192Frame_spec

#print axioms EvmAsm.Codegen.Bls12G2EncodeSAsm.blsg2Encode_spec

#print axioms EvmAsm.Codegen.Bls12G2EqNSAsm.blsg2EqN_spec

#print axioms EvmAsm.Codegen.Bls12G2Zero192SAsm.blsg2Zero192Flat_spec

#print axioms EvmAsm.Codegen.Bls12KzgG2WireSAsm.blskG2Wire_spec

#print axioms EvmAsm.Codegen.Bls12KzgLtBeSAsm.blskLtBe_spec

#print axioms EvmAsm.Codegen.Bls12PtCopySAsm.blqPtCopyFlat_spec

#print axioms EvmAsm.Codegen.Bn254CallAllotmentSAsm.bn254CallAllotment_spec

#print axioms EvmAsm.Codegen.Bn254CurveCopySAsm.bncCopy64Flat_spec

#print axioms EvmAsm.Codegen.Bn254CurveZeroSAsm.bncZero64Flat_spec

#print axioms EvmAsm.Codegen.Bn254FieldAddModPSAsm.bnfAddModP_spec

#print axioms EvmAsm.Codegen.Bn254FieldConvSAsm.bnfBeToLeFlatEntry_spec

#print axioms EvmAsm.Codegen.Bn254FieldConvSAsm.bnfLeToBeFlatEntry_spec

#print axioms EvmAsm.Codegen.Bn254FieldLtPSAsm.bnfLtP_spec

#print axioms EvmAsm.Codegen.Bn254FieldMulModPSAsm.bnfMulModP_spec

#print axioms EvmAsm.Codegen.Bn254Fp2CopySAsm.bnpFp2CopyFlat_spec

#print axioms EvmAsm.Codegen.Bn254Fp2EqSAsm.bnpFp2Eq_spec

#print axioms EvmAsm.Codegen.Bn254Fp2IsZeroSAsm.bnpFp2IsZeroFlat_spec

#print axioms EvmAsm.Codegen.Bn254Fp2ZeroSAsm.bnpFp2ZeroFlat_spec

#print axioms EvmAsm.Codegen.Bn254Fq12CopySAsm.bnqCopyFlat_spec

#print axioms EvmAsm.Codegen.Bn254Fq12EqSAsm.bnqEq_spec

#print axioms EvmAsm.Codegen.Bn254Fq12IsZeroSAsm.bnqIsZeroFlat_spec

#print axioms EvmAsm.Codegen.Bn254Fq12SetOneSAsm.bnqSetOneFrame_spec

#print axioms EvmAsm.Codegen.Bn254Fq12ZeroSAsm.bnqZeroFlatEntry_spec

#print axioms EvmAsm.Codegen.Bn254PtCopySAsm.bnqPtCopyFlat_spec

#print axioms EvmAsm.Codegen.BytesToNibblesSAsm.bytesToNibblesFlat_spec

#print axioms EvmAsm.Codegen.CallFrameBaseSAsm.frameBase_spec

#print axioms EvmAsm.Codegen.CallFrameCalldataFlat.callFrameSetCalldataFlat_spec

#print axioms EvmAsm.Codegen.CallFrameForwardGasSAsm.callFrameForwardGasFlat_spec

#print axioms EvmAsm.Codegen.ChainValidatePostMergeFullSpec.chain_validate_post_merge_full_spec_within_empty

#print axioms EvmAsm.Codegen.ChainValidatePostMergeFullSpec.cvpmfEmptyOmmerHashBytes_value

#print axioms EvmAsm.Codegen.ChainValidatePostMergeFullSpec.nonce_rule_agrees

#print axioms EvmAsm.Codegen.CheckGasLimitSAsm.checkGasLimit_ref_spec

#print axioms EvmAsm.Codegen.DCodeLeafFlatEntries.eddBe32EqFlat_spec

#print axioms EvmAsm.Codegen.DCodeLeafFlatEntries.eddMemcpyFlat_spec

#print axioms EvmAsm.Codegen.DCodeLeafFlatEntries.modexpIszeroFlat_spec

#print axioms EvmAsm.Codegen.DispatcherCaptureExecStateGasSAsm.dispatcherCaptureExecStateGas_spec

#print axioms EvmAsm.Codegen.DivisorAndPadGateCover.divisorGate_admits_eight

#print axioms EvmAsm.Codegen.DivisorAndPadGateCover.divisorGate_excludes_only_zero

#print axioms EvmAsm.Codegen.DivisorAndPadGateCover.divisorGate_iff

#print axioms EvmAsm.Codegen.DivisorAndPadGateCover.divisorGate_upper_bound_is_free

#print axioms EvmAsm.Codegen.DivisorAndPadGateCover.padGate_is_load_bearing

#print axioms EvmAsm.Codegen.DivisorAndPadGateCover.padGate_separates_the_pair

#print axioms EvmAsm.Codegen.Eip7702AuthSigningHashSpec.authCallSite_ok_sample

#print axioms EvmAsm.Codegen.Eip7702AuthSigningHashSpec.authJal_target

#print axioms EvmAsm.Codegen.Eip7702AuthSigningHashSpec.authSigningPreimage_segments

#print axioms EvmAsm.Codegen.Eip7702AuthSigningHashSpec.eip7702AuthorizationSigningHash_prog_eq_frame

#print axioms EvmAsm.Codegen.Eip7702AuthSigningHashSpec.eip7702_authorization_signing_hash_spec_within

#print axioms EvmAsm.Codegen.Eip7702AuthSigningHashSpec.recover_authority_unfold

#print axioms EvmAsm.Codegen.Eip7702AuthSigningHashSpec.sampleAuth_decodes

#print axioms EvmAsm.Codegen.Eip7702AuthSigningHashSpec.sampleAuth_preimage

#print axioms EvmAsm.Codegen.Eip7702NonceReuseGuardSAsm.enrgU32leFlat_spec

#print axioms EvmAsm.Codegen.Eip8037TxStateGasSpec.eip8037TxStateGas_spec_within

#print axioms EvmAsm.Codegen.EphU32leSAsm.ephU32leFlat_spec

#print axioms EvmAsm.Codegen.ExecutionRequestsHashBgvOffset.bgv_u32le_offset_precondition_reachable

#print axioms EvmAsm.Codegen.ExecutionRequestsHashBgvOffset.bgv_u32le_offset_spec_within

#print axioms EvmAsm.Codegen.ExecutionRequestsHashHashOneNonemptyTop.erh_hash_one_spec_within_nonempty

#print axioms EvmAsm.Codegen.ExecutionRequestsHashHashOneTop.erh_hash_one_spec_within_empty

#print axioms EvmAsm.Codegen.ExecutionRequestsHashVal.erh_validation_precondition_reachable

#print axioms EvmAsm.Codegen.ExecutionRequestsHashWrap.execution_requests_hash_validation_accept

#print axioms EvmAsm.Codegen.ExtractDepositDataFailSpec.extractDepositData_lenFail_spec

#print axioms EvmAsm.Codegen.ExtractDepositDataOkSpec.extractDepositData_ok_spec

#print axioms EvmAsm.Codegen.ExtractDepositDataOkSpec.extractDepositData_reject10_spec

#print axioms EvmAsm.Codegen.ExtractDepositDataOkSpec.extractDepositData_reject1_spec

#print axioms EvmAsm.Codegen.ExtractDepositDataUnified.extractDepositData_probe_spec

#print axioms EvmAsm.Codegen.ExtractDepositDataUnified.extractDepositData_spec

#print axioms EvmAsm.Codegen.FrameDepthPopSAsm.frameDepthPop_spec

#print axioms EvmAsm.Codegen.FrameDepthPushSAsm.frameDepthPush_spec

#print axioms EvmAsm.Codegen.FrameLoadRegsSAsm.frameLoadRegs_spec

#print axioms EvmAsm.Codegen.FrameSaveRegsSAsm.frameSaveRegs_spec

#print axioms EvmAsm.Codegen.HeaderArityCheckTie.arity_extent

#print axioms EvmAsm.Codegen.HeaderArityCheckTie.arity_gate_within

#print axioms EvmAsm.Codegen.HeaderArityCheckTie.arity_premises_refutable

#print axioms EvmAsm.Codegen.HeaderArityCheckTie.dispatchTarget_values

#print axioms EvmAsm.Codegen.HeaderArityCheckTie.dispatch_instance_12

#print axioms EvmAsm.Codegen.HeaderArityCheckTie.dispatch_instance_6

#print axioms EvmAsm.Codegen.HeaderArityCheckTie.dispatch_probe_within

#print axioms EvmAsm.Codegen.HeaderArityCheckTie.dispatch_spec_within

#print axioms EvmAsm.Codegen.HeaderArityCheckTie.dispatch_step

#print axioms EvmAsm.Codegen.HeaderArityCheckTie.dispatch_then_arm_0

#print axioms EvmAsm.Codegen.HeaderArityCheckTie.dispatch_then_arm_6

#print axioms EvmAsm.Codegen.HeaderArityCheckTie.dispatch_then_arm_within

#print axioms EvmAsm.Codegen.HeaderArityCheckTie.epilogue_spec_within

#print axioms EvmAsm.Codegen.HeaderArityCheckTie.fail_exit_instance

#print axioms EvmAsm.Codegen.HeaderArityCheckTie.fail_exit_spec_within

#print axioms EvmAsm.Codegen.HeaderArityCheckTie.len_arm_20_within

#print axioms EvmAsm.Codegen.HeaderArityCheckTie.len_arm_256_within

#print axioms EvmAsm.Codegen.HeaderArityCheckTie.len_arm_32_within

#print axioms EvmAsm.Codegen.HeaderArityCheckTie.len_arm_8_within

#print axioms EvmAsm.Codegen.HeaderArityCheckTie.len_check_arm_within

#print axioms EvmAsm.Codegen.HeaderArityCheckTie.loop_backedge_within

#print axioms EvmAsm.Codegen.HeaderArityCheckTie.loop_guard_within

#print axioms EvmAsm.Codegen.HeaderArityCheckTie.loop_measure_decreases

#print axioms EvmAsm.Codegen.HeaderArityCheckTie.ok_exit_instance

#print axioms EvmAsm.Codegen.HeaderArityCheckTie.ok_exit_spec_within

#print axioms EvmAsm.Codegen.HeaderBaseFeeSpec.k73_increase_entry_status_div_zero_clamp_live_spec_within

#print axioms EvmAsm.Codegen.HeaderBaseFeeSpec.k73_increase_entry_status_div_zero_live_spec_within

#print axioms EvmAsm.Codegen.HeaderBaseFeeSpec.k73_increase_entry_to_mul_spec_within

#print axioms EvmAsm.Codegen.HeaderBaseFeeSpec.k73_increase_first_div_source_branch_for_return

#print axioms EvmAsm.Codegen.HeaderBaseFeeSpec.k73_increase_second_add_branch_for_return

#print axioms EvmAsm.Codegen.HeaderBaseFeeSpec.k73_increase_second_div_source_branch_for_return

#print axioms EvmAsm.Codegen.HeaderBaseFeeSpec.k73_increase_status_div_zero_spec_within_for_return

#print axioms EvmAsm.Codegen.HeaderDecodeNoPrefixTest.arity_check_has_no_subword_load

#print axioms EvmAsm.Codegen.HeaderDecodeNoPrefixTest.control_branches_on_the_loaded_register

#print axioms EvmAsm.Codegen.HeaderDecodeNoPrefixTest.control_has_a_subword_load

#print axioms EvmAsm.Codegen.HeaderDecodeNoPrefixTest.never_branches_on_x6

#print axioms EvmAsm.Codegen.HeaderDecodeNoPrefixTest.subword_loads_write_x6

#print axioms EvmAsm.Codegen.HeaderExtendedDecodeCopy.copy_loop_hyps_refutable

#print axioms EvmAsm.Codegen.HeaderExtendedDecodeCopy.copy_loop_spec_within

#print axioms EvmAsm.Codegen.HeaderExtendedDecodeCopy.parent_hash_copy_content

#print axioms EvmAsm.Codegen.HeaderExtendedDecodeCopy.parent_hash_copy_instance

#print axioms EvmAsm.Codegen.HeaderExtendedDecodeCopy.parent_hash_copy_spec_within

#print axioms EvmAsm.Codegen.HeaderExtendedDecodeCopy.state_root_copy_instance

#print axioms EvmAsm.Codegen.HeaderExtendedDecodeCopy.state_root_copy_spec_within

#print axioms EvmAsm.Codegen.HeaderExtendedDecodeWalkSite.decoder_init_disjoint

#print axioms EvmAsm.Codegen.HeaderExtendedDecodeWalkSite.decoder_walk_disjoint

#print axioms EvmAsm.Codegen.HeaderExtendedDecodeWalkSite.walkPre_instance

#print axioms EvmAsm.Codegen.HeaderExtendedDecodeWalkSite.walkPre_refutable_on_empty_span

#print axioms EvmAsm.Codegen.HeaderExtendedDecodeWalkSite.walkPre_refutable_on_list

#print axioms EvmAsm.Codegen.HeaderExtendedDecodeWalkSite.walk_init_site_instance

#print axioms EvmAsm.Codegen.HeaderExtendedDecodeWalkSite.walk_init_site_spec_within

#print axioms EvmAsm.Codegen.HeaderExtendedDecodeWalkSite.walk_next_site_56_instance

#print axioms EvmAsm.Codegen.HeaderExtendedDecodeWalkSite.walk_next_site_56_spec_within

#print axioms EvmAsm.Codegen.HeaderExtendedDecodeWalkSite.walk_next_site_624_spec_within

#print axioms EvmAsm.Codegen.HeaderExtendedDecodeWalkSite.walk_next_site_composed_within

#print axioms EvmAsm.Codegen.HeaderExtractLogsBloomSpec.headerExtractLogsBloom_spec_within

#print axioms EvmAsm.Codegen.HeaderExtractLogsBloomSpec.header_logs_bloom_of_decode

#print axioms EvmAsm.Codegen.HeaderExtractNumberSpec.header_extract_number_spec_within

#print axioms EvmAsm.Codegen.HeaderExtractNumberSpec.header_number_of_decode

#print axioms EvmAsm.Codegen.HeaderFieldsHboundCover.hbound_fails_under_slack_only

#print axioms EvmAsm.Codegen.HeaderFieldsHboundCover.hbound_forces_trailing_slack

#print axioms EvmAsm.Codegen.HeaderFieldsHboundCover.hbound_instance

#print axioms EvmAsm.Codegen.HeaderFieldsHboundCover.hbound_instance_has_a_decode

#print axioms EvmAsm.Codegen.HeaderFieldsHboundCover.hbound_vacuous_control

#print axioms EvmAsm.Codegen.HeaderFieldsHboundCover.next_sub_len_classified

#print axioms EvmAsm.Codegen.HeaderFieldsSpec.header_extract_state_root_spec_within

#print axioms EvmAsm.Codegen.HeaderReceiptsRootSpec.header_extract_receipts_root_spec_within

#print axioms EvmAsm.Codegen.HeaderU64ExtractSpec.header_extended_decode_u64_segment_spec_within

#print axioms EvmAsm.Codegen.HeaderU64ExtractSpec.header_extended_decode_u64_site_324_spec_within

#print axioms EvmAsm.Codegen.HeaderU64ExtractSpec.header_extended_decode_u64_site_364_spec_within

#print axioms EvmAsm.Codegen.HeaderU64ExtractSpec.header_extended_decode_u64_site_404_spec_within

#print axioms EvmAsm.Codegen.HeaderU64ExtractSpec.header_extended_decode_u64_site_444_spec_within

#print axioms EvmAsm.Codegen.HeaderU64ExtractSpec.header_extended_decode_u64_site_604_spec_within

#print axioms EvmAsm.Codegen.HeaderU64ExtractSpec.header_extended_decode_u64_site_644_spec_within

#print axioms EvmAsm.Codegen.HeaderU64ExtractSpec.header_extended_decode_u64_site_composed_within

#print axioms EvmAsm.Codegen.HeaderU64ExtractSpec.header_extended_decode_u64_site_instance

#print axioms EvmAsm.Codegen.HeaderU64ExtractSpec.header_extended_decode_u64_site_negative_control

#print axioms EvmAsm.Codegen.HeaderValidateBaseFeeCompositionDecreaseRoute.k73_decr_entry_status_native_inhabited

#print axioms EvmAsm.Codegen.HeaderValidateBaseFeeCompositionDecreaseRoute.k73_decr_route_adapter_inhabited

#print axioms EvmAsm.Codegen.HeaderValidateBaseFeeCompositionIncreaseRoute.k73_incr_route_adapter_inhabited

#print axioms EvmAsm.Codegen.HeaderValidateBaseFeeMulNativeContract.k73_mul_call_native_spec_within

#print axioms EvmAsm.Codegen.HeaderValidateBaseFeeMulNativeContract.k73_mul_status_branch_native_inhabited

#print axioms EvmAsm.Codegen.HeaderValidateBaseFeeMulNativeContract.k73_mul_status_branch_native_spec_within

#print axioms EvmAsm.Codegen.HeaderValidateBaseFeeSpecRef.header_validate_base_fee_spec_within_inhabited

#print axioms EvmAsm.Codegen.HeaderValidateBaseFeeSpecRef.k73_routeB_post_success_split

#print axioms EvmAsm.Codegen.HeaderValidateExtraDataLengthSpec.header_extra_data_length_of_decode

#print axioms EvmAsm.Codegen.HeaderValidateExtraDataLengthSpec.header_validate_extra_data_length_spec_within

#print axioms EvmAsm.Codegen.HeaderValidateParentHashSpec.header_validate_parent_hash_extract_fail_cover

#print axioms EvmAsm.Codegen.HeaderValidateParentHashSpec.header_validate_parent_hash_match_cover

#print axioms EvmAsm.Codegen.HeaderValidateParentHashSpec.header_validate_parent_hash_mismatch2_cover

#print axioms EvmAsm.Codegen.HeaderValidateParentHashSpec.header_validate_parent_hash_spec_within

#print axioms EvmAsm.Codegen.HeaderValidatePostMergeCorrespondenceBridge.k67GuardOk_constructive_witness

#print axioms EvmAsm.Codegen.HeaderValidatePostMergeCorrespondenceBridge.k67GuardOk_decode_header

#print axioms EvmAsm.Codegen.HeaderValidatePostMergeLoopSpec.header_validate_post_merge_spec_within

#print axioms EvmAsm.Codegen.HeaderWithdrawalsRootSpec.header_extract_withdrawals_root_spec_within

#print axioms EvmAsm.Codegen.HpDecodeNibblesSAsm.hp_decode_nibbles_spec_ported

#print axioms EvmAsm.Codegen.HpEncodeNibblesSAsm.hpEncodeNibblesFlat_spec

#print axioms EvmAsm.Codegen.MptNodeKindSpec.mpt_node_kind_precondition_reachable

#print axioms EvmAsm.Codegen.MptNodeKindSpec.mpt_node_kind_spec_within

#print axioms EvmAsm.Codegen.MptNodeKindWire.mptNodeKindResult_eq_kindTag

#print axioms EvmAsm.Codegen.MptNodeKindWire.mptNodeKindResult_exists_kindTag

#print axioms EvmAsm.Codegen.MptResolveCacheResetSAsm.mptResolveCacheReset_spec

#print axioms EvmAsm.Codegen.MptWalkSpec.branch_wl_enabled_empty_establishes_shape

#print axioms EvmAsm.Codegen.MptWalkSpec.branch_wl_enabled_hit_establishes_shape

#print axioms EvmAsm.Codegen.MptWalkSpec.ext_wl_enabled_empty_establishes_shape

#print axioms EvmAsm.Codegen.MptWalkSpec.ext_wl_enabled_hit_establishes_shape

#print axioms EvmAsm.Codegen.MptWalkSpec.root_wl_enabled_empty_establishes_shape

#print axioms EvmAsm.Codegen.MptWalkSpec.root_wl_enabled_hit_establishes_shape

#print axioms EvmAsm.Codegen.MptWalkSpec.root_wl_enabled_hit_shape_sat

#print axioms EvmAsm.Codegen.MptWalkSpec.root_wl_enabled_hit_shape_wrong_offset_false

#print axioms EvmAsm.Codegen.MptWalkWlEnabledHitSat.hit_site_entryState_exists

#print axioms EvmAsm.Codegen.MptWalkWlEnabledHitSat.sample_site_shape

#print axioms EvmAsm.Codegen.NodeDbAppendSpec.lookup_db_view_eq

#print axioms EvmAsm.Codegen.NodeDbAppendSpec.nodeDbAppend_align_bites

#print axioms EvmAsm.Codegen.NodeDbAppendSpec.nodeDbAppend_pad_zero_bites

#print axioms EvmAsm.Codegen.NodeDbAppendSpec.nodeDbAppend_precondition_reachable

#print axioms EvmAsm.Codegen.NodeDbAppendSpec.nodeDbAppend_validity_negative_control

#print axioms EvmAsm.Codegen.NodeDbAppendSpec.node_db_append_grows_db

#print axioms EvmAsm.Codegen.NodeDbAppendSpec.node_db_append_sample_witness

#print axioms EvmAsm.Codegen.NodeDbAppendSpec.node_db_append_spec_within

#print axioms EvmAsm.Codegen.NodeDbLookupSpec.node_db_lookup_result_eq_build_node_db

#print axioms EvmAsm.Codegen.NodeDbLookupSpec.node_db_lookup_sample_witness

#print axioms EvmAsm.Codegen.NodeDbLookupSpec.node_db_lookup_spec_within

#print axioms EvmAsm.Codegen.P256BeToLeSAsm.p256BeToLeFlat_spec

#print axioms EvmAsm.Codegen.P256CopyNSAsm.p256CopyNFlat_spec

#print axioms EvmAsm.Codegen.P256IsZeroNSAsm.p256IsZeroNFlat_spec

#print axioms EvmAsm.Codegen.P256LeToBeSAsm.p256LeToBeFlat_spec

#print axioms EvmAsm.Codegen.P256LtBeSAsm.p256LtBe_spec

#print axioms EvmAsm.Codegen.Proofs.accountReadRecordSuppressedFlat_spec

#print axioms EvmAsm.Codegen.Proofs.bacpArena_exact_region_unobtainable

#print axioms EvmAsm.Codegen.Proofs.bacpArena_hyps_hold

#print axioms EvmAsm.Codegen.Proofs.balAccountPath_keccak_arena_call_available

#print axioms EvmAsm.Codegen.Proofs.deriveConsolidationRequestsFlat_spec

#print axioms EvmAsm.Codegen.Proofs.deriveWithdrawalRequestsFlat_spec

#print axioms EvmAsm.Codegen.Proofs.envelope_region_sat

#print axioms EvmAsm.Codegen.Proofs.envelope_sat_and_exact_fails

#print axioms EvmAsm.Codegen.Proofs.exactRegion_false_on_nonzero_tail

#print axioms EvmAsm.Codegen.Proofs.exact_region_zero_pads_but_envelope_does_not

#print axioms EvmAsm.Codegen.Proofs.keccakBodyDigest_div_eq_specref

#print axioms EvmAsm.Codegen.Proofs.keccakBodyDigest_eq_specref

#print axioms EvmAsm.Codegen.Proofs.kssDigest_eq_specref_any

#print axioms EvmAsm.Codegen.Proofs.kss_sample_witness_multi

#print axioms EvmAsm.Codegen.Proofs.readSetsDiscardTxFlat_spec

#print axioms EvmAsm.Codegen.Proofs.secfSquareModNFlat_spec

#print axioms EvmAsm.Codegen.Proofs.secfSquareModPFlat_spec

#print axioms EvmAsm.Codegen.Proofs.sha256Frame_spec

#print axioms EvmAsm.Codegen.Proofs.sha256FullBlockLoop_reload_spec

#print axioms EvmAsm.Codegen.Proofs.sha256FullBlockPrefix_spec

#print axioms EvmAsm.Codegen.Proofs.sha256SetupMoves_spec

#print axioms EvmAsm.Codegen.Proofs.u256IsZeroFlat_spec

#print axioms EvmAsm.Codegen.Proofs.wcidxCmp32Entry_spec

#print axioms EvmAsm.Codegen.Proofs.wcidxRecordPtrFlat_spec

#print axioms EvmAsm.Codegen.Proofs.widxCmp32Entry_spec

#print axioms EvmAsm.Codegen.Proofs.widxRecordPtrEntry_spec

#print axioms EvmAsm.Codegen.Proofs.widxSwapRecordsEntry_spec

#print axioms EvmAsm.Codegen.Proofs.writeSetsDiscardTxFlat_spec

#print axioms EvmAsm.Codegen.Proofs.zkvm_keccak256_segments_spec_within

#print axioms EvmAsm.Codegen.Proofs.zkvm_keccak256_spec_within

#print axioms EvmAsm.Codegen.Proofs.zkvm_keccak256_spec_within_arena_slice

#print axioms EvmAsm.Codegen.Proofs.zkvm_sha256_spec_within

#print axioms EvmAsm.Codegen.ReceiptExtractLogsBloomSpec.receiptExtractLogsBloom_spec_within

#print axioms EvmAsm.Codegen.RequestsHashVerifyTop.requests_hash_verify_spec_within

#print axioms EvmAsm.Codegen.RequestsHashVerifyTop.rhvHash_gate

#print axioms EvmAsm.Codegen.RequestsHashVerifyTop.rhv_gate_reachable

#print axioms EvmAsm.Codegen.RequestsHashVerifyTop.rhv_gate_short_expected

#print axioms EvmAsm.Codegen.RequestsHashVerifyTop.rhv_gate_unaligned

#print axioms EvmAsm.Codegen.RequestsHashVerifyTop.rhv_residual_reachable

#print axioms EvmAsm.Codegen.RequestsHashVerifyTop.rhv_residual_wrong_site

#print axioms EvmAsm.Codegen.RequestsHashVerifyTop.rhv_status_branch_fail

#print axioms EvmAsm.Codegen.RevLeBeFlat.bhrRevLeBeFlat_spec

#print axioms EvmAsm.Codegen.RevLeBeFlat.swrRevLeBeFlat_spec

#print axioms EvmAsm.Codegen.RlpBytesEncodedSizeSAsm.rlpBytesEncodedSize_encode_spec

#print axioms EvmAsm.Codegen.RlpBytesEncodedSizeSAsm.rlpBytesEncodedSize_spec

#print axioms EvmAsm.Codegen.RlpContentStrictAtGuest.rlp_content_to_u256_be_strict_at_guest_instance

#print axioms EvmAsm.Codegen.RlpContentStrictAtGuest.rlp_content_to_u256_be_strict_at_guest_negative_control

#print axioms EvmAsm.Codegen.RlpContentStrictAtGuest.rlp_content_to_u256_be_strict_at_guest_spec_within

#print axioms EvmAsm.Codegen.RlpContentStrictAtGuest.rlp_content_to_u64_strict_at_guest_instance

#print axioms EvmAsm.Codegen.RlpContentStrictAtGuest.rlp_content_to_u64_strict_at_guest_negative_control

#print axioms EvmAsm.Codegen.RlpContentStrictAtGuest.rlp_content_to_u64_strict_at_guest_spec_within

#print axioms EvmAsm.Codegen.RlpEncodeBytesSAsm.reb_spec_rlpItem_within

#print axioms EvmAsm.Codegen.RlpEncodeBytesSAsm.reb_spec_within

#print axioms EvmAsm.Codegen.RlpEncodeListPrefixArmsTile.armGate_determines_index

#print axioms EvmAsm.Codegen.RlpEncodeListPrefixArmsTile.listPrefixArms_boundary_control

#print axioms EvmAsm.Codegen.RlpEncodeListPrefixArmsTile.listPrefixArms_disjoint

#print axioms EvmAsm.Codegen.RlpEncodeListPrefixArmsTile.listPrefixArms_each_arm_reachable

#print axioms EvmAsm.Codegen.RlpEncodeListPrefixArmsTile.listPrefixArms_tile

#print axioms EvmAsm.Codegen.RlpEncodeListPrefixArmsTile.listPrefixArms_top_reachable_as_word

#print axioms EvmAsm.Codegen.RlpEncodeListPrefixCanonical.first_length_byte_ne_zero

#print axioms EvmAsm.Codegen.RlpEncodeListPrefixCanonical.pow_le_u64ByteLen

#print axioms EvmAsm.Codegen.RlpEncodeListPrefixLong2Spec.long2_first_length_byte_ne_zero

#print axioms EvmAsm.Codegen.RlpEncodeListPrefixLong2Spec.rlp_encode_list_prefix_long2_pinned_spec_within

#print axioms EvmAsm.Codegen.RlpEncodeListPrefixLong3Spec.long3_first_length_byte_ne_zero

#print axioms EvmAsm.Codegen.RlpEncodeListPrefixLong3Spec.rlp_encode_list_prefix_long3_pinned_spec_within

#print axioms EvmAsm.Codegen.RlpEncodeListPrefixLong4Spec.long4_first_length_byte_ne_zero

#print axioms EvmAsm.Codegen.RlpEncodeListPrefixLong4Spec.rlp_encode_list_prefix_long4_pinned_spec_within

#print axioms EvmAsm.Codegen.RlpEncodeListPrefixLong5Spec.long5_first_length_byte_ne_zero

#print axioms EvmAsm.Codegen.RlpEncodeListPrefixLong5Spec.rlp_encode_list_prefix_long5_pinned_spec_within

#print axioms EvmAsm.Codegen.RlpEncodeListPrefixLong6Spec.long6_first_length_byte_ne_zero

#print axioms EvmAsm.Codegen.RlpEncodeListPrefixLong6Spec.rlp_encode_list_prefix_long6_pinned_spec_within

#print axioms EvmAsm.Codegen.RlpEncodeListPrefixLong7Spec.long7_first_length_byte_ne_zero

#print axioms EvmAsm.Codegen.RlpEncodeListPrefixLong7Spec.rlp_encode_list_prefix_long7_pinned_spec_within

#print axioms EvmAsm.Codegen.RlpEncodeListPrefixLong8Spec.long8_first_length_byte_ne_zero

#print axioms EvmAsm.Codegen.RlpEncodeListPrefixLong8Spec.rlp_encode_list_prefix_long8_pinned_spec_within

#print axioms EvmAsm.Codegen.RlpEncodeListPrefixLoopSpec.lpLolBody

#print axioms EvmAsm.Codegen.RlpEncodeListPrefixLoopSpec.lpLolLoop

#print axioms EvmAsm.Codegen.RlpEncodeListPrefixLoopSpec.lpLoop_writes_toBytesBE

#print axioms EvmAsm.Codegen.RlpEncodeUintBeSAsm.gate_admits_55

#print axioms EvmAsm.Codegen.RlpEncodeUintBeSAsm.gate_excludes_56

#print axioms EvmAsm.Codegen.RlpEncodeUintBeSAsm.reubOut_at_55_is_short_form

#print axioms EvmAsm.Codegen.RlpEncodeUintBeSAsm.reubOut_header_is_at_least_two_bytes_above_55

#print axioms EvmAsm.Codegen.RlpEncodeUintBeSAsm.reub_header_path_writes_one_byte

#print axioms EvmAsm.Codegen.RlpEncodeUintBeSAsm.reub_path_allZero

#print axioms EvmAsm.Codegen.RlpEncodeUintBeSAsm.reub_path_headerL1

#print axioms EvmAsm.Codegen.RlpEncodeUintBeSAsm.reub_path_headerL1_control

#print axioms EvmAsm.Codegen.RlpEncodeUintBeSAsm.reub_path_headerL2

#print axioms EvmAsm.Codegen.RlpEncodeUintBeSAsm.reub_path_rawByte

#print axioms EvmAsm.Codegen.RlpEncodeUintBeSAsm.reub_paths_are_distinct

#print axioms EvmAsm.Codegen.RlpEncodeUintBeSAsm.reub_spec_encode_within

#print axioms EvmAsm.Codegen.RlpEncodeUintBeSAsm.reub_spec_within

#print axioms EvmAsm.Codegen.RlpEncodeUintBeSAsm.reub_spec_within_of_length_le

#print axioms EvmAsm.Codegen.RlpFieldToU256BeSAsm.rlpFieldToU256Be_spec_within

#print axioms EvmAsm.Codegen.RlpFieldToU64SAsm.rlpFieldToU64_spec_within

#print axioms EvmAsm.Codegen.RlpFieldToU64StrictSAsm.rlpFieldToU64_spec_within

#print axioms EvmAsm.Codegen.RlpItemSizeGateCover.head_byte_forms_disjoint

#print axioms EvmAsm.Codegen.RlpItemSizeGateCover.head_byte_forms_partition

#print axioms EvmAsm.Codegen.RlpItemSizeGateCover.spanForm_admits_shortList

#print axioms EvmAsm.Codegen.RlpItemSizeGateCover.spanForm_admits_shortString

#print axioms EvmAsm.Codegen.RlpItemSizeGateCover.spanForm_admits_singleByte

#print axioms EvmAsm.Codegen.RlpItemSizeGateCover.spanForm_boundaries

#print axioms EvmAsm.Codegen.RlpItemSizeGateCover.spanForm_excludes_longList

#print axioms EvmAsm.Codegen.RlpItemSizeGateCover.spanForm_excludes_longString

#print axioms EvmAsm.Codegen.RlpItemSizeLongSpec.longListSample_reachable

#print axioms EvmAsm.Codegen.RlpItemSizeLongSpec.longStringSample_reachable

#print axioms EvmAsm.Codegen.RlpItemSizeLongSpec.rlp_item_size_long_list_encode_length_spec_within

#print axioms EvmAsm.Codegen.RlpItemSizeLongSpec.rlp_item_size_long_list_pinned_spec_within

#print axioms EvmAsm.Codegen.RlpItemSizeLongSpec.rlp_item_size_long_string_encode_length_spec_within

#print axioms EvmAsm.Codegen.RlpItemSizeLongSpec.rlp_item_size_long_string_pinned_spec_within

#print axioms EvmAsm.Codegen.RlpItemSizeTotalSpec.risStepsTotal_covers

#print axioms EvmAsm.Codegen.RlpItemSizeTotalSpec.risStepsTotal_le

#print axioms EvmAsm.Codegen.RlpItemSizeTotalSpec.rlp_item_size_total_spec_within

#print axioms EvmAsm.Codegen.RlpItemSpanNoCanonicalityCheck.leadingZeroCheck_is_performed

#print axioms EvmAsm.Codegen.RlpItemSpanNoCanonicalityCheck.offsetPredicate_control

#print axioms EvmAsm.Codegen.RlpItemSpanNoCanonicalityCheck.shortFormThreshold_control

#print axioms EvmAsm.Codegen.RlpItemSpanNoCanonicalityCheck.spanNeverComparesAgainst0x38

#print axioms EvmAsm.Codegen.RlpItemSpanNoCanonicalityCheck.span_length

#print axioms EvmAsm.Codegen.RlpItemSpanNoCanonicalityCheck.subwordLoad_sites

#print axioms EvmAsm.Codegen.RlpItemSpanNoCanonicalityCheck.subwordLoads_have_zero_offset

#print axioms EvmAsm.Codegen.RlpItemSpanSpec.long_gate_negative_control

#print axioms EvmAsm.Codegen.RlpItemSpanSpec.long_walk_negative_control

#print axioms EvmAsm.Codegen.RlpItemSpanSpec.rlp_item_span_any_header_spec_within

#print axioms EvmAsm.Codegen.RlpItemSpanSpec.rlp_item_span_long_bundle_satisfiable

#print axioms EvmAsm.Codegen.RlpItemSpanSpec.rlp_item_span_long_precondition_reachable

#print axioms EvmAsm.Codegen.RlpItemSpanSpec.rlp_item_span_long_spec_within

#print axioms EvmAsm.Codegen.RlpItemSpanSpec.rlp_item_span_precondition_reachable

#print axioms EvmAsm.Codegen.RlpItemSpanSpec.rlp_item_span_spec_within

#print axioms EvmAsm.Codegen.RlpListCountItemsBridge.not_rlpWalkNextStrict_nestedNonCanonical

#print axioms EvmAsm.Codegen.RlpListCountItemsBridge.rlpItemDecodeBridgesOn_of_accepts

#print axioms EvmAsm.Codegen.RlpListCountItemsSAsm.rlp_list_count_items_spec_within

#print axioms EvmAsm.Codegen.RlpListEncodedSizeSAsm.rlpListEncodedSize_encode_spec

#print axioms EvmAsm.Codegen.RlpListEncodedSizeSAsm.rlpListEncodedSize_spec

#print axioms EvmAsm.Codegen.RlpListNthItemSAsm.rlpListNthItem_spec_within

#print axioms EvmAsm.Codegen.RlpSpliceHelperSpec.rlp_encode_list_prefix_long1_pinned_spec_within

#print axioms EvmAsm.Codegen.RlpSpliceHelperSpec.rlp_encode_list_prefix_short_pinned_spec_within

#print axioms EvmAsm.Codegen.RlpSpliceHelperSpec.rlp_item_size_spec_within

#print axioms EvmAsm.Codegen.RlpValidatePayloadProductionAdapter.items_linked_geometry_discriminating

#print axioms EvmAsm.Codegen.RlpValidatePayloadProductionAdapter.items_linked_preconditions_reachable

#print axioms EvmAsm.Codegen.RlpValidatePayloadProductionAdapter.rlp_recursive_decode_items_linked_spec_within

#print axioms EvmAsm.Codegen.RlpValidatePayloadProductionAdapter.rlp_validate_payload_items_call_post_linked

#print axioms EvmAsm.Codegen.RlpWalkInitTie.rlp_walk_init_entry_hyps_refutable

#print axioms EvmAsm.Codegen.RlpWalkInitTie.rlp_walk_init_entry_instance

#print axioms EvmAsm.Codegen.RlpWalkInitTie.rlp_walk_init_entry_spec_within

#print axioms EvmAsm.Codegen.RlpWalkNextEntryTie.budget_ge_two

#print axioms EvmAsm.Codegen.RlpWalkNextEntryTie.rlp_walk_next_entry_accept_reachable

#print axioms EvmAsm.Codegen.RlpWalkNextEntryTie.rlp_walk_next_entry_hyps_refutable

#print axioms EvmAsm.Codegen.RlpWalkNextEntryTie.rlp_walk_next_entry_instance

#print axioms EvmAsm.Codegen.RlpWalkNextEntryTie.rlp_walk_next_entry_nonlist_strict_spec_within

#print axioms EvmAsm.Codegen.RlpWalkNextEntryTie.ult_f8_of_ult_c0

#print axioms EvmAsm.Codegen.RlpWalkNextLeafTie.prefix_test_always_taken

#print axioms EvmAsm.Codegen.RlpWalkNextLeafTie.rlp_walk_next_leaf_entry_instance

#print axioms EvmAsm.Codegen.RlpWalkNextLeafTie.rlp_walk_next_leaf_entry_nonlist_strict_spec_within

#print axioms EvmAsm.Codegen.RlpWalkNextLeafTie.rlp_walk_next_leaf_prefix_test_instance

#print axioms EvmAsm.Codegen.RlpWalkNextLeafTie.rlp_walk_next_leaf_premises_refutable

#print axioms EvmAsm.Codegen.RlpWalkNextLeafTie.rlp_walk_next_leaf_single_byte_instance

#print axioms EvmAsm.Codegen.RlpWalkNextStrictFuel.mutual_fuel_witness

#print axioms EvmAsm.Codegen.RlpWalkNextStrictFuel.rlp_validate_payload_cps_under_shared

#print axioms EvmAsm.Codegen.RlpWalkNextStrictFuel.shared_list_arm_contract_from_adapter

#print axioms EvmAsm.Codegen.RlpWalkNextStrictTie.rlp_walk_next_shared_nonlist_strict_instance

#print axioms EvmAsm.Codegen.RlpWalkNextStrictTie.rlp_walk_next_shared_nonlist_strict_spec_within

#print axioms EvmAsm.Codegen.RlpWalkNextStrictTie.strictW_of_rlpItemDecode_nonlist

#print axioms EvmAsm.Codegen.Secp256k1FieldConvSAsm.secfBeToLeFlatEntry_spec

#print axioms EvmAsm.Codegen.Secp256k1FieldConvSAsm.secfLeToBeFlatEntry_spec

#print axioms EvmAsm.Codegen.Secp256k1FieldGetBitLsbSAsm.secfGetBitLsbFlat_spec

#print axioms EvmAsm.Codegen.Secp256k1FieldMulModPSAsm.secfMulModP_spec

#print axioms EvmAsm.Codegen.Secp256k1FieldReduceOnceNSAsm.secfReduceOnceNFrame_spec

#print axioms EvmAsm.Codegen.Secp256k1FieldReduceOnceSAsm.secfCopy32Direct_spec

#print axioms EvmAsm.Codegen.Secp256k1FieldReduceOnceSAsm.secfReduceOnceFrame_spec

#print axioms EvmAsm.Codegen.Secp256k1FieldReduceOnceSAsm.u256SubBeFlat_spec

#print axioms EvmAsm.Codegen.Secp256k1PointCopy64SAsm.secp256k1PointCopy64Flat_spec

#print axioms EvmAsm.Codegen.Secp256k1PointDoubleSAsm.pointDouble_spec

#print axioms EvmAsm.Codegen.Secp256k1PointDoubleSAsm.pointDouble_spec_pointAdd

#print axioms EvmAsm.Codegen.Secp256k1PointZero64SAsm.secp256k1PointZero64Flat_spec

#print axioms EvmAsm.Codegen.SgLoadU32leFlatEntry.sgLoadU32leFlat_spec

#print axioms EvmAsm.Codegen.SgMemcpyFlatEntry.sgMemcpyFlat_spec

#print axioms EvmAsm.Codegen.SgValidateFixedListSAsm.sgValidateFixedListFlat_spec

#print axioms EvmAsm.Codegen.SpecRefConstantPins.bvEip7702AuthRegularGas_eq_spec

#print axioms EvmAsm.Codegen.SpecRefConstantPins.emptyTrieRootHex_eq_adBytes

#print axioms EvmAsm.Codegen.SpecRefConstantPins.fix_emptyOmmerHashHex

#print axioms EvmAsm.Codegen.SpecRefConstantPins.keccak256EmptyHashHex_eq_adBytes

#print axioms EvmAsm.Codegen.SpecRefConstantPins.keccak256EmptyHashHex_eq_aieBytes

#print axioms EvmAsm.Codegen.SpecRefConstantPins.maxDeployedCodeSize_eq_spec

#print axioms EvmAsm.Codegen.SpecRefConstantPins.maxInitcodeSize_eq_spec

#print axioms EvmAsm.Codegen.SpecRefConstantPins.trieRoot_ne_codeHash

#print axioms EvmAsm.Codegen.SszPackBytesSAsm.sszPackBytesFlat_spec

#print axioms EvmAsm.Codegen.SszPayloadWithdrawalsSAsm.spwU32leFlat_spec

#print axioms EvmAsm.Codegen.SszWitnessStateSAsm.swsU32leFlat_spec

#print axioms EvmAsm.Codegen.SszWitnessStateSectionSpec.swsU32lePresFlat_spec

#print axioms EvmAsm.Codegen.SystemCallStagingBase.sscProgL_spans_symbol

#print axioms EvmAsm.Codegen.SystemCallStagingSegments.sscExecStatus_ne_one

#print axioms EvmAsm.Codegen.SystemCallStagingSegments.sscStatus_eq_one_iff

#print axioms EvmAsm.Codegen.SystemCallStagingSegments.sscStatus_mem_three

#print axioms EvmAsm.Codegen.SystemCallStagingTop.ardCall_balanced

#print axioms EvmAsm.Codegen.SystemCallStagingTop.ard_residual_reachable

#print axioms EvmAsm.Codegen.SystemCallStagingTop.ard_residual_wrong_site

#print axioms EvmAsm.Codegen.SystemCallStagingTop.rdc_residual_reachable

#print axioms EvmAsm.Codegen.SystemCallStagingTop.rdc_residual_wrong_site

#print axioms EvmAsm.Codegen.SystemCallStagingTop.sscpCall_balanced

#print axioms EvmAsm.Codegen.SystemCallStagingTop.sscp_residual_reachable

#print axioms EvmAsm.Codegen.SystemCallStagingTop.sscp_residual_wrong_site

#print axioms EvmAsm.Codegen.SystemCallStagingTop.stage_system_call_spec_within

#print axioms EvmAsm.Codegen.TxGasResultIncrementsSAsm.tx_gas_result_increments_spec

#print axioms EvmAsm.Codegen.TxSigningHashLegacyTailCompose.legacyKssInputSource_prefix_region_of_input_layout

#print axioms EvmAsm.Codegen.TxSigningHashLegacyTailCompose.legacyKssInputSource_suffix_region_of_input_layout

#print axioms EvmAsm.Codegen.TxSigningHashSpec.tsh_hdrGate_false_on_string_header

#print axioms EvmAsm.Codegen.TxSigningHashSpec.tsh_longArm_gate_false_on_short_header

#print axioms EvmAsm.Codegen.TxSigningHashSpec.tsh_longHdr_domain_nonvacuous

#print axioms EvmAsm.Codegen.TxSigningHashSpec.tx_signing_hash_spec_within

#print axioms EvmAsm.Codegen.TxTypeDispatchSpec.txTypeDispatch_spec_within

#print axioms EvmAsm.Codegen.U256AddBeAInPlaceSAsm.u256AddBeAInPlaceFlat_spec

#print axioms EvmAsm.Codegen.U256BeFlat.u256AddBeFlat_spec

#print axioms EvmAsm.Codegen.U256BeFlat.u256FromU64BeFlat_spec

#print axioms EvmAsm.Codegen.U256DivU64BeSAsm.u256DivU64BeInPlaceFlat_spec

#print axioms EvmAsm.Codegen.U256EqSAsm.u256Eq_spec

#print axioms EvmAsm.Codegen.U256GasPricingSAsm.priority_fee_per_gas_eip1559_body_spec

#print axioms EvmAsm.Codegen.U256GasPricingSAsm.priority_fee_per_gas_eip1559_spec

#print axioms EvmAsm.Codegen.U256LtBeSAsm.u256LtBe_spec

#print axioms EvmAsm.Codegen.U256MinSAsm.u256Min_spec

#print axioms EvmAsm.Codegen.U256MulU64Be.mulWhole_inPlace_spec

#print axioms EvmAsm.Codegen.U256MulU64Be.mulWhole_spec

#print axioms EvmAsm.Codegen.ValidateHeaderGasCorrespondence.header_validate_excess_blob_gas_boundary_spec_within

#print axioms EvmAsm.Codegen.ValidateHeaderGasCorrespondence.header_validate_excess_blob_gas_overflow_spec_within

#print axioms EvmAsm.Codegen.ValidateHeaderGasCorrespondence.header_validate_excess_blob_gas_status0_arm_spec_within

#print axioms EvmAsm.Codegen.ValidateHeaderGasCorrespondence.header_validate_excess_blob_gas_under_target_spec_within

#print axioms EvmAsm.Codegen.ValidateHeaderGasCorrespondence.status0ArmGate_admits

#print axioms EvmAsm.Codegen.ValidateHeaderGasCorrespondence.status0ArmGate_refutable

#print axioms EvmAsm.Codegen.ValidateHeaderWhole.validateHeaderCoreContract_hcoreStatus1_inhabited

#print axioms EvmAsm.Codegen.ValidateParentHashLinkSpec.top_frameSaved_with_rest_to_own

#print axioms EvmAsm.Codegen.ValidateParentHashLinkSpec.top_frameSlotsSaved_to_own

#print axioms EvmAsm.Codegen.ValidateParentHashLinkSpec.top_keccakFrameSaved_to_own

#print axioms EvmAsm.Codegen.ValidateParentHashLinkSpec.top_keccak_ret_slot

#print axioms EvmAsm.Codegen.ValidateParentHashLinkSpec.top_keccak_slot_h0

#print axioms EvmAsm.Codegen.ValidateParentHashLinkSpec.top_keccak_slot_h16

#print axioms EvmAsm.Codegen.ValidateParentHashLinkSpec.top_keccak_slot_h24

#print axioms EvmAsm.Codegen.ValidateParentHashLinkSpec.top_keccak_slot_h8

#print axioms EvmAsm.Codegen.ValidateParentHashLinkSpec.top_keccak_slots_to_stackFree

#print axioms EvmAsm.Codegen.ValidateParentHashLinkSpec.top_mem4_to_memOwn

#print axioms EvmAsm.Codegen.ValidateParentHashLinkSpec.top_mem4_with_owned_tail_to_memOwn

#print axioms EvmAsm.Codegen.ValidateParentHashLinkSpec.top_reg12_to_regOwn

#print axioms EvmAsm.Codegen.ValidateParentHashLinkSpec.top_reg4_to_regOwn

#print axioms EvmAsm.Codegen.ValidateParentHashLinkSpec.top_reg8_to_regOwn

#print axioms EvmAsm.Codegen.ValidateParentHashLinkSpec.top_regPair_to_regOwn

#print axioms EvmAsm.Codegen.ValidateParentHashLinkSpec.top_vphl_compare_prefix_to_own

#print axioms EvmAsm.Codegen.ValidateParentHashLinkSpec.validate_parent_hash_link_spec_within

#print axioms EvmAsm.Codegen.ValidateParentHashLinkSpec.vphlCode_vphl

#print axioms EvmAsm.Codegen.ValidateParentHashLinkSpec.vphlCompareAllEq

#print axioms EvmAsm.Codegen.ValidateParentHashLinkSpec.vphlCompareMatchTail

#print axioms EvmAsm.Codegen.ValidateParentHashLinkSpec.vphlCompareMismatchTail

#print axioms EvmAsm.Codegen.ValidateParentHashLinkSpec.vphlCompareRound0Eq

#print axioms EvmAsm.Codegen.ValidateParentHashLinkSpec.vphlCompareRound0Ne

#print axioms EvmAsm.Codegen.ValidateParentHashLinkSpec.vphlCompareRound1Eq

#print axioms EvmAsm.Codegen.ValidateParentHashLinkSpec.vphlCompareRound1Ne

#print axioms EvmAsm.Codegen.ValidateParentHashLinkSpec.vphlCompareRound2Eq

#print axioms EvmAsm.Codegen.ValidateParentHashLinkSpec.vphlCompareRound2Ne

#print axioms EvmAsm.Codegen.ValidateParentHashLinkSpec.vphlCompareRound3Eq

#print axioms EvmAsm.Codegen.ValidateParentHashLinkSpec.vphlCompareRound3Ne

#print axioms EvmAsm.Codegen.ValidateParentHashLinkSpec.vphlLa_claimed_5c

#print axioms EvmAsm.Codegen.ValidateParentHashLinkSpec.vphlLa_computed_6

#print axioms EvmAsm.Codegen.ValidateParentHashLinkSpec.vphlProg_length

#print axioms EvmAsm.Codegen.ValidateParentHashLinkSpec.vphl_arm_fail_spec_within

#print axioms EvmAsm.Codegen.ValidateParentHashLinkSpec.vphl_arm_len_eq32_prefix_spec_within

#print axioms EvmAsm.Codegen.ValidateParentHashLinkSpec.vphl_arm_len_ne32_spec_within

#print axioms EvmAsm.Codegen.ValidateParentHashLinkSpec.vphl_callReturn_pre

#print axioms EvmAsm.Codegen.ValidateParentHashLinkSpec.vphl_choose12

#print axioms EvmAsm.Codegen.ValidateParentHashLinkSpec.vphl_continuation_spec

#print axioms EvmAsm.Codegen.ValidateParentHashLinkSpec.vphl_copy_claimed_spec_within

#print axioms EvmAsm.Codegen.ValidateParentHashLinkSpec.vphl_dwords_eq_iff

#print axioms EvmAsm.Codegen.ValidateParentHashLinkSpec.vphl_epilogue_spec_within

#print axioms EvmAsm.Codegen.ValidateParentHashLinkSpec.vphl_hash_call_spec_within

#print axioms EvmAsm.Codegen.ValidateParentHashLinkSpec.vphl_hash_prep_spec_within

#print axioms EvmAsm.Codegen.ValidateParentHashLinkSpec.vphl_hash_tail_spec

#print axioms EvmAsm.Codegen.ValidateParentHashLinkSpec.vphl_k20_call_spec_within

#print axioms EvmAsm.Codegen.ValidateParentHashLinkSpec.vphl_of_forall_regIs_to_regOwn12

#print axioms EvmAsm.Codegen.ValidateParentHashLinkSpec.vphl_prologue_spec_within

#print axioms EvmAsm.Codegen.ValidateParentHashLinkSpec.vphl_status0_inhabited

#print axioms EvmAsm.Codegen.ValidateParentHashLinkSpec.vphl_success_eq32_spec

#print axioms EvmAsm.Codegen.ValidateParentHashLinkSpec.vphl_success_field0_bound

#print axioms EvmAsm.Codegen.WithdrawalDecodeSpec.withdrawal_decode_spec_within

#print axioms EvmAsm.Codegen.WitnessCodesLookupSpec.witness_codes_lookup_by_hash_spec_within_empty_section

#print axioms EvmAsm.Codegen.WitnessLookupByHashIndexedEmpty.witness_lookup_by_hash_indexed_spec_within_empty

#print axioms EvmAsm.Codegen.WitnessLookupByHashIndexedOneHit.witness_lookup_by_hash_indexed_spec_within_one_hit

#print axioms EvmAsm.Codegen.WitnessLookupByHashIndexedOneHit.witness_lookup_by_hash_indexed_spec_within_one_hit_gen

#print axioms EvmAsm.Codegen.WitnessLookupByHashSpec.hit_cells_distinct

#print axioms EvmAsm.Codegen.WitnessLookupByHashSpec.witness_lookup_by_hash_spec_within_empty_section

#print axioms EvmAsm.Codegen.WitnessLookupByHashSpec.witness_lookup_by_hash_spec_within_enabled_empty

#print axioms EvmAsm.Codegen.WitnessLookupByHashSpec.witness_lookup_by_hash_spec_within_enabled_one_hit

#print axioms EvmAsm.Codegen.WitnessLookupByHashSpec.wlhCallWithin_empty_section

#print axioms EvmAsm.Codegen.WitnessLookupByHashSpec.wlhCallWithin_enabled_empty

#print axioms EvmAsm.Codegen.WitnessLookupByHashSpec.wlhCallWithin_enabled_one_hit

#print axioms EvmAsm.Codegen.WitnessLookupByHashSpec.wlh_abiFrame_byte_tie

#print axioms EvmAsm.Codegen.WitnessLookupByHashSpec.wlh_cells_outside_residual_footprint

#print axioms EvmAsm.Codegen.WitnessLookupByHashSpec.wlh_empty_section_sample_witness

#print axioms EvmAsm.Codegen.WitnessLookupByHashSpec.wlh_entry_in_walk_fullCode

#print axioms EvmAsm.Codegen.account_extract_balance_spec_within

#print axioms EvmAsm.Codegen.account_extract_nonce_spec_within

#print axioms EvmAsm.Codegen.blsgLtP_spec_specref

#print axioms EvmAsm.Codegen.bnfLtP_spec_specref

#print axioms EvmAsm.Codegen.headersParentHash_out_length

#print axioms EvmAsm.Codegen.headersParentHash_out_length_refutable_without_hclaimed

#print axioms EvmAsm.Codegen.headers_parent_hash_spec_within

#print axioms EvmAsm.Codegen.hphSampleHeader_reaches_success

#print axioms EvmAsm.Codegen.mset_memcpy_align_bites

#print axioms EvmAsm.Codegen.mset_memcpy_spec_within

#print axioms EvmAsm.Codegen.mset_memcpy_spec_within_nonvacuous

#print axioms EvmAsm.Codegen.rlpItemSize_prog_eq_verified_prog

#print axioms EvmAsm.Codegen.validateHeaderFunction_eq_prog

#print axioms EvmAsm.EL.RLP.Nat.fromBytesBE_eq_zero_iff

#print axioms EvmAsm.EL.RLP.Ref.decodeD_long_bytes_badlen

#print axioms EvmAsm.EL.RLP.Ref.decodeD_long_bytes_small

#print axioms EvmAsm.EL.RLP.Ref.decodeD_long_bytes_trunc

#print axioms EvmAsm.EL.RLP.Ref.decodeD_long_bytes_zero

#print axioms EvmAsm.EL.RLP.Ref.decodeD_short_bytes_badlen

#print axioms EvmAsm.EL.RLP.Ref.decodeD_short_bytes_noncanon

#print axioms EvmAsm.EL.RLP.Ref.decodeD_single_long

#print axioms EvmAsm.EL.RLP.Ref.decodeD_single_ok

#print axioms EvmAsm.EL.RLP.RefDecodeToBytesFidelity.long_end_test_faithful

#print axioms EvmAsm.EL.RLP.RefDecodeToBytesFidelity.long_end_test_needs_range

#print axioms EvmAsm.EL.RLP.RefDecodeToBytesFidelity.long_trailing_test_faithful

#print axioms EvmAsm.EL.RLP.RefDecodeToBytesFidelity.long_trailing_test_needs_range

#print axioms EvmAsm.EL.RLP.RefDecodeToBytesFidelity.long_trunc_test_faithful

#print axioms EvmAsm.EL.RLP.RefDecodeToBytesFidelity.long_trunc_test_needs_range

#print axioms EvmAsm.EL.RLP.RefDecodeToBytesFidelity.negative_length_test_faithful

#print axioms EvmAsm.EL.RLP.decodeAux_mono_fuel

#print axioms EvmAsm.EL.RLP.decodeFully_encode

#print axioms EvmAsm.EL.RLP.decodeItems_mono_fuel

#print axioms EvmAsm.EL.RLP.decode_encode

#print axioms EvmAsm.EL.RLP.decode_encode_mutual

#print axioms EvmAsm.EL.RLP.decode_injective

#print axioms EvmAsm.EL.RLP.decode_span_longBytes

#print axioms EvmAsm.EL.RLP.decode_span_longList

#print axioms EvmAsm.EL.RLP.encode_decode

#print axioms EvmAsm.EL.RLP.encode_decode_mutual

#print axioms EvmAsm.EL.RLP.encode_injective

#print axioms EvmAsm.EL.RLP.readLength_length

#print axioms EvmAsm.EL.RLP.readLength_takeBytes

#print axioms EvmAsm.Evm64.AddMod.Compose.evm_addmod_total_result_stack_spec_within

#print axioms EvmAsm.Evm64.BlobBaseFee.evm_blobbasefee_stack_spec_within

#print axioms EvmAsm.Evm64.BlobHash.evm_blobhash_stack_spec_within

#print axioms EvmAsm.Evm64.BlockHash.evm_blockhash_stack_spec_within

#print axioms EvmAsm.Evm64.Calldata.evm_calldatacopy_stack_spec_within

#print axioms EvmAsm.Evm64.Calldata.evm_calldataload_staged_stack_spec_within

#print axioms EvmAsm.Evm64.Calldata.evm_calldatasize_stack_spec_within

#print axioms EvmAsm.Evm64.Code.evm_codecopy_stack_spec_within

#print axioms EvmAsm.Evm64.Code.evm_codesize_stack_spec_within

#print axioms EvmAsm.Evm64.ControlFlow.evm_jump_stack_spec_within

#print axioms EvmAsm.Evm64.ControlFlow.evm_jumpdest_stack_spec_within

#print axioms EvmAsm.Evm64.ControlFlow.evm_jumpi_stack_spec_within

#print axioms EvmAsm.Evm64.ControlFlow.evm_pc_stack_spec_within

#print axioms EvmAsm.Evm64.Env.evm_address_stack_spec_within

#print axioms EvmAsm.Evm64.Env.evm_basefee_stack_spec_within

#print axioms EvmAsm.Evm64.Env.evm_caller_stack_spec_within

#print axioms EvmAsm.Evm64.Env.evm_callvalue_stack_spec_within

#print axioms EvmAsm.Evm64.Env.evm_chainid_stack_spec_within

#print axioms EvmAsm.Evm64.Env.evm_coinbase_stack_spec_within

#print axioms EvmAsm.Evm64.Env.evm_gaslimit_stack_spec_within

#print axioms EvmAsm.Evm64.Env.evm_gasprice_stack_spec_within

#print axioms EvmAsm.Evm64.Env.evm_number_stack_spec_within

#print axioms EvmAsm.Evm64.Env.evm_origin_stack_spec_within

#print axioms EvmAsm.Evm64.Env.evm_prevrandao_stack_spec_within

#print axioms EvmAsm.Evm64.Env.evm_selfbalance_stack_spec_within

#print axioms EvmAsm.Evm64.Env.evm_timestamp_stack_spec_within

#print axioms EvmAsm.Evm64.GasOpcode.evm_gas_stack_spec_within

#print axioms EvmAsm.Evm64.Mcopy.evm_mcopy_stack_spec_within

#print axioms EvmAsm.Evm64.MulMod.Compose.evm_mulmod_stack_spec_within

#print axioms EvmAsm.Evm64.ReturnData.evm_returndatacopy_body_stack_spec_within

#print axioms EvmAsm.Evm64.ReturnData.evm_returndatacopy_guard_len_invalid_stack_spec_within

#print axioms EvmAsm.Evm64.ReturnData.evm_returndatacopy_guard_success_stack_spec_within

#print axioms EvmAsm.Evm64.ReturnData.evm_returndatacopy_guard_wrap_invalid_stack_spec_within

#print axioms EvmAsm.Evm64.ReturnData.evm_returndatacopy_setup_spec_within

#print axioms EvmAsm.Evm64.ReturnData.evm_returndatacopy_setup_zero_spec_within

#print axioms EvmAsm.Evm64.ReturnData.evm_returndatacopy_stack_spec_within

#print axioms EvmAsm.Evm64.ReturnData.evm_returndatasize_stack_spec_within

#print axioms EvmAsm.Evm64.SDiv.Compose.evm_sdiv_exact_callable_return_result_stack_spec_within_v5

#print axioms EvmAsm.Evm64.SMod.Compose.evm_smod_exact_callable_return_result_stack_spec_within_v5

#print axioms EvmAsm.Evm64.Terminating.evm_invalid_stack_spec_within

#print axioms EvmAsm.Evm64.Terminating.evm_return_halt_spec_within

#print axioms EvmAsm.Evm64.Terminating.evm_return_stack_spec_within_with_capture

#print axioms EvmAsm.Evm64.Terminating.evm_revert_stack_spec_within

#print axioms EvmAsm.Evm64.Terminating.evm_selfdestruct_stack_spec_resolved

#print axioms EvmAsm.Evm64.Terminating.evm_stop_stack_spec_within

#print axioms EvmAsm.Evm64.Terminating.return_capture_nondegenerate

#print axioms EvmAsm.Evm64.Terminating.revert_window_nondegenerate

#print axioms EvmAsm.Evm64.Transient.evm_tload_stack_spec_within

#print axioms EvmAsm.Evm64.Transient.evm_tstore_stack_spec_within

#print axioms EvmAsm.Evm64.account_rlp_content_to_u256_be_balance_spec_within

#print axioms EvmAsm.Evm64.account_rlp_content_to_u64_nonce_spec_within

#print axioms EvmAsm.Evm64.account_rlp_walk_init_spec_within

#print axioms EvmAsm.Evm64.account_rlp_walk_next_field0_spec_within

#print axioms EvmAsm.Evm64.account_rlp_walk_next_field1_spec_within

#print axioms EvmAsm.Evm64.bytesRegion_dword_pair_at_setBytes

#print axioms EvmAsm.Evm64.evmMemoryIs_peel_window64

#print axioms EvmAsm.Evm64.evmMemoryIs_quarter_pair_setBytes

#print axioms EvmAsm.Evm64.evm_add_stack_spec_within

#print axioms EvmAsm.Evm64.evm_and_stack_spec_within

#print axioms EvmAsm.Evm64.evm_byte_stack_spec_within

#print axioms EvmAsm.Evm64.evm_div_v6_stack_spec

#print axioms EvmAsm.Evm64.evm_dup_stack_spec_within

#print axioms EvmAsm.Evm64.evm_eq_stack_spec_within

#print axioms EvmAsm.Evm64.evm_exp_stack_spec_within

#print axioms EvmAsm.Evm64.evm_gt_stack_spec_within

#print axioms EvmAsm.Evm64.evm_iszero_stack_spec_within

#print axioms EvmAsm.Evm64.evm_lt_stack_spec_within

#print axioms EvmAsm.Evm64.evm_mload_stack_spec_within

#print axioms EvmAsm.Evm64.evm_mod_v6_stack_spec

#print axioms EvmAsm.Evm64.evm_msize_stack_spec_within

#print axioms EvmAsm.Evm64.evm_mstore8_stack_spec_within

#print axioms EvmAsm.Evm64.evm_mstore_stack_spec_within_region

#print axioms EvmAsm.Evm64.evm_mul_stack_spec_within

#print axioms EvmAsm.Evm64.evm_not_stack_spec_within

#print axioms EvmAsm.Evm64.evm_or_stack_spec_within

#print axioms EvmAsm.Evm64.evm_pop_stack_spec_within

#print axioms EvmAsm.Evm64.evm_push0_stack_spec_within

#print axioms EvmAsm.Evm64.evm_push1_stack_spec_within

#print axioms EvmAsm.Evm64.evm_push_stack_spec_within

#print axioms EvmAsm.Evm64.evm_sar_stack_spec_within

#print axioms EvmAsm.Evm64.evm_sgt_stack_spec_within

#print axioms EvmAsm.Evm64.evm_shl_stack_spec_within

#print axioms EvmAsm.Evm64.evm_shr_stack_spec_within

#print axioms EvmAsm.Evm64.evm_signextend_stack_spec_within

#print axioms EvmAsm.Evm64.evm_slt_stack_spec_within

#print axioms EvmAsm.Evm64.evm_sub_stack_spec_within

#print axioms EvmAsm.Evm64.evm_swap_stack_spec_within

#print axioms EvmAsm.Evm64.evm_xor_stack_spec_within

#print axioms EvmAsm.Evm64.hpDecode_hpEncode

#print axioms EvmAsm.Evm64.indexOfSection_hashes_eq_build_code_db

#print axioms EvmAsm.Evm64.indexOfSection_matchesSection

#print axioms EvmAsm.Evm64.mptNodeKindSpec_rlp

#print axioms EvmAsm.Evm64.mstoreDwordPairStoreLimb_eq_dwordAt_setBytes

#print axioms EvmAsm.Evm64.nodeDbIs_snoc

#print axioms EvmAsm.Evm64.nodeDbLookupSpec_eq_build_node_db

#print axioms EvmAsm.Evm64.rlpToMutableNode_rlp

#print axioms EvmAsm.Evm64.rlp_walk_init_long1_spec_within

#print axioms EvmAsm.Evm64.rlp_walk_next_scalar_spec_within

#print axioms EvmAsm.Evm64.roundUp8_eq_alignToDword

#print axioms EvmAsm.Evm64.witnessIndexIs_split_at

#print axioms EvmAsm.Evm64.witnessLookupSpec_correct

#print axioms EvmAsm.Rv64.RLP.risLenLoop

#print axioms EvmAsm.Rv64.RLP.risLenLoopBody

#print axioms EvmAsm.Rv64.RLP.rlpItemDecodeStrictW_of_decodeAux

#print axioms EvmAsm.Rv64.RLP.rlp_content_to_u256_be_scalar_spec_within

#print axioms EvmAsm.Rv64.RLP.rlp_content_to_u256_be_spec_within

#print axioms EvmAsm.Rv64.RLP.rlp_content_to_u256_be_strict_spec_within

#print axioms EvmAsm.Rv64.RLP.rlp_content_to_u64_spec_within

#print axioms EvmAsm.Rv64.RLP.rlp_content_to_u64_strict_spec_within

#print axioms EvmAsm.Rv64.RLP.rlp_walk_init_spec_within

#print axioms EvmAsm.Rv64.RLP.rlp_walk_next_spec_within

#print axioms EvmAsm.Rv64.SAsm.RecDecode.rlp_decode_correct

#print axioms EvmAsm.Stateless.SpecRef.accountExistsAndIsEmpty_eq_kernel

#print axioms EvmAsm.Stateless.SpecRef.beq_EMPTY_ACCOUNT

#print axioms EvmAsm.Stateless.SpecRef.decode_account_from_leaf_inv

#print axioms EvmAsm.Stateless.SpecRef.encode_headerToRlpItem_of_decode

#print axioms EvmAsm.Stateless.State.accountWriteUpsert_keys_dictSet

#print axioms EvmAsm.Stateless.State.accountWriteUpsert_nodup

#print axioms EvmAsm.Stateless.State.accountWriteUpsert_rowsMap

#print axioms EvmAsm.Stateless.State.storageRowLookup_storageWriteUpsert

#print axioms EvmAsm.Stateless.State.storageWriteUpsert_baselines

#print axioms EvmAsm.Stateless.State.storageWriteUpsert_nodup

#print axioms EvmAsm.Stateless.State.storageWriteUpsert_rowsMap

#print axioms EvmAsm.Stateless.accountRlp_length_le

#print axioms EvmAsm.Stateless.bytesBEtoNat_beBytes32

#print axioms EvmAsm.Stateless.decode_account_from_leaf_accountRlp

#print axioms EvmAsm.Stateless.groupByAddress_keys_nodup

#print axioms EvmAsm.Stateless.groupByAddress_total

#print axioms EvmAsm.Stateless.storageRowsAbstract_holds
