/-
  Axiom witnesses for `scripts/check-axioms.sh` (GH #10601, GH #11042).

  GENERATED by `scripts/gen-axiom-witnesses.py` from the witness abbrevs
  referenced in `EvmAsm/Progress.lean` (the `OpcodeEntry` registry) and
  `EvmAsm/Progress/Routines.lean` (the `RoutineEntry` registry of verified
  guest routines) — do not edit by hand; regenerate with
  `python3 scripts/gen-axiom-witnesses.py --write`.  The gate regenerates and
  diffs, so a stale file fails CI.

  This module exists so the axiom gate runs under `lake build` instead of
  a `lake env lean` scratch file: under the lake artifact cache,
  cache-satisfied modules have no materialized `.olean` on disk and
  `lake env lean` cannot resolve them (issue #10601, in the #10537
  family).  Building this module prints one `#print axioms` report per
  registry witness into the build log; lake replays messages on
  repeat (fully cached) builds, so the gate stays meaningful in cache
  mode and pays zero re-elaboration.

  Coverage note (#11042): the guest-routine half is a **partial** enumeration
  of the verified guest surface, not a complete one.  `EvmAsm/**` carries on
  the order of 1800 distinct `*_spec_within` names, most of them block-level
  rather than whole-routine, so populating every one is not a single change.
  What is registered is witnessed; what is not registered is still outside the
  gate.  Stated here rather than left implicit, because the assumption this
  file exists to break is "covered by CI".  #11290 tracks turning that residual
  into a measured coverage number rather than prose.  As of #11289 all three
  registries are strict, so within a *registered* file an unwitnessed row is a
  build error — the gap is only in what has not been registered yet.
-/
import EvmAsm.Progress
import EvmAsm.Progress.Routines
import EvmAsm.Progress.Correspondence

#print axioms EvmAsm.Codegen.AccountDecodeCompose.decoded_matches_specRef

#print axioms EvmAsm.Codegen.AccountDecodeCompose.outputSuccess_eq_accountDecodedIs

#print axioms EvmAsm.Codegen.AccountDecodeSpec.account_decode_spec_within

#print axioms EvmAsm.Codegen.AccountIsEip161EmptySpec.leniency_agrees

#print axioms EvmAsm.Codegen.BgvU32leSpec.bgvU32leFlat_spec

#print axioms EvmAsm.Codegen.BloomOrIntoSAsm.bloomOrIntoFn_spec

#print axioms EvmAsm.Codegen.BloomOrIntoSAsm.bloomOrInto_fold_eq_logs_bloom

#print axioms EvmAsm.Codegen.Bls12G1LtPSAsm.blsgLtP_spec

#print axioms EvmAsm.Codegen.Bn254FieldLtPSAsm.bnfLtP_spec

#print axioms EvmAsm.Codegen.BytesToNibblesSAsm.bytesToNibblesFlat_spec

#print axioms EvmAsm.Codegen.ChainValidateConsecutiveNumbersSpec.chain_validate_consecutive_numbers_spec_within

#print axioms EvmAsm.Codegen.ChainValidateGasUsedUnderLimitSpec.chain_validate_gas_used_under_limit_spec_within

#print axioms EvmAsm.Codegen.ChainValidateIncreasingTimestampsSpec.chain_validate_increasing_timestamps_spec_within

#print axioms EvmAsm.Codegen.CheckGasLimitSAsm.checkGasLimit_ref_spec

#print axioms EvmAsm.Codegen.HeaderExtractLogsBloomSpec.headerExtractLogsBloom_spec_within

#print axioms EvmAsm.Codegen.HeaderExtractLogsBloomSpec.header_logs_bloom_of_decode

#print axioms EvmAsm.Codegen.HeaderExtractNumberSpec.header_extract_number_spec_within

#print axioms EvmAsm.Codegen.HeaderExtractNumberSpec.header_number_of_decode

#print axioms EvmAsm.Codegen.HeaderValidateExtraDataLengthSpec.header_extra_data_length_of_decode

#print axioms EvmAsm.Codegen.HeaderValidateExtraDataLengthSpec.header_validate_extra_data_length_spec_within

#print axioms EvmAsm.Codegen.RlpBytesEncodedSizeSAsm.rlpBytesEncodedSize_encode_spec

#print axioms EvmAsm.Codegen.RlpBytesEncodedSizeSAsm.rlpBytesEncodedSize_spec

#print axioms EvmAsm.Codegen.RlpEncodeBytesSAsm.reb_spec_rlpItem_within

#print axioms EvmAsm.Codegen.RlpEncodeBytesSAsm.reb_spec_within

#print axioms EvmAsm.Codegen.RlpEncodeUintBeSAsm.reub_spec_encode_within

#print axioms EvmAsm.Codegen.RlpEncodeUintBeSAsm.reub_spec_within

#print axioms EvmAsm.Codegen.RlpEncodeUintBeSAsm.reub_spec_within_of_length_le

#print axioms EvmAsm.Codegen.RlpFieldToU256BeSAsm.rlpFieldToU256Be_spec_within

#print axioms EvmAsm.Codegen.RlpFieldToU64SAsm.rlpFieldToU64_spec_within

#print axioms EvmAsm.Codegen.RlpListCountItemsSAsm.rlp_list_count_items_spec_within

#print axioms EvmAsm.Codegen.RlpListEncodedSizeSAsm.rlpListEncodedSize_encode_spec

#print axioms EvmAsm.Codegen.RlpListEncodedSizeSAsm.rlpListEncodedSize_spec

#print axioms EvmAsm.Codegen.RlpListNthItemSAsm.rlpListNthItem_spec_within

#print axioms EvmAsm.Codegen.RlpSpliceHelperSpec.rlp_encode_list_prefix_short_pinned_spec_within

#print axioms EvmAsm.Codegen.RlpSpliceHelperSpec.rlp_item_size_spec_within

#print axioms EvmAsm.Codegen.WithdrawalDecodeSpec.withdrawal_decode_spec_within

#print axioms EvmAsm.Codegen.blsgLtP_spec_specref

#print axioms EvmAsm.Codegen.bnfLtP_spec_specref

#print axioms EvmAsm.EL.RLP.Nat.fromBytesBE_eq_zero_iff

#print axioms EvmAsm.EL.RLP.decodeAux_mono_fuel

#print axioms EvmAsm.EL.RLP.decodeFully_encode

#print axioms EvmAsm.EL.RLP.decodeItems_mono_fuel

#print axioms EvmAsm.EL.RLP.decode_encode

#print axioms EvmAsm.EL.RLP.decode_encode_mutual

#print axioms EvmAsm.EL.RLP.decode_injective

#print axioms EvmAsm.EL.RLP.encode_decode

#print axioms EvmAsm.EL.RLP.encode_decode_mutual

#print axioms EvmAsm.EL.RLP.encode_injective

#print axioms EvmAsm.Evm64.AddMod.Compose.evm_addmod_total_result_stack_spec_within

#print axioms EvmAsm.Evm64.BlobBaseFee.evm_blobbasefee_stack_spec_within

#print axioms EvmAsm.Evm64.BlobHash.evm_blobhash_stack_spec_within

#print axioms EvmAsm.Evm64.BlockHash.evm_blockhash_stack_spec_within

#print axioms EvmAsm.Evm64.Calldata.evm_calldatacopy_stack_spec_within

#print axioms EvmAsm.Evm64.Calldata.evm_calldataload_staged_stack_spec_within

#print axioms EvmAsm.Evm64.Calldata.evm_calldatasize_stack_spec_within

#print axioms EvmAsm.Evm64.Code.evm_codecopy_stack_spec_within

#print axioms EvmAsm.Evm64.Code.evm_codesize_stack_spec_within

#print axioms EvmAsm.Evm64.ControlFlow.evm_jump_stack_spec_within

#print axioms EvmAsm.Evm64.ControlFlow.evm_jumpdest_stack_spec_within

#print axioms EvmAsm.Evm64.ControlFlow.evm_jumpi_stack_spec_within

#print axioms EvmAsm.Evm64.ControlFlow.evm_pc_stack_spec_within

#print axioms EvmAsm.Evm64.Env.evm_address_stack_spec_within

#print axioms EvmAsm.Evm64.Env.evm_basefee_stack_spec_within

#print axioms EvmAsm.Evm64.Env.evm_caller_stack_spec_within

#print axioms EvmAsm.Evm64.Env.evm_callvalue_stack_spec_within

#print axioms EvmAsm.Evm64.Env.evm_chainid_stack_spec_within

#print axioms EvmAsm.Evm64.Env.evm_coinbase_stack_spec_within

#print axioms EvmAsm.Evm64.Env.evm_gaslimit_stack_spec_within

#print axioms EvmAsm.Evm64.Env.evm_gasprice_stack_spec_within

#print axioms EvmAsm.Evm64.Env.evm_number_stack_spec_within

#print axioms EvmAsm.Evm64.Env.evm_origin_stack_spec_within

#print axioms EvmAsm.Evm64.Env.evm_prevrandao_stack_spec_within

#print axioms EvmAsm.Evm64.Env.evm_selfbalance_stack_spec_within

#print axioms EvmAsm.Evm64.Env.evm_timestamp_stack_spec_within

#print axioms EvmAsm.Evm64.GasOpcode.evm_gas_stack_spec_within

#print axioms EvmAsm.Evm64.Mcopy.evm_mcopy_stack_spec_within

#print axioms EvmAsm.Evm64.MulMod.Compose.evm_mulmod_stack_spec_within

#print axioms EvmAsm.Evm64.ReturnData.evm_returndatacopy_body_stack_spec_within

#print axioms EvmAsm.Evm64.ReturnData.evm_returndatacopy_guard_len_invalid_stack_spec_within

#print axioms EvmAsm.Evm64.ReturnData.evm_returndatacopy_guard_success_stack_spec_within

#print axioms EvmAsm.Evm64.ReturnData.evm_returndatacopy_guard_wrap_invalid_stack_spec_within

#print axioms EvmAsm.Evm64.ReturnData.evm_returndatacopy_setup_spec_within

#print axioms EvmAsm.Evm64.ReturnData.evm_returndatacopy_setup_zero_spec_within

#print axioms EvmAsm.Evm64.ReturnData.evm_returndatacopy_stack_spec_within

#print axioms EvmAsm.Evm64.ReturnData.evm_returndatasize_stack_spec_within

#print axioms EvmAsm.Evm64.SDiv.Compose.evm_sdiv_exact_callable_return_result_stack_spec_within_v5

#print axioms EvmAsm.Evm64.SMod.Compose.evm_smod_exact_callable_return_result_stack_spec_within_v5

#print axioms EvmAsm.Evm64.Terminating.evm_invalid_stack_spec_within

#print axioms EvmAsm.Evm64.Terminating.evm_return_halt_spec_within

#print axioms EvmAsm.Evm64.Terminating.evm_return_stack_spec_within_with_capture

#print axioms EvmAsm.Evm64.Terminating.evm_revert_stack_spec_within

#print axioms EvmAsm.Evm64.Terminating.evm_selfdestruct_stack_spec_resolved

#print axioms EvmAsm.Evm64.Terminating.evm_stop_stack_spec_within

#print axioms EvmAsm.Evm64.Terminating.return_capture_nondegenerate

#print axioms EvmAsm.Evm64.Terminating.revert_window_nondegenerate

#print axioms EvmAsm.Evm64.Transient.evm_tload_stack_spec_within

#print axioms EvmAsm.Evm64.Transient.evm_tstore_stack_spec_within

#print axioms EvmAsm.Evm64.account_rlp_content_to_u256_be_balance_spec_within

#print axioms EvmAsm.Evm64.account_rlp_content_to_u64_nonce_spec_within

#print axioms EvmAsm.Evm64.account_rlp_walk_init_spec_within

#print axioms EvmAsm.Evm64.account_rlp_walk_next_field0_spec_within

#print axioms EvmAsm.Evm64.account_rlp_walk_next_field1_spec_within

#print axioms EvmAsm.Evm64.bytesRegion_dword_pair_at_setBytes

#print axioms EvmAsm.Evm64.evmMemoryIs_peel_window64

#print axioms EvmAsm.Evm64.evmMemoryIs_quarter_pair_setBytes

#print axioms EvmAsm.Evm64.evm_add_stack_spec_within

#print axioms EvmAsm.Evm64.evm_and_stack_spec_within

#print axioms EvmAsm.Evm64.evm_byte_stack_spec_within

#print axioms EvmAsm.Evm64.evm_div_v6_stack_spec

#print axioms EvmAsm.Evm64.evm_dup_stack_spec_within

#print axioms EvmAsm.Evm64.evm_eq_stack_spec_within

#print axioms EvmAsm.Evm64.evm_exp_stack_spec_within

#print axioms EvmAsm.Evm64.evm_gt_stack_spec_within

#print axioms EvmAsm.Evm64.evm_iszero_stack_spec_within

#print axioms EvmAsm.Evm64.evm_lt_stack_spec_within

#print axioms EvmAsm.Evm64.evm_mload_stack_spec_within

#print axioms EvmAsm.Evm64.evm_mod_v6_stack_spec

#print axioms EvmAsm.Evm64.evm_msize_stack_spec_within

#print axioms EvmAsm.Evm64.evm_mstore8_stack_spec_within

#print axioms EvmAsm.Evm64.evm_mstore_stack_spec_within

#print axioms EvmAsm.Evm64.evm_mul_stack_spec_within

#print axioms EvmAsm.Evm64.evm_not_stack_spec_within

#print axioms EvmAsm.Evm64.evm_or_stack_spec_within

#print axioms EvmAsm.Evm64.evm_pop_stack_spec_within

#print axioms EvmAsm.Evm64.evm_push0_stack_spec_within

#print axioms EvmAsm.Evm64.evm_push1_stack_spec_within

#print axioms EvmAsm.Evm64.evm_push_stack_spec_within

#print axioms EvmAsm.Evm64.evm_sar_stack_spec_within

#print axioms EvmAsm.Evm64.evm_sgt_stack_spec_within

#print axioms EvmAsm.Evm64.evm_shl_stack_spec_within

#print axioms EvmAsm.Evm64.evm_shr_stack_spec_within

#print axioms EvmAsm.Evm64.evm_signextend_stack_spec_within

#print axioms EvmAsm.Evm64.evm_slt_stack_spec_within

#print axioms EvmAsm.Evm64.evm_sub_stack_spec_within

#print axioms EvmAsm.Evm64.evm_swap_stack_spec_within

#print axioms EvmAsm.Evm64.evm_xor_stack_spec_within

#print axioms EvmAsm.Evm64.hpDecode_hpEncode

#print axioms EvmAsm.Evm64.indexOfSection_hashes_eq_build_code_db

#print axioms EvmAsm.Evm64.indexOfSection_matchesSection

#print axioms EvmAsm.Evm64.mptNodeKindSpec_rlp

#print axioms EvmAsm.Evm64.nodeDbIs_snoc

#print axioms EvmAsm.Evm64.nodeDbLookupSpec_eq_build_node_db

#print axioms EvmAsm.Evm64.rlpToMutableNode_rlp

#print axioms EvmAsm.Evm64.rlp_walk_init_long1_spec_within

#print axioms EvmAsm.Evm64.rlp_walk_next_scalar_spec_within

#print axioms EvmAsm.Evm64.roundUp8_eq_alignToDword

#print axioms EvmAsm.Evm64.witnessIndexIs_split_at

#print axioms EvmAsm.Evm64.witnessLookupSpec_correct

#print axioms EvmAsm.Rv64.RLP.rlp_content_to_u256_be_scalar_spec_within

#print axioms EvmAsm.Rv64.RLP.rlp_content_to_u256_be_spec_within

#print axioms EvmAsm.Rv64.RLP.rlp_content_to_u64_spec_within

#print axioms EvmAsm.Rv64.RLP.rlp_walk_init_spec_within

#print axioms EvmAsm.Rv64.RLP.rlp_walk_next_spec_within

#print axioms EvmAsm.Stateless.SpecRef.accountExistsAndIsEmpty_eq_kernel

#print axioms EvmAsm.Stateless.SpecRef.beq_EMPTY_ACCOUNT

#print axioms EvmAsm.Stateless.SpecRef.decode_account_from_leaf_inv

#print axioms EvmAsm.Stateless.accountRlp_length_le

#print axioms EvmAsm.Stateless.bytesBEtoNat_beBytes32

#print axioms EvmAsm.Stateless.decode_account_from_leaf_accountRlp
