/-
  EvmAsm.Progress.GuestImageCoverage

  The guest-image `.text` coverage figure, **DERIVED** rather than written down.

  ## Why this file exists

  #12129 was filed because three DIFFERENT hand-written coverage percentages
  coexisted in the tree, all stale, and #12286 then found two more. Every one of
  them sat under a warning telling the reader it might be stale ("re-measure
  before citing", "measure; do not copy older prose"). The lesson recorded there
  is that **a caveat is not a check** — but the gate #12286 added is only half the
  answer: it can stop a stale figure from being *written*, and cannot supply the
  figure a reader actually wants.

  This is the other half, and it is what #12129's item 3 asked for. Both inputs
  are already Lean constants:

  * `guestImageEntries` — the (address, `_prog`) pairs that ARE the image
    `CodeReq`, generated by `scripts/guest_image_coverage.py --emit-lean`;
  * `RegionMap.textSizeBytes` — `.text`'s size, one `abbrev` in
    `RegionMapLinkPins.lean`, pinned to the emitted ELF.

  So the covered byte count is a *function* of the tree, not an observation about
  it, and `DRIFT.md`'s coverage line is now rendered from these definitions by
  `lake exe progress-report drift`. There is no literal to go stale.

  ⭐ This is strictly better than substituting `guest_image_coverage.py`'s number
  into the markdown, which was the obvious reading of "generate it": that would
  re-introduce a second source of truth for a quantity Lean can already compute,
  and the Python script and the Lean `CodeReq` could then disagree without
  anything noticing. `guest_image_coverage.py` stays authoritative for the things
  it alone knows — the per-symbol GAP accounting and the unconverted-range list,
  which need the ELF symbol table.

  ## Layering

  This file imports Codegen, which is allowed for `EvmAsm/Progress/**` by the
  single documented exemption in `scripts/check-layering.sh` L1 (GH #11042), and
  is sound because L2 keeps the registry a pure sink — nothing in the verified
  core may import it back.
-/

import EvmAsm.Codegen.Proofs.GuestImage

namespace EvmAsm.Progress.GuestImageCoverage

open EvmAsm.Codegen

/-- Bytes of `.text` pinned by `guestImageCodeReq`, derived from the entries
    table. Every RV64 instruction in these programs is 4 bytes wide (the image is
    assembled without the compressed `C` extension — `Codegen/Driver.lean` passes
    `-march=rv64imac` but the emitter never produces a 2-byte form, and
    `CodeReq.ofProg` lays every entry out on a 4-byte stride), so the byte extent
    of one entry is exactly `4 * prog.length`.

    ⚠️ This counts the entries' extents, which is the right measure for THIS
    question — `guestImageCodeReq` is `CodeReq.ofEntries guestImageEntries`, so a
    byte is pinned iff it lies in some entry's extent. It is NOT a count of
    distinct addresses, and it would over-count if two entries overlapped; they
    do not, and that is the one kernel-checked fact
    `guestImageEntries_extentsOk` establishes (ascending, non-overlapping,
    inside `.text`). So the sum is exact BECAUSE of that theorem, not by
    assumption. -/
def coveredBytes : Nat :=
  guestImageEntries.foldl (fun acc e => acc + 4 * e.2.length) 0

/-- `.text`'s total size, by name, so a link-layout regen flows through. -/
def textBytes : Nat := RegionMap.textSizeBytes

/-- Number of entries in the image `CodeReq` (i.e. linked converted routines). -/
def entryCount : Nat := guestImageEntries.length

/-- Coverage in basis points (hundredths of a percent), truncated. Integer
    arithmetic only — no `Float` in a generated artifact, so the rendered digits
    are reproducible on every platform. -/
def coverageBasisPoints : Nat :=
  if textBytes = 0 then 0 else coveredBytes * 10000 / textBytes

/-- Render a basis-point count as a `"NN.NN%"` string. -/
def formatBasisPoints (bp : Nat) : String :=
  let whole := bp / 100
  let frac  := bp % 100
  s!"{whole}.{if frac < 10 then "0" else ""}{frac}%"

/-- Bytes of `.text` NOT pinned by the image `CodeReq`. Saturating, so a future
    tree where the entries somehow exceeded `.text` renders `0` rather than
    underflowing — the extent theorem rules that out, but `Nat` subtraction
    would silently wrap the intent otherwise. -/
def uncoveredBytes : Nat := textBytes - coveredBytes

/-- The one-line coverage summary rendered into `DRIFT.md`. Derived end to end;
    there is no literal here to go stale. -/
def summaryLine : String :=
  s!"`guestImageCodeReq` pins **{formatBasisPoints coverageBasisPoints}** of \
`.text` — {coveredBytes} of {textBytes} bytes across {entryCount} linked \
entries, leaving {uncoveredBytes} bytes unpinned."

end EvmAsm.Progress.GuestImageCoverage
