-- GENERATED by scripts/gen-rv64-shims.py -- do not edit by hand.
--
-- `Tactics.DropPure` now lives in the riscv-zkvm dependency, prebuilt.
-- This shim re-exports it so evm-asm's existing references keep resolving;
-- `export` aliases the SAME constants, so no statement changes meaning.
--
-- The original prelude is preserved deliberately -- aliases do not propagate
-- transitively, so those import edges are what let downstream files still see
-- the names they used to.  See original_prelude() for the full reasoning.
--
-- Regenerate with `scripts/gen-rv64-shims.py`; `--check` gates it in CI.
/-
# `drop_pure` — slice of #1435 (beads evm-asm-ww8)

Authored by @pirapira; implemented by Hermes-bot (evm-hermes).

`drop_pure h` is a sibling of `extract_pure` (#1432,
`EvmAsm/Rv64/Tactics/ExtractPure.lean`) that strips every `⌜P⌝` leaf from
`h`'s separation-conjunction chain and rebinds `h` to the bare resource
tail — *not* to an `And`-chain.

## Why a separate tactic

`extract_pure h` rewrites `h : (… ** ⌜P⌝ ** … ** ⌜Q⌝ ** R) s` into the
∧-chain `P ∧ Q ∧ R s`. That shape is convenient when the caller wants
to consume the pures (the canonical pattern is
`extract_pure h; obtain ⟨hP, hQ, h⟩ := h`).

But for the Flavor-A friction noted in beads `evm-asm-kvl` —
*hypothesis* has a pure mid-chain, *goal* has no pure — what the caller
really wants is just the resource tail in `h`'s slot, with the pures
discarded so a follow-up `xperm_hyp h` works directly with no
destructuring and no `Eq.mp`/`congrFun` reflection mismatches from
half-extracted shapes.

`xperm_pure h` (#1435 slice 2) handles the symmetric case where both
sides may carry pures and the goal needs `xperm_hyp` after pure
splitting; it does the destructure-and-split internally. `drop_pure h`
is the thinner sibling: it does *only* the rebind, leaving the user
free to pick whatever follow-up tactic fits (`xperm_hyp`, `xcancel`,
direct `exact`, …).

## Behaviour

Given `h : (A₁ ** … ** Aₙ) s` (with zero or more `Aᵢ = ⌜Pᵢ⌝`):

1. AC-normalise the chain via `extract_pure`'s simp lemma set so every
   pure leaf bubbles into a left `∧`.
2. Repeatedly project `.2` off `h`'s leading `∧` until the type is no
   longer of the form `_ ∧ _`. The pure conjuncts are discarded
   (no fresh names introduced).

Result: `h : (B₁ ** … ** Bₘ) s` where `Bⱼ` are the resource leaves of
the original chain, in `extract_pure`'s canonical AC-normal order.

If the original chain has no pure leaves, the simp step is a no-op and
the `.2` loop exits immediately, leaving `h` untouched.

## Smoke tests

The tests at the bottom of this file mirror the shapes that motivated
the kvl friction note: a single pure mid-chain, multiple pures, and the
no-pure case. They share infrastructure with `ExtractPure`'s and
`XPermPure`'s smoke tests but assert the post-tactic *type* of `h` is
the bare resource chain, not an `And`.
-/

module

public import EvmAsm.Rv64.Tactics.ExtractPure
public import EvmAsm.Rv64.Tactics.XSimp
meta import EvmAsm.Rv64.Tactics.ExtractPure
meta import EvmAsm.Rv64.Tactics.XSimp
public import RiscvZkvm.Rv64.Logic.Tactics.DropPure
meta import RiscvZkvm.Rv64.Logic.Tactics.DropPure

@[expose] public section

namespace EvmAsm.Rv64

export RiscvZkvm.Rv64 (Tactics.dropPure Tactics.dropPureLoop Tactics.evalDropPure Tactics.sepConj_pure_right_swap)

-- Namespaces downstream files `open`; see render() for why these
-- cannot come from `export`.
namespace Tactics end Tactics

end EvmAsm.Rv64
