-- GENERATED by scripts/gen-rv64-shims.py -- do not edit by hand.
--
-- `Tactics.ExtractPure` now lives in the riscv-zkvm dependency, prebuilt.
-- This shim re-exports it so evm-asm's existing references keep resolving;
-- `export` aliases the SAME constants, so no statement changes meaning.
--
-- The original prelude is preserved deliberately -- aliases do not propagate
-- transitively, so those import edges are what let downstream files still see
-- the names they used to.  See original_prelude() for the full reasoning.
--
-- Regenerate with `scripts/gen-rv64-shims.py`; `--check` gates it in CI.
/-
# `extract_pure` / `extract_pure_deep` — slice 2 of #1432

Authored by @pirapira; implemented by Hermes-bot (evm-hermes).

This file implements the pure-extraction tactics designed in slice 1
(beads evm-asm-bx7).

## Overview

`extract_pure_deep h` rewrites a hypothesis `h : (… ** ⌜P⌝ ** … ** ⌜Q⌝ ** …) s`
into a chain of `∧` applications by AC-normalising the `sepConj` chain and
applying `sepConj_pure_left` / `sepConj_pure_right` to bubble pure atoms
out. After the rewrite, the user can `obtain` directly without manually
walking the chain.

`extract_pure h` is retained as the shallow compatibility tactic. It performs
the original one-pass rewrite only, which lets existing proofs continue to
rely on their old local conjunction shape. New automation should prefer
`extract_pure_deep`.

We deliberately keep the surface small: callers say `extract_pure_deep h`,
then use plain `obtain ⟨hP, hQ, …, hRest⟩ := h` to name the extracted
purities. The richer `with ⟨…⟩` / `using P` forms sketched in slice 1
are not needed in practice — `obtain` already provides them.
-/

module

public import EvmAsm.Rv64.SepLogic
meta import EvmAsm.Rv64.SepLogic
public import RiscvZkvm.Rv64.Logic.Tactics.ExtractPure
meta import RiscvZkvm.Rv64.Logic.Tactics.ExtractPure

@[expose] public section

namespace EvmAsm.Rv64

export RiscvZkvm.Rv64 (Tactics.sepConj_pure_head_assoc_eq Tactics.sepConj_pure_mid_assoc_eq Tactics.sepConj_pure_mid_left Tactics.sepConj_pure_mid_left_eq)
export RiscvZkvm.Rv64 (Tactics.sepConj_pure_mid_right Tactics.sepConj_pure_mid_right_eq Tactics.sepConj_pure_pure_eq Tactics.sepConj_pure_pure_left_eq)
export RiscvZkvm.Rv64 (Tactics.tacticExtract_pure_ Tactics.tacticExtract_pure_deep_)

-- Namespaces downstream files `open`; see render() for why these
-- cannot come from `export`.
namespace Tactics end Tactics

end EvmAsm.Rv64
