-- GENERATED by scripts/gen-rv64-shims.py -- do not edit by hand.
--
-- `Tactics.PerfTrace` now lives in the riscv-zkvm dependency, prebuilt.
-- This shim re-exports it so evm-asm's existing references keep resolving;
-- `export` aliases the SAME constants, so no statement changes meaning.
--
-- Only the export block below is regenerated. The prelude between the
-- markers is preserved verbatim and is the source of truth -- aliases do not
-- propagate transitively, so those import edges are what let downstream files
-- still see the names they used to. Edit it here if the imports must change.
--
-- Regenerate with `scripts/gen-rv64-shims.py`; `--check` gates it in CI.
-- BEGIN shim prelude (preserved from the original module)
/-
  EvmAsm.Rv64.Tactics.PerfTrace

  Trace class hierarchy for profiling the runBlock/seqFrame/xperm tactic pipeline.

  Enable all: `set_option trace.runBlock.perf true`
  Enable subset: `set_option trace.runBlock.perf.perm true`

  Use with `set_option trace.profiler true` for wall-clock timing.
-/

module

public import Lean.Util.Trace
meta import Lean.Util.Trace
public import RiscvZkvm.Rv64.Logic.Tactics.PerfTrace
meta import RiscvZkvm.Rv64.Logic.Tactics.PerfTrace

@[expose] public section
-- END shim prelude

