-- GENERATED by scripts/gen-rv64-shims.py -- do not edit by hand.
--
-- `Tactics.RunBlock` now lives in the riscv-zkvm dependency, prebuilt.
-- This shim re-exports it so evm-asm's existing references keep resolving;
-- `export` aliases the SAME constants, so no statement changes meaning.
--
-- The original prelude is preserved deliberately -- aliases do not propagate
-- transitively, so those import edges are what let downstream files still see
-- the names they used to.  See original_prelude() for the full reasoning.
--
-- Regenerate with `scripts/gen-rv64-shims.py`; `--check` gates it in CI.
/-
  EvmAsm.Rv64.Tactics.RunBlock

  Multi-instruction block verification tactic. Composes N single-instruction
  specs into a single bounded CPS proof with automatic framing, address
  normalization, and postcondition permutation.

  ## Quick Reference

  **Auto mode** (preferred — resolves specs from `@[spec_gen_rv64]` database):
  ```
  theorem my_block_spec ... :
      cpsTripleWithin 3 base (base + 12) cr
        ((base ↦ᵢ .LW .x7 .x12 off) ** ((base + 4) ↦ᵢ .ADD .x7 .x7 .x6) **
         ((base + 8) ↦ᵢ .SW .x12 .x7 off) ** (.x12 ↦ᵣ sp) ** ...)
        (... updated state ...) := by
    runBlock
  ```

  **Manual mode** (pass spec hypotheses explicitly):
  ```
  theorem my_composite_spec ... := by
    have s1 := sub_spec_phase1 ...
    have s2 := sub_spec_phase2 ...
    runBlock s1 s2
  ```

  ## How It Works

  1. Extracts `instrAt` atoms from the goal's precondition (in order)
  2. For each instruction, looks up matching `@[spec_gen_rv64]` specs and
     instantiates via unification against the current assertion state
  3. Frames the first spec against the goal's full precondition
  4. Chains specs via `seqFrame` with automatic address normalization
  5. Permutes the final postcondition to match the goal

  ## Debugging

  Enable tracing for detailed resolution output:
  ```
  set_option trace.runBlock true in
  theorem my_spec ... := by runBlock
  ```

  Use `#spec_db` (from SpecDb.lean) to inspect registered specs:
  ```
  #spec_db  -- prints all @[spec_gen_rv64] entries grouped by instruction
  ```

  ## When Auto Mode Fails

  Common reasons and fixes:
  - **Missing spec**: Check `#spec_db` for coverage. Add `@[spec_gen_rv64]` to your spec.
  - **Proof obligation unsolved**: Auto-mode handles `rd ≠ .x0`, `rd ≠ rs`, and
    `isValidMemAccess` hypotheses. Other obligations need manual specs or extra hyps.
  - **Composite specs**: Multi-instruction sub-specs (e.g., `add_limb_carry_spec`)
    can't be auto-resolved. Use manual mode: `runBlock s1 s2`.
-/

module

public import Lean
public import EvmAsm.Rv64.Tactics.SeqFrame
public import EvmAsm.Rv64.Tactics.SpecDb
meta import Lean
meta import EvmAsm.Rv64.Tactics.SeqFrame
meta import EvmAsm.Rv64.Tactics.SpecDb
public import RiscvZkvm.Rv64.Logic.Tactics.RunBlock
meta import RiscvZkvm.Rv64.Logic.Tactics.RunBlock

@[expose] public section

namespace EvmAsm.Rv64

export RiscvZkvm.Rv64 (Tactics.expandAbbrevsInAssertion Tactics.normalizeTypeAddrs Tactics.tacticRunBlockFromPost_ Tactics.tacticRunBlock_)
export RiscvZkvm.Rv64 (Tactics.tacticValidMem)

-- Namespaces downstream files `open`; see render() for why these
-- cannot come from `export`.
namespace Tactics end Tactics

end EvmAsm.Rv64
