-- GENERATED by scripts/gen-rv64-shims.py -- do not edit by hand.
--
-- `Tactics.SeqFrame` now lives in the riscv-zkvm dependency, prebuilt.
-- This shim re-exports it so evm-asm's existing references keep resolving;
-- `export` aliases the SAME constants, so no statement changes meaning.
--
-- Only the export block below is regenerated. The prelude between the
-- markers is preserved verbatim and is the source of truth -- aliases do not
-- propagate transitively, so those import edges are what let downstream files
-- still see the names they used to. Edit it here if the imports must change.
--
-- Regenerate with `scripts/gen-rv64-shims.py`; `--check` gates it in CI.
-- BEGIN shim prelude (preserved from the original module)
/-
  EvmAsm.Rv64.Tactics.SeqFrame

  Frame-aware sequential composition of two `cpsTripleWithin` specs.

  ## Usage

  ```
  have s1 : cpsTripleWithin n base mid cr P Q1 := ...
  have s2 : cpsTripleWithin m mid exit_ cr P2 Q2 := ...
  seqFrame s1 s2
  -- Result: cpsTripleWithin (n + m) base exit_ cr P (Q2 ** Frame)
  -- where Frame = Q1 \ P2 (postcondition atoms not consumed by s2's precondition)
  ```

  ## Algorithm

  1. Extracts postcondition Q1 of h1 and precondition P2 of h2
  2. Computes frame F = Q1 \ P2 (atoms in Q1 not matched by P2)
  3. Frames h2 with the bounded frame rule
  4. Builds permutation proof Q1 → (P2 ** F)
  5. Composes via the bounded sequential rule

  If the goal is a bounded CPS triple, `seqFrame` tries to close it (with postcondition
  permutation). Otherwise, the result is introduced as a hypothesis named `h1h2`.
-/

module

public import Lean
public import EvmAsm.Rv64.Tactics.XCancel
public import EvmAsm.Rv64.InstructionSpecs
public import EvmAsm.Rv64.Tactics.PerfTrace
meta import Lean
meta import EvmAsm.Rv64.Tactics.XCancel
meta import EvmAsm.Rv64.InstructionSpecs
meta import EvmAsm.Rv64.Tactics.PerfTrace
public import RiscvZkvm.Rv64.Logic.Tactics.SeqFrame
meta import RiscvZkvm.Rv64.Logic.Tactics.SeqFrame

@[expose] public section
-- END shim prelude

namespace EvmAsm.Rv64

export RiscvZkvm.Rv64 (Tactics.assignOrPermuteWithin Tactics.buildDisjointProof Tactics.buildMonoProof Tactics.buildMonoProofDirect)
export RiscvZkvm.Rv64 (Tactics.buildPcFreeProof Tactics.computeFrame Tactics.extractUnionChain Tactics.mkIdLambda)
export RiscvZkvm.Rv64 (Tactics.mkIdentityMono Tactics.mkPermLambda Tactics.parseCpsTripleWithin? Tactics.runTacticSilent)
export RiscvZkvm.Rv64 (Tactics.seqFrameWithinCore Tactics.tacticBv_addr Tactics.tacticCrDisjoint Tactics.tacticCrMono)
export RiscvZkvm.Rv64 (Tactics.tacticIntro_letsAt_ Tactics.tacticSeqFrame__)

-- Namespaces downstream files `open`; see render() for why these
-- cannot come from `export`.
namespace Tactics end Tactics

end EvmAsm.Rv64
