-- GENERATED by scripts/gen-rv64-shims.py -- do not edit by hand.
--
-- `Tactics.SpecDb` now lives in the riscv-zkvm dependency, prebuilt.
-- This shim re-exports it so evm-asm's existing references keep resolving;
-- `export` aliases the SAME constants, so no statement changes meaning.
--
-- Only the export block below is regenerated. The prelude between the
-- markers is preserved verbatim and is the source of truth -- aliases do not
-- propagate transitively, so those import edges are what let downstream files
-- still see the names they used to. Edit it here if the imports must change.
--
-- Regenerate with `scripts/gen-rv64-shims.py`; `--check` gates it in CI.
-- BEGIN shim prelude (preserved from the original module)
/-
  EvmAsm.Rv64.Tactics.SpecDb

  Persistent database mapping instruction constructors to spec theorems.
  Used by `runBlock` (auto mode) to resolve specs automatically.

  ## Usage

  Tag single-instruction specs with `@[spec_gen_rv64]`:
  ```
  @[spec_gen_rv64]
  theorem lw_spec_gen_rv64 (rd rs1 : Reg) ... :
      cpsTripleWithin 1 addr (addr + 4) (CodeReq.singleton addr (.LW rd rs1 offset)) (...) (...) := ...
  ```

  The instruction constructor (e.g., `EvmAsm.Rv64.Instr.LW`) is auto-detected
  from the `CodeReq.singleton` argument, or (for backward compatibility) from
  an `instrAt` atom in the precondition. Supports `cpsTripleWithin`,
  `cpsBranchWithin`, `cpsNBranchWithin`, and `cpsHaltTripleWithin`; historical
  unbounded shapes are accepted while the migration is in progress.

  ## Diagnostics

  ```
  #spec_db_rv64  -- prints all registered specs grouped by instruction
  ```

  ## Requirements for `@[spec_gen_rv64]` specs

  - Must be a bounded CPS spec (`cpsTripleWithin`, `cpsBranchWithin`,
    `cpsNBranchWithin`, or `cpsHaltTripleWithin`) or a historical unbounded
    compatibility wrapper during migration
  - The CodeReq argument must be `CodeReq.singleton addr instr`, OR
    the precondition must contain an `instrAt` (`↦ᵢ`) atom (backward compat)
  - The instruction must be a concrete constructor application (e.g., `.ADD .x7 .x7 .x6`)
  - Multiple specs per instruction are allowed (tried in registration order)
-/

module

public import Lean
meta import Lean
public import RiscvZkvm.Rv64.Logic.Tactics.SpecDb
meta import RiscvZkvm.Rv64.Logic.Tactics.SpecDb

@[expose] public section
-- END shim prelude

namespace EvmAsm.Rv64

export RiscvZkvm.Rv64 (Tactics.SpecGenEntry Tactics.SpecGenEntry.casesOn Tactics.SpecGenEntry.ctorIdx Tactics.SpecGenEntry.instrCtor)
export RiscvZkvm.Rv64 (Tactics.SpecGenEntry.mk Tactics.SpecGenEntry.mk.inj Tactics.SpecGenEntry.mk.injEq Tactics.SpecGenEntry.mk.noConfusion)
export RiscvZkvm.Rv64 (Tactics.SpecGenEntry.mk.sizeOf_spec Tactics.SpecGenEntry.noConfusion Tactics.SpecGenEntry.noConfusionType Tactics.SpecGenEntry.rec)
export RiscvZkvm.Rv64 (Tactics.SpecGenEntry.recOn Tactics.SpecGenEntry.specName Tactics.findSpecsForInstr Tactics.getAllSpecs)
export RiscvZkvm.Rv64 (Tactics.instBEqSpecGenEntry Tactics.instBEqSpecGenEntry.beq Tactics.instInhabitedSpecGenEntry Tactics.instInhabitedSpecGenEntry.default)
export RiscvZkvm.Rv64 (Tactics.specGenExt Tactics.«command#spec_db_rv64»)

-- Namespaces downstream files `open`; see render() for why these
-- cannot come from `export`.
namespace Tactics end Tactics
namespace Tactics.SpecGenEntry end Tactics.SpecGenEntry
namespace Tactics.SpecGenEntry.mk end Tactics.SpecGenEntry.mk
namespace Tactics.instBEqSpecGenEntry end Tactics.instBEqSpecGenEntry
namespace Tactics.instInhabitedSpecGenEntry end Tactics.instInhabitedSpecGenEntry

end EvmAsm.Rv64
