-- GENERATED by scripts/gen-rv64-shims.py -- do not edit by hand.
--
-- `Tactics.SymStep` now lives in the riscv-zkvm dependency, prebuilt.
-- This shim re-exports it so evm-asm's existing references keep resolving;
-- `export` aliases the SAME constants, so no statement changes meaning.
--
-- Only the export block below is regenerated. The prelude between the
-- markers is preserved verbatim and is the source of truth -- aliases do not
-- propagate transitively, so those import edges are what let downstream files
-- still see the names they used to. Edit it here if the imports must change.
--
-- Regenerate with `scripts/gen-rv64-shims.py`; `--check` gates it in CI.
-- BEGIN shim prelude (preserved from the original module)
/-
  EvmAsm.Rv64.Tactics.SymStep

  Symbolic-simulation prototype tactic — slice 2 of GH #302 / beads
  `evm-asm-avjm`.

  `sym_step h` rewrites a goal of shape `step s = ?` (or a goal containing
  such a sub-term) using the canonical fetch hypothesis
  `h : s.code s.pc = some i` for a *non-branch / non-memory / non-ECALL /
  non-EBREAK* RV64IM instruction `i`. The rewrite uses
  `EvmAsm.Rv64.step_non_ecall_non_mem` and then unfolds `execInstrBr`,
  producing an explicit `(s.setReg … …).setPC (s.pc + 4)`-style record
  update.

  ## Scope (slice 2)

  This is a *prototype* aimed at the four smoke-test instruction classes
  required by the acceptance criteria of beads `evm-asm-avjm`:
  `ADDI`, `ADD`, `LUI`, `SLLI`. All four route through the
  `step_non_ecall_non_mem` non-memory path, so a single macro covers them.

  Memory instructions (LD/SD/LW/…) and branches (BEQ/BNE/JAL/…) need
  separate per-class macros that supply the validity hypothesis or the
  branch-condition decision; those are deferred to a follow-up slice
  (see GH #302).

  ## Usage

  ```lean
  example (s : MachineState) (rd rs1 : Reg) (imm : BitVec 12)
      (h : s.code s.pc = some (.ADDI rd rs1 imm)) :
      step s = some ((s.setReg rd (s.getReg rs1 + signExtend12 imm)).setPC (s.pc + 4)) := by
    sym_step h
  ```

  ## Failure modes

  - If `i` is a branch / memory / ECALL / EBREAK instruction, the
    `decide`-discharged side conditions of `step_non_ecall_non_mem` will
    fail; use the dedicated `step_*` lemmas in `EvmAsm/Rv64/Execution.lean`
    directly instead.
  - If the goal does not match `step s = ?`, the underlying `rw` will
    fail with the usual error message.

  ## References

  - GH issue #302 ("LNSym-style symbolic simulation on partial state").
  - `EvmAsm/Rv64/Execution.lean` — `step`, `execInstrBr`,
    `step_non_ecall_non_mem`, and the per-instruction `step_*` lemmas.
-/

module

public import Lean
public import EvmAsm.Rv64.Execution
meta import Lean
meta import EvmAsm.Rv64.Execution
public import RiscvZkvm.Rv64.Logic.Tactics.SymStep
meta import RiscvZkvm.Rv64.Logic.Tactics.SymStep

@[expose] public section
-- END shim prelude

namespace EvmAsm.Rv64

export RiscvZkvm.Rv64 (Tactics.symStepTac)

-- Namespaces downstream files `open`; see render() for why these
-- cannot come from `export`.
namespace Tactics end Tactics

end EvmAsm.Rv64
