-- GENERATED by scripts/gen-rv64-shims.py -- do not edit by hand.
--
-- `Tactics.WP` now lives in the riscv-zkvm dependency, prebuilt.
-- This shim re-exports it so evm-asm's existing references keep resolving;
-- `export` aliases the SAME constants, so no statement changes meaning.
--
-- Only the export block below is regenerated. The prelude between the
-- markers is preserved verbatim and is the source of truth -- aliases do not
-- propagate transitively, so those import edges are what let downstream files
-- still see the names they used to. Edit it here if the imports must change.
--
-- Regenerate with `scripts/gen-rv64-shims.py`; `--check` gates it in CI.
-- BEGIN shim prelude (preserved from the original module)
/-
  EvmAsm.Rv64.Tactics.WP

  Thin tactic surface for WP/CFG certificates.  The proof search/calculation
  lives in the certificate constructors; this tactic consumes the resulting
  object and closes the corresponding CPS goal.
-/

import Lean
import EvmAsm.Rv64.SyscallSpecs
import EvmAsm.Rv64.Tactics.WPAttr
import EvmAsm.Rv64.WP.CFG
import EvmAsm.Rv64.WP.Call
import EvmAsm.Rv64.Tactics.RunBlock
import EvmAsm.Rv64.Tactics.SeqFrame
import EvmAsm.Rv64.Tactics.XPermPure
import RiscvZkvm.Rv64.Logic.Tactics.WP
-- END shim prelude

namespace EvmAsm.Rv64

export RiscvZkvm.Rv64 (Tactics.WPTests.sltiu_one_zero_classifier Tactics.WPTests.wp_rv64_dead_test_hint Tactics.WPTests.wp_rv64_leaf_synth_add_own_cfg Tactics.WPTests.wp_rv64_leaf_synth_addi_manual_cfg)
export RiscvZkvm.Rv64 (Tactics.WPTests.wp_rv64_leaf_synth_addi_own_cfg Tactics.WPTests.wp_rv64_leaf_synth_li_cfg Tactics.WPTests.wp_rv64_leaf_synth_li_sltiu_zero_cfg Tactics.WPTests.wp_rv64_leaf_synth_partial_hint_cfg)
export RiscvZkvm.Rv64 (Tactics.WPTests.wp_rv64_leaf_synth_sd_own_cfg Tactics.WPTests.wp_rv64_leaf_synth_sltiu_zero_cfg Tactics.solveParamMVarsWithLocals Tactics.tacticWp_rv64_cert)
export RiscvZkvm.Rv64 (Tactics.tacticWp_rv64_dead_hint Tactics.tacticWp_rv64_disjoint Tactics.tacticWp_rv64_entails Tactics.tacticWp_rv64_link_fail)
export RiscvZkvm.Rv64 (Tactics.wpRv64BranchSeqNotTakenBlockDisjointTac Tactics.wpRv64BranchSeqNotTakenDisjointTac Tactics.wpRv64BranchSeqNotTakenNBranchDisjointTac Tactics.wpRv64BranchSeqTakenBlockDisjointTac)
export RiscvZkvm.Rv64 (Tactics.wpRv64BranchSeqTakenBlockNBranchDisjointTac Tactics.wpRv64BranchSeqTakenBranchConvergeDisjointTac Tactics.wpRv64BranchSeqTakenDisjointTac Tactics.wpRv64CfgCertSeqDisjointAutoTac)
export RiscvZkvm.Rv64 (Tactics.wpRv64CfgCertSeqDisjointWithAutoTac Tactics.wpRv64CfgCertSeqDisjointWithTac Tactics.wpRv64CfgSeqDisjointAutoTac Tactics.wpRv64CfgSeqDisjointExactTac)
export RiscvZkvm.Rv64 (Tactics.wpRv64CfgSeqDisjointWithAutoTac Tactics.wpRv64CfgSeqDisjointWithTac Tactics.wpRv64CfgSeqExactTac Tactics.wpRv64ChangeEntryTac)
export RiscvZkvm.Rv64 (Tactics.wpRv64ChangeExitTac Tactics.wpRv64Cmd Tactics.wpRv64DeadTac Tactics.wpRv64ExitReflTac)
export RiscvZkvm.Rv64 (Tactics.wpRv64ExtendCodeTac Tactics.wpRv64ExtendSetPreTac Tactics.wpRv64FrameRTac Tactics.wpRv64LeafSynthTac)
export RiscvZkvm.Rv64 (Tactics.wpRv64LeafTac Tactics.wpRv64LinkTac Tactics.wpRv64LoopNatSoundTac Tactics.wpRv64LoopNatTac)
export RiscvZkvm.Rv64 (Tactics.wpRv64MonoStepsTac Tactics.wpRv64NBranchExtendCodeTac Tactics.wpRv64NBranchExtendSetPreTac Tactics.wpRv64NBranchFrameRTac)
export RiscvZkvm.Rv64 (Tactics.wpRv64NBranchFrameSetPreTac Tactics.wpRv64NBranchJoin2ResolveFirstAutoTac Tactics.wpRv64NBranchJoin2ResolveFirstDeadAutoTac Tactics.wpRv64NBranchJoin2ResolveFirstTac)
export RiscvZkvm.Rv64 (Tactics.wpRv64NBranchJoin2ResolveSecondAutoTac Tactics.wpRv64NBranchJoin2ResolveSecondDeadAutoTac Tactics.wpRv64NBranchJoin2ResolveSecondTac Tactics.wpRv64NBranchJoin3ResolveSecondAutoTac)
export RiscvZkvm.Rv64 (Tactics.wpRv64NBranchJoin3ResolveSecondDeadAutoTac Tactics.wpRv64NBranchJoin3ResolveSecondTac Tactics.wpRv64NBranchJoin4MaxTac Tactics.wpRv64NBranchJoin4ResolveThirdDeadAutoTac)
export RiscvZkvm.Rv64 (Tactics.wpRv64NBranchJoin4ResolveThirdTac Tactics.wpRv64NBranchJoin4WithTac Tactics.wpRv64NBranchSeqExitCertDisjointTac Tactics.wpRv64NBranchSeqExitCertDisjointWithTac)
export RiscvZkvm.Rv64 (Tactics.wpRv64NBranchSeqExitNBranchDisjointTac Tactics.wpRv64NBranchSeqHeadBlockDisjointTac Tactics.wpRv64NBranchSeqHeadNBranchDisjointTac Tactics.wpRv64NBranchSeqSecondNBranchDisjointTac)
export RiscvZkvm.Rv64 (Tactics.wpRv64NBranchSeqThirdCertAutoTac Tactics.wpRv64NBranchSeqThirdCertDisjointTac Tactics.wpRv64NBranchSeqThirdCertDisjointWithAutoTac Tactics.wpRv64NBranchSeqThirdCertDisjointWithTac)
export RiscvZkvm.Rv64 (Tactics.wpRv64NBranchSetPreTac Tactics.wpRv64NBranchWeakenHeadPostTac Tactics.wpRv64NBranchWeakenPosts2AutoTac Tactics.wpRv64NBranchWeakenPosts2Tac)
export RiscvZkvm.Rv64 (Tactics.wpRv64NBranchWeakenPosts3AutoTac Tactics.wpRv64NBranchWeakenPosts3Tac Tactics.wpRv64NBranchWeakenPosts4AutoTac Tactics.wpRv64NBranchWeakenPosts4MergeFirstTwoWithAutoTac)
export RiscvZkvm.Rv64 (Tactics.wpRv64NBranchWeakenPosts4Tac Tactics.wpRv64NBranchWeakenPosts4WithAutoTac Tactics.wpRv64NBranchWeakenPosts4WithTac Tactics.wpRv64NBranchWeakenPostsTac)
export RiscvZkvm.Rv64 (Tactics.wpRv64NBranchWeakenPreTac Tactics.wpRv64NBranchWeakenPreWithTac Tactics.wpRv64NormAtTac Tactics.wpRv64NormTac)
export RiscvZkvm.Rv64 (Tactics.wpRv64SeqBlockDisjointExactTac Tactics.wpRv64SeqBlockDisjointTac Tactics.wpRv64SeqBlockExactTac Tactics.wpRv64SeqBlockNBranchDisjointTac)
export RiscvZkvm.Rv64 (Tactics.wpRv64SeqBlockNBranchFramedAutoTac Tactics.wpRv64SeqBlockNBranchFramedDisjointTac Tactics.wpRv64SeqBlockNBranchFramedDisjointWithTac Tactics.wpRv64SeqBlockTac)
export RiscvZkvm.Rv64 (Tactics.wpRv64SeqDisjointExactTac Tactics.wpRv64SeqDisjointTac Tactics.wpRv64SeqExactTac Tactics.wpRv64SeqTac)
export RiscvZkvm.Rv64 (Tactics.wpRv64SetPostTac Tactics.wpRv64SetPreTac Tactics.wpRv64Tac Tactics.wpRv64UnreachableTac)
export RiscvZkvm.Rv64 (Tactics.wpRv64WeakenPostTac Tactics.wpRv64WeakenPreTac)

-- Namespaces downstream files `open`; see render() for why these
-- cannot come from `export`.
namespace Tactics end Tactics
namespace Tactics.WPTests end Tactics.WPTests

end EvmAsm.Rv64
