-- GENERATED by scripts/gen-rv64-shims.py -- do not edit by hand.
--
-- `Tactics.WPAttr` now lives in the riscv-zkvm dependency, prebuilt.
-- This shim re-exports it so evm-asm's existing references keep resolving;
-- `export` aliases the SAME constants, so no statement changes meaning.
--
-- Only the export block below is regenerated. The prelude between the
-- markers is preserved verbatim and is the source of truth -- aliases do not
-- propagate transitively, so those import edges are what let downstream files
-- still see the names they used to. Edit it here if the imports must change.
--
-- Regenerate with `scripts/gen-rv64-shims.py`; `--check` gates it in CI.
-- BEGIN shim prelude (preserved from the original module)
/-
  EvmAsm.Rv64.Tactics.WPAttr

  Declares the `rv64_wp` simp set used by `wp_rv64_link` to expose
  WP-calculator handoff shapes before separation-frame permutation.
-/

module

public import Lean.Meta.Tactic.Simp.RegisterCommand
meta import Lean.Meta.Tactic.Simp.RegisterCommand
public meta import Lean.Meta.Tactic.Simp.Attr
public import RiscvZkvm.Rv64.Logic.Tactics.WPAttr
meta import RiscvZkvm.Rv64.Logic.Tactics.WPAttr

@[expose] public section
-- END shim prelude

namespace EvmAsm.Rv64

export RiscvZkvm.Rv64 (Tactics.Parser.Attr.rv64_wp Tactics.Parser.Attr.rv64_wp_proc Tactics.rv64WpCertExt Tactics.rv64WpDeadExt)
export RiscvZkvm.Rv64 (Tactics.rv64WpDisjointExt Tactics.rv64WpEntailsExt)

-- Namespaces downstream files `open`; see render() for why these
-- cannot come from `export`.
namespace Tactics end Tactics
namespace Tactics.Parser end Tactics.Parser
namespace Tactics.Parser.Attr end Tactics.Parser.Attr

end EvmAsm.Rv64
