-- GENERATED by scripts/gen-rv64-shims.py -- do not edit by hand.
--
-- `Tactics.XCancelStruct` now lives in the riscv-zkvm dependency, prebuilt.
-- This shim re-exports it so evm-asm's existing references keep resolving;
-- `export` aliases the SAME constants, so no statement changes meaning.
--
-- Only the export block below is regenerated. The prelude between the
-- markers is preserved verbatim and is the source of truth -- aliases do not
-- propagate transitively, so those import edges are what let downstream files
-- still see the names they used to. Edit it here if the imports must change.
--
-- Regenerate with `scripts/gen-rv64-shims.py`; `--check` gates it in CI.
-- BEGIN shim prelude (preserved from the original module)
/-
  EvmAsm.Rv64.Tactics.XCancelStruct

  Structural cancellation tactic — sibling of `xperm` / `xperm_hyp` / `xcancel`
  that closes a goal `⊢ G s` from a hypothesis `h : H s` *without* flattening
  either `**`-chain to its leaf atoms.

  Design reference: `docs/structural-cancel-design.md` (#245 slice 2,
  beads `evm-asm-0qba`). Prerequisite lemma family `sepConj_eq_congr_left` /
  `_right` / `_mid_left` lives in `EvmAsm/Rv64/SepLogic.lean` (#245 slice 3-pre,
  PR #1661).

  ## Usage

  ```lean
  -- (a) Pure AC-permutation, no opaque-bridge needed.
  example {A B C : Assertion} {s : PartialState} (h : (A ** B ** C) s) :
      (C ** A ** B) s := by xcancel_struct h

  -- (b) With `with`: pre-rewrite `h` via user-supplied equation lemmas before
  -- the AC-permutation step. Each lemma is applied as a `simp only` rewrite
  -- and may use `sepConj_eq_congr_mid_left` implicitly via simp's congruence
  -- closure to lift the equality through the surrounding `**`-chain.
  example {A B C D : Assertion} {s : PartialState}
      (heq : A = D) (h : (A ** B ** C) s) :
      (D ** B ** C) s := by xcancel_struct h with heq
  ```

  ## Algorithm

  Let `H` and `G` be the hypothesis and goal assertions.

  1. **Optional bridge step.** If `with e₁, …, eₙ` is supplied, apply
     `simp only [e₁, …, eₙ]` to `h`. Each `eᵢ : Aᵢ = Bᵢ` is lifted through the
     surrounding `**`-chain by `simp`'s congruence machinery — the AC-rewrite
     trio (`sepConj_assoc'` / `sepConj_comm'` / `sepConj_left_comm'`) is **not**
     unfolded at this stage; only the matched sub-assertions are rewritten.
  2. **AC-permutation step.** `sep_perm h` closes the goal via
     `congrFun (show H' = G by ac_rfl) s`. Crucially `ac_rfl` operates over
     the registered `Std.Associative (sepConj)` and `Std.Commutative (sepConj)`
     instances and treats every non-`sepConj` sub-tree as an atom — opaque
     `@[irreducible]` bundles like `iterN3Max_da …` stay opaque.
  3. **Fallback.** If the structural AC step fails (notably on flat,
     large chains where `ac_rfl` can hit recursion limits), retry with
     `xperm_hyp`. This preserves the existing proven permutation path for
     non-structural sites while keeping `xcancel_struct` opt-in.

  ## Why structural

  Both steps preserve sub-tree opacity. The AC engine sees the chain as a
  binary tree over `sepConj`; whatever lives at the leaves is a black box.
  This is exactly the property `xperm_hyp` lacks — `xperm_hyp` flattens to
  atoms via `flattenSepConj` and then runs an O(n²) `isDefEq` matching loop,
  so its cost scales with the *total* atom count rather than the changing
  portion. See `docs/structural-cancel-design.md` §"Why structural beats
  flatten-based at the hot sites".

  ## Failure mode

  If the AC step cannot close the goal (residual atoms differ between `h`
  and the goal) `ac_rfl` raises a clear error pointing at the residual.
  Graceful "leave the residual as a sub-goal" handling is a follow-up
  (#156 / `xperm_partial`) — the prototype here is fail-fast.

  ## Out of scope (per design note §"Out of scope for slice 3")

  - "Match modulo `isDefEq`" mode — keep the prototype cheap by *not* paying
    the unfolding cost.
  - Automatic discovery of equation lemmas via the `simp` set; the user
    passes them explicitly with `with …`.
  - Goal-side variant; only `xcancel_struct <hyp>` ships in this slice.

  ## References

  - GH issue #245.
  - `docs/structural-cancel-design.md`.
  - `EvmAsm/Rv64/SepLogic.lean` — `sepConj_eq_congr_*` family + `sep_perm`.
-/

module

public import Lean
public import EvmAsm.Rv64.SepLogic
public import EvmAsm.Rv64.Tactics.XSimp
meta import Lean
meta import EvmAsm.Rv64.SepLogic
meta import EvmAsm.Rv64.Tactics.XSimp
public import RiscvZkvm.Rv64.Logic.Tactics.XCancelStruct
meta import RiscvZkvm.Rv64.Logic.Tactics.XCancelStruct

@[expose] public section
-- END shim prelude

namespace EvmAsm.Rv64

export RiscvZkvm.Rv64 (Tactics.xcancelStructTac)

-- Namespaces downstream files `open`; see render() for why these
-- cannot come from `export`.
namespace Tactics end Tactics

end EvmAsm.Rv64
