-- GENERATED by scripts/gen-rv64-shims.py -- do not edit by hand.
--
-- `Tactics.XPermChunked` now lives in the riscv-zkvm dependency, prebuilt.
-- This shim re-exports it so evm-asm's existing references keep resolving;
-- `export` aliases the SAME constants, so no statement changes meaning.
--
-- The original prelude is preserved deliberately -- aliases do not propagate
-- transitively, so those import edges are what let downstream files still see
-- the names they used to.  See original_prelude() for the full reasoning.
--
-- Regenerate with `scripts/gen-rv64-shims.py`; `--check` gates it in CI.
/-
  EvmAsm.Rv64.Tactics.XPermChunked

  Opt-in surface for chunked sepConj permutation experiments.
-/

module

public import Lean
public import EvmAsm.Rv64.Tactics.XPerm
meta import Lean
meta import EvmAsm.Rv64.Tactics.XPerm
public import RiscvZkvm.Rv64.Logic.Tactics.XPermChunked
meta import RiscvZkvm.Rv64.Logic.Tactics.XPermChunked

@[expose] public section

namespace EvmAsm.Rv64

export RiscvZkvm.Rv64 (Tactics.tacticXperm_chunked_ Tactics.tacticXperm_chunked_Only Tactics.tacticXperm_chunked_WithStrict)

-- Namespaces downstream files `open`; see render() for why these
-- cannot come from `export`.
namespace Tactics end Tactics

end EvmAsm.Rv64
