-- GENERATED by scripts/gen-rv64-shims.py -- do not edit by hand.
--
-- `Tactics.XSimp` now lives in the riscv-zkvm dependency, prebuilt.
-- This shim re-exports it so evm-asm's existing references keep resolving;
-- `export` aliases the SAME constants, so no statement changes meaning.
--
-- Only the export block below is regenerated. The prelude between the
-- markers is preserved verbatim and is the source of truth -- aliases do not
-- propagate transitively, so those import edges are what let downstream files
-- still see the names they used to. Edit it here if the imports must change.
--
-- Regenerate with `scripts/gen-rv64-shims.py`; `--check` gates it in CI.
-- BEGIN shim prelude (preserved from the original module)
/-
  EvmAsm.Rv64.Tactics.XSimp

  Higher-level separation logic tactics built on xperm, inspired by the
  `xsimpl` tactic from SPlean / CFML (see XPerm.lean for full references).

  - `xperm_hyp h`: Given hypothesis `h : P s`, proves goal `Q s` where Q is
    an AC-permutation of P. Drop-in replacement for `sep_perm h`.

  - `xsimp`: Proves goals of the form `∀ h, P h → Q h` (i.e., `himpl P Q`)
    where Q is an AC-permutation of P.
-/

module

public import Lean
public import EvmAsm.Rv64.Tactics.XPerm
meta import Lean
meta import EvmAsm.Rv64.Tactics.XPerm
public import RiscvZkvm.Rv64.Logic.Tactics.XSimp
meta import RiscvZkvm.Rv64.Logic.Tactics.XSimp

@[expose] public section
-- END shim prelude

namespace EvmAsm.Rv64

export RiscvZkvm.Rv64 (Tactics.tacticXperm_hyp_ Tactics.tacticXsimp)

-- Namespaces downstream files `open`; see render() for why these
-- cannot come from `export`.
namespace Tactics end Tactics

end EvmAsm.Rv64
