-- GENERATED by scripts/gen-rv64-shims.py -- do not edit by hand.
--
-- `AddrNorm` now lives in the riscv-zkvm dependency, prebuilt.
-- This shim re-exports it so evm-asm's existing references keep resolving;
-- `export` aliases the SAME constants, so no statement changes meaning.
--
-- Only the export block below is regenerated. The prelude between the
-- markers is preserved verbatim and is the source of truth -- aliases do not
-- propagate transitively, so those import edges are what let downstream files
-- still see the names they used to. Edit it here if the imports must change.
--
-- Regenerate with `scripts/gen-rv64-shims.py`; `--check` gates it in CI.
-- BEGIN shim prelude (preserved from the original module)
/-
  EvmAsm.Rv64.AddrNorm

  `rv64_addr` grindset for Rv64 address arithmetic (GRIND.md Phase 3).

  Historical baseline: the existing `bv_addr` macro (in `Tactics/SeqFrame.lean`)
  closes simple `(a + k₁) + k₂ = a + k₃` shapes via
  `simp only [BitVec.add_assoc]; rfl`. That works for 578 existing callsites
  in DivMod but does not handle address equalities that mix
  `signExtend13` / `signExtend21` evaluations (branch/jump/frame offsets),
  which are currently closed by hand-written `show … from by decide` chains.

  This file centralizes the atomic facts once:

    * `BitVec.add_assoc` (and the right-identity `x + 0 = x`) as `@[rv64_addr, grind =]`
    * every `signExtend13 N : Word = <const>` and `signExtend21 N : Word = <const>`
      pair used in the repo today

  and exposes a `rv64_addr` tactic that tries `grind` first (resilient to
  vocabulary growth) and falls back to `simp only [rv64_addr]; rfl` (smaller
  proof term, matches `bv_addr`'s shape). Callers that migrate from `bv_addr`
  get the signExtend13/21 reductions for free.

  Adding a new concrete offset is one line here — every downstream proof that
  uses `by rv64_addr` picks it up automatically.
-/

module

public import EvmAsm.Rv64.Instructions
public import EvmAsm.Rv64.AddrNormAttr
meta import EvmAsm.Rv64.Instructions
meta import EvmAsm.Rv64.AddrNormAttr
public import RiscvZkvm.Rv64.Logic.AddrNorm
meta import RiscvZkvm.Rv64.Logic.AddrNorm

@[expose] public section
-- END shim prelude

namespace EvmAsm.Rv64

export RiscvZkvm.Rv64 (AddrNorm.bv64_4mul_0 AddrNorm.bv64_4mul_1 AddrNorm.bv64_4mul_10 AddrNorm.bv64_4mul_11)
export RiscvZkvm.Rv64 (AddrNorm.bv64_4mul_12 AddrNorm.bv64_4mul_13 AddrNorm.bv64_4mul_14 AddrNorm.bv64_4mul_15)
export RiscvZkvm.Rv64 (AddrNorm.bv64_4mul_17 AddrNorm.bv64_4mul_20 AddrNorm.bv64_4mul_21 AddrNorm.bv64_4mul_3)
export RiscvZkvm.Rv64 (AddrNorm.bv64_4mul_5 AddrNorm.bv64_4mul_9 AddrNorm.bv64_toNat_63 AddrNorm.bv6_toNat_16)
export RiscvZkvm.Rv64 (AddrNorm.bv6_toNat_2 AddrNorm.bv6_toNat_3 AddrNorm.bv6_toNat_32 AddrNorm.bv6_toNat_4)
export RiscvZkvm.Rv64 (AddrNorm.bv6_toNat_48 AddrNorm.bv6_toNat_56 AddrNorm.bv6_toNat_6 AddrNorm.bv6_toNat_60)
export RiscvZkvm.Rv64 (AddrNorm.bv6_toNat_62 AddrNorm.bv6_toNat_63 AddrNorm.bv6_toNat_8 AddrNorm.se12_0)
export RiscvZkvm.Rv64 (AddrNorm.se12_1 AddrNorm.se12_12 AddrNorm.se12_16 AddrNorm.se12_2)
export RiscvZkvm.Rv64 (AddrNorm.se12_20 AddrNorm.se12_24 AddrNorm.se12_28 AddrNorm.se12_3)
export RiscvZkvm.Rv64 (AddrNorm.se12_32 AddrNorm.se12_36 AddrNorm.se12_3936 AddrNorm.se12_3944)
export RiscvZkvm.Rv64 (AddrNorm.se12_3952 AddrNorm.se12_3960 AddrNorm.se12_3968 AddrNorm.se12_3976)
export RiscvZkvm.Rv64 (AddrNorm.se12_3984 AddrNorm.se12_3992 AddrNorm.se12_4 AddrNorm.se12_40)
export RiscvZkvm.Rv64 (AddrNorm.se12_4000 AddrNorm.se12_4008 AddrNorm.se12_4016 AddrNorm.se12_4024)
export RiscvZkvm.Rv64 (AddrNorm.se12_4032 AddrNorm.se12_4040 AddrNorm.se12_4048 AddrNorm.se12_4056)
export RiscvZkvm.Rv64 (AddrNorm.se12_4064 AddrNorm.se12_4072 AddrNorm.se12_4080 AddrNorm.se12_4088)
export RiscvZkvm.Rv64 (AddrNorm.se12_4095 AddrNorm.se12_44 AddrNorm.se12_48 AddrNorm.se12_52)
export RiscvZkvm.Rv64 (AddrNorm.se12_56 AddrNorm.se12_60 AddrNorm.se12_7 AddrNorm.se12_8)
export RiscvZkvm.Rv64 (AddrNorm.se13_0 AddrNorm.se13_100 AddrNorm.se13_1020 AddrNorm.se13_12)
export RiscvZkvm.Rv64 (AddrNorm.se13_128 AddrNorm.se13_140 AddrNorm.se13_156 AddrNorm.se13_16)
export RiscvZkvm.Rv64 (AddrNorm.se13_168 AddrNorm.se13_172 AddrNorm.se13_176 AddrNorm.se13_188)
export RiscvZkvm.Rv64 (AddrNorm.se13_20 AddrNorm.se13_24 AddrNorm.se13_308 AddrNorm.se13_32)
export RiscvZkvm.Rv64 (AddrNorm.se13_320 AddrNorm.se13_332 AddrNorm.se13_36 AddrNorm.se13_4)
export RiscvZkvm.Rv64 (AddrNorm.se13_44 AddrNorm.se13_464 AddrNorm.se13_60 AddrNorm.se13_68)
export RiscvZkvm.Rv64 (AddrNorm.se13_7736 AddrNorm.se13_8 AddrNorm.se13_8044 AddrNorm.se13_92)
export RiscvZkvm.Rv64 (AddrNorm.se13_96 AddrNorm.se21_0 AddrNorm.se21_12 AddrNorm.se21_124)
export RiscvZkvm.Rv64 (AddrNorm.se21_132 AddrNorm.se21_16 AddrNorm.se21_200 AddrNorm.se21_212)
export RiscvZkvm.Rv64 (AddrNorm.se21_24 AddrNorm.se21_252 AddrNorm.se21_268 AddrNorm.se21_32)
export RiscvZkvm.Rv64 (AddrNorm.se21_36 AddrNorm.se21_40 AddrNorm.se21_48 AddrNorm.se21_560)
export RiscvZkvm.Rv64 (AddrNorm.se21_64 AddrNorm.se21_68 AddrNorm.se21_8 AddrNorm.se21_96)
export RiscvZkvm.Rv64 (AddrNorm.tacticRv64_addr AddrNorm.word_add_zero AddrNorm.word_toNat_0 AddrNorm.word_toNat_1)
export RiscvZkvm.Rv64 (AddrNorm.word_toNat_2 AddrNorm.word_toNat_255 AddrNorm.word_toNat_3 AddrNorm.word_toNat_32)
export RiscvZkvm.Rv64 (AddrNorm.word_toNat_4 AddrNorm.word_toNat_7 AddrNorm.word_zero_add AddrNorm.zero_add_se12_1_toNat)
export RiscvZkvm.Rv64 (AddrNorm.zero_add_se12_2_toNat)

-- Namespaces downstream files `open`; see render() for why these
-- cannot come from `export`.
namespace AddrNorm end AddrNorm

end EvmAsm.Rv64
