-- GENERATED by scripts/gen-rv64-shims.py -- do not edit by hand.
--
-- `AddrNormAttr` now lives in the riscv-zkvm dependency, prebuilt.
-- This shim re-exports it so evm-asm's existing references keep resolving;
-- `export` aliases the SAME constants, so no statement changes meaning.
--
-- Only the export block below is regenerated. The prelude between the
-- markers is preserved verbatim and is the source of truth -- aliases do not
-- propagate transitively, so those import edges are what let downstream files
-- still see the names they used to. Edit it here if the imports must change.
--
-- Regenerate with `scripts/gen-rv64-shims.py`; `--check` gates it in CI.
-- BEGIN shim prelude (preserved from the original module)
/-
  EvmAsm.Rv64.AddrNormAttr

  Declares the `rv64_addr` simp attribute used by `AddrNorm.lean`.

  Split out from `AddrNorm.lean` because Lean 4 does not allow an attribute
  to be used in the same file in which it is declared. Downstream code should
  import `AddrNorm.lean` (which imports this file) — not this file directly.
-/

module

public import Lean.Meta.Tactic.Simp.RegisterCommand
meta import Lean.Meta.Tactic.Simp.RegisterCommand
public meta import Lean.Meta.Tactic.Simp.Attr
public import RiscvZkvm.Rv64.Logic.AddrNormAttr
meta import RiscvZkvm.Rv64.Logic.AddrNormAttr

@[expose] public section
-- END shim prelude

