-- GENERATED by scripts/gen-rv64-shims.py -- do not edit by hand.
--
-- `Basic` now lives in the riscv-zkvm dependency, prebuilt.
-- This shim re-exports it so evm-asm's existing references keep resolving;
-- `export` aliases the SAME constants, so no statement changes meaning.
--
-- The original prelude is preserved deliberately -- aliases do not propagate
-- transitively, so those import edges are what let downstream files still see
-- the names they used to.  See original_prelude() for the full reasoning.
--
-- Regenerate with `scripts/gen-rv64-shims.py`; `--check` gates it in CI.
/-
  EvmAsm.Rv64.Basic

  A simplified RV64IM machine model for macro assembly verification.
  64-bit variant of EvmAsm.Basic (which models RV32IM).

  Pure word/address utilities (Word notation, alignment predicates,
  byte-extraction ops, address constants) live in `Rv64.Word`, imported
  below.
-/

module

public import EvmAsm.Rv64.Word
public import RiscvZkvm.Rv64.Basic

@[expose] public section

namespace EvmAsm.Rv64

export RiscvZkvm.Rv64 (Instr Instr.ADD Instr.ADD.elim Instr.ADD.inj)
export RiscvZkvm.Rv64 (Instr.ADD.injEq Instr.ADD.noConfusion Instr.ADD.sizeOf_spec Instr.ADDI)
export RiscvZkvm.Rv64 (Instr.ADDI.elim Instr.ADDI.inj Instr.ADDI.injEq Instr.ADDI.noConfusion)
export RiscvZkvm.Rv64 (Instr.ADDI.sizeOf_spec Instr.ADDIW Instr.ADDIW.elim Instr.ADDIW.inj)
export RiscvZkvm.Rv64 (Instr.ADDIW.injEq Instr.ADDIW.noConfusion Instr.ADDIW.sizeOf_spec Instr.AND)
export RiscvZkvm.Rv64 (Instr.AND.elim Instr.AND.inj Instr.AND.injEq Instr.AND.noConfusion)
export RiscvZkvm.Rv64 (Instr.AND.sizeOf_spec Instr.ANDI Instr.ANDI.elim Instr.ANDI.inj)
export RiscvZkvm.Rv64 (Instr.ANDI.injEq Instr.ANDI.noConfusion Instr.ANDI.sizeOf_spec Instr.AUIPC)
export RiscvZkvm.Rv64 (Instr.AUIPC.elim Instr.AUIPC.inj Instr.AUIPC.injEq Instr.AUIPC.noConfusion)
export RiscvZkvm.Rv64 (Instr.AUIPC.sizeOf_spec Instr.BEQ Instr.BEQ.elim Instr.BEQ.inj)
export RiscvZkvm.Rv64 (Instr.BEQ.injEq Instr.BEQ.noConfusion Instr.BEQ.sizeOf_spec Instr.BGE)
export RiscvZkvm.Rv64 (Instr.BGE.elim Instr.BGE.inj Instr.BGE.injEq Instr.BGE.noConfusion)
export RiscvZkvm.Rv64 (Instr.BGE.sizeOf_spec Instr.BGEU Instr.BGEU.elim Instr.BGEU.inj)
export RiscvZkvm.Rv64 (Instr.BGEU.injEq Instr.BGEU.noConfusion Instr.BGEU.sizeOf_spec Instr.BLT)
export RiscvZkvm.Rv64 (Instr.BLT.elim Instr.BLT.inj Instr.BLT.injEq Instr.BLT.noConfusion)
export RiscvZkvm.Rv64 (Instr.BLT.sizeOf_spec Instr.BLTU Instr.BLTU.elim Instr.BLTU.inj)
export RiscvZkvm.Rv64 (Instr.BLTU.injEq Instr.BLTU.noConfusion Instr.BLTU.sizeOf_spec Instr.BNE)
export RiscvZkvm.Rv64 (Instr.BNE.elim Instr.BNE.inj Instr.BNE.injEq Instr.BNE.noConfusion)
export RiscvZkvm.Rv64 (Instr.BNE.sizeOf_spec Instr.CSRS Instr.CSRS.elim Instr.CSRS.inj)
export RiscvZkvm.Rv64 (Instr.CSRS.injEq Instr.CSRS.noConfusion Instr.CSRS.sizeOf_spec Instr.DIV)
export RiscvZkvm.Rv64 (Instr.DIV.elim Instr.DIV.inj Instr.DIV.injEq Instr.DIV.noConfusion)
export RiscvZkvm.Rv64 (Instr.DIV.sizeOf_spec Instr.DIVU Instr.DIVU.elim Instr.DIVU.inj)
export RiscvZkvm.Rv64 (Instr.DIVU.injEq Instr.DIVU.noConfusion Instr.DIVU.sizeOf_spec Instr.EBREAK)
export RiscvZkvm.Rv64 (Instr.EBREAK.elim Instr.EBREAK.sizeOf_spec Instr.ECALL Instr.ECALL.elim)
export RiscvZkvm.Rv64 (Instr.ECALL.sizeOf_spec Instr.FENCE Instr.FENCE.elim Instr.FENCE.sizeOf_spec)
export RiscvZkvm.Rv64 (Instr.JAL Instr.JAL.elim Instr.JAL.inj Instr.JAL.injEq)
export RiscvZkvm.Rv64 (Instr.JAL.noConfusion Instr.JAL.sizeOf_spec Instr.JALR Instr.JALR.elim)
export RiscvZkvm.Rv64 (Instr.JALR.inj Instr.JALR.injEq Instr.JALR.noConfusion Instr.JALR.sizeOf_spec)
export RiscvZkvm.Rv64 (Instr.LB Instr.LB.elim Instr.LB.inj Instr.LB.injEq)
export RiscvZkvm.Rv64 (Instr.LB.noConfusion Instr.LB.sizeOf_spec Instr.LBU Instr.LBU.elim)
export RiscvZkvm.Rv64 (Instr.LBU.inj Instr.LBU.injEq Instr.LBU.noConfusion Instr.LBU.sizeOf_spec)
export RiscvZkvm.Rv64 (Instr.LD Instr.LD.elim Instr.LD.inj Instr.LD.injEq)
export RiscvZkvm.Rv64 (Instr.LD.noConfusion Instr.LD.sizeOf_spec Instr.LH Instr.LH.elim)
export RiscvZkvm.Rv64 (Instr.LH.inj Instr.LH.injEq Instr.LH.noConfusion Instr.LH.sizeOf_spec)
export RiscvZkvm.Rv64 (Instr.LHU Instr.LHU.elim Instr.LHU.inj Instr.LHU.injEq)
export RiscvZkvm.Rv64 (Instr.LHU.noConfusion Instr.LHU.sizeOf_spec Instr.LI Instr.LI.elim)
export RiscvZkvm.Rv64 (Instr.LI.inj Instr.LI.injEq Instr.LI.noConfusion Instr.LI.sizeOf_spec)
export RiscvZkvm.Rv64 (Instr.LUI Instr.LUI.elim Instr.LUI.inj Instr.LUI.injEq)
export RiscvZkvm.Rv64 (Instr.LUI.noConfusion Instr.LUI.sizeOf_spec Instr.LW Instr.LW.elim)
export RiscvZkvm.Rv64 (Instr.LW.inj Instr.LW.injEq Instr.LW.noConfusion Instr.LW.sizeOf_spec)
export RiscvZkvm.Rv64 (Instr.LWU Instr.LWU.elim Instr.LWU.inj Instr.LWU.injEq)
export RiscvZkvm.Rv64 (Instr.LWU.noConfusion Instr.LWU.sizeOf_spec Instr.MUL Instr.MUL.elim)
export RiscvZkvm.Rv64 (Instr.MUL.inj Instr.MUL.injEq Instr.MUL.noConfusion Instr.MUL.sizeOf_spec)
export RiscvZkvm.Rv64 (Instr.MULH Instr.MULH.elim Instr.MULH.inj Instr.MULH.injEq)
export RiscvZkvm.Rv64 (Instr.MULH.noConfusion Instr.MULH.sizeOf_spec Instr.MULHSU Instr.MULHSU.elim)
export RiscvZkvm.Rv64 (Instr.MULHSU.inj Instr.MULHSU.injEq Instr.MULHSU.noConfusion Instr.MULHSU.sizeOf_spec)
export RiscvZkvm.Rv64 (Instr.MULHU Instr.MULHU.elim Instr.MULHU.inj Instr.MULHU.injEq)
export RiscvZkvm.Rv64 (Instr.MULHU.noConfusion Instr.MULHU.sizeOf_spec Instr.MV Instr.MV.elim)
export RiscvZkvm.Rv64 (Instr.MV.inj Instr.MV.injEq Instr.MV.noConfusion Instr.MV.sizeOf_spec)
export RiscvZkvm.Rv64 (Instr.NOP Instr.NOP.elim Instr.NOP.sizeOf_spec Instr.OR)
export RiscvZkvm.Rv64 (Instr.OR.elim Instr.OR.inj Instr.OR.injEq Instr.OR.noConfusion)
export RiscvZkvm.Rv64 (Instr.OR.sizeOf_spec Instr.ORI Instr.ORI.elim Instr.ORI.inj)
export RiscvZkvm.Rv64 (Instr.ORI.injEq Instr.ORI.noConfusion Instr.ORI.sizeOf_spec Instr.REM)
export RiscvZkvm.Rv64 (Instr.REM.elim Instr.REM.inj Instr.REM.injEq Instr.REM.noConfusion)
export RiscvZkvm.Rv64 (Instr.REM.sizeOf_spec Instr.REMU Instr.REMU.elim Instr.REMU.inj)
export RiscvZkvm.Rv64 (Instr.REMU.injEq Instr.REMU.noConfusion Instr.REMU.sizeOf_spec Instr.SB)
export RiscvZkvm.Rv64 (Instr.SB.elim Instr.SB.inj Instr.SB.injEq Instr.SB.noConfusion)
export RiscvZkvm.Rv64 (Instr.SB.sizeOf_spec Instr.SD Instr.SD.elim Instr.SD.inj)
export RiscvZkvm.Rv64 (Instr.SD.injEq Instr.SD.noConfusion Instr.SD.sizeOf_spec Instr.SH)
export RiscvZkvm.Rv64 (Instr.SH.elim Instr.SH.inj Instr.SH.injEq Instr.SH.noConfusion)
export RiscvZkvm.Rv64 (Instr.SH.sizeOf_spec Instr.SLL Instr.SLL.elim Instr.SLL.inj)
export RiscvZkvm.Rv64 (Instr.SLL.injEq Instr.SLL.noConfusion Instr.SLL.sizeOf_spec Instr.SLLI)
export RiscvZkvm.Rv64 (Instr.SLLI.elim Instr.SLLI.inj Instr.SLLI.injEq Instr.SLLI.noConfusion)
export RiscvZkvm.Rv64 (Instr.SLLI.sizeOf_spec Instr.SLT Instr.SLT.elim Instr.SLT.inj)
export RiscvZkvm.Rv64 (Instr.SLT.injEq Instr.SLT.noConfusion Instr.SLT.sizeOf_spec Instr.SLTI)
export RiscvZkvm.Rv64 (Instr.SLTI.elim Instr.SLTI.inj Instr.SLTI.injEq Instr.SLTI.noConfusion)
export RiscvZkvm.Rv64 (Instr.SLTI.sizeOf_spec Instr.SLTIU Instr.SLTIU.elim Instr.SLTIU.inj)
export RiscvZkvm.Rv64 (Instr.SLTIU.injEq Instr.SLTIU.noConfusion Instr.SLTIU.sizeOf_spec Instr.SLTU)
export RiscvZkvm.Rv64 (Instr.SLTU.elim Instr.SLTU.inj Instr.SLTU.injEq Instr.SLTU.noConfusion)
export RiscvZkvm.Rv64 (Instr.SLTU.sizeOf_spec Instr.SRA Instr.SRA.elim Instr.SRA.inj)
export RiscvZkvm.Rv64 (Instr.SRA.injEq Instr.SRA.noConfusion Instr.SRA.sizeOf_spec Instr.SRAI)
export RiscvZkvm.Rv64 (Instr.SRAI.elim Instr.SRAI.inj Instr.SRAI.injEq Instr.SRAI.noConfusion)
export RiscvZkvm.Rv64 (Instr.SRAI.sizeOf_spec Instr.SRL Instr.SRL.elim Instr.SRL.inj)
export RiscvZkvm.Rv64 (Instr.SRL.injEq Instr.SRL.noConfusion Instr.SRL.sizeOf_spec Instr.SRLI)
export RiscvZkvm.Rv64 (Instr.SRLI.elim Instr.SRLI.inj Instr.SRLI.injEq Instr.SRLI.noConfusion)
export RiscvZkvm.Rv64 (Instr.SRLI.sizeOf_spec Instr.SUB Instr.SUB.elim Instr.SUB.inj)
export RiscvZkvm.Rv64 (Instr.SUB.injEq Instr.SUB.noConfusion Instr.SUB.sizeOf_spec Instr.SW)
export RiscvZkvm.Rv64 (Instr.SW.elim Instr.SW.inj Instr.SW.injEq Instr.SW.noConfusion)
export RiscvZkvm.Rv64 (Instr.SW.sizeOf_spec Instr.XOR Instr.XOR.elim Instr.XOR.inj)
export RiscvZkvm.Rv64 (Instr.XOR.injEq Instr.XOR.noConfusion Instr.XOR.sizeOf_spec Instr.XORI)
export RiscvZkvm.Rv64 (Instr.XORI.elim Instr.XORI.inj Instr.XORI.injEq Instr.XORI.noConfusion)
export RiscvZkvm.Rv64 (Instr.XORI.sizeOf_spec Instr.casesOn Instr.ctorElim Instr.ctorElimType)
export RiscvZkvm.Rv64 (Instr.ctorIdx Instr.noConfusion Instr.noConfusionType Instr.rec)
export RiscvZkvm.Rv64 (Instr.recOn MachineState MachineState.appendCommit MachineState.appendCommit.eq_1)
export RiscvZkvm.Rv64 (MachineState.appendPublicValues MachineState.appendPublicValues.eq_1 MachineState.casesOn MachineState.code)
export RiscvZkvm.Rv64 (MachineState.code_appendCommit MachineState.code_appendPublicValues MachineState.code_setByte MachineState.code_setHalfword)
export RiscvZkvm.Rv64 (MachineState.code_setMem MachineState.code_setPC MachineState.code_setReg MachineState.code_setWord32)
export RiscvZkvm.Rv64 (MachineState.code_writeBytesAsWords MachineState.code_writeOutput MachineState.code_writeWords MachineState.committed)
export RiscvZkvm.Rv64 (MachineState.committedIs MachineState.committed_appendCommit MachineState.committed_appendPublicValues MachineState.committed_setByte)
export RiscvZkvm.Rv64 (MachineState.committed_setHalfword MachineState.committed_setMem MachineState.committed_setPC MachineState.committed_setReg)
export RiscvZkvm.Rv64 (MachineState.committed_writeBytesAsWords MachineState.committed_writeOutput MachineState.committed_writeWords MachineState.ctorIdx)
export RiscvZkvm.Rv64 (MachineState.getByte MachineState.getHalfword MachineState.getMem MachineState.getMem.eq_1)
export RiscvZkvm.Rv64 (MachineState.getMem_appendCommit MachineState.getMem_appendPublicValues MachineState.getMem_setMem_eq MachineState.getMem_setMem_ne)
export RiscvZkvm.Rv64 (MachineState.getMem_setPC MachineState.getMem_setReg MachineState.getMem_writeOutput MachineState.getReg)
export RiscvZkvm.Rv64 (MachineState.getReg.eq_1 MachineState.getReg.eq_2 MachineState.getReg_appendCommit MachineState.getReg_appendPublicValues)
export RiscvZkvm.Rv64 (MachineState.getReg_setPC MachineState.getReg_setReg_eq MachineState.getReg_setReg_ne MachineState.getReg_writeBytesAsWords)
export RiscvZkvm.Rv64 (MachineState.getReg_writeOutput MachineState.getReg_writeWords MachineState.getWord32 MachineState.inputBufBase)
export RiscvZkvm.Rv64 (MachineState.inputBufBase_appendCommit MachineState.inputBufBase_appendPublicValues MachineState.inputBufBase_setByte MachineState.inputBufBase_setHalfword)
export RiscvZkvm.Rv64 (MachineState.inputBufBase_setMem MachineState.inputBufBase_setPC MachineState.inputBufBase_setReg MachineState.inputBufBase_writeBytesAsWords)
export RiscvZkvm.Rv64 (MachineState.inputBufBase_writeOutput MachineState.inputBufBase_writeWords MachineState.mem MachineState.mk)
export RiscvZkvm.Rv64 (MachineState.mk.inj MachineState.mk.injEq MachineState.mk.noConfusion MachineState.mk.sizeOf_spec)
export RiscvZkvm.Rv64 (MachineState.noConfusion MachineState.noConfusionType MachineState.pc MachineState.pc_appendCommit)
export RiscvZkvm.Rv64 (MachineState.pc_appendPublicValues MachineState.pc_setByte MachineState.pc_setHalfword MachineState.pc_setMem)
export RiscvZkvm.Rv64 (MachineState.pc_setReg MachineState.pc_setWord32 MachineState.pc_writeBytesAsWords MachineState.pc_writeOutput)
export RiscvZkvm.Rv64 (MachineState.pc_writeWords MachineState.privateInput MachineState.privateInputIs MachineState.privateInput_appendCommit)
export RiscvZkvm.Rv64 (MachineState.privateInput_appendPublicValues MachineState.privateInput_setByte MachineState.privateInput_setHalfword MachineState.privateInput_setMem)
export RiscvZkvm.Rv64 (MachineState.privateInput_setPC MachineState.privateInput_setReg MachineState.privateInput_writeBytesAsWords MachineState.privateInput_writeOutput)
export RiscvZkvm.Rv64 (MachineState.privateInput_writeWords MachineState.publicValues MachineState.publicValuesIs MachineState.publicValues_appendCommit)
export RiscvZkvm.Rv64 (MachineState.publicValues_appendPublicValues MachineState.publicValues_setByte MachineState.publicValues_setHalfword MachineState.publicValues_setMem)
export RiscvZkvm.Rv64 (MachineState.publicValues_setPC MachineState.publicValues_setReg MachineState.publicValues_writeBytesAsWords MachineState.publicValues_writeOutput)
export RiscvZkvm.Rv64 (MachineState.publicValues_writeWords MachineState.readBytes MachineState.readBytes_succ MachineState.readBytes_zero)
export RiscvZkvm.Rv64 (MachineState.readWords MachineState.readWords_succ MachineState.readWords_zero MachineState.rec)
export RiscvZkvm.Rv64 (MachineState.recOn MachineState.regs MachineState.setByte MachineState.setByte.eq_1)
export RiscvZkvm.Rv64 (MachineState.setHalfword MachineState.setHalfword.eq_1 MachineState.setMem MachineState.setMem.eq_1)
export RiscvZkvm.Rv64 (MachineState.setPC MachineState.setPC.eq_1 MachineState.setReg MachineState.setReg.eq_1)
export RiscvZkvm.Rv64 (MachineState.setReg.eq_2 MachineState.setWord32 MachineState.setWord32.eq_1 MachineState.writeBytesAsWords)
export RiscvZkvm.Rv64 (MachineState.writeBytesAsWords.eq_def MachineState.writeBytesAsWords_nil MachineState.writeOutput MachineState.writeOutput.eq_1)
export RiscvZkvm.Rv64 (MachineState.writeWords MachineState.writeWords.eq_1 MachineState.writeWords.eq_2 MachineState.writeWords.eq_def)
export RiscvZkvm.Rv64 (MachineState.writeWords_cons MachineState.writeWords_nil Reg Reg.casesOn)
export RiscvZkvm.Rv64 (Reg.ctorElim Reg.ctorElimType Reg.ctorIdx Reg.instToString)
export RiscvZkvm.Rv64 (Reg.noConfusion Reg.noConfusionType Reg.ofNat Reg.ofNat_ctorIdx)
export RiscvZkvm.Rv64 (Reg.rec Reg.recOn Reg.toCtorIdx Reg.toNat)
export RiscvZkvm.Rv64 (Reg.x0 Reg.x0.elim Reg.x0.sizeOf_spec Reg.x1)
export RiscvZkvm.Rv64 (Reg.x1.elim Reg.x1.sizeOf_spec Reg.x10 Reg.x10.elim)
export RiscvZkvm.Rv64 (Reg.x10.sizeOf_spec Reg.x11 Reg.x11.elim Reg.x11.sizeOf_spec)
export RiscvZkvm.Rv64 (Reg.x12 Reg.x12.elim Reg.x12.sizeOf_spec Reg.x13)
export RiscvZkvm.Rv64 (Reg.x13.elim Reg.x13.sizeOf_spec Reg.x14 Reg.x14.elim)
export RiscvZkvm.Rv64 (Reg.x14.sizeOf_spec Reg.x15 Reg.x15.elim Reg.x15.sizeOf_spec)
export RiscvZkvm.Rv64 (Reg.x16 Reg.x16.elim Reg.x16.sizeOf_spec Reg.x17)
export RiscvZkvm.Rv64 (Reg.x17.elim Reg.x17.sizeOf_spec Reg.x18 Reg.x18.elim)
export RiscvZkvm.Rv64 (Reg.x18.sizeOf_spec Reg.x19 Reg.x19.elim Reg.x19.sizeOf_spec)
export RiscvZkvm.Rv64 (Reg.x2 Reg.x2.elim Reg.x2.sizeOf_spec Reg.x20)
export RiscvZkvm.Rv64 (Reg.x20.elim Reg.x20.sizeOf_spec Reg.x21 Reg.x21.elim)
export RiscvZkvm.Rv64 (Reg.x21.sizeOf_spec Reg.x22 Reg.x22.elim Reg.x22.sizeOf_spec)
export RiscvZkvm.Rv64 (Reg.x23 Reg.x23.elim Reg.x23.sizeOf_spec Reg.x24)
export RiscvZkvm.Rv64 (Reg.x24.elim Reg.x24.sizeOf_spec Reg.x25 Reg.x25.elim)
export RiscvZkvm.Rv64 (Reg.x25.sizeOf_spec Reg.x26 Reg.x26.elim Reg.x26.sizeOf_spec)
export RiscvZkvm.Rv64 (Reg.x27 Reg.x27.elim Reg.x27.sizeOf_spec Reg.x28)
export RiscvZkvm.Rv64 (Reg.x28.elim Reg.x28.sizeOf_spec Reg.x29 Reg.x29.elim)
export RiscvZkvm.Rv64 (Reg.x29.sizeOf_spec Reg.x3 Reg.x3.elim Reg.x3.sizeOf_spec)
export RiscvZkvm.Rv64 (Reg.x30 Reg.x30.elim Reg.x30.sizeOf_spec Reg.x31)
export RiscvZkvm.Rv64 (Reg.x31.elim Reg.x31.sizeOf_spec Reg.x4 Reg.x4.elim)
export RiscvZkvm.Rv64 (Reg.x4.sizeOf_spec Reg.x5 Reg.x5.elim Reg.x5.sizeOf_spec)
export RiscvZkvm.Rv64 (Reg.x6 Reg.x6.elim Reg.x6.sizeOf_spec Reg.x7)
export RiscvZkvm.Rv64 (Reg.x7.elim Reg.x7.sizeOf_spec Reg.x8 Reg.x8.elim)
export RiscvZkvm.Rv64 (Reg.x8.sizeOf_spec Reg.x9 Reg.x9.elim Reg.x9.sizeOf_spec)
export RiscvZkvm.Rv64 (defaultInputBufBase instBEqReg instBEqReg.beq instDecidableEqInstr)
export RiscvZkvm.Rv64 (instDecidableEqInstr.decEq instDecidableEqReg instHashableReg instHashableReg.hash)
export RiscvZkvm.Rv64 (instLawfulBEqReg instReprInstr instReprInstr.repr instReprReg)
export RiscvZkvm.Rv64 (instReprReg.repr)

-- Namespaces downstream files `open`; see render() for why these
-- cannot come from `export`.
namespace Instr end Instr
namespace Instr.ADD end Instr.ADD
namespace Instr.ADDI end Instr.ADDI
namespace Instr.ADDIW end Instr.ADDIW
namespace Instr.AND end Instr.AND
namespace Instr.ANDI end Instr.ANDI
namespace Instr.AUIPC end Instr.AUIPC
namespace Instr.BEQ end Instr.BEQ
namespace Instr.BGE end Instr.BGE
namespace Instr.BGEU end Instr.BGEU
namespace Instr.BLT end Instr.BLT
namespace Instr.BLTU end Instr.BLTU
namespace Instr.BNE end Instr.BNE
namespace Instr.CSRS end Instr.CSRS
namespace Instr.DIV end Instr.DIV
namespace Instr.DIVU end Instr.DIVU
namespace Instr.EBREAK end Instr.EBREAK
namespace Instr.ECALL end Instr.ECALL
namespace Instr.FENCE end Instr.FENCE
namespace Instr.JAL end Instr.JAL
namespace Instr.JALR end Instr.JALR
namespace Instr.LB end Instr.LB
namespace Instr.LBU end Instr.LBU
namespace Instr.LD end Instr.LD
namespace Instr.LH end Instr.LH
namespace Instr.LHU end Instr.LHU
namespace Instr.LI end Instr.LI
namespace Instr.LUI end Instr.LUI
namespace Instr.LW end Instr.LW
namespace Instr.LWU end Instr.LWU
namespace Instr.MUL end Instr.MUL
namespace Instr.MULH end Instr.MULH
namespace Instr.MULHSU end Instr.MULHSU
namespace Instr.MULHU end Instr.MULHU
namespace Instr.MV end Instr.MV
namespace Instr.NOP end Instr.NOP
namespace Instr.OR end Instr.OR
namespace Instr.ORI end Instr.ORI
namespace Instr.REM end Instr.REM
namespace Instr.REMU end Instr.REMU
namespace Instr.SB end Instr.SB
namespace Instr.SD end Instr.SD
namespace Instr.SH end Instr.SH
namespace Instr.SLL end Instr.SLL
namespace Instr.SLLI end Instr.SLLI
namespace Instr.SLT end Instr.SLT
namespace Instr.SLTI end Instr.SLTI
namespace Instr.SLTIU end Instr.SLTIU
namespace Instr.SLTU end Instr.SLTU
namespace Instr.SRA end Instr.SRA
namespace Instr.SRAI end Instr.SRAI
namespace Instr.SRL end Instr.SRL
namespace Instr.SRLI end Instr.SRLI
namespace Instr.SUB end Instr.SUB
namespace Instr.SW end Instr.SW
namespace Instr.XOR end Instr.XOR
namespace Instr.XORI end Instr.XORI
namespace MachineState end MachineState
namespace MachineState.appendCommit end MachineState.appendCommit
namespace MachineState.appendPublicValues end MachineState.appendPublicValues
namespace MachineState.getMem end MachineState.getMem
namespace MachineState.getReg end MachineState.getReg
namespace MachineState.mk end MachineState.mk
namespace MachineState.setByte end MachineState.setByte
namespace MachineState.setHalfword end MachineState.setHalfword
namespace MachineState.setMem end MachineState.setMem
namespace MachineState.setPC end MachineState.setPC
namespace MachineState.setReg end MachineState.setReg
namespace MachineState.setWord32 end MachineState.setWord32
namespace MachineState.writeBytesAsWords end MachineState.writeBytesAsWords
namespace MachineState.writeOutput end MachineState.writeOutput
namespace MachineState.writeWords end MachineState.writeWords
namespace Reg end Reg
namespace Reg.x0 end Reg.x0
namespace Reg.x1 end Reg.x1
namespace Reg.x10 end Reg.x10
namespace Reg.x11 end Reg.x11
namespace Reg.x12 end Reg.x12
namespace Reg.x13 end Reg.x13
namespace Reg.x14 end Reg.x14
namespace Reg.x15 end Reg.x15
namespace Reg.x16 end Reg.x16
namespace Reg.x17 end Reg.x17
namespace Reg.x18 end Reg.x18
namespace Reg.x19 end Reg.x19
namespace Reg.x2 end Reg.x2
namespace Reg.x20 end Reg.x20
namespace Reg.x21 end Reg.x21
namespace Reg.x22 end Reg.x22
namespace Reg.x23 end Reg.x23
namespace Reg.x24 end Reg.x24
namespace Reg.x25 end Reg.x25
namespace Reg.x26 end Reg.x26
namespace Reg.x27 end Reg.x27
namespace Reg.x28 end Reg.x28
namespace Reg.x29 end Reg.x29
namespace Reg.x3 end Reg.x3
namespace Reg.x30 end Reg.x30
namespace Reg.x31 end Reg.x31
namespace Reg.x4 end Reg.x4
namespace Reg.x5 end Reg.x5
namespace Reg.x6 end Reg.x6
namespace Reg.x7 end Reg.x7
namespace Reg.x8 end Reg.x8
namespace Reg.x9 end Reg.x9
namespace instBEqReg end instBEqReg
namespace instDecidableEqInstr end instDecidableEqInstr
namespace instHashableReg end instHashableReg
namespace instReprInstr end instReprInstr
namespace instReprReg end instReprReg

end EvmAsm.Rv64
