-- GENERATED by scripts/gen-rv64-shims.py -- do not edit by hand.
--
-- `BitAux` now lives in the riscv-zkvm dependency, prebuilt.
-- This shim re-exports it so evm-asm's existing references keep resolving;
-- `export` aliases the SAME constants, so no statement changes meaning.
--
-- Only the export block below is regenerated. The prelude between the
-- markers is preserved verbatim and is the source of truth -- aliases do not
-- propagate transitively, so those import edges are what let downstream files
-- still see the names they used to. Edit it here if the imports must change.
--
-- Regenerate with `scripts/gen-rv64-shims.py`; `--check` gates it in CI.
-- BEGIN shim prelude (preserved from the original module)
/-
  EvmAsm.Rv64.BitAux

  Shared `Word` (= `BitVec 64`) bit-level helper lemmas distilled from the
  `bv_decide` elimination. Before this file, the small lemmas below were copied
  verbatim as `private` declarations into `Evm64/SDiv/Compose/Words.lean` and
  `Evm64/SMod/Compose/Words.lean`; they now live here once.

  Also exposes the 2-byte-alignment lemmas used to discharge the JALR low-bit
  masks (`… &&& ~~~1`, `… &&& 1 = 0`) that recur across the EXP / SDIV / SMOD /
  ADDMOD composition proofs. The forward `@[grind →]` tags let `grind` derive
  alignment from a `… &&& 1 = 0` hypothesis automatically.

  All proofs are kernel-checkable (no `bv_decide` / `native_decide`).
-/

module

public import EvmAsm.Rv64.Basic
public import RiscvZkvm.Rv64.Logic.BitAux

@[expose] public section
-- END shim prelude

namespace EvmAsm.Rv64

export RiscvZkvm.Rv64 (BitAux.bv6_63_toNat BitAux.getLsbD_zero_of_and_one BitAux.ult_zero_false BitAux.ushr63_bool)
export RiscvZkvm.Rv64 (BitAux.word_add_even_and_one BitAux.word_add_even_andn_one BitAux.word_add_zero BitAux.word_andn_one_of_even)
export RiscvZkvm.Rv64 (BitAux.word_if_false_eq_zero BitAux.word_if_false_zero BitAux.word_xor_allOnes BitAux.word_xor_zero)
export RiscvZkvm.Rv64 (BitAux.word_zero_sub_one)

-- Namespaces downstream files `open`; see render() for why these
-- cannot come from `export`.
namespace BitAux end BitAux

end EvmAsm.Rv64
