-- GENERATED by scripts/gen-rv64-shims.py -- do not edit by hand.
--
-- `BranchRelaxation` now lives in the riscv-zkvm dependency, prebuilt.
-- This shim re-exports it so evm-asm's existing references keep resolving;
-- `export` aliases the SAME constants, so no statement changes meaning.
--
-- The original prelude is preserved deliberately -- aliases do not propagate
-- transitively, so those import edges are what let downstream files still see
-- the names they used to.  See original_prelude() for the full reasoning.
--
-- Regenerate with `scripts/gen-rv64-shims.py`; `--check` gates it in CI.
/-
  EvmAsm.Rv64.BranchRelaxation

  Semantics of the **assembler's branch relaxation**, for the handler lane
  (GH #12204 decision 1).

  ## Why this exists

  A conditional branch to a far target does not survive assembly as one
  instruction. B-type reach is ±4 KiB, and every dispatcher handler branches to
  the dispatcher-owned `.exit_outofgas` roughly 65 KB away, so GNU-as **relaxes**
  each site into a two-instruction pair with the *inverted* condition skipping
  over an unconditional jump:

  ```
    beq  rs1, rs2, .exit_outofgas        -- source
  ⇒ bne  rs1, rs2, .+8                   -- relaxed: skip the jump when NOT equal
    j    .exit_outofgas
  ```

  The linked image therefore contains the **pair**, so any `Program` faithful to
  the image contains the pair too — which is what makes the instruction count a
  function of the link layout rather than the source text (the #12128
  measurement, and the reason `AsmSym.br` exists in `Codegen/Emit.lean`).

  ## What the lemmas below buy

  Without them, every handler triple that crosses one of these ~130 sites has to
  case-split on a two-instruction dance and reason about an intermediate PC that
  corresponds to nothing in the source. These lemmas collapse the pair back to
  the single conditional branch the author wrote:

  * **taken** ⇒ two steps land at the far target;
  * **not taken** ⇒ one step lands at `pc + 8`.

  ⚠️ Note the fall-through is `pc + 8`, **not** `pc + 4`: the pair occupies eight
  bytes, so "the instruction after the branch" is two words along. That offset is
  the whole reason a hand-written triple over a relaxed site is easy to get wrong,
  and it is why these are stated as lemmas rather than left to `simp`.

  ## Coverage

  Complete for the conditions that actually occur at far-branch sites in
  `EvmAsm/Codegen/`, measured by grepping branches targeting `.exit_outofgas`:
  `bltu` (65 sites), `bnez` (55), `bgeu` (5), `beq` (5). Those close under
  inversion into two pairs — {`BEQ`, `BNE`} and {`BLTU`, `BGEU`} — and all four
  relaxations are proved here. `bnez rs` is `BNE rs x0`, so it is the `BNE` case
  with `rs2 := .x0` and needs nothing extra.

  `BLT`/`BGE` do not occur at far-branch sites today; if one appears, add its
  pair here rather than inlining the reasoning at the use site.

  ## Trust

  These lemmas are about the **Lean `step` semantics of the relaxed pair**. That
  GNU-as produces exactly this pair for a far branch is an assembler fact, not a
  Lean theorem — it is checked by the byte-identity gate (`cmp` against the
  linked image), not here. Keep the two claims distinct when citing this file.
-/

module

public import EvmAsm.Rv64.Execution
public import RiscvZkvm.Rv64.Logic.BranchRelaxation

@[expose] public section

namespace EvmAsm.Rv64

export RiscvZkvm.Rv64 (BranchRelaxation.beq_relaxed_not_taken BranchRelaxation.beq_relaxed_taken BranchRelaxation.bgeu_relaxed_not_taken BranchRelaxation.bgeu_relaxed_taken)
export RiscvZkvm.Rv64 (BranchRelaxation.bltu_relaxed_not_taken BranchRelaxation.bltu_relaxed_taken BranchRelaxation.bne_relaxed_not_taken BranchRelaxation.bne_relaxed_taken)
export RiscvZkvm.Rv64 (BranchRelaxation.step_j BranchRelaxation.witnessCode BranchRelaxation.witnessCode.eq_1 BranchRelaxation.witnessCode_br)
export RiscvZkvm.Rv64 (BranchRelaxation.witnessCode_j signExtend13.eq_1)

-- Namespaces downstream files `open`; see render() for why these
-- cannot come from `export`.
namespace BranchRelaxation end BranchRelaxation
namespace BranchRelaxation.witnessCode end BranchRelaxation.witnessCode
namespace signExtend13 end signExtend13

end EvmAsm.Rv64
