-- GENERATED by scripts/gen-rv64-shims.py -- do not edit by hand.
--
-- `ByteAlg` now lives in the riscv-zkvm dependency, prebuilt.
-- This shim re-exports it so evm-asm's existing references keep resolving;
-- `export` aliases the SAME constants, so no statement changes meaning.
--
-- The original prelude is preserved deliberately -- aliases do not propagate
-- transitively, so those import edges are what let downstream files still see
-- the names they used to.  See original_prelude() for the full reasoning.
--
-- Regenerate with `scripts/gen-rv64-shims.py`; `--check` gates it in CI.
/-
  EvmAsm.Rv64.ByteAlg

  `byte_alg` grindset for `extractByte` / `replaceByte` algebra on 64-bit
  words (GRIND.md Phase 4).

  Seeds the set with the single algebra identity that currently exists in
  `Rv64/ByteOps.lean`:

    extractByte_replaceByte_same
      : extractByte (replaceByte w pos.val b) pos.val = b

  Future siblings (`extractByte_replaceByte_diff` for `pos₁ ≠ pos₂`,
  `replaceByte_replaceByte_same` idempotency, byte-index arithmetic,
  `extractByte` of concrete word literals) land as one-line
  `@[byte_alg, grind =]` facts in this file as they are proved.

  The `byte_alg` tactic macro wraps `first | grind | simp only [byte_alg]`,
  matching the `divmod_addr` / `rv64_addr` / `reg_ops` pattern.
-/

module

public import EvmAsm.Rv64.ByteOps
public import EvmAsm.Rv64.ByteAlgAttr
meta import EvmAsm.Rv64.ByteOps
meta import EvmAsm.Rv64.ByteAlgAttr
public import RiscvZkvm.Rv64.Logic.ByteAlg
meta import RiscvZkvm.Rv64.Logic.ByteAlg

@[expose] public section

namespace EvmAsm.Rv64

export RiscvZkvm.Rv64 (tacticByte_alg)

end EvmAsm.Rv64
