-- GENERATED by scripts/gen-rv64-shims.py -- do not edit by hand.
--
-- `ByteAlgAttr` now lives in the riscv-zkvm dependency, prebuilt.
-- This shim re-exports it so evm-asm's existing references keep resolving;
-- `export` aliases the SAME constants, so no statement changes meaning.
--
-- The original prelude is preserved deliberately -- aliases do not propagate
-- transitively, so those import edges are what let downstream files still see
-- the names they used to.  See original_prelude() for the full reasoning.
--
-- Regenerate with `scripts/gen-rv64-shims.py`; `--check` gates it in CI.
/-
  EvmAsm.Rv64.ByteAlgAttr

  Declares the `byte_alg` simp attribute used by `ByteAlg.lean`.

  Split out from `ByteAlg.lean` because Lean 4 does not allow an attribute
  to be used in the same file in which it is declared. Downstream code should
  import `ByteAlg.lean` (which imports this file) — not this file directly.
-/

module

public import Lean.Meta.Tactic.Simp.RegisterCommand
meta import Lean.Meta.Tactic.Simp.RegisterCommand
public meta import Lean.Meta.Tactic.Simp.Attr
public import RiscvZkvm.Rv64.Logic.ByteAlgAttr
meta import RiscvZkvm.Rv64.Logic.ByteAlgAttr

@[expose] public section

