-- GENERATED by scripts/gen-rv64-shims.py -- do not edit by hand.
--
-- `ByteOps` now lives in the riscv-zkvm dependency, prebuilt.
-- This shim re-exports it so evm-asm's existing references keep resolving;
-- `export` aliases the SAME constants, so no statement changes meaning.
--
-- Only the export block below is regenerated. The prelude between the
-- markers is preserved verbatim and is the source of truth -- aliases do not
-- propagate transitively, so those import edges are what let downstream files
-- still see the names they used to. Edit it here if the imports must change.
--
-- Regenerate with `scripts/gen-rv64-shims.py`; `--check` gates it in CI.
-- BEGIN shim prelude (preserved from the original module)
/-
  EvmAsm.Rv64.ByteOps

  Byte-level infrastructure: extractByte/replaceByte algebra and
  generic CPS specs for LBU (load byte unsigned) and SB (store byte).
-/
-- `CPSSpec` transitively imports `Basic`, `SepLogic`, and `Execution`.
module

public import EvmAsm.Rv64.CPSSpec
public import Mathlib.Tactic.IntervalCases
public import Mathlib.Tactic.FinCases
public import Mathlib.Data.Fintype.Basic
meta import EvmAsm.Rv64.CPSSpec
meta import Mathlib.Tactic.IntervalCases
meta import Mathlib.Tactic.FinCases
meta import Mathlib.Data.Fintype.Basic
public import RiscvZkvm.Rv64.Logic.ByteOps
meta import RiscvZkvm.Rv64.Logic.ByteOps

@[expose] public section
-- END shim prelude

namespace EvmAsm.Rv64

export RiscvZkvm.Rv64 (alignToDword_add_byteOffset alignToDword_byteOffset_zero alignToDword_idempotent byteOffset_lt_8)
export RiscvZkvm.Rv64 (extractByte.eq_1 extractByte_packBytes extractByte_packDword extractByte_replaceByte_same)
export RiscvZkvm.Rv64 (generic_lb_spec_within generic_lbu_spec_within generic_sb_spec_within getByteAt)
export RiscvZkvm.Rv64 (getByteAt.eq_1 getByte_eq packBytes packBytes.eq_1)
export RiscvZkvm.Rv64 (packDword packDword.eq_1 packDword_getLsbD replaceByte.eq_1)
export RiscvZkvm.Rv64 (setByte_eq)

-- Namespaces downstream files `open`; see render() for why these
-- cannot come from `export`.
namespace extractByte end extractByte
namespace getByteAt end getByteAt
namespace packBytes end packBytes
namespace packDword end packDword
namespace replaceByte end replaceByte

end EvmAsm.Rv64
