-- GENERATED by scripts/gen-rv64-shims.py -- do not edit by hand.
--
-- `CodeReqExtents` now lives in the riscv-zkvm dependency, prebuilt.
-- This shim re-exports it so evm-asm's existing references keep resolving;
-- `export` aliases the SAME constants, so no statement changes meaning.
--
-- The original prelude is preserved deliberately -- aliases do not propagate
-- transitively, so those import edges are what let downstream files still see
-- the names they used to.  See original_prelude() for the full reasoning.
--
-- Regenerate with `scripts/gen-rv64-shims.py`; `--check` gates it in CI.
/-
  EvmAsm.Rv64.CodeReqExtents

  Generic composition of an image-level `CodeReq` from a list of
  `(base, Program)` entries with ascending, non-overlapping extents
  (bead evm-asm-4ch8f.63).

  The guest image is `CodeReq.unionAll` over hundreds of per-function
  `CodeReq.ofProg` blocks.  A per-function triple proved against its own
  block lifts to the whole image via `cpsTripleWithin_extend_code` /
  `cpsHaltTripleWithin_extend_code`, whose monotonicity witness
  (`∀ a i, cr a = some i → cr' a = some i`) is what
  `ofProg_sub_unionAll_of_extentsOk` provides — with the entire
  384-block disjointness discharged by ONE decidable extent check
  (`extentsOkFrom`), never a per-block case split (the standing
  compose-don't-enumerate rule).
-/

import EvmAsm.Rv64.Program
import EvmAsm.Rv64.SepLogic
import EvmAsm.Rv64.MemSat
import RiscvZkvm.Rv64.Logic.CodeReqExtents

namespace EvmAsm.Rv64

export RiscvZkvm.Rv64 (CodeReq.extentsOkFrom CodeReq.extentsOkFrom.eq_1 CodeReq.extentsOkFrom.eq_2 CodeReq.extentsOkFrom.eq_def)
export RiscvZkvm.Rv64 (CodeReq.extentsOkFrom_le CodeReq.extentsOkFrom_mem CodeReq.ofEntries CodeReq.ofEntries.eq_1)
export RiscvZkvm.Rv64 (CodeReq.ofProg_sub_ofEntries_of_extentsOk)

-- Namespaces downstream files `open`; see render() for why these
-- cannot come from `export`.
namespace CodeReq end CodeReq
namespace CodeReq.extentsOkFrom end CodeReq.extentsOkFrom
namespace CodeReq.ofEntries end CodeReq.ofEntries

end EvmAsm.Rv64
