-- GENERATED by scripts/gen-rv64-shims.py -- do not edit by hand.
--
-- `ControlFlow` now lives in the riscv-zkvm dependency, prebuilt.
-- This shim re-exports it so evm-asm's existing references keep resolving;
-- `export` aliases the SAME constants, so no statement changes meaning.
--
-- Only the export block below is regenerated. The prelude between the
-- markers is preserved verbatim and is the source of truth -- aliases do not
-- propagate transitively, so those import edges are what let downstream files
-- still see the names they used to. Edit it here if the imports must change.
--
-- Regenerate with `scripts/gen-rv64-shims.py`; `--check` gates it in CI.
-- BEGIN shim prelude (preserved from the original module)
/-
  EvmAsm.Rv64.ControlFlow

  Control flow macros using branch and jump instructions, with CPS-style
  specifications.  (64-bit RISC-V port)

  This module provides:
  - if_eq: a conditional macro (if rs1 = rs2 then ... else ...)
  - CPS specifications for the macro
  - Concrete examples verified by decide
-/

-- `GenericSpecs` transitively imports `Basic`, `Instructions`, `Program`
-- (via `Execution`), `SepLogic`, `Execution`, and `CPSSpec`.
module

public import EvmAsm.Rv64.Program
public import EvmAsm.Rv64.GenericSpecs
public import EvmAsm.Rv64.Tactics.SpecDb
public import RiscvZkvm.Rv64.Logic.ControlFlow

@[expose] public section
-- END shim prelude

namespace EvmAsm.Rv64

export RiscvZkvm.Rv64 (countdown_loop execInstrBr_jal_x0 execInstrBr_jalr_x0 if_eq)
export RiscvZkvm.Rv64 (if_eq.eq_1 if_eq_arith if_eq_branch_step_n_within if_eq_branch_step_within)
export RiscvZkvm.Rv64 (if_eq_example if_eq_length jal_x0_spec_gen_within jalr_x0_spec_gen_within)
export RiscvZkvm.Rv64 (loadProgram_at_base loadProgram_at_index mkTestState runCountdown)
export RiscvZkvm.Rv64 (runIfEqArith runIfEqExample signExtend13_ofNat_small signExtend21_ofNat_small)

-- Namespaces downstream files `open`; see render() for why these
-- cannot come from `export`.
namespace if_eq end if_eq

end EvmAsm.Rv64
