-- GENERATED by scripts/gen-rv64-shims.py -- do not edit by hand.
--
-- `CPSCall` now lives in the riscv-zkvm dependency, prebuilt.
-- This shim re-exports it so evm-asm's existing references keep resolving;
-- `export` aliases the SAME constants, so no statement changes meaning.
--
-- The original prelude is preserved deliberately -- aliases do not propagate
-- transitively, so those import edges are what let downstream files still see
-- the names they used to.  See original_prelude() for the full reasoning.
--
-- Regenerate with `scripts/gen-rv64-shims.py`; `--check` gates it in CI.
/-
  EvmAsm.Rv64.CPSCall

  Compatibility import for direct-call composition.  New proof scripts should
  prefer `EvmAsm.Rv64.WP.Call`, but this root-level theorem keeps older
  #9522-style CPS scripts easy to adapt.
-/

import EvmAsm.Rv64.WP.Call
import RiscvZkvm.Rv64.Logic.CPSCall

namespace EvmAsm.Rv64

export RiscvZkvm.Rv64 (cpsCallWithin)

end EvmAsm.Rv64
