-- GENERATED by scripts/gen-rv64-shims.py -- do not edit by hand.
--
-- `Execution` now lives in the riscv-zkvm dependency, prebuilt.
-- This shim re-exports it so evm-asm's existing references keep resolving;
-- `export` aliases the SAME constants, so no statement changes meaning.
--
-- The original prelude is preserved deliberately -- aliases do not propagate
-- transitively, so those import edges are what let downstream files still see
-- the names they used to.  See original_prelude() for the full reasoning.
--
-- Regenerate with `scripts/gen-rv64-shims.py`; `--check` gates it in CI.
/-
  EvmAsm.Rv64.Execution

  Branch-aware instruction execution, code memory, and step-based execution.
  64-bit variant of EvmAsm.Execution (which models RV32IM).

  This module provides an alternative execution model that handles branch and
  jump instructions with proper PC semantics (as opposed to the straight-line
  execInstr which always advances PC by 4).

  Key components:
  - execInstrBr: per-instruction PC control (branches change PC by offset)
  - CodeMem: maps addresses to instructions
  - loadProgram: loads a program into code memory at a base address
  - step / stepN: single-step and multi-step execution over code memory
-/

-- `Instructions` transitively imports `Basic`. `Program` is not used in this
-- module — its consumers (RLP/opcode programs, ControlFlow) import `Program`
-- directly.
module

public import EvmAsm.Rv64.Instructions
public import RiscvZkvm.Rv64.Execution

@[expose] public section

namespace EvmAsm.Rv64

export RiscvZkvm.Rv64 (CodeMem Instr.isBranch.eq_1 Instr.isBranch.eq_2 Instr.isBranch.eq_3)
export RiscvZkvm.Rv64 (Instr.isBranch.eq_4 Instr.isBranch.eq_5 Instr.isBranch.eq_6 Instr.isBranch.eq_7)
export RiscvZkvm.Rv64 (Instr.isBranch.eq_8 Instr.isBranch.eq_9 Instr.isMemAccess.eq_1 Instr.isMemAccess.eq_10)
export RiscvZkvm.Rv64 (Instr.isMemAccess.eq_11 Instr.isMemAccess.eq_12 Instr.isMemAccess.eq_13 Instr.isMemAccess.eq_2)
export RiscvZkvm.Rv64 (Instr.isMemAccess.eq_3 Instr.isMemAccess.eq_4 Instr.isMemAccess.eq_5 Instr.isMemAccess.eq_6)
export RiscvZkvm.Rv64 (Instr.isMemAccess.eq_7 Instr.isMemAccess.eq_8 Instr.isMemAccess.eq_9 MEM_END.eq_1)
export RiscvZkvm.Rv64 (MEM_START.eq_1 ProgramAt ProgramAt.fetch ProgramAt.get)
export RiscvZkvm.Rv64 (ProgramAt.prefix ProgramAt.suffix StepResult StepResult.casesOn)
export RiscvZkvm.Rv64 (StepResult.ctorElim StepResult.ctorElimType StepResult.ctorIdx StepResult.noConfusion)
export RiscvZkvm.Rv64 (StepResult.noConfusionType StepResult.ok StepResult.ok.elim StepResult.ok.inj)
export RiscvZkvm.Rv64 (StepResult.ok.injEq StepResult.ok.noConfusion StepResult.ok.sizeOf_spec StepResult.rec)
export RiscvZkvm.Rv64 (StepResult.recOn StepResult.toOption StepResult.toOption.eq_1 StepResult.toOption.eq_2)
export RiscvZkvm.Rv64 (StepResult.trap StepResult.trap.elim StepResult.trap.inj StepResult.trap.injEq)
export RiscvZkvm.Rv64 (StepResult.trap.noConfusion StepResult.trap.sizeOf_spec TrapKind TrapKind.casesOn)
export RiscvZkvm.Rv64 (TrapKind.ctorElim TrapKind.ctorElimType TrapKind.ctorIdx TrapKind.misalignedAccess)
export RiscvZkvm.Rv64 (TrapKind.misalignedAccess.elim TrapKind.misalignedAccess.sizeOf_spec TrapKind.noConfusion TrapKind.noConfusionType)
export RiscvZkvm.Rv64 (TrapKind.ofNat TrapKind.ofNat_ctorIdx TrapKind.other TrapKind.other.elim)
export RiscvZkvm.Rv64 (TrapKind.other.sizeOf_spec TrapKind.rec TrapKind.recOn TrapKind.toCtorIdx)
export RiscvZkvm.Rv64 (code_execInstrBr code_step code_stepN committed_execInstrBr)
export RiscvZkvm.Rv64 (execInstr.eq_1 execInstr.eq_10 execInstr.eq_11 execInstr.eq_12)
export RiscvZkvm.Rv64 (execInstr.eq_13 execInstr.eq_14 execInstr.eq_15 execInstr.eq_16)
export RiscvZkvm.Rv64 (execInstr.eq_17 execInstr.eq_18 execInstr.eq_19 execInstr.eq_2)
export RiscvZkvm.Rv64 (execInstr.eq_20 execInstr.eq_21 execInstr.eq_22 execInstr.eq_23)
export RiscvZkvm.Rv64 (execInstr.eq_24 execInstr.eq_25 execInstr.eq_26 execInstr.eq_27)
export RiscvZkvm.Rv64 (execInstr.eq_28 execInstr.eq_29 execInstr.eq_3 execInstr.eq_30)
export RiscvZkvm.Rv64 (execInstr.eq_31 execInstr.eq_32 execInstr.eq_33 execInstr.eq_34)
export RiscvZkvm.Rv64 (execInstr.eq_35 execInstr.eq_36 execInstr.eq_37 execInstr.eq_38)
export RiscvZkvm.Rv64 (execInstr.eq_39 execInstr.eq_4 execInstr.eq_40 execInstr.eq_41)
export RiscvZkvm.Rv64 (execInstr.eq_42 execInstr.eq_43 execInstr.eq_44 execInstr.eq_45)
export RiscvZkvm.Rv64 (execInstr.eq_46 execInstr.eq_47 execInstr.eq_48 execInstr.eq_49)
export RiscvZkvm.Rv64 (execInstr.eq_5 execInstr.eq_50 execInstr.eq_51 execInstr.eq_52)
export RiscvZkvm.Rv64 (execInstr.eq_53 execInstr.eq_54 execInstr.eq_55 execInstr.eq_56)
export RiscvZkvm.Rv64 (execInstr.eq_6 execInstr.eq_7 execInstr.eq_8 execInstr.eq_9)
export RiscvZkvm.Rv64 (execInstrBr execInstrBr.eq_1 execInstrBr.eq_10 execInstrBr.eq_11)
export RiscvZkvm.Rv64 (execInstrBr.eq_12 execInstrBr.eq_13 execInstrBr.eq_14 execInstrBr.eq_15)
export RiscvZkvm.Rv64 (execInstrBr.eq_16 execInstrBr.eq_17 execInstrBr.eq_18 execInstrBr.eq_19)
export RiscvZkvm.Rv64 (execInstrBr.eq_2 execInstrBr.eq_20 execInstrBr.eq_21 execInstrBr.eq_22)
export RiscvZkvm.Rv64 (execInstrBr.eq_23 execInstrBr.eq_24 execInstrBr.eq_25 execInstrBr.eq_26)
export RiscvZkvm.Rv64 (execInstrBr.eq_27 execInstrBr.eq_28 execInstrBr.eq_29 execInstrBr.eq_3)
export RiscvZkvm.Rv64 (execInstrBr.eq_30 execInstrBr.eq_31 execInstrBr.eq_32 execInstrBr.eq_33)
export RiscvZkvm.Rv64 (execInstrBr.eq_34 execInstrBr.eq_35 execInstrBr.eq_36 execInstrBr.eq_37)
export RiscvZkvm.Rv64 (execInstrBr.eq_38 execInstrBr.eq_39 execInstrBr.eq_4 execInstrBr.eq_40)
export RiscvZkvm.Rv64 (execInstrBr.eq_41 execInstrBr.eq_42 execInstrBr.eq_43 execInstrBr.eq_44)
export RiscvZkvm.Rv64 (execInstrBr.eq_45 execInstrBr.eq_46 execInstrBr.eq_47 execInstrBr.eq_48)
export RiscvZkvm.Rv64 (execInstrBr.eq_49 execInstrBr.eq_5 execInstrBr.eq_50 execInstrBr.eq_51)
export RiscvZkvm.Rv64 (execInstrBr.eq_52 execInstrBr.eq_53 execInstrBr.eq_54 execInstrBr.eq_55)
export RiscvZkvm.Rv64 (execInstrBr.eq_56 execInstrBr.eq_6 execInstrBr.eq_7 execInstrBr.eq_8)
export RiscvZkvm.Rv64 (execInstrBr.eq_9 execInstrBr_eq_execInstr instDecidableEqTrapKind instReprTrapKind)
export RiscvZkvm.Rv64 (instReprTrapKind.repr isAligned2.eq_1 isAligned4.eq_1 isAligned8.eq_1)
export RiscvZkvm.Rv64 (isMisalignedAccess isMisalignedAccess_imp_step_none isValidByteAccess.eq_1 isValidDwordAccess.eq_1)
export RiscvZkvm.Rv64 (isValidHalfwordAccess.eq_1 isValidMemAccess.eq_1 isValidMemAddr.eq_1 loadProgram)
export RiscvZkvm.Rv64 (loadProgram.eq_1 loadProgram_programAt privateInput_execInstrBr publicValues_execInstrBr)
export RiscvZkvm.Rv64 (step step.eq_1 stepN stepN.eq_1)
export RiscvZkvm.Rv64 (stepN.eq_2 stepN.eq_def stepN_add stepN_add_eq)
export RiscvZkvm.Rv64 (stepN_one stepN_succ stepN_zero stepResult)
export RiscvZkvm.Rv64 (stepResultOfOption stepResultOfOption_toOption stepResult_ok_iff step_csrs)
export RiscvZkvm.Rv64 (step_csrs_trap step_ebreak step_ecall_commit step_ecall_continue)
export RiscvZkvm.Rv64 (step_ecall_halt step_ecall_read_input step_ecall_read_input_trap_a0 step_ecall_write_other)
export RiscvZkvm.Rv64 (step_ecall_write_output step_ecall_write_public step_eq_stepResult_toOption step_lb)
export RiscvZkvm.Rv64 (step_lb_trap step_lbu step_lbu_trap step_ld)
export RiscvZkvm.Rv64 (step_ld_trap step_lh step_lh_trap step_lhu)
export RiscvZkvm.Rv64 (step_lhu_trap step_lw step_lw_trap step_lwu)
export RiscvZkvm.Rv64 (step_lwu_trap step_non_ecall_non_mem step_sb step_sb_trap)
export RiscvZkvm.Rv64 (step_sd step_sd_trap step_sh step_sh_trap)
export RiscvZkvm.Rv64 (step_sw step_sw_trap)

-- Namespaces downstream files `open`; see render() for why these
-- cannot come from `export`.
namespace Instr end Instr
namespace Instr.isBranch end Instr.isBranch
namespace Instr.isMemAccess end Instr.isMemAccess
namespace MEM_END end MEM_END
namespace MEM_START end MEM_START
namespace ProgramAt end ProgramAt
namespace StepResult end StepResult
namespace StepResult.ok end StepResult.ok
namespace StepResult.toOption end StepResult.toOption
namespace StepResult.trap end StepResult.trap
namespace TrapKind end TrapKind
namespace TrapKind.misalignedAccess end TrapKind.misalignedAccess
namespace TrapKind.other end TrapKind.other
namespace execInstr end execInstr
namespace execInstrBr end execInstrBr
namespace instReprTrapKind end instReprTrapKind
namespace isAligned2 end isAligned2
namespace isAligned4 end isAligned4
namespace isAligned8 end isAligned8
namespace isValidByteAccess end isValidByteAccess
namespace isValidDwordAccess end isValidDwordAccess
namespace isValidHalfwordAccess end isValidHalfwordAccess
namespace isValidMemAccess end isValidMemAccess
namespace isValidMemAddr end isValidMemAddr
namespace loadProgram end loadProgram
namespace step end step
namespace stepN end stepN

end EvmAsm.Rv64
