-- GENERATED by scripts/gen-rv64-shims.py -- do not edit by hand.
--
-- `GenericSpecs` now lives in the riscv-zkvm dependency, prebuilt.
-- This shim re-exports it so evm-asm's existing references keep resolving;
-- `export` aliases the SAME constants, so no statement changes meaning.
--
-- Only the export block below is regenerated. The prelude between the
-- markers is preserved verbatim and is the source of truth -- aliases do not
-- propagate transitively, so those import edges are what let downstream files
-- still see the names they used to. Edit it here if the imports must change.
--
-- Regenerate with `scripts/gen-rv64-shims.py`; `--check` gates it in CI.
-- BEGIN shim prelude (preserved from the original module)
/-
  EvmAsm.Rv64.GenericSpecs

  Parametric (generic) separation-logic specifications for single-instruction
  execution patterns.  Each lemma factors out the common proof shape:

    1. Extract code fetch from CodeReq side-condition.
    2. Extract register / memory values from the precondition.
    3. Show `step s = some nextState` using the extracted values.
    4. Rearrange the separating conjunction to apply the update lemma.
    5. Update the PC using `holdsFor_pcFree_setPC`.

  Concrete per-instruction specs (in InstructionSpecs.lean and SyscallSpecs.lean)
  are one-line applications of these generic lemmas.
-/

-- `CPSSpec` transitively imports `Basic`, `SepLogic`, `Execution`, and
-- (via `Execution`) `Instructions`.
module

public import EvmAsm.Rv64.CPSSpec
public import RiscvZkvm.Rv64.Logic.GenericSpecs

@[expose] public section
-- END shim prelude

namespace EvmAsm.Rv64

export RiscvZkvm.Rv64 (generic_1reg_spec_within generic_2reg_rd_eq_rs1_spec_within generic_2reg_spec_within generic_3reg_spec_within)
export RiscvZkvm.Rv64 (generic_beq_spec_within generic_bge_spec_within generic_bgeu_spec_within generic_blt_spec_within)
export RiscvZkvm.Rv64 (generic_bltu_spec_within generic_bne_spec_within generic_jal_spec_within generic_jalr_spec_within)
export RiscvZkvm.Rv64 (generic_ld_spec_within generic_nop_spec_within generic_sd_spec_within generic_sd_x0_spec_within)

end EvmAsm.Rv64
