-- GENERATED by scripts/gen-rv64-shims.py -- do not edit by hand.
--
-- `HalfwordOps` now lives in the riscv-zkvm dependency, prebuilt.
-- This shim re-exports it so evm-asm's existing references keep resolving;
-- `export` aliases the SAME constants, so no statement changes meaning.
--
-- Only the export block below is regenerated. The prelude between the
-- markers is preserved verbatim and is the source of truth -- aliases do not
-- propagate transitively, so those import edges are what let downstream files
-- still see the names they used to. Edit it here if the imports must change.
--
-- Regenerate with `scripts/gen-rv64-shims.py`; `--check` gates it in CI.
-- BEGIN shim prelude (preserved from the original module)
/-
  EvmAsm.Rv64.HalfwordOps

  Halfword-level infrastructure: extractHalfword/replaceHalfword algebra and
  generic CPS specs for LH (load halfword signed), LHU (load halfword unsigned),
  and SH (store halfword).
-/
-- `CPSSpec` transitively imports `Basic`, `SepLogic`, and `Execution`.
module

public import EvmAsm.Rv64.CPSSpec
public import Mathlib.Tactic.IntervalCases
public import Mathlib.Tactic.FinCases
public import Mathlib.Data.Fintype.Basic
meta import EvmAsm.Rv64.CPSSpec
meta import Mathlib.Tactic.IntervalCases
meta import Mathlib.Tactic.FinCases
meta import Mathlib.Data.Fintype.Basic
public import RiscvZkvm.Rv64.Logic.HalfwordOps
meta import RiscvZkvm.Rv64.Logic.HalfwordOps

@[expose] public section
-- END shim prelude

namespace EvmAsm.Rv64

export RiscvZkvm.Rv64 (extractHalfword.eq_1 extractHalfword_replaceHalfword_same generic_lh_spec_within generic_lhu_spec_within)
export RiscvZkvm.Rv64 (generic_sh_spec_within getHalfword_eq halfwordOffset_lt_4 replaceHalfword.eq_1)
export RiscvZkvm.Rv64 (setHalfword_eq)

-- Namespaces downstream files `open`; see render() for why these
-- cannot come from `export`.
namespace extractHalfword end extractHalfword
namespace replaceHalfword end replaceHalfword

end EvmAsm.Rv64
