-- GENERATED by scripts/gen-rv64-shims.py -- do not edit by hand.
--
-- `InstructionSpecs` now lives in the riscv-zkvm dependency, prebuilt.
-- This shim re-exports it so evm-asm's existing references keep resolving;
-- `export` aliases the SAME constants, so no statement changes meaning.
--
-- The original prelude is preserved deliberately -- aliases do not propagate
-- transitively, so those import edges are what let downstream files still see
-- the names they used to.  See original_prelude() for the full reasoning.
--
-- Regenerate with `scripts/gen-rv64-shims.py`; `--check` gates it in CI.
/-
  EvmAsm.Rv64.InstructionSpecs

  Separation logic specifications for each RISC-V (RV64) instruction using
  bounded CPS specs.

  Code is accessed via CodeReq.singleton side-condition (not instrAt in P/Q).

  Proofs delegate to the generic lemmas in GenericSpecs.lean.

  Ported from EvmAsm.InstructionSpecs (RV32) with the following changes:
  - LUI/AUIPC: postcondition uses signExtend 64 of the 32-bit shifted value
  - LW/SW specs removed (RV64 LW uses getWord32, not getMem)
  - LD/SD specs added using generic_ld_spec/generic_sd_spec
-/

-- `GenericSpecs` transitively imports `Basic`, `Instructions`, `SepLogic`,
-- `Execution`, and `CPSSpec`.
module

public import EvmAsm.Rv64.GenericSpecs
public import RiscvZkvm.Rv64.Logic.InstructionSpecs

@[expose] public section

namespace EvmAsm.Rv64

export RiscvZkvm.Rv64 (add_spec_all_same_within add_spec_rd_eq_rs1_within add_spec_rd_eq_rs2_within add_spec_within)
export RiscvZkvm.Rv64 (addi_spec_same_within addi_spec_within addiw_spec_same_within addiw_spec_within)
export RiscvZkvm.Rv64 (auipc_spec_within beq_spec_same_within beq_spec_within bgeu_spec_within)
export RiscvZkvm.Rv64 (bne_spec_same_within bne_spec_within fence_spec_within jal_spec_within)
export RiscvZkvm.Rv64 (jalr_spec_same_within jalr_spec_within ld_spec_same_within ld_spec_within)
export RiscvZkvm.Rv64 (li_spec_within lui_spec_within mv_spec_within nop_spec_within)
export RiscvZkvm.Rv64 (ori_spec_same_within ori_spec_within sd_spec_same_within sd_spec_within)
export RiscvZkvm.Rv64 (slti_spec_same_within slti_spec_within sub_spec_all_same_within sub_spec_rd_eq_rs1_within)
export RiscvZkvm.Rv64 (sub_spec_within)

end EvmAsm.Rv64
