-- GENERATED by scripts/gen-rv64-shims.py -- do not edit by hand.
--
-- `Instructions` now lives in the riscv-zkvm dependency, prebuilt.
-- This shim re-exports it so evm-asm's existing references keep resolving;
-- `export` aliases the SAME constants, so no statement changes meaning.
--
-- The original prelude is preserved deliberately -- aliases do not propagate
-- transitively, so those import edges are what let downstream files still see
-- the names they used to.  See original_prelude() for the full reasoning.
--
-- Regenerate with `scripts/gen-rv64-shims.py`; `--check` gates it in CI.
/-
  EvmAsm.Rv64.Instructions

  RISC-V 64-bit instruction definitions and their semantics (RV64IM).
-/

module

public import EvmAsm.Rv64.Basic
public import EvmAsm.Rv64.ZiskAccel
public import RiscvZkvm.Rv64.Instructions

@[expose] public section

namespace EvmAsm.Rv64

export RiscvZkvm.Rv64 (Instr.isBranch Instr.isMemAccess execInstr rv64_div)
export RiscvZkvm.Rv64 (rv64_divu rv64_mulh rv64_mulhsu rv64_mulhu)
export RiscvZkvm.Rv64 (rv64_rem rv64_remu signExtend12 signExtend12_0)
export RiscvZkvm.Rv64 (signExtend12_1 signExtend12_12 signExtend12_16 signExtend12_2)
export RiscvZkvm.Rv64 (signExtend12_20 signExtend12_24 signExtend12_255 signExtend12_28)
export RiscvZkvm.Rv64 (signExtend12_3 signExtend12_31 signExtend12_32 signExtend12_36)
export RiscvZkvm.Rv64 (signExtend12_3944 signExtend12_3952 signExtend12_3960 signExtend12_3968)
export RiscvZkvm.Rv64 (signExtend12_3976 signExtend12_3984 signExtend12_3992 signExtend12_4)
export RiscvZkvm.Rv64 (signExtend12_40 signExtend12_4000 signExtend12_4008 signExtend12_4016)
export RiscvZkvm.Rv64 (signExtend12_4024 signExtend12_4032 signExtend12_4040 signExtend12_4048)
export RiscvZkvm.Rv64 (signExtend12_4056 signExtend12_4064 signExtend12_4072 signExtend12_4080)
export RiscvZkvm.Rv64 (signExtend12_4088 signExtend12_4095 signExtend12_44 signExtend12_48)
export RiscvZkvm.Rv64 (signExtend12_5 signExtend12_52 signExtend12_56 signExtend12_6)
export RiscvZkvm.Rv64 (signExtend12_60 signExtend12_63 signExtend12_64 signExtend12_8)
export RiscvZkvm.Rv64 (signExtend12_neg16 signExtend13 signExtend21)

-- Namespaces downstream files `open`; see render() for why these
-- cannot come from `export`.
namespace Instr end Instr

end EvmAsm.Rv64
