-- GENERATED by scripts/gen-rv64-shims.py -- do not edit by hand.
--
-- `LaResolve` now lives in the riscv-zkvm dependency, prebuilt.
-- This shim re-exports it so evm-asm's existing references keep resolving;
-- `export` aliases the SAME constants, so no statement changes meaning.
--
-- The original prelude is preserved deliberately -- aliases do not propagate
-- transitively, so those import edges are what let downstream files still see
-- the names they used to.  See original_prelude() for the full reasoning.
--
-- Regenerate with `scripts/gen-rv64-shims.py`; `--check` gates it in CI.
/-
  EvmAsm.Rv64.LaResolve

  **The `la` (AUIPC/ADDI address-materialization) resolution model**
  (bead evm-asm-85699; subsumes the arithmetic half of 4ch8f.59.1.1).

  The emitter materializes a global `.data` address with the standard
  RISC-V `la` idiom

  ```
    auipc rd, %pcrel_hi(sym)     -- rd := pc + sext32→64(hi << 12)
    addi  rd, rd, %pcrel_lo(sym) -- rd := rd + sext12(lo)
  ```

  Until now the terminating `.conditional` specs (RETURN / REVERT /
  SELFDESTRUCT and the guarded-handler family) carried the resolution as
  ASSUMED hypotheses (`hla1`/`hla2`/…):

  ```
    pc + ((hi.zeroExtend 32) <<< 12).signExtend 64 + signExtend12 lo = sym
  ```

  This module PROVES that arithmetic instead:

  * `laHi`/`laLo` — the psABI `%pcrel_hi`/`%pcrel_lo` immediates as
    functions of the AUIPC pc and the target (`hi = trunc20((Δ + 0x800)
    >>> 12)`, `lo = trunc12 Δ`, `Δ = target − pc`);
  * `la_resolve` — the round-trip: whenever the displacement is
    representable (`laInRange`: signed Δ ∈ (−2³¹, 2³¹ − 2¹¹)), the
    materialized address IS the target.  Fully generic, kernel-checked
    (per-bit-free: `toNat` decomposition + `omega`);
  * `la_materialize_within` — the two-instruction `cpsTripleWithin`:
    executing the emitted pair at `pc` yields `rd ↦ᵣ target`.

  Consumers instantiate `hi := laHi pc sym`, `lo := laLo pc sym`, discharge
  `laInRange` (decidable — for linked layouts Δ is a few MB), and the former
  `hla*` hypotheses become `la_resolve` facts
  (`Terminating/ReturnHaltResolved.lean` retires RETURN's).
-/

module

public import EvmAsm.Rv64.InstructionSpecs
public import RiscvZkvm.Rv64.Logic.LaResolve

@[expose] public section

namespace EvmAsm.Rv64

export RiscvZkvm.Rv64 (instDecidableLaInRange laHi laInRange laLo)
export RiscvZkvm.Rv64 (la_materialize_within la_resolve)

end EvmAsm.Rv64
