-- GENERATED by scripts/gen-rv64-shims.py -- do not edit by hand.
--
-- `MemRegion` now lives in the riscv-zkvm dependency, prebuilt.
-- This shim re-exports it so evm-asm's existing references keep resolving;
-- `export` aliases the SAME constants, so no statement changes meaning.
--
-- Only the export block below is regenerated. The prelude between the
-- markers is preserved verbatim and is the source of truth -- aliases do not
-- propagate transitively, so those import edges are what let downstream files
-- still see the names they used to. Edit it here if the imports must change.
--
-- Regenerate with `scripts/gen-rv64-shims.py`; `--check` gates it in CI.
-- BEGIN shim prelude (preserved from the original module)
/-
  EvmAsm.Rv64.MemRegion

  A contiguous multi-dword **byte region** in RISC-V memory: a `List (BitVec 8)`
  stored little-endian across consecutive 8-byte dwords, each named by `↦ₘ` with
  value `packBytes`. This is the separation-logic resource the RLP list decoder
  needs to read a payload spanning more than one dword — the existing decoder
  (`Phase2LongLoopGeneral`) reads only within a single dword.

  The base address is assumed dword-aligned (a payload at an unaligned pointer is
  read as a byte offset into a region whose base is the aligned input buffer).
-/

module

public import EvmAsm.Rv64.ByteOps
public import EvmAsm.Rv64.Tactics.XSimp
public import RiscvZkvm.Rv64.Logic.MemRegion

@[expose] public section
-- END shim prelude

namespace EvmAsm.Rv64

export RiscvZkvm.Rv64 (alignToDword_add_ofNat_of_aligned anyBytes byteOffset_add_ofNat_of_aligned bytesRegion)
export RiscvZkvm.Rv64 (bytesRegionAux bytesRegionAux_pcFree bytesRegion_anyBytes bytesRegion_dword_at)
export RiscvZkvm.Rv64 (bytesRegion_dword_pair_at bytesRegion_eq_cons bytesRegion_lbu_within bytesRegion_nil)
export RiscvZkvm.Rv64 (bytesRegion_pcFree pcFree_anyBytes)

end EvmAsm.Rv64
