-- GENERATED by scripts/gen-rv64-shims.py -- do not edit by hand.
--
-- `MemRegionWriteWide` now lives in the riscv-zkvm dependency, prebuilt.
-- This shim re-exports it so evm-asm's existing references keep resolving;
-- `export` aliases the SAME constants, so no statement changes meaning.
--
-- The original prelude is preserved deliberately -- aliases do not propagate
-- transitively, so those import edges are what let downstream files still see
-- the names they used to.  See original_prelude() for the full reasoning.
--
-- Regenerate with `scripts/gen-rv64-shims.py`; `--check` gates it in CI.
/-
  EvmAsm.Rv64.MemRegionWriteWide

  Multi-byte writes into a `bytesRegion`: the SH/SW/SD counterparts of
  `packBytes_set` / `bytesRegion_dword_at_set` (MemRegionWrite/MemRegionStore).

  - `setBytes` splices a little-endian store payload into a region's byte list.
  - `packBytes_setBytes_halfword` / `_word32` / `_dword`: replacing an aligned
    halfword / 32-bit word / whole cell of a packed dword equals packing the
    byte list with the payload spliced in — the algebraic core of `SH`/`SW`/`SD`
    into a byte region.
  - `bytesRegion_dword_at_setBytes` frames the `q`-th dword for BOTH `bs` and
    `setBytes bs (8q+r) ns` with the SAME `front`/`rest` (the multi-byte
    generalization of `bytesRegion_dword_at_set`), so an aligned store lands
    exactly on the spliced region.

  All payloads stay within one dword cell (`r + ns.length ≤ 8`), which the
  n-alignment of machine store addresses guarantees.
-/

module

public import EvmAsm.Rv64.MemRegionWrite
public import EvmAsm.Rv64.MemRegion
meta import EvmAsm.Rv64.MemRegionWrite
meta import EvmAsm.Rv64.MemRegion
public import RiscvZkvm.Rv64.Logic.MemRegionWriteWide
meta import RiscvZkvm.Rv64.Logic.MemRegionWriteWide

@[expose] public section

namespace EvmAsm.Rv64

export RiscvZkvm.Rv64 (bytesRegion_dword_at_setBytes dwordBytes dwordBytes.eq_1 extractByte_replaceHalfword)
export RiscvZkvm.Rv64 (extractByte_replaceWord32 getByteAt_setBytes halfwordBytes halfwordBytes.eq_1)
export RiscvZkvm.Rv64 (length_dwordBytes length_halfwordBytes length_setBytes length_word32Bytes)
export RiscvZkvm.Rv64 (packBytes_setBytes_dword packBytes_setBytes_halfword packBytes_setBytes_word32 setBytes)
export RiscvZkvm.Rv64 (setBytes_cons setBytes_drop_of_ge setBytes_drop_of_le setBytes_nil)
export RiscvZkvm.Rv64 (setBytes_nil_left setBytes_take_of_ge setBytes_take_of_le word32Bytes)
export RiscvZkvm.Rv64 (word32Bytes.eq_1)

-- Namespaces downstream files `open`; see render() for why these
-- cannot come from `export`.
namespace dwordBytes end dwordBytes
namespace halfwordBytes end halfwordBytes
namespace word32Bytes end word32Bytes

end EvmAsm.Rv64
