-- GENERATED by scripts/gen-rv64-shims.py -- do not edit by hand.
--
-- `MemRegionStoreWide` now lives in the riscv-zkvm dependency, prebuilt.
-- This shim re-exports it so evm-asm's existing references keep resolving;
-- `export` aliases the SAME constants, so no statement changes meaning.
--
-- The original prelude is preserved deliberately -- aliases do not propagate
-- transitively, so those import edges are what let downstream files still see
-- the names they used to.  See original_prelude() for the full reasoning.
--
-- Regenerate with `scripts/gen-rv64-shims.py`; `--check` gates it in CI.
/-
  EvmAsm.Rv64.MemRegionStoreWide

  `bytesRegion_sw_at_within`: the `SW` counterpart of `bytesRegion_sb_within`
  (MemRegionStore). Storing a 32-bit word at a 4-aligned byte index `i` of a
  region turns `bytesRegion regionBase bs` into
  `bytesRegion regionBase (setBytes bs i (word32Bytes (v.truncate 32)))`.

  The algebraic core (`packBytes_setBytes_word32`) and the paired region split
  (`bytesRegion_dword_at_setBytes`) both already live in `MemRegionWriteWide`;
  this module only ties them to `generic_sw_spec_within`, exactly as
  `bytesRegion_sb_within` ties `packBytes_set` to `generic_sb_spec_within`.

  Unlike the `SB` lemma the address is given as `ptr + signExtend12 offset`
  with a caller-supplied identification `hptr`, because the callers that need
  this (little-endian offset headers such as EIP-7685 SSZ `ExecutionRequests`)
  write several words off ONE base register with different immediates.
-/

module

public import EvmAsm.Rv64.MemRegionStore
public import EvmAsm.Rv64.MemRegionWriteWide
public import EvmAsm.Rv64.WordOps
public import RiscvZkvm.Rv64.Logic.MemRegionStoreWide

@[expose] public section

namespace EvmAsm.Rv64

export RiscvZkvm.Rv64 (bytesRegion_sw_at_within)

end EvmAsm.Rv64
