-- GENERATED by scripts/gen-rv64-shims.py -- do not edit by hand.
--
-- `MemRegionWrite` now lives in the riscv-zkvm dependency, prebuilt.
-- This shim re-exports it so evm-asm's existing references keep resolving;
-- `export` aliases the SAME constants, so no statement changes meaning.
--
-- Only the export block below is regenerated. The prelude between the
-- markers is preserved verbatim and is the source of truth -- aliases do not
-- propagate transitively, so those import edges are what let downstream files
-- still see the names they used to. Edit it here if the imports must change.
--
-- Regenerate with `scripts/gen-rv64-shims.py`; `--check` gates it in CI.
-- BEGIN shim prelude (preserved from the original module)
/-
  EvmAsm.Rv64.MemRegionWrite

  Writing into a `bytesRegion`: the byte-store counterpart to `bytesRegion_lbu_within`.
  An `SB` to byte `i` of a region turns `bytesRegion regionBase bs` into
  `bytesRegion regionBase (bs.set i b)`. The destination resource a byte-array copy
  loop needs (RLP address / hash fields → output struct).

  The algebraic core is `packBytes_set`: replacing byte `k` of a packed dword equals
  packing the byte list with position `k` set. Proved via byte-wise extensionality
  of dwords (`eq_of_forall_extractByte`).
-/

module

public import EvmAsm.Rv64.ByteOps
meta import EvmAsm.Rv64.ByteOps
public import RiscvZkvm.Rv64.Logic.MemRegionWrite
meta import RiscvZkvm.Rv64.Logic.MemRegionWrite

@[expose] public section
-- END shim prelude

namespace EvmAsm.Rv64

export RiscvZkvm.Rv64 (eq_of_forall_extractByte extractByte_packBytes_total extractByte_replaceByte_diff getByteAt_set)
export RiscvZkvm.Rv64 (packBytes_set)

end EvmAsm.Rv64
