-- GENERATED by scripts/gen-rv64-shims.py -- do not edit by hand.
--
-- `MemSat` now lives in the riscv-zkvm dependency, prebuilt.
-- This shim re-exports it so evm-asm's existing references keep resolving;
-- `export` aliases the SAME constants, so no statement changes meaning.
--
-- The original prelude is preserved deliberately -- aliases do not propagate
-- transitively, so those import edges are what let downstream files still see
-- the names they used to.  See original_prelude() for the full reasoning.
--
-- Regenerate with `scripts/gen-rv64-shims.py`; `--check` gates it in CI.
/-
  EvmAsm.Rv64.MemSat

  Satisfiability witnesses for byte-range assertions (bead evm-asm-4ch8f.63).

  `GuestFraming.scratch_sat` (Stateless/EntrySpec.lean) demands an explicit
  heap satisfying `guestInputAssertion input ** scratch` for every admissible
  input — a `cpsHaltTripleWithin` with an unsatisfiable precondition holds
  vacuously, so the framing must come with a non-vacuity witness.  This file
  provides the generic construction: `SatWithin P lo hi` packages "P is
  satisfied by a heap owning ONLY memory dwords inside `[lo, hi)`", and the
  combinators build witnesses for `memIs` / `bytesRegion` / `anyBytes` and
  chain them across `**` for address-ascending, footprint-disjoint regions.

  The footprint bookkeeping is in `Nat` (not `Word`) so the disjointness of
  adjacent ranges is `omega`-territory and never wraps: every valid dword
  address is ≤ `RAM_MEM_END = 0xc0000000` (`isValidDwordAccess`), far below
  `2^64`.
-/

import EvmAsm.Rv64.MemRegion
import EvmAsm.Rv64.SAsm.PhaseSplit
import RiscvZkvm.Rv64.Logic.MemSat

namespace EvmAsm.Rv64

export RiscvZkvm.Rv64 (Assertion.SatWithin Assertion.SatWithin.congr_bounds Assertion.SatWithin.mono Assertion.SatWithin.sat)
export RiscvZkvm.Rv64 (Assertion.SatWithin.sepConj INPUT_MEM_END.eq_1 INPUT_MEM_START.eq_1 PartialState.MemOnlyWithin)
export RiscvZkvm.Rv64 (PartialState.MemOnlyWithin.casesOn PartialState.MemOnlyWithin.code PartialState.MemOnlyWithin.inputBufBase PartialState.MemOnlyWithin.mem)
export RiscvZkvm.Rv64 (PartialState.MemOnlyWithin.mk PartialState.MemOnlyWithin.mono PartialState.MemOnlyWithin.pc PartialState.MemOnlyWithin.privateInput)
export RiscvZkvm.Rv64 (PartialState.MemOnlyWithin.publicValues PartialState.MemOnlyWithin.rec PartialState.MemOnlyWithin.recOn PartialState.MemOnlyWithin.regs)
export RiscvZkvm.Rv64 (RAM_MEM_END.eq_1 RAM_MEM_START.eq_1 isValidDwordAccess_ofNat isValidDwordAccess_of_toNat)
export RiscvZkvm.Rv64 (satWithin_anyBytes satWithin_bytesRegion satWithin_emp satWithin_memIs)
export RiscvZkvm.Rv64 (toNat_add_ofNat_of_le toNat_le_of_validByte toNat_le_of_validDword)

-- Namespaces downstream files `open`; see render() for why these
-- cannot come from `export`.
namespace Assertion end Assertion
namespace Assertion.SatWithin end Assertion.SatWithin
namespace INPUT_MEM_END end INPUT_MEM_END
namespace INPUT_MEM_START end INPUT_MEM_START
namespace PartialState end PartialState
namespace PartialState.MemOnlyWithin end PartialState.MemOnlyWithin
namespace RAM_MEM_END end RAM_MEM_END
namespace RAM_MEM_START end RAM_MEM_START

end EvmAsm.Rv64
