-- GENERATED by scripts/gen-rv64-shims.py -- do not edit by hand.
--
-- `RegOps` now lives in the riscv-zkvm dependency, prebuilt.
-- This shim re-exports it so evm-asm's existing references keep resolving;
-- `export` aliases the SAME constants, so no statement changes meaning.
--
-- Only the export block below is regenerated. The prelude between the
-- markers is preserved verbatim and is the source of truth -- aliases do not
-- propagate transitively, so those import edges are what let downstream files
-- still see the names they used to. Edit it here if the imports must change.
--
-- Regenerate with `scripts/gen-rv64-shims.py`; `--check` gates it in CI.
-- BEGIN shim prelude (preserved from the original module)
/-
  EvmAsm.Rv64.RegOps

  `reg_ops` grindset for `MachineState` projection lemmas (GRIND.md Phase 5).

  The lemmas live in `Basic.lean` already tagged `@[simp]`; this file registers
  them *additionally* in the `reg_ops` named simp set and the `grind`
  equational index, then exposes a one-line tactic macro.

  GRIND.md identifies this phase as the **lowest-risk** in the roadmap:
  augmenting already-`@[simp]` lemmas with `@[grind =]` cannot break existing
  `simp`-based proofs — nothing is removed from the default simp set, nothing
  is reshaped. Downstream modules opt in to `by reg_ops` where it wins; the
  legacy `simp [..]` closers continue to work unchanged.

  Included lemmas: the *projection* family — reading one field after
  writing another:
    * `pc_set<Field>`               (5 lemmas)
    * `code_set<Field>` / `code_append*`       (8 lemmas)
    * `getReg_setPC` / `getReg_append*`        (3 lemmas)
    * `getMem_setMem_eq` / `getMem_setMem_ne`  (2 lemmas)
    * `getMem_setReg` / `getMem_setPC`         (2 lemmas)
    * `getMem_append*`                         (2 lemmas)
    * `pc_append*`                             (2 lemmas)
    * `committed_set<Field>` / `committed_append<Public>` (6 lemmas)
    * `publicValues_set<Field>` / `publicValues_appendCommit` (6 lemmas)
    * `privateInput_set<Field>` / `privateInput_append<Commit/Public>` (7 lemmas)

  Deliberately *excluded*: the inductive `*_writeWords` / `*_writeBytesAsWords`
  family. Those unfold via induction on the list argument and are liable to
  loop `grind`'s equational index on open-ended lists. They remain `@[simp]`
  in `Basic.lean` so existing `simp` closers keep working.
-/

module

public import EvmAsm.Rv64.Basic
public import EvmAsm.Rv64.RegOpsAttr
meta import EvmAsm.Rv64.Basic
meta import EvmAsm.Rv64.RegOpsAttr
public import RiscvZkvm.Rv64.Logic.RegOps
meta import RiscvZkvm.Rv64.Logic.RegOps

@[expose] public section
-- END shim prelude

namespace EvmAsm.Rv64

export RiscvZkvm.Rv64 (tacticReg_ops)

end EvmAsm.Rv64
