-- GENERATED by scripts/gen-rv64-shims.py -- do not edit by hand.
--
-- `RemuNat` now lives in the riscv-zkvm dependency, prebuilt.
-- This shim re-exports it so evm-asm's existing references keep resolving;
-- `export` aliases the SAME constants, so no statement changes meaning.
--
-- The original prelude is preserved deliberately -- aliases do not propagate
-- transitively, so those import edges are what let downstream files still see
-- the names they used to.  See original_prelude() for the full reasoning.
--
-- Regenerate with `scripts/gen-rv64-shims.py`; `--check` gates it in CI.
/-
  EvmAsm.Rv64.RemuNat

  `rv64_remu` as `Nat` remainder, and the divisibility test guest code actually
  writes (GH #11578).

  ## Why this file exists

  `rv64_divu` already had its `Nat` bridge — `rv64_divu_toNat`
  (`EvmAsm/Evm64/EvmWordArith/KnuthTheoremB.lean:101`). **`rv64_remu` had none**,
  anywhere in the tree: the only prior proof reasoning about a `DIVU`/`REMU` pair
  is `U256DivU64BeSAsm.lean`, and it keeps both **opaque** behind a mirror model
  (`divByteStep`, `:26-28`) rather than bridging to `Nat`.

  ⚠️ Homed here rather than beside its `divu` sibling on purpose. That sibling
  sits in a 600-line file about Knuth's Algorithm B, where a reader looking for a
  general remainder bridge will not find it — which is exactly the failure mode
  ("searching by name finds a name; only reading the statement finds the fact")
  that has now cost this project four rediscoveries. A one-purpose file with the
  statement in its name is the cheap fix.

  ## The shape callers want

  Guest code does not test divisibility as `a % b = 0` on `Nat`; it computes
  `remu` into a register and branches on `bnez`. So the load-bearing form is the
  **`= 0` iff**, not the `toNat` equation — `remu_eq_zero_iff_mod_eq_zero` below
  is what a `bnez` obligation reduces to in one rewrite.
-/

module

public import EvmAsm.Rv64.Instructions
public import RiscvZkvm.Rv64.Logic.RemuNat

@[expose] public section

namespace EvmAsm.Rv64

export RiscvZkvm.Rv64 (remu_eq_zero_iff_mod_eq_zero remu_ne_zero_iff_mod_ne_zero rv64_remu_toNat)

end EvmAsm.Rv64
