-- GENERATED by scripts/gen-rv64-shims.py -- do not edit by hand.
--
-- `SyscallSpecs` now lives in the riscv-zkvm dependency, prebuilt.
-- This shim re-exports it so evm-asm's existing references keep resolving;
-- `export` aliases the SAME constants, so no statement changes meaning.
--
-- The original prelude is preserved deliberately -- aliases do not propagate
-- transitively, so those import edges are what let downstream files still see
-- the names they used to.  See original_prelude() for the full reasoning.
--
-- Regenerate with `scripts/gen-rv64-shims.py`; `--check` gates it in CI.
/-
  EvmAsm.Rv64.SyscallSpecs

  Spec database registrations for the `runBlock` auto-mode tactic.
  Each `@[spec_gen_rv64]` theorem is auto-detected by instruction constructor.

  64-bit RISC-V (RV64IM) variant. Uses LD/SD instead of LW/SW for
  64-bit doubleword memory access. Shift amounts use % 64 (not % 32).

  Code is accessed via CodeReq.singleton side-condition (not instrAt in P/Q).
-/

-- `InstructionSpecs → GenericSpecs → Basic, Instructions, SepLogic,
-- Execution, CPSSpec`. `ByteOps`/`HalfwordOps`/`WordOps` are independent
-- leaves and remain as direct imports.
module

public import EvmAsm.Rv64.InstructionSpecs
public import EvmAsm.Rv64.ByteOps
public import EvmAsm.Rv64.HalfwordOps
public import EvmAsm.Rv64.WordOps
public import EvmAsm.Rv64.Tactics.SpecDb
public import RiscvZkvm.Rv64.Logic.SyscallSpecs

@[expose] public section

namespace EvmAsm.Rv64

export RiscvZkvm.Rv64 (add_spec_gen_rd_eq_rs1_within add_spec_gen_rd_eq_rs2_within add_spec_gen_within addi_spec_gen_same_within)
export RiscvZkvm.Rv64 (addi_spec_gen_within addi_x0_spec_gen_within addiw_spec_gen_same_within addiw_spec_gen_within)
export RiscvZkvm.Rv64 (and_spec_gen_rd_eq_rs1_within andi_spec_gen_same_within andi_spec_gen_within auipc_spec_gen_within)
export RiscvZkvm.Rv64 (beq_spec_gen_within bge_spec_gen_within bgeu_spec_gen_within blt_spec_gen_within)
export RiscvZkvm.Rv64 (bltu_spec_gen_within bne_spec_gen_within div_spec_gen_rd_eq_rs1_within div_spec_gen_within)
export RiscvZkvm.Rv64 (divu_spec_gen_rd_eq_rs1_within divu_spec_gen_within ecall_halt_spec_gen_within isHalted.eq_1)
export RiscvZkvm.Rv64 (lb_spec_gen_within lbu_spec_gen_within ld_spec_gen_same_within ld_spec_gen_within)
export RiscvZkvm.Rv64 (lh_spec_gen_within lhu_spec_gen_within li_spec_gen_own_within li_spec_gen_within)
export RiscvZkvm.Rv64 (lui_spec_gen_within lw_spec_gen_within lwu_spec_gen_within mul_spec_gen_rd_eq_rs1_within)
export RiscvZkvm.Rv64 (mul_spec_gen_rd_eq_rs2_within mul_spec_gen_within mulh_spec_gen_rd_eq_rs1_within mulh_spec_gen_within)
export RiscvZkvm.Rv64 (mulhsu_spec_gen_rd_eq_rs1_within mulhsu_spec_gen_within mulhu_spec_gen_rd_eq_rs1_within mulhu_spec_gen_rd_eq_rs2_within)
export RiscvZkvm.Rv64 (mulhu_spec_gen_within mv_spec_gen_within or_spec_gen_rd_eq_rs1_within or_spec_gen_rd_eq_rs2_within)
export RiscvZkvm.Rv64 (or_spec_gen_within ori_spec_gen_same_within ori_spec_gen_within rem_spec_gen_rd_eq_rs1_within)
export RiscvZkvm.Rv64 (rem_spec_gen_within remu_spec_gen_rd_eq_rs1_within remu_spec_gen_within sb_spec_gen_within)
export RiscvZkvm.Rv64 (sd_spec_gen_own_within sd_spec_gen_within sd_x0_spec_gen_within sh_spec_gen_within)
export RiscvZkvm.Rv64 (sll_spec_gen_rd_eq_rs1_within sll_spec_gen_within slli_spec_gen_same_within slli_spec_gen_within)
export RiscvZkvm.Rv64 (slt_spec_gen_within slti_spec_gen_same_within slti_spec_gen_within sltiu_spec_gen_same_within)
export RiscvZkvm.Rv64 (sltiu_spec_gen_within sltu_spec_gen_rd_eq_rs1_within sltu_spec_gen_rd_eq_rs2_within sltu_spec_gen_within)
export RiscvZkvm.Rv64 (sra_spec_gen_rd_eq_rs1_within srai_spec_gen_same_within srai_spec_gen_within srl_spec_gen_rd_eq_rs1_within)
export RiscvZkvm.Rv64 (srl_spec_gen_within srli_spec_gen_same_within srli_spec_gen_within sub_spec_gen_rd_eq_rs1_within)
export RiscvZkvm.Rv64 (sub_spec_gen_rd_eq_rs2_within sub_spec_gen_within sw_spec_gen_within xor_spec_gen_rd_eq_rs1_within)
export RiscvZkvm.Rv64 (xori_spec_gen_same_within)

-- Namespaces downstream files `open`; see render() for why these
-- cannot come from `export`.
namespace isHalted end isHalted

end EvmAsm.Rv64
