-- GENERATED by scripts/gen-rv64-shims.py -- do not edit by hand.
--
-- `WordOps` now lives in the riscv-zkvm dependency, prebuilt.
-- This shim re-exports it so evm-asm's existing references keep resolving;
-- `export` aliases the SAME constants, so no statement changes meaning.
--
-- The original prelude is preserved deliberately -- aliases do not propagate
-- transitively, so those import edges are what let downstream files still see
-- the names they used to.  See original_prelude() for the full reasoning.
--
-- Regenerate with `scripts/gen-rv64-shims.py`; `--check` gates it in CI.
/-
  EvmAsm.Rv64.WordOps

  Word32-level infrastructure: extractWord32/replaceWord32 algebra and
  generic CPS specs for LW (load word signed), LWU (load word unsigned),
  and SW (store word).
-/
-- `CPSSpec` transitively imports `Basic`, `SepLogic`, and `Execution`.
module

public import EvmAsm.Rv64.CPSSpec
public import Mathlib.Tactic.IntervalCases
public import Mathlib.Tactic.FinCases
public import Mathlib.Data.Fintype.Basic
meta import EvmAsm.Rv64.CPSSpec
meta import Mathlib.Tactic.IntervalCases
meta import Mathlib.Tactic.FinCases
meta import Mathlib.Data.Fintype.Basic
public import RiscvZkvm.Rv64.Logic.WordOps
meta import RiscvZkvm.Rv64.Logic.WordOps

@[expose] public section

namespace EvmAsm.Rv64

export RiscvZkvm.Rv64 (extractWord32.eq_1 extractWord32_replaceWord32_same generic_lw_spec_within generic_lwu_spec_within)
export RiscvZkvm.Rv64 (generic_sw_spec_within getWord32_eq replaceWord32.eq_1 setWord32_eq)

-- Namespaces downstream files `open`; see render() for why these
-- cannot come from `export`.
namespace extractWord32 end extractWord32
namespace replaceWord32 end replaceWord32

end EvmAsm.Rv64
