-- GENERATED by scripts/gen-rv64-shims.py -- do not edit by hand.
--
-- `Word` now lives in the riscv-zkvm dependency, prebuilt.
-- This shim re-exports it so evm-asm's existing references keep resolving;
-- `export` aliases the SAME constants, so no statement changes meaning.
--
-- Only the export block below is regenerated. The prelude between the
-- markers is preserved verbatim and is the source of truth -- aliases do not
-- propagate transitively, so those import edges are what let downstream files
-- still see the names they used to. Edit it here if the imports must change.
--
-- Regenerate with `scripts/gen-rv64-shims.py`; `--check` gates it in CI.
-- BEGIN shim prelude (preserved from the original module)
/-
  EvmAsm.Rv64.Word

  Pure bitvector / address utilities for the RV64 word type, with NO
  dependency on the machine model (Reg / Instr / MachineState). This
  module is a root (no imports), so consumers that only need the `Word`
  notation, alignment predicates, byte-extraction ops, or address
  constants do not transitively pull in the full machine model.

  `Rv64.Basic` imports this file and layers the machine model on top.
-/

module

public import RiscvZkvm.Rv64.Word

@[expose] public section
-- END shim prelude

namespace EvmAsm.Rv64

export RiscvZkvm.Rv64 (INPUT_MEM_END INPUT_MEM_START MEM_END MEM_START)
export RiscvZkvm.Rv64 (RAM_MEM_END RAM_MEM_START ValidMemRange ValidMemRange.fetch)
export RiscvZkvm.Rv64 (ValidMemRange.get alignToDword byteOffset bytesToWordLE)
export RiscvZkvm.Rv64 (extractByte extractHalfword extractWord32 isAligned2)
export RiscvZkvm.Rv64 (isAligned2_eq isAligned4 isAligned4_eq isAligned8)
export RiscvZkvm.Rv64 (isAligned8_eq isValidByteAccess isValidByteAccess_eq isValidDwordAccess)
export RiscvZkvm.Rv64 (isValidDwordAccess_eq isValidHalfwordAccess isValidHalfwordAccess_eq isValidMemAccess)
export RiscvZkvm.Rv64 (isValidMemAccess_eq isValidMemAddr isValidMemAddr_eq replaceByte)
export RiscvZkvm.Rv64 (replaceHalfword replaceWord32 termWord)

-- Namespaces downstream files `open`; see render() for why these
-- cannot come from `export`.
namespace ValidMemRange end ValidMemRange

end EvmAsm.Rv64
