-- GENERATED by scripts/gen-rv64-shims.py -- do not edit by hand.
--
-- `ZiskAccel` now lives in the riscv-zkvm dependency, prebuilt.
-- This shim re-exports it so evm-asm's existing references keep resolving;
-- `export` aliases the SAME constants, so no statement changes meaning.
--
-- The original prelude is preserved deliberately -- aliases do not propagate
-- transitively, so those import edges are what let downstream files still see
-- the names they used to.  See original_prelude() for the full reasoning.
--
-- Regenerate with `scripts/gen-rv64-shims.py`; `--check` gates it in CI.
/-
  EvmAsm.Rv64.ZiskAccel

  Concrete semantics of the ZisK accelerator instructions
  (bead evm-asm-4ch8f.1).

  The guest invokes ZisK precompiles via raw `csrs <id>, <reg>` encodings
  (`.4byte` words, e.g. `0x80052073 = csrs 0x800, a0`); the register holds
  a pointer to the operand block.  This module gives those instructions
  *concrete* mathematical semantics — the actual Keccak-f[1600]
  permutation, the actual SHA-256 compression function, exact
  512-bit-intermediate modular arithmetic — rather than an axiomatized
  accelerator contract:

  * evm-asm carries SOFTWARE implementations of several hashes (RIPEMD-160,
    the SHA-256 Merkle–Damgård wrapper, P-256 over Arith256Mod); proofs
    must relate the software and accelerator paths to the SAME function,
    so the function has to exist concretely;
  * the project's trusted base is the three classical axioms — an
    axiomatized accelerator contract would widen it;
  * concrete permutations are testable in-repo: the known-answer theorems
    below are kernel-checked with `decide` against pinned vectors
    (`keccak256("")`, `sha256("")`).

  Modeled accelerators (CSR ids per `ziskos` and the pinned probes in
  `Codegen/Probes/HashProbes.lean` / `Secp256k1Field.lean`):

    0x800  Keccakf      rs1 → 200-byte state, 25 LE u64 lanes, in place
    0x802  Arith256Mod  rs1 → [a*, b*, c*, module*, d*], 4 LE u64 limbs
                        each; d := (a*b + c) mod module (exact 512-bit
                        intermediate; module = 0 traps)
    0x805  Sha256f      rs1 → [state*, input*]; state = 8 u32 (LE-u32
                        packed in u64), input = 16 u32; one compression,
                        in place
    0x803  Secp256k1Add rs1 → [p1*, p2*], 64-byte affine points (x||y,
                        4 LE u64 limbs each); p1 := p1 + p2 by the chord
                        formula (coords reduced, x1 ≠ x2 — else trap)
    0x804  Secp256k1Dbl rs1 → 64-byte affine point, doubled in place by
                        the tangent formula (coords reduced, y ≠ 0)
    0x806  Bn254CurveAdd    like 0x803/0x804 over the BN254 field
    0x807  Bn254CurveDbl
    0x808  Bn254ComplexAdd  rs1 → [f1*, f2*], 64-byte Fp2 elements
    0x809  Bn254ComplexSub  (x0 limbs at +0, x1 at +32); f1 op= f2,
    0x80A  Bn254ComplexMul  u² = −1, components reduced (else trap)
    0x80B  Arith384Mod  rs1 → [a*, b*, c*, module*, d*], 6 LE u64 limbs
                        each; d := (a*b + c) mod module (module = 0 traps)
    0x80C  Bls12_381CurveAdd    the 6-limb (96-byte point / element)
    0x80D  Bls12_381CurveDbl    siblings of the BN254 entries, over the
    0x80E  Bls12_381ComplexAdd  BLS12-381 base field
    0x80F  Bls12_381ComplexSub
    0x810  Bls12_381ComplexMul
    0x819  Blake2bRound rs1 → [sigmaIdx, state*, input*]; one BLAKE2b
                        round on the 16-word working vector with SIGMA
                        row `sigmaIdx` (must be < 10), in place

  Any other CSR id traps (`step` returns `none`): unmodeled accelerators
  halt the model rather than silently no-op.  This closes the full set
  of accelerator ids the guest emits (`grep '.4byte 0x8' Codegen/`).
-/

module

public import EvmAsm.Rv64.Basic
public import RiscvZkvm.Rv64.ZiskAccel

@[expose] public section

namespace EvmAsm.Rv64

export RiscvZkvm.Rv64 (Accel.arith256Mod Accel.blake2Sigma Accel.blake2bRound Accel.blake2bRound_kat_abc)
export RiscvZkvm.Rv64 (Accel.blakeG Accel.bls12P Accel.bls12_curveDbl_kat Accel.bn254P)
export RiscvZkvm.Rv64 (Accel.bn254_complexMul_kat Accel.bn254_curveAdd_kat Accel.bn254_curveDbl_kat Accel.byteSwap32)
export RiscvZkvm.Rv64 (Accel.complexAddL Accel.complexMulL Accel.complexSubL Accel.curveAdd)
export RiscvZkvm.Rv64 (Accel.curveAddL Accel.curveDbl Accel.curveDblL Accel.dwordBE)
export RiscvZkvm.Rv64 (Accel.dwordsToU32s Accel.dwordsToU32s.eq_1 Accel.dwordsToU32sBE Accel.dwordsToU32sBE_empty_padding)
export RiscvZkvm.Rv64 (Accel.dwordsToU32s_u32sToDwords Accel.dwordsToU32s_u32sToDwords_pair Accel.foldl_length_fixed Accel.invMod)
export RiscvZkvm.Rv64 (Accel.keccakF Accel.keccakF_eq_keccakRounds_split Accel.keccakF_kat_empty Accel.keccakF_kat_rlp_empty)
export RiscvZkvm.Rv64 (Accel.keccakF_length Accel.keccakRC Accel.keccakRound Accel.keccakRound_length)
export RiscvZkvm.Rv64 (Accel.keccakRounds Accel.leLimbsToNat Accel.length_dwordsToU32s Accel.length_u32sToDwords)
export RiscvZkvm.Rv64 (Accel.natToLeLimbs Accel.powMod Accel.powModAux Accel.ptValid)
export RiscvZkvm.Rv64 (Accel.rhoOff Accel.secpP Accel.secp_curveAdd_kat Accel.secp_curveDbl_kat)
export RiscvZkvm.Rv64 (Accel.setWidth32_or_shift_hi Accel.setWidth32_or_shift_lo Accel.sha256Compress Accel.sha256Compress_kat_empty)
export RiscvZkvm.Rv64 (Accel.sha256Compress_length Accel.sha256K Accel.sha256W Accel.u32sToDwords)
export RiscvZkvm.Rv64 (Accel.u32sToDwords.eq_1 Accel.u32sToDwords.eq_2 Accel.u32sToDwords.eq_def Accel.u32sToDwords_dwordsToU32s_pair)
export RiscvZkvm.Rv64 (MachineState.code_execCsrs MachineState.committed_execCsrs MachineState.csrsValid MachineState.csrsWrite)
export RiscvZkvm.Rv64 (MachineState.execCsrs MachineState.getReg_execCsrs MachineState.inputBufBase_execCsrs MachineState.pc_execCsrs)
export RiscvZkvm.Rv64 (MachineState.privateInput_execCsrs MachineState.publicValues_execCsrs MachineState.validDwordRange)

-- Namespaces downstream files `open`; see render() for why these
-- cannot come from `export`.
namespace Accel end Accel
namespace Accel.dwordsToU32s end Accel.dwordsToU32s
namespace Accel.u32sToDwords end Accel.u32sToDwords
namespace MachineState end MachineState

end EvmAsm.Rv64
