/-
  EvmAsm.Evm64.MulMod.ProductLayoutCall15

  Product-layout call15 suffix composition for MULMOD.
-/

import EvmAsm.Evm64.MulMod.ProductLayoutCall14

open EvmAsm.Rv64.Tactics

namespace EvmAsm.Evm64

open EvmAsm.Rv64

local macro "evm_mulmod_product_layout_slice_rfl" : tactic =>
  `(tactic|
    first
      | rfl
      | (unfold evm_mulmod_product_layout evm_mulmod_product_zero
            evm_mulmod_product_add_partial evm_mulmod_product_propagate_carry
            LD SD ADD SLTU OR' MUL MULHU single seq
         rfl))

/-- Core+finish code for layout call 15 is contained in `evm_mulmod_product_layout`. -/
theorem evm_mulmod_product_layout_call15_core_code_sub (base : Word) :
    ∀ a i, (evm_mulmod_product_add_partial_core_finish_code (base + 1700)
        (24 : BitVec 12) (56 : BitVec 12) (3984 : BitVec 12) (3992 : BitVec 12)) a = some i →
      (evm_mulmod_product_layout_code base) a = some i := by
  unfold evm_mulmod_product_add_partial_core_finish_code evm_mulmod_product_layout_code
  refine CodeReq.ofProg_mono_sub base (base + 1700) evm_mulmod_product_layout _ 425 ?_ ?_ ?_ ?_
  · bv_omega
  · evm_mulmod_product_layout_slice_rfl
  · rw [evm_mulmod_product_layout_length]
    decide
  · rw [evm_mulmod_product_layout_length]
    decide

/-- Layout call 15 code is contained in `evm_mulmod_product_layout`. -/
theorem evm_mulmod_product_layout_call15_code_sub (base : Word) :
    ∀ a i, (evm_mulmod_product_add_partial_core_finish_code (base + 1700)
        (24 : BitVec 12) (56 : BitVec 12) (3984 : BitVec 12) (3992 : BitVec 12)) a = some i →
      (evm_mulmod_product_layout_code base) a = some i :=
  evm_mulmod_product_layout_call15_core_code_sub base

/-- Layout call 15 spec lifted onto the local product-layout code requirement. -/
abbrev evm_mulmod_product_layout_call15_spec_within :=
  fun sp base a b lo hi x5Old x6Old x7Old x8Old x9Old x10Old x11Old x13Old x14Old =>
    cpsTripleWithin_extend_code
      (h := evm_mulmod_product_add_partial_layout_call15_spec_within sp (base + 1700) a b lo hi x5Old x6Old x7Old x8Old x9Old x10Old x11Old x13Old x14Old)
      (hmono := evm_mulmod_product_layout_call15_code_sub base)

/-- Product offset 136 after layout call14. -/
def mulModProductLayoutCall14P136 (a b : EvmWord) : Word :=
  mulModAddPartialLoValue (mulModProductLayoutCall13P136 a b) (a.getLimbN 2) (b.getLimbN 3)

/-- Product offset 144 after layout call14. -/
def mulModProductLayoutCall14P144 (a b : EvmWord) : Word :=
  mulModAddPartialHiValue (mulModProductLayoutCall13P144 a b)
    (mulModProductLayoutCall13P136 a b) (a.getLimbN 2) (b.getLimbN 3)

/-- Carry generated by layout call14 before propagating through offset 152. -/
def mulModProductLayoutCall14Carry144 (a b : EvmWord) : Word :=
  mulModAddPartialHiCarry (mulModProductLayoutCall13P144 a b)
    (mulModProductLayoutCall13P136 a b) (a.getLimbN 2) (b.getLimbN 3)

/-- Product offset 152 after layout call14. -/
def mulModProductLayoutCall14P152 (a b : EvmWord) : Word :=
  mulModCarryStepValue (mulModProductLayoutCall13P152 a b) (mulModProductLayoutCall14Carry144 a b)

/-- Carry after layout call14 propagates through offset 152. -/
def mulModProductLayoutCall14Carry152 (a b : EvmWord) : Word :=
  mulModCarryStepCarry (mulModProductLayoutCall13P152 a b) (mulModProductLayoutCall14Carry144 a b)

/-- Product-layout cells that layout call15 does not touch after call14. -/
@[irreducible]
def evmMulModProductLayoutCall15Frame (sp : Word) (a b n : EvmWord) : Assertion :=
  ((sp + signExtend12 (0 : BitVec 12)) ↦ₘ a.getLimbN 0) **
  ((sp + signExtend12 (8 : BitVec 12)) ↦ₘ a.getLimbN 1) **
  ((sp + signExtend12 (16 : BitVec 12)) ↦ₘ a.getLimbN 2) **
  ((sp + signExtend12 (32 : BitVec 12)) ↦ₘ b.getLimbN 0) **
  ((sp + signExtend12 (40 : BitVec 12)) ↦ₘ b.getLimbN 1) **
  ((sp + signExtend12 (48 : BitVec 12)) ↦ₘ b.getLimbN 2) **
  ((sp + 64) ↦ₘ n.getLimbN 0) **
  ((sp + 72) ↦ₘ n.getLimbN 1) **
  ((sp + 80) ↦ₘ n.getLimbN 2) **
  ((sp + 88) ↦ₘ n.getLimbN 3) **
  ((sp + signExtend12 (3936 : BitVec 12)) ↦ₘ mulModProductLayoutCall00P96 a b) **
  ((sp + signExtend12 (3944 : BitVec 12)) ↦ₘ mulModProductLayoutCall02P104 a b) **
  ((sp + signExtend12 (3952 : BitVec 12)) ↦ₘ mulModProductLayoutCall05P112 a b) **
  ((sp + signExtend12 (3960 : BitVec 12)) ↦ₘ mulModProductLayoutCall09P120 a b) **
  ((sp + signExtend12 (3968 : BitVec 12)) ↦ₘ mulModProductLayoutCall12P128 a b) **
  ((sp + signExtend12 (3976 : BitVec 12)) ↦ₘ mulModProductLayoutCall14P136 a b)

/-- Folded post after zeroing and product-layout calls 00 through 15. -/
@[irreducible]
def evmMulModProductLayoutZeroCall15Post (sp : Word) (a b n : EvmWord) : Assertion :=
  (((.x12 ↦ᵣ sp) **
    (.x5 ↦ᵣ a.getLimbN 3) **
    (.x6 ↦ᵣ b.getLimbN 3) **
    (.x7 ↦ᵣ mulModAddPartialLoProduct (a.getLimbN 3) (b.getLimbN 3)) **
    (.x8 ↦ᵣ mulModAddPartialHiProduct (a.getLimbN 3) (b.getLimbN 3)) **
    (.x9 ↦ᵣ mulModProductLayoutCall14P152 a b) **
    (.x10 ↦ᵣ mulModAddPartialHiCarry (mulModProductLayoutCall14P152 a b)
      (mulModProductLayoutCall14P144 a b) (a.getLimbN 3) (b.getLimbN 3)) **
    (.x11 ↦ᵣ mulModAddPartialHiValue (mulModProductLayoutCall14P152 a b)
      (mulModProductLayoutCall14P144 a b) (a.getLimbN 3) (b.getLimbN 3)) **
    (.x13 ↦ᵣ mulModAddPartialHiBaseCarry (mulModProductLayoutCall14P152 a b)
      (a.getLimbN 3) (b.getLimbN 3)) **
    (.x14 ↦ᵣ mulModAddPartialHiCarryFromLo (mulModProductLayoutCall14P152 a b)
      (mulModProductLayoutCall14P144 a b) (a.getLimbN 3) (b.getLimbN 3)) **
    ((sp + signExtend12 (24 : BitVec 12)) ↦ₘ a.getLimbN 3) **
    ((sp + signExtend12 (56 : BitVec 12)) ↦ₘ b.getLimbN 3) **
    ((sp + signExtend12 (3984 : BitVec 12)) ↦ₘ mulModAddPartialLoValue (mulModProductLayoutCall14P144 a b)
      (a.getLimbN 3) (b.getLimbN 3)) **
    ((sp + signExtend12 (3992 : BitVec 12)) ↦ₘ mulModAddPartialHiValue (mulModProductLayoutCall14P152 a b)
      (mulModProductLayoutCall14P144 a b) (a.getLimbN 3) (b.getLimbN 3))) **
   evmMulModProductLayoutCall15Frame sp a b n)

/-- Product-layout prefix through call15. -/
theorem evm_mulmod_product_layout_zero_call15_spec_within
    (sp base : Word) (a b n : EvmWord)
    (p0 p1 p2 p3 p4 p5 p6 p7 : Word)
    (x5Old x6Old x7Old x8Old x9Old x10Old x11Old x13Old x14Old : Word) :
    cpsTripleWithin ((((((((((((((((8 + (15 + 24)) + (15 + 20)) + (15 + 20)) + (15 + 16)) + (15 + 16)) + (15 + 16)) + (15 + 12)) + (15 + 12)) + (15 + 12)) + (15 + 12)) + (15 + 8)) + (15 + 8)) + (15 + 8)) + (15 + 4)) + (15 + 4)) + 15)
      base (base + 1760) (evm_mulmod_product_layout_code base)
      (evmMulModProductLayoutPre sp a b n p0 p1 p2 p3 p4 p5 p6 p7 **
       ((.x5 ↦ᵣ x5Old) ** (.x6 ↦ᵣ x6Old) ** (.x7 ↦ᵣ x7Old) ** (.x8 ↦ᵣ x8Old) **
        (.x9 ↦ᵣ x9Old) ** (.x10 ↦ᵣ x10Old) ** (.x11 ↦ᵣ x11Old) **
        (.x13 ↦ᵣ x13Old) ** (.x14 ↦ᵣ x14Old)))
      (evmMulModProductLayoutZeroCall15Post sp a b n) := by
  simp only [evmMulModProductLayoutPre_unfold]
  have hPrev := evm_mulmod_product_layout_zero_call14_spec_within sp base a b n
    p0 p1 p2 p3 p4 p5 p6 p7
    x5Old x6Old x7Old x8Old x9Old x10Old x11Old x13Old x14Old
  simp only [evmMulModProductLayoutPre_unfold] at hPrev
  unfold evmMulModProductLayoutZeroCall14Post evmMulModProductLayoutCall14Frame at hPrev
  simp only [signExtend12_0, signExtend12_8, signExtend12_16, signExtend12_24,
    signExtend12_32, signExtend12_40,
    show signExtend12 (48 : BitVec 12) = (48 : Word) by decide,
    show signExtend12 (56 : BitVec 12) = (56 : Word) by decide] at hPrev
  rw [show sp + (0 : Word) = sp by bv_omega] at hPrev
  rw [← mulModProductLayoutCall14P136, ← mulModProductLayoutCall14P144,
    ← mulModProductLayoutCall14Carry144, ← mulModProductLayoutCall14P152,
    ← mulModProductLayoutCall14Carry152] at hPrev
  have hCall := evm_mulmod_product_layout_call15_spec_within sp base
    (a.getLimbN 3) (b.getLimbN 3)
    (mulModProductLayoutCall14P144 a b) (mulModProductLayoutCall14P152 a b)
    (a.getLimbN 2) (b.getLimbN 3)
    (mulModAddPartialLoProduct (a.getLimbN 2) (b.getLimbN 3))
    (mulModAddPartialHiProduct (a.getLimbN 2) (b.getLimbN 3))
    (mulModProductLayoutCall14P152 a b) (mulModProductLayoutCall14Carry152 a b)
    (mulModProductLayoutCall14P144 a b)
    (mulModAddPartialHiBaseCarry (mulModProductLayoutCall13P144 a b) (a.getLimbN 2) (b.getLimbN 3))
    (mulModAddPartialHiCarryFromLo (mulModProductLayoutCall13P144 a b)
      (mulModProductLayoutCall13P136 a b) (a.getLimbN 2) (b.getLimbN 3))
  unfold evmMulModAddPartialCoreFullPre at hCall
  simp only [signExtend12_24, show signExtend12 (56 : BitVec 12) = (56 : Word) by decide] at hCall
  let call15Frame : Assertion :=
    ((sp ↦ₘ a.getLimbN 0) **
      ((sp + 8) ↦ₘ a.getLimbN 1) **
      ((sp + 16) ↦ₘ a.getLimbN 2) **
      ((sp + 32) ↦ₘ b.getLimbN 0) **
      ((sp + 40) ↦ₘ b.getLimbN 1) **
      ((sp + 48) ↦ₘ b.getLimbN 2) **
      ((sp + 64) ↦ₘ n.getLimbN 0) **
      ((sp + 72) ↦ₘ n.getLimbN 1) **
      ((sp + 80) ↦ₘ n.getLimbN 2) **
      ((sp + 88) ↦ₘ n.getLimbN 3) **
      ((sp + signExtend12 (3936 : BitVec 12)) ↦ₘ (mulModProductLayoutCall00P96 a b)) **
      ((sp + signExtend12 (3944 : BitVec 12)) ↦ₘ (mulModProductLayoutCall02P104 a b)) **
      ((sp + signExtend12 (3952 : BitVec 12)) ↦ₘ (mulModProductLayoutCall05P112 a b)) **
      ((sp + signExtend12 (3960 : BitVec 12)) ↦ₘ (mulModProductLayoutCall09P120 a b)) **
      ((sp + signExtend12 (3968 : BitVec 12)) ↦ₘ (mulModProductLayoutCall12P128 a b)) **
      ((sp + signExtend12 (3976 : BitVec 12)) ↦ₘ (mulModProductLayoutCall14P136 a b)))
  have hCallF := cpsTripleWithin_frameR call15Frame (by pcFree) hCall
  have hComp := cpsTripleWithin_seq_perm_same_cr (fun _ hp => by xperm_hyp hp) hPrev hCallF
  rw [show base + 1700 + 60 = base + 1760 by bv_omega] at hComp
  dsimp [call15Frame] at hComp
  exact cpsTripleWithin_weaken
    (fun _ hp => by
      simpa using hp)
    (fun _ hq => by
      delta evmMulModProductLayoutZeroCall15Post evmMulModProductLayoutCall15Frame
      delta evmMulModAddPartialCorePost at hq
      simp only [signExtend12_0, signExtend12_8, signExtend12_16, signExtend12_24,
        signExtend12_32, signExtend12_40] at hq ⊢
      simp only [show signExtend12 (3936 : BitVec 12) = (18446744073709551456 : Word) by decide,
        show signExtend12 (3944 : BitVec 12) = (18446744073709551464 : Word) by decide,
        show signExtend12 (48 : BitVec 12) = (48 : Word) by decide,
        show signExtend12 (56 : BitVec 12) = (56 : Word) by decide,
        show signExtend12 (3952 : BitVec 12) = (18446744073709551472 : Word) by decide,
        show signExtend12 (3960 : BitVec 12) = (18446744073709551480 : Word) by decide,
        show signExtend12 (3968 : BitVec 12) = (18446744073709551488 : Word) by decide,
        show signExtend12 (3976 : BitVec 12) = (18446744073709551496 : Word) by decide,
        show signExtend12 (3984 : BitVec 12) = (18446744073709551504 : Word) by decide,
        show signExtend12 (3992 : BitVec 12) = (18446744073709551512 : Word) by decide] at ⊢
      rw [show signExtend12 (3936#12) = (18446744073709551456#64) by decide,
        show signExtend12 (3944#12) = (18446744073709551464#64) by decide,
        show signExtend12 (3952#12) = (18446744073709551472#64) by decide,
        show signExtend12 (3960#12) = (18446744073709551480#64) by decide,
        show signExtend12 (3968#12) = (18446744073709551488#64) by decide,
        show signExtend12 (3976#12) = (18446744073709551496#64) by decide,
        show signExtend12 (3984#12) = (18446744073709551504#64) by decide,
        show signExtend12 (3992#12) = (18446744073709551512#64) by decide] at hq
      rw [show sp + (0 : Word) = sp by bv_omega]
      simpa only [sepConj_assoc'] using hq)
    hComp

end EvmAsm.Evm64
