/-
  EvmAsm.Evm64.MulMod.ProductLayoutCall08

  Product-layout call08 suffix composition for MULMOD.
-/

import EvmAsm.Evm64.MulMod.ProductLayoutCall07

open EvmAsm.Rv64.Tactics

namespace EvmAsm.Evm64

open EvmAsm.Rv64

local macro "evm_mulmod_product_layout_slice_rfl" : tactic =>
  `(tactic|
    first
      | rfl
      | (unfold evm_mulmod_product_layout evm_mulmod_product_zero
            evm_mulmod_product_add_partial evm_mulmod_product_propagate_carry
            LD SD ADD SLTU OR' MUL MULHU single seq
         rfl))

/-- Core+finish code for layout call 08 is contained in `evm_mulmod_product_layout`. -/
theorem evm_mulmod_product_layout_call08_core_code_sub (base : Word) :
    ∀ a i, (evm_mulmod_product_add_partial_core_finish_code (base + 1056)
        (8 : BitVec 12) (48 : BitVec 12) (3960 : BitVec 12) (3968 : BitVec 12)) a = some i →
      (evm_mulmod_product_layout_code base) a = some i := by
  unfold evm_mulmod_product_add_partial_core_finish_code evm_mulmod_product_layout_code
  refine CodeReq.ofProg_mono_sub base (base + 1056) evm_mulmod_product_layout _ 264 ?_ ?_ ?_ ?_
  · bv_omega
  · evm_mulmod_product_layout_slice_rfl
  · rw [evm_mulmod_product_layout_length]
    decide
  · rw [evm_mulmod_product_layout_length]
    decide

/-- Carry-propagation code for layout call 08 is contained in `evm_mulmod_product_layout`. -/
theorem evm_mulmod_product_layout_call08_carry_code_sub (base : Word) :
    ∀ a i, (evm_mulmod_product_propagate_carry_code (base + 1116) [3976, 3984, 3992]) a = some i →
      (evm_mulmod_product_layout_code base) a = some i := by
  unfold evm_mulmod_product_propagate_carry_code evm_mulmod_product_layout_code
  refine CodeReq.ofProg_mono_sub base (base + 1116) evm_mulmod_product_layout _ 279 ?_ ?_ ?_ ?_
  · bv_omega
  · evm_mulmod_product_layout_slice_rfl
  · rw [evm_mulmod_product_layout_length]
    decide
  · rw [evm_mulmod_product_layout_length]
    decide

/-- Layout call 08 split code is contained in `evm_mulmod_product_layout`. -/
theorem evm_mulmod_product_layout_call08_code_sub (base : Word) :
    ∀ a i, ((evm_mulmod_product_add_partial_core_finish_code (base + 1056)
        (8 : BitVec 12) (48 : BitVec 12) (3960 : BitVec 12) (3968 : BitVec 12)).union
        (evm_mulmod_product_propagate_carry_code ((base + 1056) + 60) [3976, 3984, 3992])) a = some i →
      (evm_mulmod_product_layout_code base) a = some i :=
  CodeReq.union_sub (evm_mulmod_product_layout_call08_core_code_sub base)
    (by
      intro a i h
      apply evm_mulmod_product_layout_call08_carry_code_sub base
      rw [show (base + 1056) + 60 = base + 1116 by bv_omega] at h
      exact h)

/-- Layout call 08 spec lifted onto the local product-layout code requirement. -/
abbrev evm_mulmod_product_layout_call08_spec_within :=
  fun sp base a b lo hi p5 p6 p7 x5Old x6Old x7Old x8Old x9Old x10Old x11Old x13Old x14Old =>
    cpsTripleWithin_extend_code
      (h := evm_mulmod_product_add_partial_layout_call08_spec_within sp (base + 1056) a b lo hi p5 p6 p7 x5Old x6Old x7Old x8Old x9Old x10Old x11Old x13Old x14Old)
      (hmono := evm_mulmod_product_layout_call08_code_sub base)

/-- Product offset 120 after layout call07. -/
def mulModProductLayoutCall07P120 (a b : EvmWord) : Word :=
  mulModAddPartialLoValue (mulModProductLayoutCall06P120 a b) (a.getLimbN 2) (b.getLimbN 1)

/-- Product offset 128 after layout call07. -/
def mulModProductLayoutCall07P128 (a b : EvmWord) : Word :=
  mulModAddPartialHiValue (mulModProductLayoutCall06P128 a b)
    (mulModProductLayoutCall06P120 a b) (a.getLimbN 2) (b.getLimbN 1)

/-- Carry generated by layout call07 before propagating through offset 136. -/
def mulModProductLayoutCall07Carry128 (a b : EvmWord) : Word :=
  mulModAddPartialHiCarry (mulModProductLayoutCall06P128 a b)
    (mulModProductLayoutCall06P120 a b) (a.getLimbN 2) (b.getLimbN 1)

/-- Product offset 136 after layout call07. -/
def mulModProductLayoutCall07P136 (a b : EvmWord) : Word :=
  mulModCarryStepValue (mulModProductLayoutCall06P136 a b) (mulModProductLayoutCall07Carry128 a b)

/-- Carry after layout call07 propagates through offset 136. -/
def mulModProductLayoutCall07Carry136 (a b : EvmWord) : Word :=
  mulModCarryStepCarry (mulModProductLayoutCall06P136 a b) (mulModProductLayoutCall07Carry128 a b)

/-- Product offset 144 after layout call07. -/
def mulModProductLayoutCall07P144 (a b : EvmWord) : Word :=
  mulModCarryStepValue (mulModProductLayoutCall06P144 a b) (mulModProductLayoutCall07Carry136 a b)

/-- Carry after layout call07 propagates through offset 144. -/
def mulModProductLayoutCall07Carry144 (a b : EvmWord) : Word :=
  mulModCarryStepCarry (mulModProductLayoutCall06P144 a b) (mulModProductLayoutCall07Carry136 a b)

/-- Product offset 152 after layout call07. -/
def mulModProductLayoutCall07P152 (a b : EvmWord) : Word :=
  mulModCarryStepValue (mulModProductLayoutCall06P152 a b) (mulModProductLayoutCall07Carry144 a b)

/-- Carry after layout call07 propagates through offset 152. -/
def mulModProductLayoutCall07Carry152 (a b : EvmWord) : Word :=
  mulModCarryStepCarry (mulModProductLayoutCall06P152 a b) (mulModProductLayoutCall07Carry144 a b)

/-- Product-layout cells that layout call08 does not touch after call07. -/
@[irreducible]
def evmMulModProductLayoutCall08Frame (sp : Word) (a b n : EvmWord) : Assertion :=
  ((sp + signExtend12 (0 : BitVec 12)) ↦ₘ a.getLimbN 0) **
  ((sp + signExtend12 (16 : BitVec 12)) ↦ₘ a.getLimbN 2) **
  ((sp + signExtend12 (24 : BitVec 12)) ↦ₘ a.getLimbN 3) **
  ((sp + signExtend12 (32 : BitVec 12)) ↦ₘ b.getLimbN 0) **
  ((sp + signExtend12 (40 : BitVec 12)) ↦ₘ b.getLimbN 1) **
  ((sp + 56) ↦ₘ b.getLimbN 3) **
  ((sp + 64) ↦ₘ n.getLimbN 0) **
  ((sp + 72) ↦ₘ n.getLimbN 1) **
  ((sp + 80) ↦ₘ n.getLimbN 2) **
  ((sp + 88) ↦ₘ n.getLimbN 3) **
  ((sp + signExtend12 (3936 : BitVec 12)) ↦ₘ mulModProductLayoutCall00P96 a b) **
  ((sp + signExtend12 (3944 : BitVec 12)) ↦ₘ mulModProductLayoutCall02P104 a b) **
  ((sp + signExtend12 (3952 : BitVec 12)) ↦ₘ mulModProductLayoutCall05P112 a b)

/-- Folded post after zeroing and product-layout calls 00 through 08. -/
@[irreducible]
def evmMulModProductLayoutZeroCall08Post (sp : Word) (a b n : EvmWord) : Assertion :=
  (((.x12 ↦ᵣ sp) **
    (.x10 ↦ᵣ mulModCarryStepCarry (mulModProductLayoutCall07P152 a b)
      (mulModCarryStepCarry (mulModProductLayoutCall07P144 a b)
        (mulModCarryStepCarry (mulModProductLayoutCall07P136 a b)
          (mulModAddPartialHiCarry (mulModProductLayoutCall07P128 a b)
            (mulModProductLayoutCall07P120 a b) (a.getLimbN 1) (b.getLimbN 2))))) **
    (.x9 ↦ᵣ mulModCarryStepValue (mulModProductLayoutCall07P152 a b)
      (mulModCarryStepCarry (mulModProductLayoutCall07P144 a b)
        (mulModCarryStepCarry (mulModProductLayoutCall07P136 a b)
          (mulModAddPartialHiCarry (mulModProductLayoutCall07P128 a b)
            (mulModProductLayoutCall07P120 a b) (a.getLimbN 1) (b.getLimbN 2))))) **
    ((sp + signExtend12 (3976 : BitVec 12)) ↦ₘ mulModCarryStepValue (mulModProductLayoutCall07P136 a b)
      (mulModAddPartialHiCarry (mulModProductLayoutCall07P128 a b)
        (mulModProductLayoutCall07P120 a b) (a.getLimbN 1) (b.getLimbN 2))) **
    ((sp + signExtend12 (3984 : BitVec 12)) ↦ₘ mulModCarryStepValue (mulModProductLayoutCall07P144 a b)
      (mulModCarryStepCarry (mulModProductLayoutCall07P136 a b)
        (mulModAddPartialHiCarry (mulModProductLayoutCall07P128 a b)
          (mulModProductLayoutCall07P120 a b) (a.getLimbN 1) (b.getLimbN 2)))) **
    ((sp + signExtend12 (3992 : BitVec 12)) ↦ₘ mulModCarryStepValue (mulModProductLayoutCall07P152 a b)
      (mulModCarryStepCarry (mulModProductLayoutCall07P144 a b)
        (mulModCarryStepCarry (mulModProductLayoutCall07P136 a b)
          (mulModAddPartialHiCarry (mulModProductLayoutCall07P128 a b)
            (mulModProductLayoutCall07P120 a b) (a.getLimbN 1) (b.getLimbN 2))))) **
    (.x5 ↦ᵣ a.getLimbN 1) **
    (.x6 ↦ᵣ b.getLimbN 2) **
    (.x7 ↦ᵣ mulModAddPartialLoProduct (a.getLimbN 1) (b.getLimbN 2)) **
    (.x8 ↦ᵣ mulModAddPartialHiProduct (a.getLimbN 1) (b.getLimbN 2)) **
    (.x11 ↦ᵣ mulModAddPartialHiValue (mulModProductLayoutCall07P128 a b)
      (mulModProductLayoutCall07P120 a b) (a.getLimbN 1) (b.getLimbN 2)) **
    (.x13 ↦ᵣ mulModAddPartialHiBaseCarry (mulModProductLayoutCall07P128 a b)
      (a.getLimbN 1) (b.getLimbN 2)) **
    (.x14 ↦ᵣ mulModAddPartialHiCarryFromLo (mulModProductLayoutCall07P128 a b)
      (mulModProductLayoutCall07P120 a b) (a.getLimbN 1) (b.getLimbN 2)) **
    ((sp + signExtend12 (8 : BitVec 12)) ↦ₘ a.getLimbN 1) **
    ((sp + signExtend12 (48 : BitVec 12)) ↦ₘ b.getLimbN 2) **
    ((sp + signExtend12 (3960 : BitVec 12)) ↦ₘ mulModAddPartialLoValue (mulModProductLayoutCall07P120 a b)
      (a.getLimbN 1) (b.getLimbN 2)) **
    ((sp + signExtend12 (3968 : BitVec 12)) ↦ₘ mulModAddPartialHiValue (mulModProductLayoutCall07P128 a b)
      (mulModProductLayoutCall07P120 a b) (a.getLimbN 1) (b.getLimbN 2))) **
   evmMulModProductLayoutCall08Frame sp a b n)

/-- Product-layout prefix through call08. -/
theorem evm_mulmod_product_layout_zero_call08_spec_within
    (sp base : Word) (a b n : EvmWord)
    (p0 p1 p2 p3 p4 p5 p6 p7 : Word)
    (x5Old x6Old x7Old x8Old x9Old x10Old x11Old x13Old x14Old : Word) :
    cpsTripleWithin (((((((((8 + (15 + 24)) + (15 + 20)) + (15 + 20)) + (15 + 16)) + (15 + 16)) + (15 + 16)) + (15 + 12)) + (15 + 12)) + (15 + 12))
      base (base + 1164) (evm_mulmod_product_layout_code base)
      (evmMulModProductLayoutPre sp a b n p0 p1 p2 p3 p4 p5 p6 p7 **
       ((.x5 ↦ᵣ x5Old) ** (.x6 ↦ᵣ x6Old) ** (.x7 ↦ᵣ x7Old) ** (.x8 ↦ᵣ x8Old) **
        (.x9 ↦ᵣ x9Old) ** (.x10 ↦ᵣ x10Old) ** (.x11 ↦ᵣ x11Old) **
        (.x13 ↦ᵣ x13Old) ** (.x14 ↦ᵣ x14Old)))
      (evmMulModProductLayoutZeroCall08Post sp a b n) := by
  simp only [evmMulModProductLayoutPre_unfold]
  have hPrev := evm_mulmod_product_layout_zero_call07_spec_within sp base a b n
    p0 p1 p2 p3 p4 p5 p6 p7
    x5Old x6Old x7Old x8Old x9Old x10Old x11Old x13Old x14Old
  simp only [evmMulModProductLayoutPre_unfold] at hPrev
  unfold evmMulModProductLayoutZeroCall07Post evmMulModProductLayoutCall07Frame at hPrev
  simp only [signExtend12_0, signExtend12_8, signExtend12_16, signExtend12_24,
    signExtend12_32, signExtend12_40] at hPrev
  rw [show sp + (0 : Word) = sp by bv_omega] at hPrev
  rw [← mulModProductLayoutCall07P120, ← mulModProductLayoutCall07P128,
    ← mulModProductLayoutCall07Carry128, ← mulModProductLayoutCall07P136,
    ← mulModProductLayoutCall07Carry136, ← mulModProductLayoutCall07P144,
    ← mulModProductLayoutCall07Carry144, ← mulModProductLayoutCall07P152,
    ← mulModProductLayoutCall07Carry152] at hPrev
  have hCall := evm_mulmod_product_layout_call08_spec_within sp base
    (a.getLimbN 1) (b.getLimbN 2)
    (mulModProductLayoutCall07P120 a b) (mulModProductLayoutCall07P128 a b)
    (mulModProductLayoutCall07P136 a b) (mulModProductLayoutCall07P144 a b)
    (mulModProductLayoutCall07P152 a b)
    (a.getLimbN 2) (b.getLimbN 1)
    (mulModAddPartialLoProduct (a.getLimbN 2) (b.getLimbN 1))
    (mulModAddPartialHiProduct (a.getLimbN 2) (b.getLimbN 1))
    (mulModProductLayoutCall07P152 a b) (mulModProductLayoutCall07Carry152 a b)
    (mulModProductLayoutCall07P128 a b)
    (mulModAddPartialHiBaseCarry (mulModProductLayoutCall06P128 a b) (a.getLimbN 2) (b.getLimbN 1))
    (mulModAddPartialHiCarryFromLo (mulModProductLayoutCall06P128 a b)
      (mulModProductLayoutCall06P120 a b) (a.getLimbN 2) (b.getLimbN 1))
  unfold evmMulModAddPartialCoreFullPre at hCall
  simp only [signExtend12_8, show signExtend12 (48 : BitVec 12) = (48 : Word) by decide] at hCall
  let call08Frame : Assertion :=
    ((sp ↦ₘ a.getLimbN 0) **
      ((sp + 16) ↦ₘ a.getLimbN 2) **
      ((sp + 24) ↦ₘ a.getLimbN 3) **
      ((sp + 32) ↦ₘ b.getLimbN 0) **
      ((sp + 40) ↦ₘ b.getLimbN 1) **
      ((sp + 56) ↦ₘ b.getLimbN 3) **
      ((sp + 64) ↦ₘ n.getLimbN 0) **
      ((sp + 72) ↦ₘ n.getLimbN 1) **
      ((sp + 80) ↦ₘ n.getLimbN 2) **
      ((sp + 88) ↦ₘ n.getLimbN 3) **
      ((sp + signExtend12 (3936 : BitVec 12)) ↦ₘ (mulModProductLayoutCall00P96 a b)) **
      ((sp + signExtend12 (3944 : BitVec 12)) ↦ₘ (mulModProductLayoutCall02P104 a b)) **
      ((sp + signExtend12 (3952 : BitVec 12)) ↦ₘ (mulModProductLayoutCall05P112 a b)))
  have hCallF := cpsTripleWithin_frameR call08Frame (by pcFree) hCall
  have hComp := cpsTripleWithin_seq_perm_same_cr (fun _ hp => by xperm_hyp hp) hPrev hCallF
  rw [show base + 1056 + 60 + 48 = base + 1164 by bv_omega] at hComp
  dsimp [call08Frame] at hComp
  exact cpsTripleWithin_weaken
    (fun _ hp => by
      simpa using hp)
    (fun _ hq => by
      delta evmMulModProductLayoutZeroCall08Post evmMulModProductLayoutCall08Frame
      simp only [signExtend12_0, signExtend12_8, signExtend12_16, signExtend12_24,
        signExtend12_32, signExtend12_40] at hq ⊢
      simp only [show signExtend12 (3936 : BitVec 12) = (18446744073709551456 : Word) by decide,
        show signExtend12 (3944 : BitVec 12) = (18446744073709551464 : Word) by decide,
        show signExtend12 (3952 : BitVec 12) = (18446744073709551472 : Word) by decide,
        show signExtend12 (3960 : BitVec 12) = (18446744073709551480 : Word) by decide,
        show signExtend12 (3968 : BitVec 12) = (18446744073709551488 : Word) by decide,
        show signExtend12 (3976 : BitVec 12) = (18446744073709551496 : Word) by decide,
        show signExtend12 (3984 : BitVec 12) = (18446744073709551504 : Word) by decide,
        show signExtend12 (3992 : BitVec 12) = (18446744073709551512 : Word) by decide] at ⊢
      rw [show signExtend12 (3936#12) = (18446744073709551456#64) by decide,
        show signExtend12 (3944#12) = (18446744073709551464#64) by decide,
        show signExtend12 (3952#12) = (18446744073709551472#64) by decide,
        show signExtend12 (3960#12) = (18446744073709551480#64) by decide,
        show signExtend12 (3968#12) = (18446744073709551488#64) by decide,
        show signExtend12 (3976#12) = (18446744073709551496#64) by decide,
        show signExtend12 (3984#12) = (18446744073709551504#64) by decide,
        show signExtend12 (3992#12) = (18446744073709551512#64) by decide] at hq
      rw [show sp + (0 : Word) = sp by bv_omega]
      simpa only [sepConj_assoc'] using hq)
    hComp

end EvmAsm.Evm64
