/-
  EvmAsm.Evm64.MulMod.ProductLayoutCall05

  Final zero-through-call05 prefix composition for the MULMOD product layout,
  split out of ProductLayoutLifts to keep opcode proof files below the size cap.
-/

import EvmAsm.Evm64.MulMod.ProductLayoutLifts

open EvmAsm.Rv64.Tactics

namespace EvmAsm.Evm64

open EvmAsm.Rv64

/-- Product offset 112 after layout call04. -/
def mulModProductLayoutCall04P112 (a b : EvmWord) : Word :=
  mulModAddPartialLoValue (mulModProductLayoutCall03P112 a b) (a.getLimbN 1) (b.getLimbN 1)

/-- Product offset 120 after layout call04. -/
def mulModProductLayoutCall04P120 (a b : EvmWord) : Word :=
  mulModAddPartialHiValue (mulModProductLayoutCall03P120 a b)
    (mulModProductLayoutCall03P112 a b) (a.getLimbN 1) (b.getLimbN 1)

/-- Carry generated by layout call04 before propagating through offset 128. -/
def mulModProductLayoutCall04Carry120 (a b : EvmWord) : Word :=
  mulModAddPartialHiCarry (mulModProductLayoutCall03P120 a b)
    (mulModProductLayoutCall03P112 a b) (a.getLimbN 1) (b.getLimbN 1)

/-- Product offset 128 after layout call04. -/
def mulModProductLayoutCall04P128 (a b : EvmWord) : Word :=
  mulModCarryStepValue (mulModProductLayoutCall03P128 a b) (mulModProductLayoutCall04Carry120 a b)

/-- Carry after layout call04 propagates through offset 128. -/
def mulModProductLayoutCall04Carry128 (a b : EvmWord) : Word :=
  mulModCarryStepCarry (mulModProductLayoutCall03P128 a b) (mulModProductLayoutCall04Carry120 a b)

/-- Product offset 136 after layout call04. -/
def mulModProductLayoutCall04P136 (a b : EvmWord) : Word :=
  mulModCarryStepValue (mulModProductLayoutCall03P136 a b) (mulModProductLayoutCall04Carry128 a b)

/-- Carry after layout call04 propagates through offset 136. -/
def mulModProductLayoutCall04Carry136 (a b : EvmWord) : Word :=
  mulModCarryStepCarry (mulModProductLayoutCall03P136 a b) (mulModProductLayoutCall04Carry128 a b)

/-- Product offset 144 after layout call04. -/
def mulModProductLayoutCall04P144 (a b : EvmWord) : Word :=
  mulModCarryStepValue (mulModProductLayoutCall03P144 a b) (mulModProductLayoutCall04Carry136 a b)

/-- Carry after layout call04 propagates through offset 144. -/
def mulModProductLayoutCall04Carry144 (a b : EvmWord) : Word :=
  mulModCarryStepCarry (mulModProductLayoutCall03P144 a b) (mulModProductLayoutCall04Carry136 a b)

/-- Product offset 152 after layout call04. -/
def mulModProductLayoutCall04P152 (a b : EvmWord) : Word :=
  mulModCarryStepValue (mulModProductLayoutCall03P152 a b) (mulModProductLayoutCall04Carry144 a b)

/-- Carry after layout call04 propagates through offset 152. -/
def mulModProductLayoutCall04Carry152 (a b : EvmWord) : Word :=
  mulModCarryStepCarry (mulModProductLayoutCall03P152 a b) (mulModProductLayoutCall04Carry144 a b)

/-- Product-layout cells that layout call05 does not touch after call04. -/
@[irreducible]
def evmMulModProductLayoutCall05Frame (sp : Word) (a b n : EvmWord) : Assertion :=
  ((sp + signExtend12 (8 : BitVec 12)) ↦ₘ a.getLimbN 1) **
  ((sp + signExtend12 (16 : BitVec 12)) ↦ₘ a.getLimbN 2) **
  ((sp + 24) ↦ₘ a.getLimbN 3) **
  ((sp + signExtend12 (32 : BitVec 12)) ↦ₘ b.getLimbN 0) **
  ((sp + signExtend12 (40 : BitVec 12)) ↦ₘ b.getLimbN 1) **
  ((sp + 56) ↦ₘ b.getLimbN 3) **
  ((sp + 64) ↦ₘ n.getLimbN 0) **
  ((sp + 72) ↦ₘ n.getLimbN 1) **
  ((sp + 80) ↦ₘ n.getLimbN 2) **
  ((sp + 88) ↦ₘ n.getLimbN 3) **
  ((sp + signExtend12 (3936 : BitVec 12)) ↦ₘ mulModProductLayoutCall00P96 a b) **
  ((sp + signExtend12 (3944 : BitVec 12)) ↦ₘ mulModProductLayoutCall02P104 a b)

/-- Folded post after zeroing and product-layout calls 00 through 05. -/
@[irreducible]
def evmMulModProductLayoutZeroCall05Post (sp : Word) (a b n : EvmWord) : Assertion :=
  (((.x12 ↦ᵣ sp) **
    (.x10 ↦ᵣ mulModCarryStepCarry (mulModProductLayoutCall04P152 a b)
      (mulModCarryStepCarry (mulModProductLayoutCall04P144 a b)
        (mulModCarryStepCarry (mulModProductLayoutCall04P136 a b)
          (mulModCarryStepCarry (mulModProductLayoutCall04P128 a b)
            (mulModAddPartialHiCarry (mulModProductLayoutCall04P120 a b)
              (mulModProductLayoutCall04P112 a b) (a.getLimbN 0) (b.getLimbN 2)))))) **
    (.x9 ↦ᵣ mulModCarryStepValue (mulModProductLayoutCall04P152 a b)
      (mulModCarryStepCarry (mulModProductLayoutCall04P144 a b)
        (mulModCarryStepCarry (mulModProductLayoutCall04P136 a b)
          (mulModCarryStepCarry (mulModProductLayoutCall04P128 a b)
            (mulModAddPartialHiCarry (mulModProductLayoutCall04P120 a b)
              (mulModProductLayoutCall04P112 a b) (a.getLimbN 0) (b.getLimbN 2)))))) **
    ((sp + signExtend12 (3968 : BitVec 12)) ↦ₘ mulModCarryStepValue (mulModProductLayoutCall04P128 a b)
      (mulModAddPartialHiCarry (mulModProductLayoutCall04P120 a b)
        (mulModProductLayoutCall04P112 a b) (a.getLimbN 0) (b.getLimbN 2))) **
    ((sp + signExtend12 (3976 : BitVec 12)) ↦ₘ mulModCarryStepValue (mulModProductLayoutCall04P136 a b)
      (mulModCarryStepCarry (mulModProductLayoutCall04P128 a b)
        (mulModAddPartialHiCarry (mulModProductLayoutCall04P120 a b)
          (mulModProductLayoutCall04P112 a b) (a.getLimbN 0) (b.getLimbN 2)))) **
    ((sp + signExtend12 (3984 : BitVec 12)) ↦ₘ mulModCarryStepValue (mulModProductLayoutCall04P144 a b)
      (mulModCarryStepCarry (mulModProductLayoutCall04P136 a b)
        (mulModCarryStepCarry (mulModProductLayoutCall04P128 a b)
          (mulModAddPartialHiCarry (mulModProductLayoutCall04P120 a b)
            (mulModProductLayoutCall04P112 a b) (a.getLimbN 0) (b.getLimbN 2))))) **
    ((sp + signExtend12 (3992 : BitVec 12)) ↦ₘ mulModCarryStepValue (mulModProductLayoutCall04P152 a b)
      (mulModCarryStepCarry (mulModProductLayoutCall04P144 a b)
        (mulModCarryStepCarry (mulModProductLayoutCall04P136 a b)
          (mulModCarryStepCarry (mulModProductLayoutCall04P128 a b)
            (mulModAddPartialHiCarry (mulModProductLayoutCall04P120 a b)
              (mulModProductLayoutCall04P112 a b) (a.getLimbN 0) (b.getLimbN 2)))))) **
    (.x5 ↦ᵣ a.getLimbN 0) **
    (.x6 ↦ᵣ b.getLimbN 2) **
    (.x7 ↦ᵣ mulModAddPartialLoProduct (a.getLimbN 0) (b.getLimbN 2)) **
    (.x8 ↦ᵣ mulModAddPartialHiProduct (a.getLimbN 0) (b.getLimbN 2)) **
    (.x11 ↦ᵣ mulModAddPartialHiValue (mulModProductLayoutCall04P120 a b)
      (mulModProductLayoutCall04P112 a b) (a.getLimbN 0) (b.getLimbN 2)) **
    (.x13 ↦ᵣ mulModAddPartialHiBaseCarry (mulModProductLayoutCall04P120 a b)
      (a.getLimbN 0) (b.getLimbN 2)) **
    (.x14 ↦ᵣ mulModAddPartialHiCarryFromLo (mulModProductLayoutCall04P120 a b)
      (mulModProductLayoutCall04P112 a b) (a.getLimbN 0) (b.getLimbN 2)) **
    ((sp + signExtend12 (0 : BitVec 12)) ↦ₘ a.getLimbN 0) **
    ((sp + signExtend12 (48 : BitVec 12)) ↦ₘ b.getLimbN 2) **
    ((sp + signExtend12 (3952 : BitVec 12)) ↦ₘ mulModAddPartialLoValue (mulModProductLayoutCall04P112 a b)
      (a.getLimbN 0) (b.getLimbN 2)) **
    ((sp + signExtend12 (3960 : BitVec 12)) ↦ₘ mulModAddPartialHiValue (mulModProductLayoutCall04P120 a b)
      (mulModProductLayoutCall04P112 a b) (a.getLimbN 0) (b.getLimbN 2))) **
   evmMulModProductLayoutCall05Frame sp a b n)

/-- Product-layout prefix through call05. -/
theorem evm_mulmod_product_layout_zero_call05_spec_within
    (sp base : Word) (a b n : EvmWord)
    (p0 p1 p2 p3 p4 p5 p6 p7 : Word)
    (x5Old x6Old x7Old x8Old x9Old x10Old x11Old x13Old x14Old : Word) :
    cpsTripleWithin ((((((8 + (15 + 24)) + (15 + 20)) + (15 + 20)) + (15 + 16)) + (15 + 16)) + (15 + 16))
      base (base + 840) (evm_mulmod_product_layout_code base)
      (evmMulModProductLayoutPre sp a b n p0 p1 p2 p3 p4 p5 p6 p7 **
       ((.x5 ↦ᵣ x5Old) ** (.x6 ↦ᵣ x6Old) ** (.x7 ↦ᵣ x7Old) ** (.x8 ↦ᵣ x8Old) **
        (.x9 ↦ᵣ x9Old) ** (.x10 ↦ᵣ x10Old) ** (.x11 ↦ᵣ x11Old) **
        (.x13 ↦ᵣ x13Old) ** (.x14 ↦ᵣ x14Old)))
      (evmMulModProductLayoutZeroCall05Post sp a b n) := by
  simp only [evmMulModProductLayoutPre_unfold]
  have hPrev := evm_mulmod_product_layout_zero_call04_spec_within sp base a b n
    p0 p1 p2 p3 p4 p5 p6 p7
    x5Old x6Old x7Old x8Old x9Old x10Old x11Old x13Old x14Old
  simp only [evmMulModProductLayoutPre_unfold] at hPrev
  unfold evmMulModProductLayoutZeroCall04Post evmMulModProductLayoutCall04Frame at hPrev
  simp only [signExtend12_0, signExtend12_8, signExtend12_16, signExtend12_32, signExtend12_40] at hPrev
  rw [← mulModProductLayoutCall04P112, ← mulModProductLayoutCall04P120,
    ← mulModProductLayoutCall04Carry120, ← mulModProductLayoutCall04P128,
    ← mulModProductLayoutCall04Carry128, ← mulModProductLayoutCall04P136,
    ← mulModProductLayoutCall04Carry136, ← mulModProductLayoutCall04P144,
    ← mulModProductLayoutCall04Carry144, ← mulModProductLayoutCall04P152,
    ← mulModProductLayoutCall04Carry152] at hPrev
  have hCall := evm_mulmod_product_layout_call05_spec_within sp base
    (a.getLimbN 0) (b.getLimbN 2)
    (mulModProductLayoutCall04P112 a b) (mulModProductLayoutCall04P120 a b)
    (mulModProductLayoutCall04P128 a b) (mulModProductLayoutCall04P136 a b)
    (mulModProductLayoutCall04P144 a b) (mulModProductLayoutCall04P152 a b)
    (a.getLimbN 1) (b.getLimbN 1)
    (mulModAddPartialLoProduct (a.getLimbN 1) (b.getLimbN 1))
    (mulModAddPartialHiProduct (a.getLimbN 1) (b.getLimbN 1))
    (mulModProductLayoutCall04P152 a b) (mulModProductLayoutCall04Carry152 a b)
    (mulModProductLayoutCall04P120 a b)
    (mulModAddPartialHiBaseCarry (mulModProductLayoutCall03P120 a b) (a.getLimbN 1) (b.getLimbN 1))
    (mulModAddPartialHiCarryFromLo (mulModProductLayoutCall03P120 a b)
      (mulModProductLayoutCall03P112 a b) (a.getLimbN 1) (b.getLimbN 1))
  unfold evmMulModAddPartialCoreFullPre at hCall
  simp only [signExtend12_0, signExtend12_48] at hCall
  let call05Frame : Assertion :=
    (((sp + 8) ↦ₘ a.getLimbN 1) **
      ((sp + 16) ↦ₘ a.getLimbN 2) **
      ((sp + 24) ↦ₘ a.getLimbN 3) **
      ((sp + 32) ↦ₘ b.getLimbN 0) **
      ((sp + 40) ↦ₘ b.getLimbN 1) **
      ((sp + 56) ↦ₘ b.getLimbN 3) **
      ((sp + 64) ↦ₘ n.getLimbN 0) **
      ((sp + 72) ↦ₘ n.getLimbN 1) **
      ((sp + 80) ↦ₘ n.getLimbN 2) **
      ((sp + 88) ↦ₘ n.getLimbN 3) **
      ((sp + signExtend12 (3936 : BitVec 12)) ↦ₘ (mulModProductLayoutCall00P96 a b)) **
      ((sp + signExtend12 (3944 : BitVec 12)) ↦ₘ (mulModProductLayoutCall02P104 a b)))
  have hCallF := cpsTripleWithin_frameR call05Frame (by pcFree) hCall
  have hComp := cpsTripleWithin_seq_perm_same_cr (fun _ hp => by xperm_hyp hp) hPrev hCallF
  rw [show base + 716 + 60 + 64 = base + 840 by bv_omega] at hComp
  dsimp [call05Frame] at hComp
  exact cpsTripleWithin_weaken
    (fun _ hp => by
      simpa using hp)
    (fun _ hq => by
      delta evmMulModProductLayoutZeroCall05Post evmMulModProductLayoutCall05Frame
      simp only [signExtend12_0, signExtend12_8, signExtend12_16, signExtend12_32, signExtend12_40] at hq ⊢
      simp only [show signExtend12 (48 : BitVec 12) = (48 : Word) by decide,
        show signExtend12 (3936 : BitVec 12) = (18446744073709551456 : Word) by decide,
        show signExtend12 (3944 : BitVec 12) = (18446744073709551464 : Word) by decide,
        show signExtend12 (3952 : BitVec 12) = (18446744073709551472 : Word) by decide,
        show signExtend12 (3960 : BitVec 12) = (18446744073709551480 : Word) by decide,
        show signExtend12 (3968 : BitVec 12) = (18446744073709551488 : Word) by decide,
        show signExtend12 (3976 : BitVec 12) = (18446744073709551496 : Word) by decide,
        show signExtend12 (3984 : BitVec 12) = (18446744073709551504 : Word) by decide,
        show signExtend12 (3992 : BitVec 12) = (18446744073709551512 : Word) by decide] at ⊢
      rw [show signExtend12 (3936#12) = (18446744073709551456#64) by decide,
        show signExtend12 (3944#12) = (18446744073709551464#64) by decide,
        show signExtend12 (3952#12) = (18446744073709551472#64) by decide,
        show signExtend12 (3960#12) = (18446744073709551480#64) by decide,
        show signExtend12 (3968#12) = (18446744073709551488#64) by decide,
        show signExtend12 (3976#12) = (18446744073709551496#64) by decide,
        show signExtend12 (3984#12) = (18446744073709551504#64) by decide,
        show signExtend12 (3992#12) = (18446744073709551512#64) by decide] at hq
      rw [show sp + (0#64) = sp by bv_omega] at hq
      rw [show sp + (0 : Word) = sp by bv_omega]
      simpa only [sepConj_assoc'] using hq)
    hComp


end EvmAsm.Evm64
