#!/usr/bin/env python3
"""Generate EvmAsm/Progress/AxiomWitnesses.lean (GH #10601, GH #11042).

The module carries one `#print axioms` line per witness abbrev referenced from
a kernel-checked progress registry, so the axiom gate
(`scripts/check-axioms.sh`) can run under `lake build` instead of a
`lake env lean` scratch file: under the lake artifact cache, cache-satisfied
modules have no materialized `.olean` on disk and `lake env lean` cannot
resolve them (issue #10601, in the #10537 family).

Two registries are scanned (GH #11042):

  * `EvmAsm/Progress.lean`          — the `OpcodeEntry` registry (EVM opcodes)
  * `EvmAsm/Progress/Routines.lean` — the `RoutineEntry` registry (verified
                                      guest routines: `rlp_encode_uint_be`,
                                      `rlp_item_size`, the RLP walk chain, …)

⚠️ The name pattern is deliberately namespace-agnostic (`@EvmAsm.<anything>`).
It used to be `@EvmAsm\\.(?:Evm64|Stateless)…`, which matched **nothing** for
the guest surface: `reub_spec_within` is
`EvmAsm.Codegen.RlpEncodeUintBeSAsm.reub_spec_within`, and 289 modules live
under `EvmAsm.Rv64.*`. A witness abbrev outside those two namespaces was
silently dropped, so the gate stayed green while covering nothing — which is
worse than an honest absence, because "covered by CI" is the kind of
assumption nobody re-checks.

⭐ Hence the cross-check in `check_refs`: every theorem a registry row *names*
must have a matching witness abbrev in the same file. A row without one is a
row the axiom gate cannot see, and this script now fails loudly instead of
emitting a quietly-incomplete module. (That check found MCOPY: registered
`.proven` since the registry was introduced, theorem present, abbrev absent.)

Usage:
  python3 scripts/gen-axiom-witnesses.py           # print module to stdout
  python3 scripts/gen-axiom-witnesses.py --write   # overwrite the module

The gate regenerates to a temp file and diffs, so a stale module fails CI.
"""

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PROGRESS = ROOT / "EvmAsm" / "Progress.lean"
ROUTINES = ROOT / "EvmAsm" / "Progress" / "Routines.lean"
WITNESS = ROOT / "EvmAsm" / "Progress" / "AxiomWitnesses.lean"

# Registry sources, each paired with the Lean module that must be imported for
# its witnesses to resolve.
SOURCES = [
    (PROGRESS, "EvmAsm.Progress"),
    (ROUTINES, "EvmAsm.Progress.Routines"),
]

# Any `EvmAsm.*` witness abbrev target, in any namespace.  Narrowing the
# namespace is what caused the guest surface to be silently uncovered — see the
# module docstring.
#
# Anchored on the abbrev's `:=` rather than matching bare `@EvmAsm.…` anywhere:
# these registries discuss witness names in their own docstrings, and a prose
# mention would otherwise be emitted as a `#print axioms` line for a
# nonexistent declaration (an `@EvmAsm.Codegen.…` in prose yielded a stray
# `#print axioms EvmAsm.Codegen.`).  The `:=` also encodes the actual
# requirement: what puts a theorem in the gate is being *bound* by an abbrev.
NAME_RE = re.compile(r":=\s*(@EvmAsm\.[A-Za-z0-9_.']+)")

# A theorem named by a registry row: `(some "…")` for the positional
# `proofRef`, and `<field> := some "…"` for `coverRef` / named-argument forms.
REF_RE = re.compile(r'some "([A-Za-z0-9_.\']+)"')

HEADER = """\
/-
  Axiom witnesses for `scripts/check-axioms.sh` (GH #10601, GH #11042).

  GENERATED by `scripts/gen-axiom-witnesses.py` from the witness abbrevs
  referenced in `EvmAsm/Progress.lean` (the `OpcodeEntry` registry) and
  `EvmAsm/Progress/Routines.lean` (the `RoutineEntry` registry of verified
  guest routines) — do not edit by hand; regenerate with
  `python3 scripts/gen-axiom-witnesses.py --write`.  The gate regenerates and
  diffs, so a stale file fails CI.

  This module exists so the axiom gate runs under `lake build` instead of
  a `lake env lean` scratch file: under the lake artifact cache,
  cache-satisfied modules have no materialized `.olean` on disk and
  `lake env lean` cannot resolve them (issue #10601, in the #10537
  family).  Building this module prints one `#print axioms` report per
  registry witness into the build log; lake replays messages on
  repeat (fully cached) builds, so the gate stays meaningful in cache
  mode and pays zero re-elaboration.

  Coverage note (#11042): the guest-routine half is a **partial** enumeration
  of the verified guest surface, not a complete one.  `EvmAsm/**` carries on
  the order of 1800 distinct `*_spec_within` names, most of them block-level
  rather than whole-routine, so populating every one is not a single change.
  What is registered is witnessed; what is not registered is still outside the
  gate.  Stated here rather than left implicit, because the assumption this
  file exists to break is "covered by CI".
-/
"""


def witness_names(text: str) -> list[str]:
    """Witness abbrev targets bound in one registry source."""
    names = {n.lstrip("@") for n in NAME_RE.findall(text)}
    # A trailing dot means the match ran into prose, not a real declaration.
    # Refuse rather than emit a `#print axioms` line that cannot resolve.
    malformed = sorted(n for n in names if n.endswith(".") or ".." in n)
    if malformed:
        sys.exit(
            "malformed witness name(s) — these cannot be declarations:\n"
            + "".join(f"    {m}\n" for m in malformed)
        )
    return sorted(names)


def check_refs(path: Path, text: str, names: list[str]) -> list[str]:
    """Registry rows naming a theorem with no matching witness abbrev.

    A `proofRef` is written unqualified or partly qualified (`"ADD…"`,
    `"Env.evm_address_stack_spec_within"`) while the abbrev target is fully
    qualified, so the match is on dotted suffix.
    """
    refs = sorted(set(REF_RE.findall(text)))
    return [
        r for r in refs
        if not any(n == r or n.endswith("." + r) for n in names)
    ]


def collect() -> list[str]:
    """Union of witness names across registries, with the row cross-check."""
    all_names: list[str] = []
    problems: list[str] = []
    for path, _module in SOURCES:
        if not path.exists():
            sys.exit(f"missing registry source: {path.relative_to(ROOT)}")
        text = path.read_text()
        names = witness_names(text)
        if not names:
            sys.exit(f"no witness abbrevs found in {path.relative_to(ROOT)}")
        missing = check_refs(path, text, names)
        if missing:
            rel = path.relative_to(ROOT)
            problems.append(
                f"{rel}: {len(missing)} registry row(s) name a theorem with no "
                f"witness abbrev, so the axiom gate cannot see them:\n"
                + "".join(f"    {m}\n" for m in missing)
            )
        all_names.extend(names)
    if problems:
        sys.exit(
            "\n".join(problems)
            + "\nAdd a `private noncomputable abbrev _<name>_witness := "
            "@EvmAsm.…` for each, or drop the row.\n"
            "(Naming a theorem in a registry row does NOT put it in the gate — "
            "the abbrev is what does.)"
        )
    return sorted(set(all_names))


def render(names: list[str]) -> str:
    imports = "".join(f"import {module}\n" for _path, module in SOURCES)
    body = "".join(f"\n#print axioms {n}\n" for n in names)
    return HEADER + imports + body


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true",
                    help=f"overwrite {WITNESS.relative_to(ROOT)}")
    args = ap.parse_args()
    names = collect()
    text = render(names)
    if args.write:
        WITNESS.write_text(text)
        print(f"wrote {WITNESS.relative_to(ROOT)} "
              f"({len(names)} witnesses)")
    else:
        sys.stdout.write(text)


if __name__ == "__main__":
    main()
