#!/usr/bin/env python3
"""Generate EvmAsm/Progress/AxiomWitnesses.lean (GH #10601).

The module carries one `#print axioms` line per witness abbrev referenced
from the kernel-checked progress registry (`@EvmAsm.Evm64…` /
`@EvmAsm.Stateless…` names in `EvmAsm/Progress.lean`), so the axiom gate
(`scripts/check-axioms.sh`) can run under `lake build` instead of a
`lake env lean` scratch file: under the lake artifact cache, cache-satisfied
modules have no materialized `.olean` on disk and `lake env lean` cannot
resolve them (issue #10601, in the #10537 family).

Usage:
  python3 scripts/gen-axiom-witnesses.py           # print module to stdout
  python3 scripts/gen-axiom-witnesses.py --write   # overwrite the module

The gate regenerates to a temp file and diffs, so a stale module fails CI.
"""

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PROGRESS = ROOT / "EvmAsm" / "Progress.lean"
WITNESS = ROOT / "EvmAsm" / "Progress" / "AxiomWitnesses.lean"

NAME_RE = re.compile(r"@EvmAsm\.(?:Evm64|Stateless)[A-Za-z0-9_.']*")

HEADER = """\
/-
  Axiom witnesses for `scripts/check-axioms.sh` (GH #10601).

  GENERATED by `scripts/gen-axiom-witnesses.py` from the witness abbrevs
  referenced in `EvmAsm/Progress.lean` — do not edit by hand; regenerate
  with `python3 scripts/gen-axiom-witnesses.py --write`.  The gate
  regenerates and diffs, so a stale file fails CI.

  This module exists so the axiom gate runs under `lake build` instead of
  a `lake env lean` scratch file: under the lake artifact cache,
  cache-satisfied modules have no materialized `.olean` on disk and
  `lake env lean` cannot resolve them (issue #10601, in the #10537
  family).  Building this module prints one `#print axioms` report per
  Progress-registry witness into the build log; lake replays messages on
  repeat (fully cached) builds, so the gate stays meaningful in cache
  mode and pays zero re-elaboration.
-/
import EvmAsm.Progress
"""


def witness_names() -> list[str]:
    names = sorted(set(NAME_RE.findall(PROGRESS.read_text())))
    if not names:
        sys.exit(f"no witness abbrevs found in {PROGRESS}")
    return [n.lstrip("@") for n in names]


def render(names: list[str]) -> str:
    body = "".join(f"\n#print axioms {n}\n" for n in names)
    return HEADER + body


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true",
                    help=f"overwrite {WITNESS.relative_to(ROOT)}")
    args = ap.parse_args()
    names = witness_names()
    text = render(names)
    if args.write:
        WITNESS.write_text(text)
        print(f"wrote {WITNESS.relative_to(ROOT)} "
              f"({len(names)} witnesses)")
    else:
        sys.stdout.write(text)


if __name__ == "__main__":
    main()
