/-
  EvmAsm.Codegen.Programs.Bls12MapG2Real

  Extracted from `Bls12Map.lean` to keep every file under the
  `FileSizeGuard` line cap. Holds the real BLS12-381 map-Fp2-to-G2
  (0x11) kernel string (pure assembly text); assembled back into the
  map-precompile suite via `bls12MapKernelFunctions` in `Bls12Map.lean`.
-/

namespace EvmAsm.Codegen

/-- Real BLS12-381 map-Fp2-to-G2 (0x11) kernel: a0 = raw 128-byte wire
    Fp2 element (two padded felts c0 || c1), a1 = 192-byte compact BE
    G2 output. py_ecc optimized_swu_G2 + iso_map_G2 + clear_cofactor
    (h_eff_G2 scalar mul via the affine blsg2 ops). a0 = 0 ok / 1 bad. -/
def zkvmBls12MapFp2ToG2RealFunction : String :=
  ".globl zkvm_bls12_map_fp2_to_g2\n" ++
  "zkvm_bls12_map_fp2_to_g2:\n" ++
  "  addi sp, sp, -48\n" ++
  "  sd ra, 0(sp); sd s0, 8(sp); sd s1, 16(sp); sd s2, 24(sp); sd s3, 32(sp); sd s4, 40(sp)\n" ++
  "  mv s0, a0; mv s1, a1\n" ++
  "  addi a0, s0, 0\n" ++
  "  li a1, 16\n" ++
  "  jal ra, blsg_is_zero_n\n" ++
  "  beqz a0, .Lblm2_invalid\n" ++
  "  addi a0, s0, 16\n" ++
  "  jal ra, blsg_lt_p\n" ++
  "  beqz a0, .Lblm2_invalid\n" ++
  "  addi a0, s0, 16\n" ++
  "  la a1, blm2_t\n" ++
  "  jal ra, blsg_be_to_le\n" ++
  "  addi a0, s0, 64\n" ++
  "  li a1, 16\n" ++
  "  jal ra, blsg_is_zero_n\n" ++
  "  beqz a0, .Lblm2_invalid\n" ++
  "  addi a0, s0, 80\n" ++
  "  jal ra, blsg_lt_p\n" ++
  "  beqz a0, .Lblm2_invalid\n" ++
  "  addi a0, s0, 80\n" ++
  "  la a1, blm2_t\n" ++
  "  addi a1, a1, 48\n" ++
  "  jal ra, blsg_be_to_le\n" ++
  "  la a0, blm2_t\n" ++
  "  li a1, 48\n" ++
  "  jal ra, blsg_is_zero_n\n" ++
  "  la t0, blm2_t\n" ++
  "  ld t1, 0(t0)\n" ++
  "  andi t1, t1, 1\n" ++
  "  ld t2, 48(t0)\n" ++
  "  andi t2, t2, 1\n" ++
  "  and t2, t2, a0\n" ++
  "  or s4, t1, t2                  # s4 = sgn0(t)\n" ++
  "  la a0, blm2_t\n" ++
  "  la a1, blm2_t2\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  la a0, blm2_t2\n" ++
  "  la a1, blm2_t\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm_iso3_z\n" ++
  "  la a1, blm2_zt2\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  la a0, blm2_zt2\n" ++
  "  la a1, blm2_t2\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_zt2\n" ++
  "  la a1, blm2_tmp\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  la a0, blm2_tmp\n" ++
  "  la a1, blm2_zt2\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_tmp\n" ++
  "  la a1, blm2_zt2\n" ++
  "  jal ra, blsg2_fp2_add\n" ++
  "  la a0, blm_iso3_a\n" ++
  "  la a1, blm2_d\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  la a0, blm2_d\n" ++
  "  la a1, blm2_tmp\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_d\n" ++
  "  la a1, blsg2_pm1_le\n" ++
  "  la a2, blm2_d\n" ++
  "  jal ra, blsg2_fp_mul\n" ++
  "  la a0, blm2_d\n" ++
  "  addi a0, a0, 48\n" ++
  "  mv t6, a0\n" ++
  "  la a1, blsg2_pm1_le\n" ++
  "  mv a2, t6\n" ++
  "  jal ra, blsg2_fp_mul\n" ++
  "  la a0, blm2_tmp\n" ++
  "  la a1, blsf_le_one\n" ++
  "  la a2, blm2_tmp\n" ++
  "  jal ra, blsg2_fp_add\n" ++
  "  la a0, blm_iso3_b\n" ++
  "  la a1, blm2_n\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  la a0, blm2_n\n" ++
  "  la a1, blm2_tmp\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_d\n" ++
  "  li a1, 96\n" ++
  "  jal ra, blsg_is_zero_n\n" ++
  "  beqz a0, .Lblm2_d_ok\n" ++
  "  la a0, blm_iso3_z\n" ++
  "  la a1, blm2_d\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  la a0, blm2_d\n" ++
  "  la a1, blm_iso3_a\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  ".Lblm2_d_ok:\n" ++
  "  la a0, blm2_d\n" ++
  "  la a1, blm2_s1\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  la a0, blm2_s1\n" ++
  "  la a1, blm2_d\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_s1\n" ++
  "  la a1, blm2_v\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  la a0, blm2_v\n" ++
  "  la a1, blm2_d\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_n\n" ++
  "  la a1, blm2_u\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  la a0, blm2_u\n" ++
  "  la a1, blm2_n\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_u\n" ++
  "  la a1, blm2_n\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm_iso3_a\n" ++
  "  la a1, blm2_w\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  la a0, blm2_w\n" ++
  "  la a1, blm2_n\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_w\n" ++
  "  la a1, blm2_s1\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_u\n" ++
  "  la a1, blm2_w\n" ++
  "  jal ra, blsg2_fp2_add\n" ++
  "  la a0, blm_iso3_b\n" ++
  "  la a1, blm2_w\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  la a0, blm2_w\n" ++
  "  la a1, blm2_v\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_u\n" ++
  "  la a1, blm2_w\n" ++
  "  jal ra, blsg2_fp2_add\n" ++
  "  la a0, blm2_v\n" ++
  "  la a1, blm2_s1\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  la a0, blm2_s1\n" ++
  "  la a1, blm2_v\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_s1\n" ++
  "  la a1, blm2_s2\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  la a0, blm2_s2\n" ++
  "  la a1, blm2_s1\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_s2\n" ++
  "  la a1, blm2_w\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  la a0, blm2_w\n" ++
  "  la a1, blm2_s1\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_w\n" ++
  "  la a1, blm2_v\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_u\n" ++
  "  la a1, blm2_cand\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  la a0, blm2_cand\n" ++
  "  la a1, blm2_w\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_w\n" ++
  "  la a1, blm2_v\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_cand\n" ++
  "  la a1, blm2_s2\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  la a0, blm2_s2\n" ++
  "  la a1, blm2_w\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_g\n" ++
  "  la a1, blm2_s2\n" ++
  "  la a2, blm_pm9d16\n" ++
  "  li a3, 757\n" ++
  "  jal ra, blm_fp2_pow\n" ++
  "  la a0, blm2_g\n" ++
  "  la a1, blm2_cand\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_g\n" ++
  "  la a1, blm2_r\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  li s2, 0                       # success\n" ++
  "  la a0, blm_root8_0\n" ++
  "  la a1, blm2_s1\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  la a0, blm2_s1\n" ++
  "  la a1, blm2_g\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_s1\n" ++
  "  la a1, blm2_chk\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  la a0, blm2_chk\n" ++
  "  la a1, blm2_s1\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_chk\n" ++
  "  la a1, blm2_v\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_chk\n" ++
  "  la a1, blm2_u\n" ++
  "  jal ra, blsg2_fp2_sub\n" ++
  "  la a0, blm2_chk\n" ++
  "  li a1, 96\n" ++
  "  jal ra, blsg_is_zero_n\n" ++
  "  beqz a0, .Lblm2_r8_0\n" ++
  "  bnez s2, .Lblm2_r8_0\n" ++
  "  li s2, 1\n" ++
  "  la a0, blm2_s1\n" ++
  "  la a1, blm2_r\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  ".Lblm2_r8_0:\n" ++
  "  la a0, blm_root8_1\n" ++
  "  la a1, blm2_s1\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  la a0, blm2_s1\n" ++
  "  la a1, blm2_g\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_s1\n" ++
  "  la a1, blm2_chk\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  la a0, blm2_chk\n" ++
  "  la a1, blm2_s1\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_chk\n" ++
  "  la a1, blm2_v\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_chk\n" ++
  "  la a1, blm2_u\n" ++
  "  jal ra, blsg2_fp2_sub\n" ++
  "  la a0, blm2_chk\n" ++
  "  li a1, 96\n" ++
  "  jal ra, blsg_is_zero_n\n" ++
  "  beqz a0, .Lblm2_r8_1\n" ++
  "  bnez s2, .Lblm2_r8_1\n" ++
  "  li s2, 1\n" ++
  "  la a0, blm2_s1\n" ++
  "  la a1, blm2_r\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  ".Lblm2_r8_1:\n" ++
  "  la a0, blm_root8_2\n" ++
  "  la a1, blm2_s1\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  la a0, blm2_s1\n" ++
  "  la a1, blm2_g\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_s1\n" ++
  "  la a1, blm2_chk\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  la a0, blm2_chk\n" ++
  "  la a1, blm2_s1\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_chk\n" ++
  "  la a1, blm2_v\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_chk\n" ++
  "  la a1, blm2_u\n" ++
  "  jal ra, blsg2_fp2_sub\n" ++
  "  la a0, blm2_chk\n" ++
  "  li a1, 96\n" ++
  "  jal ra, blsg_is_zero_n\n" ++
  "  beqz a0, .Lblm2_r8_2\n" ++
  "  bnez s2, .Lblm2_r8_2\n" ++
  "  li s2, 1\n" ++
  "  la a0, blm2_s1\n" ++
  "  la a1, blm2_r\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  ".Lblm2_r8_2:\n" ++
  "  la a0, blm_root8_3\n" ++
  "  la a1, blm2_s1\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  la a0, blm2_s1\n" ++
  "  la a1, blm2_g\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_s1\n" ++
  "  la a1, blm2_chk\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  la a0, blm2_chk\n" ++
  "  la a1, blm2_s1\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_chk\n" ++
  "  la a1, blm2_v\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_chk\n" ++
  "  la a1, blm2_u\n" ++
  "  jal ra, blsg2_fp2_sub\n" ++
  "  la a0, blm2_chk\n" ++
  "  li a1, 96\n" ++
  "  jal ra, blsg_is_zero_n\n" ++
  "  beqz a0, .Lblm2_r8_3\n" ++
  "  bnez s2, .Lblm2_r8_3\n" ++
  "  li s2, 1\n" ++
  "  la a0, blm2_s1\n" ++
  "  la a1, blm2_r\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  ".Lblm2_r8_3:\n" ++
  "  la a0, blm2_t2\n" ++
  "  la a1, blm2_s1\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  la a0, blm2_s1\n" ++
  "  la a1, blm2_t\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_r\n" ++
  "  la a1, blm2_cand\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  la a0, blm2_cand\n" ++
  "  la a1, blm2_s1\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_zt2\n" ++
  "  la a1, blm2_s1\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  la a0, blm2_s1\n" ++
  "  la a1, blm2_zt2\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_s1\n" ++
  "  la a1, blm2_zt2\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_s1\n" ++
  "  la a1, blm2_u\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  li s3, 0                       # success_2\n" ++
  "  la a0, blm2_r\n" ++
  "  la a1, blm2_y\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  la a0, blm_eta_0\n" ++
  "  la a1, blm2_s2\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  la a0, blm2_s2\n" ++
  "  la a1, blm2_cand\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_s2\n" ++
  "  la a1, blm2_chk\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  la a0, blm2_chk\n" ++
  "  la a1, blm2_s2\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_chk\n" ++
  "  la a1, blm2_v\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_chk\n" ++
  "  la a1, blm2_s1\n" ++
  "  jal ra, blsg2_fp2_sub\n" ++
  "  la a0, blm2_chk\n" ++
  "  li a1, 96\n" ++
  "  jal ra, blsg_is_zero_n\n" ++
  "  beqz a0, .Lblm2_eta_0\n" ++
  "  bnez s2, .Lblm2_eta_0\n" ++
  "  bnez s3, .Lblm2_eta_0\n" ++
  "  li s3, 1\n" ++
  "  la a0, blm2_s2\n" ++
  "  la a1, blm2_y\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  ".Lblm2_eta_0:\n" ++
  "  la a0, blm_eta_1\n" ++
  "  la a1, blm2_s2\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  la a0, blm2_s2\n" ++
  "  la a1, blm2_cand\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_s2\n" ++
  "  la a1, blm2_chk\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  la a0, blm2_chk\n" ++
  "  la a1, blm2_s2\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_chk\n" ++
  "  la a1, blm2_v\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_chk\n" ++
  "  la a1, blm2_s1\n" ++
  "  jal ra, blsg2_fp2_sub\n" ++
  "  la a0, blm2_chk\n" ++
  "  li a1, 96\n" ++
  "  jal ra, blsg_is_zero_n\n" ++
  "  beqz a0, .Lblm2_eta_1\n" ++
  "  bnez s2, .Lblm2_eta_1\n" ++
  "  bnez s3, .Lblm2_eta_1\n" ++
  "  li s3, 1\n" ++
  "  la a0, blm2_s2\n" ++
  "  la a1, blm2_y\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  ".Lblm2_eta_1:\n" ++
  "  la a0, blm_eta_2\n" ++
  "  la a1, blm2_s2\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  la a0, blm2_s2\n" ++
  "  la a1, blm2_cand\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_s2\n" ++
  "  la a1, blm2_chk\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  la a0, blm2_chk\n" ++
  "  la a1, blm2_s2\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_chk\n" ++
  "  la a1, blm2_v\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_chk\n" ++
  "  la a1, blm2_s1\n" ++
  "  jal ra, blsg2_fp2_sub\n" ++
  "  la a0, blm2_chk\n" ++
  "  li a1, 96\n" ++
  "  jal ra, blsg_is_zero_n\n" ++
  "  beqz a0, .Lblm2_eta_2\n" ++
  "  bnez s2, .Lblm2_eta_2\n" ++
  "  bnez s3, .Lblm2_eta_2\n" ++
  "  li s3, 1\n" ++
  "  la a0, blm2_s2\n" ++
  "  la a1, blm2_y\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  ".Lblm2_eta_2:\n" ++
  "  la a0, blm_eta_3\n" ++
  "  la a1, blm2_s2\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  la a0, blm2_s2\n" ++
  "  la a1, blm2_cand\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_s2\n" ++
  "  la a1, blm2_chk\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  la a0, blm2_chk\n" ++
  "  la a1, blm2_s2\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_chk\n" ++
  "  la a1, blm2_v\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_chk\n" ++
  "  la a1, blm2_s1\n" ++
  "  jal ra, blsg2_fp2_sub\n" ++
  "  la a0, blm2_chk\n" ++
  "  li a1, 96\n" ++
  "  jal ra, blsg_is_zero_n\n" ++
  "  beqz a0, .Lblm2_eta_3\n" ++
  "  bnez s2, .Lblm2_eta_3\n" ++
  "  bnez s3, .Lblm2_eta_3\n" ++
  "  li s3, 1\n" ++
  "  la a0, blm2_s2\n" ++
  "  la a1, blm2_y\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  ".Lblm2_eta_3:\n" ++
  "  or t0, s2, s3\n" ++
  "  beqz t0, .Lblm2_invalid        # unreachable per RFC 9380\n" ++
  "  bnez s2, .Lblm2_n_ok\n" ++
  "  la a0, blm2_n\n" ++
  "  la a1, blm2_zt2\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  ".Lblm2_n_ok:\n" ++
  "  la a0, blm2_y\n" ++
  "  li a1, 48\n" ++
  "  jal ra, blsg_is_zero_n\n" ++
  "  la t0, blm2_y\n" ++
  "  ld t1, 0(t0)\n" ++
  "  andi t1, t1, 1\n" ++
  "  ld t2, 48(t0)\n" ++
  "  andi t2, t2, 1\n" ++
  "  and t2, t2, a0\n" ++
  "  or t1, t1, t2\n" ++
  "  beq t1, s4, .Lblm2_sgn_ok\n" ++
  "  la a0, blm2_y\n" ++
  "  la a1, blsg2_pm1_le\n" ++
  "  la a2, blm2_y\n" ++
  "  jal ra, blsg2_fp_mul\n" ++
  "  la a0, blm2_y\n" ++
  "  addi a0, a0, 48\n" ++
  "  mv t6, a0\n" ++
  "  la a1, blsg2_pm1_le\n" ++
  "  mv a2, t6\n" ++
  "  jal ra, blsg2_fp_mul\n" ++
  ".Lblm2_sgn_ok:\n" ++
  "  la a0, blm2_y\n" ++
  "  la a1, blm2_d\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_d\n" ++
  "  la a1, blm2_zp1\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  la a0, blm2_zp1\n" ++
  "  la a1, blm2_zp2\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  la a0, blm2_zp2\n" ++
  "  la a1, blm2_d\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_zp2\n" ++
  "  la a1, blm2_zp3\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  la a0, blm2_zp3\n" ++
  "  la a1, blm2_d\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm_k3_0_3\n" ++
  "  la a1, blm2_m0\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  la a0, blm2_m0\n" ++
  "  la a1, blm2_n\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_zp1\n" ++
  "  la a1, blm2_s1\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  la a0, blm2_s1\n" ++
  "  la a1, blm_k3_0_2\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_m0\n" ++
  "  la a1, blm2_s1\n" ++
  "  jal ra, blsg2_fp2_add\n" ++
  "  la a0, blm2_m0\n" ++
  "  la a1, blm2_n\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_zp2\n" ++
  "  la a1, blm2_s1\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  la a0, blm2_s1\n" ++
  "  la a1, blm_k3_0_1\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_m0\n" ++
  "  la a1, blm2_s1\n" ++
  "  jal ra, blsg2_fp2_add\n" ++
  "  la a0, blm2_m0\n" ++
  "  la a1, blm2_n\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_zp3\n" ++
  "  la a1, blm2_s1\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  la a0, blm2_s1\n" ++
  "  la a1, blm_k3_0_0\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_m0\n" ++
  "  la a1, blm2_s1\n" ++
  "  jal ra, blsg2_fp2_add\n" ++
  "  la a0, blm_k3_1_3\n" ++
  "  la a1, blm2_m1\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  la a0, blm2_m1\n" ++
  "  la a1, blm2_n\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_zp1\n" ++
  "  la a1, blm2_s1\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  la a0, blm2_s1\n" ++
  "  la a1, blm_k3_1_2\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_m1\n" ++
  "  la a1, blm2_s1\n" ++
  "  jal ra, blsg2_fp2_add\n" ++
  "  la a0, blm2_m1\n" ++
  "  la a1, blm2_n\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_zp2\n" ++
  "  la a1, blm2_s1\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  la a0, blm2_s1\n" ++
  "  la a1, blm_k3_1_1\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_m1\n" ++
  "  la a1, blm2_s1\n" ++
  "  jal ra, blsg2_fp2_add\n" ++
  "  la a0, blm2_m1\n" ++
  "  la a1, blm2_n\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_zp3\n" ++
  "  la a1, blm2_s1\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  la a0, blm2_s1\n" ++
  "  la a1, blm_k3_1_0\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_m1\n" ++
  "  la a1, blm2_s1\n" ++
  "  jal ra, blsg2_fp2_add\n" ++
  "  la a0, blm_k3_2_3\n" ++
  "  la a1, blm2_m2\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  la a0, blm2_m2\n" ++
  "  la a1, blm2_n\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_zp1\n" ++
  "  la a1, blm2_s1\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  la a0, blm2_s1\n" ++
  "  la a1, blm_k3_2_2\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_m2\n" ++
  "  la a1, blm2_s1\n" ++
  "  jal ra, blsg2_fp2_add\n" ++
  "  la a0, blm2_m2\n" ++
  "  la a1, blm2_n\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_zp2\n" ++
  "  la a1, blm2_s1\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  la a0, blm2_s1\n" ++
  "  la a1, blm_k3_2_1\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_m2\n" ++
  "  la a1, blm2_s1\n" ++
  "  jal ra, blsg2_fp2_add\n" ++
  "  la a0, blm2_m2\n" ++
  "  la a1, blm2_n\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_zp3\n" ++
  "  la a1, blm2_s1\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  la a0, blm2_s1\n" ++
  "  la a1, blm_k3_2_0\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_m2\n" ++
  "  la a1, blm2_s1\n" ++
  "  jal ra, blsg2_fp2_add\n" ++
  "  la a0, blm_k3_3_3\n" ++
  "  la a1, blm2_m3\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  la a0, blm2_m3\n" ++
  "  la a1, blm2_n\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_zp1\n" ++
  "  la a1, blm2_s1\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  la a0, blm2_s1\n" ++
  "  la a1, blm_k3_3_2\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_m3\n" ++
  "  la a1, blm2_s1\n" ++
  "  jal ra, blsg2_fp2_add\n" ++
  "  la a0, blm2_m3\n" ++
  "  la a1, blm2_n\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_zp2\n" ++
  "  la a1, blm2_s1\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  la a0, blm2_s1\n" ++
  "  la a1, blm_k3_3_1\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_m3\n" ++
  "  la a1, blm2_s1\n" ++
  "  jal ra, blsg2_fp2_add\n" ++
  "  la a0, blm2_m3\n" ++
  "  la a1, blm2_n\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_zp3\n" ++
  "  la a1, blm2_s1\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  la a0, blm2_s1\n" ++
  "  la a1, blm_k3_3_0\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_m3\n" ++
  "  la a1, blm2_s1\n" ++
  "  jal ra, blsg2_fp2_add\n" ++
  "  la a0, blm2_m2\n" ++
  "  la a1, blm2_y\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_m3\n" ++
  "  la a1, blm2_d\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_m1\n" ++
  "  la a1, blm2_zg\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  la a0, blm2_zg\n" ++
  "  la a1, blm2_m3\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_m0\n" ++
  "  la a1, blm2_xg\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  la a0, blm2_xg\n" ++
  "  la a1, blm2_m3\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_m1\n" ++
  "  la a1, blm2_yg\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  la a0, blm2_yg\n" ++
  "  la a1, blm2_m2\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_zg\n" ++
  "  li a1, 96\n" ++
  "  jal ra, blsg_is_zero_n\n" ++
  "  beqz a0, .Lblm2_fin\n" ++
  "  mv a0, s1\n" ++
  "  jal ra, blsg2_zero192          # infinity output\n" ++
  "  j .Lblm2_ok\n" ++
  ".Lblm2_fin:\n" ++
  "  la a0, blm2_zg\n" ++
  "  la a1, blm2_zinv\n" ++
  "  jal ra, blsg2_fp2_inv\n" ++
  "  la a0, blm2_xg\n" ++
  "  la a1, blm2_zinv\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_yg\n" ++
  "  la a1, blm2_zinv\n" ++
  "  jal ra, blsg2_fp2_mul\n" ++
  "  la a0, blm2_xg\n" ++
  "  la a1, blm2_aff\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  la a0, blm2_yg\n" ++
  "  la a1, blm2_aff\n" ++
  "  addi a1, a1, 96\n" ++
  "  li a2, 12\n" ++
  "  jal ra, blsf_copy_quads\n" ++
  "  la a0, blm_heff_g2_be\n" ++
  "  li a1, 80\n" ++
  "  la a2, blm2_aff\n" ++
  "  la a3, blm2_res\n" ++
  "  jal ra, blsg2_scalar_mul\n" ++
  "  la a0, blm2_res\n" ++
  "  mv a1, s1\n" ++
  "  jal ra, blsg2_encode\n" ++
  ".Lblm2_ok:\n" ++
  "  li a0, 0\n" ++
  "  j .Lblm2_ret\n" ++
  ".Lblm2_invalid:\n" ++
  "  li a0, 1\n" ++
  ".Lblm2_ret:\n" ++
  "  ld ra, 0(sp); ld s0, 8(sp); ld s1, 16(sp); ld s2, 24(sp); ld s3, 32(sp); ld s4, 40(sp)\n" ++
  "  addi sp, sp, 48\n" ++
  "  ret"

end EvmAsm.Codegen
