/-
  EvmAsm.Codegen.Programs.Bls12MapG1Real

  Extracted from `Bls12Map.lean` to keep every file under the
  `FileSizeGuard` line cap. Holds the real BLS12-381 map-Fp-to-G1
  (0x10) kernel string (pure assembly text); assembled back into the
  map-precompile suite via `bls12MapKernelFunctions` in `Bls12Map.lean`.
-/

namespace EvmAsm.Codegen

/-- Real BLS12-381 map-Fp-to-G1 (0x10) kernel: a0 = raw 64-byte wire
    field element (16-byte zero pad + 48-byte BE value < p), a1 =
    96-byte compact BE G1 output. py_ecc optimized_swu_G1 +
    iso_map_G1 + clear_cofactor (h_eff scalar mul via the accelerated
    G1 ops). Returns a0 = 0 ok, 1 invalid encoding. -/
def zkvmBls12MapFpToG1RealFunction : String :=
  ".globl zkvm_bls12_map_fp_to_g1\n" ++
  "zkvm_bls12_map_fp_to_g1:\n" ++
  "  addi sp, sp, -32
  sd ra, 0(sp); sd s0, 8(sp); sd s1, 16(sp); sd s2, 24(sp)
  mv s0, a0; mv s1, a1
  mv a0, s0
  li a1, 16
  jal ra, blsg_is_zero_n
  beqz a0, .Lblm1_invalid
  addi a0, s0, 16
  jal ra, blsg_lt_p
  beqz a0, .Lblm1_invalid
  addi a0, s0, 16
  la a1, blm_t
  jal ra, blsg_be_to_le
  la a0, blm_t
  la a1, blm_t
  la a2, blm_t2
  jal ra, blsg2_fp_mul
  la a0, blm_iso11_z
  la a1, blm_t2
  la a2, blm_zt2
  jal ra, blsg2_fp_mul
  la a0, blm_zt2
  la a1, blm_zt2
  la a2, blm_tmp
  jal ra, blsg2_fp_mul
  la a0, blm_tmp
  la a1, blm_zt2
  la a2, blm_tmp
  jal ra, blsg2_fp_add
  la a0, blm_iso11_a
  la a1, blm_tmp
  la a2, blm_d
  jal ra, blsg2_fp_mul
  la a0, blm_d
  la a1, blsg2_pm1_le
  la a2, blm_d
  jal ra, blsg2_fp_mul
  la a0, blm_tmp
  la a1, blsf_le_one
  la a2, blm_tmp
  jal ra, blsg2_fp_add
  la a0, blm_iso11_b
  la a1, blm_tmp
  la a2, blm_n
  jal ra, blsg2_fp_mul
  la a0, blm_d
  li a1, 48
  jal ra, blsg_is_zero_n
  beqz a0, .Lblm1_d_ok
  la a0, blm_iso11_z
  la a1, blm_iso11_a
  la a2, blm_d
  jal ra, blsg2_fp_mul
" ++
  ".Lblm1_d_ok:\n" ++
  "  la a0, blm_d
  la a1, blm_d
  la a2, blm_s1
  jal ra, blsg2_fp_mul
  la a0, blm_s1
  la a1, blm_d
  la a2, blm_v
  jal ra, blsg2_fp_mul
  la a0, blm_n
  la a1, blm_n
  la a2, blm_u
  jal ra, blsg2_fp_mul
  la a0, blm_u
  la a1, blm_n
  la a2, blm_u
  jal ra, blsg2_fp_mul
  la a0, blm_iso11_a
  la a1, blm_n
  la a2, blm_w
  jal ra, blsg2_fp_mul
  la a0, blm_w
  la a1, blm_s1
  la a2, blm_w
  jal ra, blsg2_fp_mul
  la a0, blm_u
  la a1, blm_w
  la a2, blm_u
  jal ra, blsg2_fp_add
  la a0, blm_iso11_b
  la a1, blm_v
  la a2, blm_w
  jal ra, blsg2_fp_mul
  la a0, blm_u
  la a1, blm_w
  la a2, blm_u
  jal ra, blsg2_fp_add
  la a0, blm_u
  la a1, blm_v
  la a2, blm_w
  jal ra, blsg2_fp_mul
  la a0, blm_v
  la a1, blm_v
  la a2, blm_s1
  jal ra, blsg2_fp_mul
  la a0, blm_w
  la a1, blm_s1
  la a2, blm_s1
  jal ra, blsg2_fp_mul
  la a0, blm_r
  la a1, blm_s1
  la a2, blm_pm3d4
  li a3, 378
  jal ra, blm_fp_pow
  la a0, blm_w
  la a1, blm_r
  la a2, blm_r
  jal ra, blsg2_fp_mul
  la a0, blm_r
  la a1, blm_r
  la a2, blm_chk
  jal ra, blsg2_fp_mul
  la a0, blm_chk
  la a1, blm_v
  la a2, blm_chk
  jal ra, blsg2_fp_mul
  la a0, blm_chk
  la a1, blm_u
  li a2, 48
  jal ra, blsg2_eq_n
  bnez a0, .Lblm1_root_ok
  la a0, blm_t2
  la a1, blm_t
  la a2, blm_s1
  jal ra, blsg2_fp_mul
  la a0, blm_r
  la a1, blm_s1
  la a2, blm_y
  jal ra, blsg2_fp_mul
  la a0, blm_y
  la a1, blm_sqrt_m11c
  la a2, blm_y
  jal ra, blsg2_fp_mul
  la a0, blm_n
  la a1, blm_zt2
  la a2, blm_n
  jal ra, blsg2_fp_mul
  j .Lblm1_have_y
" ++
  ".Lblm1_root_ok:\n" ++
  "  la a0, blm_r
  la a1, blm_y
  li a2, 6
  jal ra, blsf_copy_quads
" ++
  ".Lblm1_have_y:\n" ++
  "  la t0, blm_t
  ld t1, 0(t0)
  andi t1, t1, 1
  la t0, blm_y
  ld t2, 0(t0)
  andi t2, t2, 1
  beq t1, t2, .Lblm1_sgn_ok
  la a0, blm_y
  la a1, blsg2_pm1_le
  la a2, blm_y
  jal ra, blsg2_fp_mul
" ++
  ".Lblm1_sgn_ok:\n" ++
  "  la a0, blm_y
  la a1, blm_d
  la a2, blm_y
  jal ra, blsg2_fp_mul
  la a0, blm_d
  la a1, blm_zp0
  li a2, 6
  jal ra, blsf_copy_quads
  la a0, blm_zp0
  la a1, blm_d
  la a2, blm_zp1
  jal ra, blsg2_fp_mul
  la a0, blm_zp1
  la a1, blm_d
  la a2, blm_zp2
  jal ra, blsg2_fp_mul
  la a0, blm_zp2
  la a1, blm_d
  la a2, blm_zp3
  jal ra, blsg2_fp_mul
  la a0, blm_zp3
  la a1, blm_d
  la a2, blm_zp4
  jal ra, blsg2_fp_mul
  la a0, blm_zp4
  la a1, blm_d
  la a2, blm_zp5
  jal ra, blsg2_fp_mul
  la a0, blm_zp5
  la a1, blm_d
  la a2, blm_zp6
  jal ra, blsg2_fp_mul
  la a0, blm_zp6
  la a1, blm_d
  la a2, blm_zp7
  jal ra, blsg2_fp_mul
  la a0, blm_zp7
  la a1, blm_d
  la a2, blm_zp8
  jal ra, blsg2_fp_mul
  la a0, blm_zp8
  la a1, blm_d
  la a2, blm_zp9
  jal ra, blsg2_fp_mul
  la a0, blm_zp9
  la a1, blm_d
  la a2, blm_zp10
  jal ra, blsg2_fp_mul
  la a0, blm_zp10
  la a1, blm_d
  la a2, blm_zp11
  jal ra, blsg2_fp_mul
  la a0, blm_zp11
  la a1, blm_d
  la a2, blm_zp12
  jal ra, blsg2_fp_mul
  la a0, blm_zp12
  la a1, blm_d
  la a2, blm_zp13
  jal ra, blsg2_fp_mul
  la a0, blm_zp13
  la a1, blm_d
  la a2, blm_zp14
  jal ra, blsg2_fp_mul
  la a0, blm_k11_0_11
  la a1, blm_m0
  li a2, 6
  jal ra, blsf_copy_quads
  la a0, blm_m0
  la a1, blm_n
  la a2, blm_m0
  jal ra, blsg2_fp_mul
  la a0, blm_zp0
  la a1, blm_k11_0_10
  la a2, blm_s1
  jal ra, blsg2_fp_mul
  la a0, blm_m0
  la a1, blm_s1
  la a2, blm_m0
  jal ra, blsg2_fp_add
  la a0, blm_m0
  la a1, blm_n
  la a2, blm_m0
  jal ra, blsg2_fp_mul
  la a0, blm_zp1
  la a1, blm_k11_0_9
  la a2, blm_s1
  jal ra, blsg2_fp_mul
  la a0, blm_m0
  la a1, blm_s1
  la a2, blm_m0
  jal ra, blsg2_fp_add
  la a0, blm_m0
  la a1, blm_n
  la a2, blm_m0
  jal ra, blsg2_fp_mul
  la a0, blm_zp2
  la a1, blm_k11_0_8
  la a2, blm_s1
  jal ra, blsg2_fp_mul
  la a0, blm_m0
  la a1, blm_s1
  la a2, blm_m0
  jal ra, blsg2_fp_add
  la a0, blm_m0
  la a1, blm_n
  la a2, blm_m0
  jal ra, blsg2_fp_mul
  la a0, blm_zp3
  la a1, blm_k11_0_7
  la a2, blm_s1
  jal ra, blsg2_fp_mul
  la a0, blm_m0
  la a1, blm_s1
  la a2, blm_m0
  jal ra, blsg2_fp_add
  la a0, blm_m0
  la a1, blm_n
  la a2, blm_m0
  jal ra, blsg2_fp_mul
  la a0, blm_zp4
  la a1, blm_k11_0_6
  la a2, blm_s1
  jal ra, blsg2_fp_mul
  la a0, blm_m0
  la a1, blm_s1
  la a2, blm_m0
  jal ra, blsg2_fp_add
  la a0, blm_m0
  la a1, blm_n
  la a2, blm_m0
  jal ra, blsg2_fp_mul
  la a0, blm_zp5
  la a1, blm_k11_0_5
  la a2, blm_s1
  jal ra, blsg2_fp_mul
  la a0, blm_m0
  la a1, blm_s1
  la a2, blm_m0
  jal ra, blsg2_fp_add
  la a0, blm_m0
  la a1, blm_n
  la a2, blm_m0
  jal ra, blsg2_fp_mul
  la a0, blm_zp6
  la a1, blm_k11_0_4
  la a2, blm_s1
  jal ra, blsg2_fp_mul
  la a0, blm_m0
  la a1, blm_s1
  la a2, blm_m0
  jal ra, blsg2_fp_add
  la a0, blm_m0
  la a1, blm_n
  la a2, blm_m0
  jal ra, blsg2_fp_mul
  la a0, blm_zp7
  la a1, blm_k11_0_3
  la a2, blm_s1
  jal ra, blsg2_fp_mul
  la a0, blm_m0
  la a1, blm_s1
  la a2, blm_m0
  jal ra, blsg2_fp_add
  la a0, blm_m0
  la a1, blm_n
  la a2, blm_m0
  jal ra, blsg2_fp_mul
  la a0, blm_zp8
  la a1, blm_k11_0_2
  la a2, blm_s1
  jal ra, blsg2_fp_mul
  la a0, blm_m0
  la a1, blm_s1
  la a2, blm_m0
  jal ra, blsg2_fp_add
  la a0, blm_m0
  la a1, blm_n
  la a2, blm_m0
  jal ra, blsg2_fp_mul
  la a0, blm_zp9
  la a1, blm_k11_0_1
  la a2, blm_s1
  jal ra, blsg2_fp_mul
  la a0, blm_m0
  la a1, blm_s1
  la a2, blm_m0
  jal ra, blsg2_fp_add
  la a0, blm_m0
  la a1, blm_n
  la a2, blm_m0
  jal ra, blsg2_fp_mul
  la a0, blm_zp10
  la a1, blm_k11_0_0
  la a2, blm_s1
  jal ra, blsg2_fp_mul
  la a0, blm_m0
  la a1, blm_s1
  la a2, blm_m0
  jal ra, blsg2_fp_add
  la a0, blm_k11_1_10
  la a1, blm_m1
  li a2, 6
  jal ra, blsf_copy_quads
  la a0, blm_m1
  la a1, blm_n
  la a2, blm_m1
  jal ra, blsg2_fp_mul
  la a0, blm_zp0
  la a1, blm_k11_1_9
  la a2, blm_s1
  jal ra, blsg2_fp_mul
  la a0, blm_m1
  la a1, blm_s1
  la a2, blm_m1
  jal ra, blsg2_fp_add
  la a0, blm_m1
  la a1, blm_n
  la a2, blm_m1
  jal ra, blsg2_fp_mul
  la a0, blm_zp1
  la a1, blm_k11_1_8
  la a2, blm_s1
  jal ra, blsg2_fp_mul
  la a0, blm_m1
  la a1, blm_s1
  la a2, blm_m1
  jal ra, blsg2_fp_add
  la a0, blm_m1
  la a1, blm_n
  la a2, blm_m1
  jal ra, blsg2_fp_mul
  la a0, blm_zp2
  la a1, blm_k11_1_7
  la a2, blm_s1
  jal ra, blsg2_fp_mul
  la a0, blm_m1
  la a1, blm_s1
  la a2, blm_m1
  jal ra, blsg2_fp_add
  la a0, blm_m1
  la a1, blm_n
  la a2, blm_m1
  jal ra, blsg2_fp_mul
  la a0, blm_zp3
  la a1, blm_k11_1_6
  la a2, blm_s1
  jal ra, blsg2_fp_mul
  la a0, blm_m1
  la a1, blm_s1
  la a2, blm_m1
  jal ra, blsg2_fp_add
  la a0, blm_m1
  la a1, blm_n
  la a2, blm_m1
  jal ra, blsg2_fp_mul
  la a0, blm_zp4
  la a1, blm_k11_1_5
  la a2, blm_s1
  jal ra, blsg2_fp_mul
  la a0, blm_m1
  la a1, blm_s1
  la a2, blm_m1
  jal ra, blsg2_fp_add
  la a0, blm_m1
  la a1, blm_n
  la a2, blm_m1
  jal ra, blsg2_fp_mul
  la a0, blm_zp5
  la a1, blm_k11_1_4
  la a2, blm_s1
  jal ra, blsg2_fp_mul
  la a0, blm_m1
  la a1, blm_s1
  la a2, blm_m1
  jal ra, blsg2_fp_add
  la a0, blm_m1
  la a1, blm_n
  la a2, blm_m1
  jal ra, blsg2_fp_mul
  la a0, blm_zp6
  la a1, blm_k11_1_3
  la a2, blm_s1
  jal ra, blsg2_fp_mul
  la a0, blm_m1
  la a1, blm_s1
  la a2, blm_m1
  jal ra, blsg2_fp_add
  la a0, blm_m1
  la a1, blm_n
  la a2, blm_m1
  jal ra, blsg2_fp_mul
  la a0, blm_zp7
  la a1, blm_k11_1_2
  la a2, blm_s1
  jal ra, blsg2_fp_mul
  la a0, blm_m1
  la a1, blm_s1
  la a2, blm_m1
  jal ra, blsg2_fp_add
  la a0, blm_m1
  la a1, blm_n
  la a2, blm_m1
  jal ra, blsg2_fp_mul
  la a0, blm_zp8
  la a1, blm_k11_1_1
  la a2, blm_s1
  jal ra, blsg2_fp_mul
  la a0, blm_m1
  la a1, blm_s1
  la a2, blm_m1
  jal ra, blsg2_fp_add
  la a0, blm_m1
  la a1, blm_n
  la a2, blm_m1
  jal ra, blsg2_fp_mul
  la a0, blm_zp9
  la a1, blm_k11_1_0
  la a2, blm_s1
  jal ra, blsg2_fp_mul
  la a0, blm_m1
  la a1, blm_s1
  la a2, blm_m1
  jal ra, blsg2_fp_add
  la a0, blm_k11_2_15
  la a1, blm_m2
  li a2, 6
  jal ra, blsf_copy_quads
  la a0, blm_m2
  la a1, blm_n
  la a2, blm_m2
  jal ra, blsg2_fp_mul
  la a0, blm_zp0
  la a1, blm_k11_2_14
  la a2, blm_s1
  jal ra, blsg2_fp_mul
  la a0, blm_m2
  la a1, blm_s1
  la a2, blm_m2
  jal ra, blsg2_fp_add
  la a0, blm_m2
  la a1, blm_n
  la a2, blm_m2
  jal ra, blsg2_fp_mul
  la a0, blm_zp1
  la a1, blm_k11_2_13
  la a2, blm_s1
  jal ra, blsg2_fp_mul
  la a0, blm_m2
  la a1, blm_s1
  la a2, blm_m2
  jal ra, blsg2_fp_add
  la a0, blm_m2
  la a1, blm_n
  la a2, blm_m2
  jal ra, blsg2_fp_mul
  la a0, blm_zp2
  la a1, blm_k11_2_12
  la a2, blm_s1
  jal ra, blsg2_fp_mul
  la a0, blm_m2
  la a1, blm_s1
  la a2, blm_m2
  jal ra, blsg2_fp_add
  la a0, blm_m2
  la a1, blm_n
  la a2, blm_m2
  jal ra, blsg2_fp_mul
  la a0, blm_zp3
  la a1, blm_k11_2_11
  la a2, blm_s1
  jal ra, blsg2_fp_mul
  la a0, blm_m2
  la a1, blm_s1
  la a2, blm_m2
  jal ra, blsg2_fp_add
  la a0, blm_m2
  la a1, blm_n
  la a2, blm_m2
  jal ra, blsg2_fp_mul
  la a0, blm_zp4
  la a1, blm_k11_2_10
  la a2, blm_s1
  jal ra, blsg2_fp_mul
  la a0, blm_m2
  la a1, blm_s1
  la a2, blm_m2
  jal ra, blsg2_fp_add
  la a0, blm_m2
  la a1, blm_n
  la a2, blm_m2
  jal ra, blsg2_fp_mul
  la a0, blm_zp5
  la a1, blm_k11_2_9
  la a2, blm_s1
  jal ra, blsg2_fp_mul
  la a0, blm_m2
  la a1, blm_s1
  la a2, blm_m2
  jal ra, blsg2_fp_add
  la a0, blm_m2
  la a1, blm_n
  la a2, blm_m2
  jal ra, blsg2_fp_mul
  la a0, blm_zp6
  la a1, blm_k11_2_8
  la a2, blm_s1
  jal ra, blsg2_fp_mul
  la a0, blm_m2
  la a1, blm_s1
  la a2, blm_m2
  jal ra, blsg2_fp_add
  la a0, blm_m2
  la a1, blm_n
  la a2, blm_m2
  jal ra, blsg2_fp_mul
  la a0, blm_zp7
  la a1, blm_k11_2_7
  la a2, blm_s1
  jal ra, blsg2_fp_mul
  la a0, blm_m2
  la a1, blm_s1
  la a2, blm_m2
  jal ra, blsg2_fp_add
  la a0, blm_m2
  la a1, blm_n
  la a2, blm_m2
  jal ra, blsg2_fp_mul
  la a0, blm_zp8
  la a1, blm_k11_2_6
  la a2, blm_s1
  jal ra, blsg2_fp_mul
  la a0, blm_m2
  la a1, blm_s1
  la a2, blm_m2
  jal ra, blsg2_fp_add
  la a0, blm_m2
  la a1, blm_n
  la a2, blm_m2
  jal ra, blsg2_fp_mul
  la a0, blm_zp9
  la a1, blm_k11_2_5
  la a2, blm_s1
  jal ra, blsg2_fp_mul
  la a0, blm_m2
  la a1, blm_s1
  la a2, blm_m2
  jal ra, blsg2_fp_add
  la a0, blm_m2
  la a1, blm_n
  la a2, blm_m2
  jal ra, blsg2_fp_mul
  la a0, blm_zp10
  la a1, blm_k11_2_4
  la a2, blm_s1
  jal ra, blsg2_fp_mul
  la a0, blm_m2
  la a1, blm_s1
  la a2, blm_m2
  jal ra, blsg2_fp_add
  la a0, blm_m2
  la a1, blm_n
  la a2, blm_m2
  jal ra, blsg2_fp_mul
  la a0, blm_zp11
  la a1, blm_k11_2_3
  la a2, blm_s1
  jal ra, blsg2_fp_mul
  la a0, blm_m2
  la a1, blm_s1
  la a2, blm_m2
  jal ra, blsg2_fp_add
  la a0, blm_m2
  la a1, blm_n
  la a2, blm_m2
  jal ra, blsg2_fp_mul
  la a0, blm_zp12
  la a1, blm_k11_2_2
  la a2, blm_s1
  jal ra, blsg2_fp_mul
  la a0, blm_m2
  la a1, blm_s1
  la a2, blm_m2
  jal ra, blsg2_fp_add
  la a0, blm_m2
  la a1, blm_n
  la a2, blm_m2
  jal ra, blsg2_fp_mul
  la a0, blm_zp13
  la a1, blm_k11_2_1
  la a2, blm_s1
  jal ra, blsg2_fp_mul
  la a0, blm_m2
  la a1, blm_s1
  la a2, blm_m2
  jal ra, blsg2_fp_add
  la a0, blm_m2
  la a1, blm_n
  la a2, blm_m2
  jal ra, blsg2_fp_mul
  la a0, blm_zp14
  la a1, blm_k11_2_0
  la a2, blm_s1
  jal ra, blsg2_fp_mul
  la a0, blm_m2
  la a1, blm_s1
  la a2, blm_m2
  jal ra, blsg2_fp_add
  la a0, blm_k11_3_15
  la a1, blm_m3
  li a2, 6
  jal ra, blsf_copy_quads
  la a0, blm_m3
  la a1, blm_n
  la a2, blm_m3
  jal ra, blsg2_fp_mul
  la a0, blm_zp0
  la a1, blm_k11_3_14
  la a2, blm_s1
  jal ra, blsg2_fp_mul
  la a0, blm_m3
  la a1, blm_s1
  la a2, blm_m3
  jal ra, blsg2_fp_add
  la a0, blm_m3
  la a1, blm_n
  la a2, blm_m3
  jal ra, blsg2_fp_mul
  la a0, blm_zp1
  la a1, blm_k11_3_13
  la a2, blm_s1
  jal ra, blsg2_fp_mul
  la a0, blm_m3
  la a1, blm_s1
  la a2, blm_m3
  jal ra, blsg2_fp_add
  la a0, blm_m3
  la a1, blm_n
  la a2, blm_m3
  jal ra, blsg2_fp_mul
  la a0, blm_zp2
  la a1, blm_k11_3_12
  la a2, blm_s1
  jal ra, blsg2_fp_mul
  la a0, blm_m3
  la a1, blm_s1
  la a2, blm_m3
  jal ra, blsg2_fp_add
  la a0, blm_m3
  la a1, blm_n
  la a2, blm_m3
  jal ra, blsg2_fp_mul
  la a0, blm_zp3
  la a1, blm_k11_3_11
  la a2, blm_s1
  jal ra, blsg2_fp_mul
  la a0, blm_m3
  la a1, blm_s1
  la a2, blm_m3
  jal ra, blsg2_fp_add
  la a0, blm_m3
  la a1, blm_n
  la a2, blm_m3
  jal ra, blsg2_fp_mul
  la a0, blm_zp4
  la a1, blm_k11_3_10
  la a2, blm_s1
  jal ra, blsg2_fp_mul
  la a0, blm_m3
  la a1, blm_s1
  la a2, blm_m3
  jal ra, blsg2_fp_add
  la a0, blm_m3
  la a1, blm_n
  la a2, blm_m3
  jal ra, blsg2_fp_mul
  la a0, blm_zp5
  la a1, blm_k11_3_9
  la a2, blm_s1
  jal ra, blsg2_fp_mul
  la a0, blm_m3
  la a1, blm_s1
  la a2, blm_m3
  jal ra, blsg2_fp_add
  la a0, blm_m3
  la a1, blm_n
  la a2, blm_m3
  jal ra, blsg2_fp_mul
  la a0, blm_zp6
  la a1, blm_k11_3_8
  la a2, blm_s1
  jal ra, blsg2_fp_mul
  la a0, blm_m3
  la a1, blm_s1
  la a2, blm_m3
  jal ra, blsg2_fp_add
  la a0, blm_m3
  la a1, blm_n
  la a2, blm_m3
  jal ra, blsg2_fp_mul
  la a0, blm_zp7
  la a1, blm_k11_3_7
  la a2, blm_s1
  jal ra, blsg2_fp_mul
  la a0, blm_m3
  la a1, blm_s1
  la a2, blm_m3
  jal ra, blsg2_fp_add
  la a0, blm_m3
  la a1, blm_n
  la a2, blm_m3
  jal ra, blsg2_fp_mul
  la a0, blm_zp8
  la a1, blm_k11_3_6
  la a2, blm_s1
  jal ra, blsg2_fp_mul
  la a0, blm_m3
  la a1, blm_s1
  la a2, blm_m3
  jal ra, blsg2_fp_add
  la a0, blm_m3
  la a1, blm_n
  la a2, blm_m3
  jal ra, blsg2_fp_mul
  la a0, blm_zp9
  la a1, blm_k11_3_5
  la a2, blm_s1
  jal ra, blsg2_fp_mul
  la a0, blm_m3
  la a1, blm_s1
  la a2, blm_m3
  jal ra, blsg2_fp_add
  la a0, blm_m3
  la a1, blm_n
  la a2, blm_m3
  jal ra, blsg2_fp_mul
  la a0, blm_zp10
  la a1, blm_k11_3_4
  la a2, blm_s1
  jal ra, blsg2_fp_mul
  la a0, blm_m3
  la a1, blm_s1
  la a2, blm_m3
  jal ra, blsg2_fp_add
  la a0, blm_m3
  la a1, blm_n
  la a2, blm_m3
  jal ra, blsg2_fp_mul
  la a0, blm_zp11
  la a1, blm_k11_3_3
  la a2, blm_s1
  jal ra, blsg2_fp_mul
  la a0, blm_m3
  la a1, blm_s1
  la a2, blm_m3
  jal ra, blsg2_fp_add
  la a0, blm_m3
  la a1, blm_n
  la a2, blm_m3
  jal ra, blsg2_fp_mul
  la a0, blm_zp12
  la a1, blm_k11_3_2
  la a2, blm_s1
  jal ra, blsg2_fp_mul
  la a0, blm_m3
  la a1, blm_s1
  la a2, blm_m3
  jal ra, blsg2_fp_add
  la a0, blm_m3
  la a1, blm_n
  la a2, blm_m3
  jal ra, blsg2_fp_mul
  la a0, blm_zp13
  la a1, blm_k11_3_1
  la a2, blm_s1
  jal ra, blsg2_fp_mul
  la a0, blm_m3
  la a1, blm_s1
  la a2, blm_m3
  jal ra, blsg2_fp_add
  la a0, blm_m3
  la a1, blm_n
  la a2, blm_m3
  jal ra, blsg2_fp_mul
  la a0, blm_zp14
  la a1, blm_k11_3_0
  la a2, blm_s1
  jal ra, blsg2_fp_mul
  la a0, blm_m3
  la a1, blm_s1
  la a2, blm_m3
  jal ra, blsg2_fp_add
" ++
  -- x-denominator poly is one order lower than x-numerator: m1 *= z
  "  la a0, blm_m1
  la a1, blm_d
  la a2, blm_m1
  jal ra, blsg2_fp_mul
  la a0, blm_m2
  la a1, blm_y
  la a2, blm_m2
  jal ra, blsg2_fp_mul
  la a0, blm_m3
  la a1, blm_d
  la a2, blm_m3
  jal ra, blsg2_fp_mul
  la a0, blm_m1
  la a1, blm_m3
  la a2, blm_zg
  jal ra, blsg2_fp_mul
  la a0, blm_m0
  la a1, blm_m3
  la a2, blm_xg
  jal ra, blsg2_fp_mul
  la a0, blm_m1
  la a1, blm_m2
  la a2, blm_yg
  jal ra, blsg2_fp_mul
  la a0, blm_zg
  li a1, 48
  jal ra, blsg_is_zero_n
  beqz a0, .Lblm1_fin
  mv a0, s1
  jal ra, blsg_zero96
  j .Lblm1_ok
" ++
  ".Lblm1_fin:\n" ++
  "  la a0, blm_zg
  la a1, blm_zinv
  jal ra, blsg2_fp_inv
  la a0, blm_xg
  la a1, blm_zinv
  la a2, blm_xg
  jal ra, blsg2_fp_mul
  la a0, blm_yg
  la a1, blm_zinv
  la a2, blm_yg
  jal ra, blsg2_fp_mul
  la a0, blm_xg
  la a1, blm_aff
  jal ra, blsg_le_to_be
  la a0, blm_yg
  la a1, blm_aff
  addi a1, a1, 48
  jal ra, blsg_le_to_be
  la a0, blm_heff_g1_be
  li a1, 8
  la a2, blm_aff
  mv a3, s1
  jal ra, blsg_scalar_mul
" ++
  ".Lblm1_ok:\n" ++
  "  li a0, 0\n" ++
  "  j .Lblm1_ret\n" ++
  ".Lblm1_invalid:\n" ++
  "  li a0, 1\n" ++
  ".Lblm1_ret:\n" ++
  "  ld ra, 0(sp); ld s0, 8(sp); ld s1, 16(sp); ld s2, 24(sp)\n" ++
  "  addi sp, sp, 32\n" ++
  "  ret"

end EvmAsm.Codegen
