/-
  EvmAsm.Codegen.Programs.CallFrameForwardGasSAsm

  Proof-first (DCode) port of `call_frame_forward_gas` — EIP-150
  message-call gas forwarding (`vm/gas.py:419,424,64,415`):

    a0 = gas_left, a1 = requested, a2 = value_nonzero
    →  a1 = cap = min(requested, gas_left - gas_left/64)      (caller charge)
       a0 = cap + (value_nonzero ? 2300 : 0)                  (callee gas)

  The derivation is written FIRST, as a calc chain from the ABI
  precondition to the postcondition, and the code is GENERATED from it
  (docs/sasm-deriv.md); the generated bytes are pinned below and are
  byte-identical to the hand-written routine in
  `Programs/CallFrameDescend.lean` (the ite's empty then-arm is a pure
  step, so the `bltu → j → mv` diamond and the `beqz`-guarded stipend
  add flatten to exactly the original layout).

  Note (verified-replacement-strategy §4.5): this routine is a second
  implementation of the EIP-150 capping rule also implemented by the
  verified `message_call_gas`; `cffgCap_eq_capped` ties this port's cap
  to that file's `capped` at `s = 0` (this routine takes `gas_left`
  AFTER the memory/access charge).
-/

import EvmAsm.Rv64.SAsm.Deriv
import EvmAsm.Codegen.Programs.MessageCallGasSAsm

namespace EvmAsm.Codegen

open EvmAsm.Rv64
open EvmAsm.Rv64.SAsm

namespace CallFrameForwardGasSAsm

/-- `Program` is a def alias, opaque to instance search. -/
instance : BEq Program := inferInstanceAs (BEq (List Instr))

/-- Register-only routine: no read-only region, no writable window. -/
local infix:36 " ⤳ " => DCode Region.empty RwRegion.empty

/-! ## The routine's semantics -/

/-- `max_message_call_gas`: all-but-one-64th of the remaining gas. -/
def cffgMax (g : Word) : Word := g - (g >>> (6 : Nat))

/-- The forwarded-gas cap: the request, capped at `cffgMax`. -/
def cffgCap (r g : Word) : Word :=
  if BitVec.ult r (cffgMax g) then r else cffgMax g

/-- This routine's cap is `MessageCallGasSAsm.capped` at `s = 0` (the
    memory/access charge is already deducted from this routine's
    `gas_left` input). -/
theorem cffgCap_eq_capped (r g : Word) :
    cffgCap r g = MessageCallGasSAsm.capped r g 0 := by
  have hg : g - 0 = g := by simp
  have h0 : BitVec.ult g 0 = false := by
    simp [BitVec.ult]
  unfold cffgCap cffgMax MessageCallGasSAsm.capped
  rw [hg]
  simp only [h0, Bool.false_eq_true, if_false]
  generalize g - g >>> 6 = m
  have hp : ∀ x y : Word, BitVec.ult x y = true → x.toNat < y.toNat := by
    intro x y h
    simpa [BitVec.ult] using h
  have hn : ∀ x y : Word, ¬ (BitVec.ult x y = true) → y.toNat ≤ x.toNat := by
    intro x y h
    simp only [BitVec.ult, decide_eq_true_eq, Nat.not_lt] at h
    exact h
  by_cases h1 : BitVec.ult r m = true
  · by_cases h2 : BitVec.ult m r = true
    · exact (Nat.lt_asymm (hp _ _ h1) (hp _ _ h2)).elim
    · rw [if_pos h1, if_neg h2]
  · by_cases h2 : BitVec.ult m r = true
    · rw [if_neg h1, if_pos h2]
    · rw [if_neg h1, if_neg h2]
      exact BitVec.eq_of_toNat_eq
        (Nat.le_antisymm (hn r m h1) (hn m r h2))

/-! ## The derivation (the code falls out of it) -/

/-- Proof-first EIP-150 forwarding: compute the cap into `t1` (the
    `requested ≥ max` arm of the ite is a pure step — zero
    instructions), expose it as the caller charge in `a1`, add the
    stipend for value-bearing calls, return the callee gas in `a0`.
    Clobbers t0/t1 only (both exposed). -/
def callFrameForwardGasDeriv (g r v : Word) :
    (fun rf _ _ => rf.get .x10 = g ∧ rf.get .x11 = r ∧ rf.get .x12 = v)
      ⤳ (fun rf _ _ =>
          rf.get .x10 = cffgCap r g + MessageCallGasSAsm.stipend v
          ∧ rf.get .x11 = cffgCap r g) :=
  calc (fun rf _ _ => rf.get .x10 = g ∧ rf.get .x11 = r ∧ rf.get .x12 = v
        : Reach)
    _ ⤳ (fun rf _ _ => rf.get .x6 = cffgMax g ∧ rf.get .x11 = r
          ∧ rf.get .x12 = v : Reach) :=
      DCode.block "max" [.SRLI .x5 .x10 6, .SUB .x6 .x10 .x5] (by decide)
        (fun h => absurd h (by decide))
        (by
          rintro rf ws A _ ⟨h10, h11, h12⟩
          simp only [execBlock_cons, execBlock_nil, execInstrRF, aluSem]
          refine ⟨?_, ?_, ?_⟩
          · rw [RegFile.get_set_self _ _ _ (by decide),
              RegFile.get_set_ne _ _ _ _ (by decide),
              RegFile.get_set_self _ _ _ (by decide), h10]
            rfl
          · rw [RegFile.get_set_ne _ _ _ _ (by decide),
              RegFile.get_set_ne _ _ _ _ (by decide), h11]
          · rw [RegFile.get_set_ne _ _ _ _ (by decide),
              RegFile.get_set_ne _ _ _ _ (by decide), h12])
    _ ⤳ (fun rf _ _ => rf.get .x6 = cffgCap r g ∧ rf.get .x12 = v
          : Reach) :=
      DCode.ite "cap" (.bgeu .x11 .x6)
        (DCode.pure "keepmax"
          (by
            rintro rf ws A ⟨⟨h6, h11, h12⟩, hc⟩
            simp only [Cond.holds, h6, h11] at hc
            refine ⟨?_, h12⟩
            rw [h6, cffgCap, if_neg hc]))
        (DCode.block "takereq" [.MV .x6 .x11] (by decide)
          (fun h => absurd h (by decide))
          (by
            rintro rf ws A _ ⟨⟨h6, h11, h12⟩, hc⟩
            simp only [Cond.holds, h6, h11, not_not] at hc
            simp only [execBlock_cons, execBlock_nil, execInstrRF, aluSem]
            refine ⟨?_, ?_⟩
            · rw [RegFile.get_set_self _ _ _ (by decide), h11,
                cffgCap, if_pos hc]
            · rw [RegFile.get_set_ne _ _ _ _ (by decide), h12]))
    _ ⤳ (fun rf _ _ => rf.get .x11 = cffgCap r g
          ∧ rf.get .x6 = cffgCap r g ∧ rf.get .x12 = v : Reach) :=
      DCode.block "cost" [.MV .x11 .x6] (by decide)
        (fun h => absurd h (by decide))
        (by
          rintro rf ws A _ ⟨h6, h12⟩
          simp only [execBlock_cons, execBlock_nil, execInstrRF, aluSem]
          refine ⟨?_, ?_, ?_⟩
          · rw [RegFile.get_set_self _ _ _ (by decide), h6]
          · rw [RegFile.get_set_ne _ _ _ _ (by decide), h6]
          · rw [RegFile.get_set_ne _ _ _ _ (by decide), h12])
    _ ⤳ (fun rf _ _ => rf.get .x11 = cffgCap r g
          ∧ rf.get .x6 = cffgCap r g + MessageCallGasSAsm.stipend v
          : Reach) :=
      DCode.when "stipend" (.bne .x12 .x0)
        -- CALL_STIPEND = 2300 > 2047: emitted as its exact GNU-as `li`
        -- expansion (lui+addiw) so Program layout = machine layout.
        (DCode.block "addstipend"
          [.LUI .x5 (1 : BitVec 20), .ADDIW .x5 .x5 (-1796 : BitVec 12),
           .ADD .x6 .x6 .x5]
          (by decide)
          (fun h => absurd h (by decide))
          (by
            rintro rf ws A _ ⟨⟨h11, h6, h12⟩, hc⟩
            simp only [Cond.holds, RegFile.get_x0, h12] at hc
            simp only [execBlock_cons, execBlock_nil, execInstrRF, aluSem]
            refine ⟨?_, ?_⟩
            · rw [RegFile.get_set_ne _ _ _ _ (by decide),
                RegFile.get_set_ne _ _ _ _ (by decide),
                RegFile.get_set_ne _ _ _ _ (by decide), h11]
            · rw [RegFile.get_set_self _ _ _ (by decide),
                RegFile.get_set_ne _ _ _ _ (by decide),
                RegFile.get_set_ne _ _ _ _ (by decide),
                RegFile.get_set_self _ _ _ (by decide),
                RegFile.get_set_self _ _ _ (by decide), h6,
                MessageCallGasSAsm.stipend, if_neg hc]
              congr 1))
        (by
          rintro rf ws A ⟨h11, h6, h12⟩ hc
          simp only [Cond.holds, RegFile.get_x0, h12, ne_eq, not_not] at hc
          refine ⟨h11, ?_⟩
          rw [h6, MessageCallGasSAsm.stipend, if_pos hc]
          bv_omega)
    _ ⤳ (fun rf _ _ =>
          rf.get .x10 = cffgCap r g + MessageCallGasSAsm.stipend v
          ∧ rf.get .x11 = cffgCap r g : Reach) :=
      DCode.block "ret0" [.MV .x10 .x6] (by decide)
        (fun h => absurd h (by decide))
        (by
          rintro rf ws A _ ⟨h11, h6⟩
          simp only [execBlock_cons, execBlock_nil, execInstrRF, aluSem]
          refine ⟨?_, ?_⟩
          · rw [RegFile.get_set_self _ _ _ (by decide), h6]
          · rw [RegFile.get_set_ne _ _ _ _ (by decide), h11])

/-! ## The generated function, spec, and code -/

/-- The generated SAsm function (register-only leaf). -/
def callFrameForwardGasFn (g r v : Word) : Fn :=
  (callFrameForwardGasDeriv g r v).fn "call_frame_forward_gas"

/-- The machine-level correctness of the generated body: the bounded CPS
    triple, at any base. -/
theorem callFrameForwardGasFn_spec (g r v base : Word) :
    (callFrameForwardGasFn g r v).Spec base :=
  DCode.fn_spec "call_frame_forward_gas" (callFrameForwardGasDeriv g r v)
    base Region.empty_wf RwRegion.empty_wf

/-- The generated code, with the return epilogue — this IS the routine
    the guest emits (see the drift tie in `CallFrameDescend.lean`).
    Position-independent (no call nodes), so base 0 is canonical. -/
def callFrameForwardGas_prog : Program :=
  (callFrameForwardGasFn 0 0 0).programRet 0

-- The generated instruction sequence, pinned (build-time evaluation):
-- byte-identical to the original hand-written routine (bltu/j diamond,
-- beqz-guarded stipend, jalr ret).  The kernel-checked chain does not
-- depend on this pin: the emitted string is DEFINED as
-- `emitProgram callFrameForwardGas_prog`, and the spec is about the same
-- `Fn` whose `programRet` that is.
#guard (callFrameForwardGas_prog : List Instr) ==
    [ .SRLI .x5 .x10 6,
      .SUB  .x6 .x10 .x5,
      .BLTU .x11 .x6 (8 : BitVec 13),
      .JAL  .x0 (8 : BitVec 21),
      .MV   .x6 .x11,
      .MV   .x11 .x6,
      .BEQ  .x12 .x0 (16 : BitVec 13),
      .LUI  .x5 (1 : BitVec 20),
      .ADDIW .x5 .x5 (-1796 : BitVec 12),
      .ADD  .x6 .x6 .x5,
      .MV   .x10 .x6,
      .JALR .x0 .x1 (0 : BitVec 12) ]

#guard callFrameForwardGas_prog.length = 12

-- The code does not depend on the ghost arguments (sampled; the ghosts
-- occur only in `Prop`/`Reach` positions by construction).
#guard ((callFrameForwardGasFn 5 7 9).programRet 0 : List Instr)
    == (callFrameForwardGas_prog : List Instr)

end CallFrameForwardGasSAsm

end EvmAsm.Codegen
