/- Generated by scripts/asm_to_program.py (gen_lean_layout, GH #10753) -/
import EvmAsm.Codegen.Emit
import EvmAsm.Codegen.AsmReloc
import EvmAsm.Codegen.GuestLayout

/-!
# Generated RV64 Program for `frame_base`

LEAF module (GH #10753): the program is parameterised over the abstract
`GuestLayout` record; the concrete `frameBase_prog` with the original
name and type is re-exposed by the bridge module
`EvmAsm.Codegen.Programs.CallFrameBase`.  The `Function` emission string,
`_eq_prog` theorem and `#guard` pins below are elaborated at `.zero`:
`emitProgramR` emits `la`/`jal` instructions symbolically from the
relocation table and never reads the layout, so the strings are
layout-independent (checked, not assumed: the emitted-reloc-count and
assemble-vs-fixture gates reject any layout-dependent emission).
-/
namespace EvmAsm.Codegen

open EvmAsm.Rv64

/-! ## frame_base

    a0 = depth (>= 0). Returns a0 = `call_frame_arena + depth * 0x19000`.

    Clobbers t0/t1. -/
def frameBase_prog_of (L : GuestLayout) : Program :=
  [ .LUI .x6 (25 : BitVec 20),
    .MUL .x5 .x10 .x6,
    .AUIPC .x6 (laHi L.call_frame_arena (L.frame_base + 8)),
    .ADDI .x6 .x6 (laLo L.call_frame_arena (L.frame_base + 8)),
    .ADD .x10 .x6 .x5,
    .JALR .x0 .x1 (0 : BitVec 12) ]

/-- Reloc side-table for `frameBase_prog_of`: the `la`/cross-`jal` instruction
    indices kept SYMBOLIC in the emitted image text (`emitProgramR`), while
    the Program above carries the layout-parameterised immediates
    (`laHi`/`laLo`/`jalOff L.…`) for verification. -/
def frameBase_relocs : RelocTable :=
  [ (2, .la .x6 "call_frame_arena") ]

def frameBaseFunction : String :=
  "frame_base:\n" ++ emitProgramR (frameBase_prog_of .zero) frameBase_relocs

/-- Kernel-checked drift guard: the emitted (image-agnostic, symbolic) Codegen
    string is exactly `frameBase_prog_of .zero` rendered under its label with the
    `la`/`jal` relocs kept symbolic (layout-parameterised per GH #10753;
    emission is layout-independent, mechanical conversion by
    `scripts/asm_to_program.py`). Guest binary byte-identity + guest-linked
    consistency of the concrete Program verified offline by assemble/link+cmp
    over the bridge's `frameBase_prog` (`_of guestLayout`). -/
theorem frameBaseFunction_eq_prog :
    frameBaseFunction = "frame_base:\n" ++ emitProgramR (frameBase_prog_of .zero) frameBase_relocs := rfl

#guard frameBaseFunction.startsWith "frame_base:\n"
#guard (frameBase_prog_of .zero).length = 6

end EvmAsm.Codegen
