/-
  EvmAsm.Stateless.Ports.HeaderExtractWithdrawalsRootSAsm

  Verified port of `header_extract_withdrawals_root` (source: EvmAsm/Codegen/Programs/HeaderFields.lean, def `headerExtractWithdrawalsRootFunction`).
  Generated by scripts/gen-port-kit.py — fill the TODO(port) blocks.

  Playbook: docs/agents/port-playbook.md   (class table in Step 0)
  Big picture: docs/agents/top-theorem-ledger.md

  ## Delivery checklist (sasm-howto §9)
  1. scripts/port-check.sh <this file>   -- build, warnings, tactics, axioms
  2. If emitted code changed — EEST A/B (both legs, identical failures only):
       git stash -u && lake exe codegen --program stateless_guest \
         --halt linux93 -o gen-out/base && git stash pop
       lake exe codegen --program stateless_guest --halt linux93 -o gen-out/cand
       GUEST_ELF=<elf> EEST_RUN_DIR=<dir> \
         scripts/codegen-eest-stateless-check.sh --no-build --backend spike \
         --random --seed 4242 --limit 200 --jobs 8 --quiet-passes
  3. PLAN.md + docs/agents/top-theorem-ledger.md updated; bead closed only
     after the PR lands on main.
-/

import EvmAsm.Rv64.SAsm.Tactic

namespace EvmAsm.Stateless.Ports

open EvmAsm.Rv64 EvmAsm.Rv64.SAsm EvmAsm.Rv64.SAsm.Stmt

-- `header_extract_withdrawals_root` is ALREADY converted: `headerExtractWithdrawalsRoot_prog : Program` in EvmAsm/Codegen/Programs/HeaderFields.lean
-- (correspondence theorem `headerExtractWithdrawalsRootFunction_eq_prog` exists there).
-- The remaining work is the SPEC over `headerExtractWithdrawalsRoot_prog`:
--   * straight-line leaf -> cpsTripleWithin block spec directly over it;
--   * otherwise rebuild as an SAsm `Fn` whose flatten equals it,
--     with a `#guard <fn>.flatten 0 = headerExtractWithdrawalsRoot_prog` pin.
-- NOTE: this skeleton lives in the verified core and must NOT import
-- Codegen (layering L1) — restate the Program here with a value-equality
-- `#guard`/`decide` pin against the Codegen copy in the PR description,
-- or verify it under EvmAsm/Codegen/Proofs/ (which may import both).


-- ============================================================================
-- TODO(port): the SAsm function + spec.
--
-- 1. Rebuild the routine as an SAsm `Fn` (structured control flow) whose
--    flattening equals `headerExtractWithdrawalsRoot_prog` — or, for a straight-line leaf, verify
--    `headerExtractWithdrawalsRoot_prog` directly with a cpsTripleWithin block spec.
-- 2. State the contract (playbook Step 2):
--    * pre  = the asm's implicit assumptions (offsets in range, alignment),
--      ghost input values via leByte/leU32/leU64 (ChainIdSAsm pattern);
--    * post = the ABI registers downstream code documents + written windows.
-- 3. Prove via `vcgen`; close VCs with the playbook Step 3 closers.
-- 4. Emit + swap (playbook Step 4) and run `scripts/port-check.sh` on this
--    file; EEST A/B if the emitted guest changed.
--
-- Exemplar for your routine class: see the table in
-- docs/agents/port-playbook.md Step 0.
-- ============================================================================

end EvmAsm.Stateless.Ports
