/-
  EvmAsm.Codegen.Programs.RlpWalkInitTie

  Own-anchored `rlp_walk_init` contract (GH #12799, ownership-table row 8).

  ## What this module adds

  `EvmAsm.Rv64.RLP.rlp_walk_init_spec_within` (`Rv64/RLP/WalkInit.lean:1590`)
  is the FORM-GENERIC whole-routine triple for `rlp_walk_init`: all nine
  outcomes (statuses 0..7 plus the two success shapes), 53 instructions, one
  loop, no callees.  It is stated over a universally quantified `base`, so it
  says nothing on its own about the routine at its LINKED entry.

  The two registry rows that existed before this module are both unusable by a
  caller sitting at `GuestAddrs.rlp_walk_init`:

  * `account_rlp_walk_init_spec_within` is `∀`-base AND account-specialised
    (`encodeAccount`, cursor at `listBase + 2`).  A block header is not an
    `encodeAccount` list.
  * `rlp_walk_init_long1_spec_within` gates on `56 ≤ payload.length`, the
    long-form-1 arm only.

  ## Decision: RE-ANCHOR, do not re-prove

  `rlp_walk_init_code base := CodeReq.ofProg base rlp_walk_init_prog` is
  already parametric in `base`, and the form-generic theorem's `base` is a
  plain universally quantified `Word` with no side conditions.  Instantiating
  it at `I := (GuestAddrs.rlp_walk_init : Word)` therefore yields the anchored
  `cpsTripleWithin` directly, with nothing left to prove.  Proving a fresh
  53-instruction triple here would duplicate 1300 lines of `WalkInit.lean` and
  produce a theorem provably equal to this one.

  ## Why there is no `GuestImageEntries` pairing (and why that is not a gap here)

  `rlp_walk_init` is absent from the 442-row `guestImageEntries` table, and
  that absence is DELIBERATE and tooling-side, not a proof gap:

  * The table is GENERATED by `scripts/guest_image_coverage.py --emit-lean`
    from `scripts/asm-fixtures/MANIFEST.tsv`.
  * `rlpWalkInitFunction` (`Codegen/Programs/RlpWalk.lean:83`) emits
    `emitProgram EvmAsm.Rv64.RLP.rlp_walk_init_prog` — it reaches its program
    through a QUALIFIED name, because unlike its siblings it has no separate
    Codegen-side `rlpWalkInit_prog` transcription; the verified Program IS the
    emitted body.
  * `guest_image_coverage.py` rejects qualified-name rows outright
    (`_QUALIFIED`, the `sys.exit` that names GH #12686): the downstream
    consumers `check-manifest-guestimage.py` and
    `check-guest-image-program-bytes.py` bind rows with a plain-identifier
    regex, so such a row would look registered while the byte-identity gate
    silently skipped it.  Registering a routine in this shape is an OPEN
    DESIGN QUESTION (#12686), not a one-line addition.

  So adding the pairing is emitter/tooling work blocked on #12686 and is out
  of scope for this module.  It is also not needed: the anchor established
  here is the same one `RlpWalkNextStrictTie` uses for
  `rlp_walk_next_shared` — `CodeReq.ofProg <GuestAddrs entry> <Program>` — and
  the Program/emitted-text tie is the kernel-checked
  `rlpWalkInitFunction_eq_verified_prog`, restated below as
  `initCode_emitted_body`.
-/
import EvmAsm.Codegen.Programs.RlpWalk

namespace EvmAsm.Codegen.RlpWalkInitTie

open EvmAsm.Rv64 EvmAsm.Rv64.RLP EvmAsm.EL.RLP

/-- Guest entry of `rlp_walk_init` (`0x80004c08`, 212 B = 53 instructions). -/
abbrev I : Word := (GuestAddrs.rlp_walk_init : Word)

/-- The linked image of `rlp_walk_init`, anchored at its own `GuestAddrs`
    entry.  Definitionally `rlp_walk_init_code I`; kept as a local name so the
    anchored triple below reads at a glance. -/
abbrev initCode : CodeReq := CodeReq.ofProg I rlp_walk_init_prog

theorem initCode_eq_verified : initCode = rlp_walk_init_code I := rfl

/-- Length pin: the Program matches the linked 212-byte extent
    (`0x80004c08` .. `0x80004cdc`, the next symbol in address order). -/
theorem init_length : rlp_walk_init_prog.length = 53 := rfl

/-- The emitted guest text under the `rlp_walk_init:` label IS this Program.
    Restatement of the drift guard in `Codegen/Programs/RlpWalk.lean`, pulled
    in here so the anchor's evidence chain is readable from one place. -/
theorem initCode_emitted_body :
    rlpWalkInitFunction = "rlp_walk_init:\n" ++ emitProgram rlp_walk_init_prog :=
  rlpWalkInitFunction_eq_verified_prog

/-- Postcondition of the anchored `rlp_walk_init` triple: the register frame
    the routine restores, separated from the nine-way outcome disjunction it
    lands in.  Named (rather than inlined) so the closed instance below can
    mention it without restating 100 lines — the same idiom as
    `RlpWalkNextStrictTie.sharedPost`. -/
def initPost (listBase raVal listLen : Word) (listBytes : List (BitVec 8)) (listOff : Nat)
    (hoff : listOff < listBytes.length) : Assertion :=
  ((regOwn .x5 ** regOwn .x6 ** regOwn .x7 ** regOwn .x28 ** regOwn .x29 ** regOwn .x30 **
    regOwn .x31 ** (.x0 ↦ᵣ (0 : Word)) ** (.x1 ↦ᵣ raVal) ** bytesRegion listBase listBytes) **
   (fun h =>
     -- empty (a2 = 2)
     (((.x10 ↦ᵣ (listBase + BitVec.ofNat 64 listOff)) ** (.x11 ↦ᵣ (0 : Word)) **
        (.x12 ↦ᵣ (2 : Word)) ** ⌜listLen = (0 : Word)⌝) h) ∨
     -- not-a-list (a2 = 1)
     (((.x10 ↦ᵣ (listBase + BitVec.ofNat 64 listOff)) **
        (.x11 ↦ᵣ ((listBase + BitVec.ofNat 64 listOff) + listLen)) ** (.x12 ↦ᵣ (1 : Word)) **
        ⌜listLen ≠ (0 : Word) ∧
          BitVec.ult ((listBytes[listOff]'hoff).zeroExtend 64) (0xc0 : Word) = true⌝) h) ∨
     -- short success (a2 = 0)
     (((.x10 ↦ᵣ ((listBase + BitVec.ofNat 64 listOff) + signExtend12 (1 : BitVec 12))) **
        (.x11 ↦ᵣ ((listBase + BitVec.ofNat 64 listOff) + listLen)) ** (.x12 ↦ᵣ (0 : Word)) **
        ⌜listLen ≠ (0 : Word) ∧
          ¬ BitVec.ult ((listBytes[listOff]'hoff).zeroExtend 64) (0xc0 : Word) = true ∧
          BitVec.ult ((listBytes[listOff]'hoff).zeroExtend 64) (0xf8 : Word) = true ∧
          (listBase + BitVec.ofNat 64 listOff) +
            (((listBytes[listOff]'hoff).zeroExtend 64 - (0xc0 : Word)) + signExtend12 (1 : BitVec 12))
            = (listBase + BitVec.ofNat 64 listOff) + listLen⌝) h) ∨
     -- short mismatch (a2 = 3)
     (((.x10 ↦ᵣ (listBase + BitVec.ofNat 64 listOff)) **
        (.x11 ↦ᵣ ((listBase + BitVec.ofNat 64 listOff) + listLen)) ** (.x12 ↦ᵣ (3 : Word)) **
        ⌜listLen ≠ (0 : Word) ∧
          ¬ BitVec.ult ((listBytes[listOff]'hoff).zeroExtend 64) (0xc0 : Word) = true ∧
          BitVec.ult ((listBytes[listOff]'hoff).zeroExtend 64) (0xf8 : Word) = true ∧
          (listBase + BitVec.ofNat 64 listOff) +
            (((listBytes[listOff]'hoff).zeroExtend 64 - (0xc0 : Word)) + signExtend12 (1 : BitVec 12))
            ≠ (listBase + BitVec.ofNat 64 listOff) + listLen⌝) h) ∨
     -- long header truncated (a2 = 4)
     (((.x10 ↦ᵣ (listBase + BitVec.ofNat 64 listOff)) **
        (.x11 ↦ᵣ ((listBase + BitVec.ofNat 64 listOff) + listLen)) ** (.x12 ↦ᵣ (4 : Word)) **
        ⌜listLen ≠ (0 : Word) ∧
          ¬ BitVec.ult ((listBytes[listOff]'hoff).zeroExtend 64) (0xc0 : Word) = true ∧
          ¬ BitVec.ult ((listBytes[listOff]'hoff).zeroExtend 64) (0xf8 : Word) = true ∧
          BitVec.ult ((listBase + BitVec.ofNat 64 listOff) + listLen)
            ((listBase + BitVec.ofNat 64 listOff) +
              (((listBytes[listOff]'hoff).zeroExtend 64 - (0xf7 : Word)) + signExtend12 (1 : BitVec 12)))
            = true⌝) h) ∨
     -- long leading zero (a2 = 5): header fits, but the first length byte is 0
     (((.x10 ↦ᵣ (listBase + BitVec.ofNat 64 listOff)) **
        (.x11 ↦ᵣ ((listBase + BitVec.ofNat 64 listOff) + listLen)) ** (.x12 ↦ᵣ (5 : Word)) **
        ⌜listLen ≠ (0 : Word) ∧
          ¬ BitVec.ult ((listBytes[listOff]'hoff).zeroExtend 64) (0xc0 : Word) = true ∧
          ¬ BitVec.ult ((listBytes[listOff]'hoff).zeroExtend 64) (0xf8 : Word) = true ∧
          ¬ BitVec.ult ((listBase + BitVec.ofNat 64 listOff) + listLen)
            ((listBase + BitVec.ofNat 64 listOff) +
              (((listBytes[listOff]'hoff).zeroExtend 64 - (0xf7 : Word)) + signExtend12 (1 : BitVec 12)))
            = true ∧
          listBytes[listOff + 1]? = some (0 : BitVec 8)⌝) h) ∨
     -- long non-minimal (a2 = 6): header fits, decoded length < 56
     (((.x10 ↦ᵣ (listBase + BitVec.ofNat 64 listOff)) **
        (.x11 ↦ᵣ ((listBase + BitVec.ofNat 64 listOff) + listLen)) ** (.x12 ↦ᵣ (6 : Word)) **
        ⌜listLen ≠ (0 : Word) ∧
          ¬ BitVec.ult ((listBytes[listOff]'hoff).zeroExtend 64) (0xc0 : Word) = true ∧
          ¬ BitVec.ult ((listBytes[listOff]'hoff).zeroExtend 64) (0xf8 : Word) = true ∧
          ¬ BitVec.ult ((listBase + BitVec.ofNat 64 listOff) + listLen)
            ((listBase + BitVec.ofNat 64 listOff) +
              (((listBytes[listOff]'hoff).zeroExtend 64 - (0xf7 : Word)) + signExtend12 (1 : BitVec 12)))
            = true ∧
          listBytes[listOff + 1]? ≠ some (0 : BitVec 8) ∧
          BitVec.ult (BitVec.ofNat 64 (Nat.fromBytesBE ((listBytes.drop (listOff + 1)).take
            ((listBytes[listOff]'hoff).zeroExtend 64 - (0xf7 : Word)).toNat))) (56 : Word) = true⌝) h) ∨
     -- long mismatch (a2 = 7): decoded ≥ 56 but cursor + decoded ≠ end
     (((.x10 ↦ᵣ (listBase + BitVec.ofNat 64 listOff)) **
        (.x11 ↦ᵣ ((listBase + BitVec.ofNat 64 listOff) + listLen)) ** (.x12 ↦ᵣ (7 : Word)) **
        ⌜listLen ≠ (0 : Word) ∧
          ¬ BitVec.ult ((listBytes[listOff]'hoff).zeroExtend 64) (0xc0 : Word) = true ∧
          ¬ BitVec.ult ((listBytes[listOff]'hoff).zeroExtend 64) (0xf8 : Word) = true ∧
          ¬ BitVec.ult ((listBase + BitVec.ofNat 64 listOff) + listLen)
            ((listBase + BitVec.ofNat 64 listOff) +
              (((listBytes[listOff]'hoff).zeroExtend 64 - (0xf7 : Word)) + signExtend12 (1 : BitVec 12)))
            = true ∧
          listBytes[listOff + 1]? ≠ some (0 : BitVec 8) ∧
          ¬ BitVec.ult (BitVec.ofNat 64 (Nat.fromBytesBE ((listBytes.drop (listOff + 1)).take
            ((listBytes[listOff]'hoff).zeroExtend 64 - (0xf7 : Word)).toNat))) (56 : Word) = true ∧
          ((listBase + BitVec.ofNat 64 listOff) +
              (((listBytes[listOff]'hoff).zeroExtend 64 - (0xf7 : Word)) + signExtend12 (1 : BitVec 12))) +
              BitVec.ofNat 64 (Nat.fromBytesBE ((listBytes.drop (listOff + 1)).take
                ((listBytes[listOff]'hoff).zeroExtend 64 - (0xf7 : Word)).toNat))
            ≠ (listBase + BitVec.ofNat 64 listOff) + listLen⌝) h) ∨
     -- long success (a2 = 0): decoded ≥ 56 and cursor + decoded = end
     (((.x10 ↦ᵣ ((listBase + BitVec.ofNat 64 listOff) +
          (((listBytes[listOff]'hoff).zeroExtend 64 - (0xf7 : Word)) + signExtend12 (1 : BitVec 12)))) **
        (.x11 ↦ᵣ ((listBase + BitVec.ofNat 64 listOff) + listLen)) ** (.x12 ↦ᵣ (0 : Word)) **
        ⌜listLen ≠ (0 : Word) ∧
          ¬ BitVec.ult ((listBytes[listOff]'hoff).zeroExtend 64) (0xc0 : Word) = true ∧
          ¬ BitVec.ult ((listBytes[listOff]'hoff).zeroExtend 64) (0xf8 : Word) = true ∧
          ¬ BitVec.ult ((listBase + BitVec.ofNat 64 listOff) + listLen)
            ((listBase + BitVec.ofNat 64 listOff) +
              (((listBytes[listOff]'hoff).zeroExtend 64 - (0xf7 : Word)) + signExtend12 (1 : BitVec 12)))
            = true ∧
          listBytes[listOff + 1]? ≠ some (0 : BitVec 8) ∧
          ¬ BitVec.ult (BitVec.ofNat 64 (Nat.fromBytesBE ((listBytes.drop (listOff + 1)).take
            ((listBytes[listOff]'hoff).zeroExtend 64 - (0xf7 : Word)).toNat))) (56 : Word) = true ∧
          ((listBase + BitVec.ofNat 64 listOff) +
              (((listBytes[listOff]'hoff).zeroExtend 64 - (0xf7 : Word)) + signExtend12 (1 : BitVec 12))) +
              BitVec.ofNat 64 (Nat.fromBytesBE ((listBytes.drop (listOff + 1)).take
                ((listBytes[listOff]'hoff).zeroExtend 64 - (0xf7 : Word)).toNat))
            = (listBase + BitVec.ofNat 64 listOff) + listLen⌝) h)))

/-! ## The anchored triple.

    Identical in every component to `EvmAsm.Rv64.RLP.rlp_walk_init_spec_within`
    except that `base` is fixed to the linked entry `I` and the code
    requirement is the image at `I`.  Nine outcomes, `≤ 81` steps, `t0..t6`
    clobbered. -/
theorem rlp_walk_init_entry_spec_within
    (listBase raVal listLen a2Old t0Old t1Old t2Old t3Old t4Old t5Old t6Old : Word)
    (listBytes : List (BitVec 8)) (listOff : Nat) (hsalign : listBase.toNat % 8 = 0)
    (hoff : listOff < listBytes.length) (hover : listBase.toNat + listOff < 2 ^ 64)
    (hvalid : isValidByteAccess (listBase + BitVec.ofNat 64 listOff) = true)
    -- Length-field readability is required only when the long header *fits*
    -- in `[listOff, listOff + listLen)` (asm: `bltu end, cursor` not taken).
    -- Truncated long headers reject without loading length bytes, so the old
    -- unconditional `listOff + 1 + lol ≤ length` forced an unsatisfiable
    -- lookahead past an exact-length buffer (#12404).
    (hll_len : ¬ BitVec.ult ((listBytes[listOff]'hoff).zeroExtend 64) (0xf8 : Word) = true →
        ¬ BitVec.ult ((listBase + BitVec.ofNat 64 listOff) + listLen)
            ((listBase + BitVec.ofNat 64 listOff) +
              (((listBytes[listOff]'hoff).zeroExtend 64 - (0xf7 : Word)) +
                signExtend12 (1 : BitVec 12))) = true →
        listOff + 1 + ((listBytes[listOff]'hoff).zeroExtend 64 - (0xf7 : Word)).toNat
          ≤ listBytes.length)
    (hll_over : ¬ BitVec.ult ((listBytes[listOff]'hoff).zeroExtend 64) (0xf8 : Word) = true →
        ¬ BitVec.ult ((listBase + BitVec.ofNat 64 listOff) + listLen)
            ((listBase + BitVec.ofNat 64 listOff) +
              (((listBytes[listOff]'hoff).zeroExtend 64 - (0xf7 : Word)) +
                signExtend12 (1 : BitVec 12))) = true →
        listBase.toNat + (listOff + 1 +
          ((listBytes[listOff]'hoff).zeroExtend 64 - (0xf7 : Word)).toNat) ≤ 2 ^ 64)
    (hll_valid : ¬ BitVec.ult ((listBytes[listOff]'hoff).zeroExtend 64) (0xf8 : Word) = true →
        ¬ BitVec.ult ((listBase + BitVec.ofNat 64 listOff) + listLen)
            ((listBase + BitVec.ofNat 64 listOff) +
              (((listBytes[listOff]'hoff).zeroExtend 64 - (0xf7 : Word)) +
                signExtend12 (1 : BitVec 12))) = true →
        ∀ k, k < ((listBytes[listOff]'hoff).zeroExtend 64 - (0xf7 : Word)).toNat →
          isValidByteAccess (listBase + BitVec.ofNat 64 (listOff + 1 + k)) = true) :
    cpsTripleWithin 81 I (raVal &&& ~~~1) initCode
      ((.x10 ↦ᵣ (listBase + BitVec.ofNat 64 listOff)) ** (.x11 ↦ᵣ listLen) ** (.x12 ↦ᵣ a2Old) **
        (.x5 ↦ᵣ t0Old) ** (.x6 ↦ᵣ t1Old) ** (.x7 ↦ᵣ t2Old) ** (.x28 ↦ᵣ t3Old) **
        (.x29 ↦ᵣ t4Old) ** (.x30 ↦ᵣ t5Old) ** (.x31 ↦ᵣ t6Old) ** (.x0 ↦ᵣ (0 : Word)) **
        (.x1 ↦ᵣ raVal) ** bytesRegion listBase listBytes)
      (initPost listBase raVal listLen listBytes listOff hoff) :=
  rlp_walk_init_spec_within I listBase raVal listLen a2Old t0Old t1Old t2Old t3Old t4Old
    t5Old t6Old listBytes listOff hsalign hoff hover hvalid hll_len hll_over hll_valid

/-! ## Non-vacuity.

    Discipline (#12799): every contract gets a satisfiable instance AND a
    negative control in which the same hypotheses are provably FALSE.

    The instance is HEADER-SHAPED on purpose — a long-form-1 list
    (`0xf8`, one length byte, payload 56 bytes), which is the arm a block
    header takes — so it exercises the `hll_len` / `hll_over` / `hll_valid`
    premises with their antecedents TRUE, rather than discharging them
    vacuously through a short-list prefix. -/

/-- The 58-byte long-form-1 list used by the witnesses below:
    `0xf8 0x38` followed by 56 zero payload bytes. -/
def sampleList : List (BitVec 8) :=
  (0xf8 : BitVec 8) :: (0x38 : BitVec 8) :: List.replicate 56 (0 : BitVec 8)

theorem sampleList_length : sampleList.length = 58 := by decide

/-- The long-header premises of `rlp_walk_init_entry_spec_within` are reached
    with their ANTECEDENTS TRUE at `sampleList`: the prefix is `0xf8` (not
    `< 0xf8`) and the one-byte length field fits inside the 58-byte span.  So
    the instance below is not the degenerate short-list one, in which
    `hll_len`/`hll_over`/`hll_valid` would hold vacuously. -/
theorem sampleList_long_arm_reached :
    0 < sampleList.length ∧
    (¬ BitVec.ult ((sampleList[0]'(by decide)).zeroExtend 64) (0xf8 : Word) = true) ∧
    (¬ BitVec.ult (((0x40000000 : Word) + BitVec.ofNat 64 0) + (58 : Word))
        (((0x40000000 : Word) + BitVec.ofNat 64 0) +
          (((sampleList[0]'(by decide)).zeroExtend 64 - (0xf7 : Word)) +
            signExtend12 (1 : BitVec 12))) = true) := by
  refine ⟨by decide, by decide, by decide⟩

/-- Closed instantiation of `rlp_walk_init_entry_spec_within` at the
    header-shaped long list of `sampleList`, placed at the guest input-arena
    base `0x40000000`.  Every hypothesis is discharged by `decide`, so this is
    a hypothesis-free machine triple at `GuestAddrs.rlp_walk_init` — which is
    what rules out a vacuous contract. -/
theorem rlp_walk_init_entry_instance :
    cpsTripleWithin 81 I ((0xa0000000 : Word) &&& ~~~1) initCode
      ((.x10 ↦ᵣ ((0x40000000 : Word) + BitVec.ofNat 64 0)) ** (.x11 ↦ᵣ (58 : Word)) **
        (.x12 ↦ᵣ (0 : Word)) **
        (.x5 ↦ᵣ (0 : Word)) ** (.x6 ↦ᵣ (0 : Word)) ** (.x7 ↦ᵣ (0 : Word)) **
        (.x28 ↦ᵣ (0 : Word)) ** (.x29 ↦ᵣ (0 : Word)) ** (.x30 ↦ᵣ (0 : Word)) **
        (.x31 ↦ᵣ (0 : Word)) ** (.x0 ↦ᵣ (0 : Word)) **
        (.x1 ↦ᵣ (0xa0000000 : Word)) ** bytesRegion (0x40000000 : Word) sampleList)
      (initPost (0x40000000 : Word) (0xa0000000 : Word) (58 : Word) sampleList 0
        (by decide)) :=
  rlp_walk_init_entry_spec_within
    (0x40000000 : Word) (0xa0000000 : Word) (58 : Word)
    (0 : Word) (0 : Word) (0 : Word) (0 : Word) (0 : Word) (0 : Word) (0 : Word) (0 : Word)
    sampleList 0 (by decide) (by decide) (by decide) (by decide)
    (fun _ _ => by decide) (fun _ _ => by decide)
    (fun _ _ k hk => by
      have hk1 : k < 1 := by
        refine Nat.lt_of_lt_of_le hk (Nat.le_of_eq ?_)
        decide
      have hk0 : k = 0 := by omega
      subst hk0
      decide)

/-- NEGATIVE CONTROL.  The same premises are a real restriction, not a
    tautology: at a text-segment address (`0x80000000`, which lies between
    `MEM_END = 0x78000000` and `RAM_MEM_START = 0xa0000000`) the readability
    premise `hvalid` is provably FALSE; on an empty buffer `hoff` is provably
    FALSE; and a short-list prefix provably FAILS the long-header antecedent
    that `sampleList` satisfies above. -/
theorem rlp_walk_init_entry_hyps_refutable :
    ¬ (isValidByteAccess ((0x80000000 : Word) + BitVec.ofNat 64 0) = true) ∧
    ¬ (0 < ([] : List (BitVec 8)).length) ∧
    ¬ (¬ BitVec.ult (((0xc2 : BitVec 8)).zeroExtend 64) (0xf8 : Word) = true) := by
  refine ⟨by decide, by decide, by decide⟩

end EvmAsm.Codegen.RlpWalkInitTie
