"""spec_oracle — family-agnostic core of the spec-correspondence oracle.

METHOD: docs/agents/spec-correspondence.md. That page defines the verdict
vocabulary, the `basis` grading, and when a family is a legitimate audit target.
This package implements only the mechanics.

A correspondence oracle runs a *pinned external reference* over a deterministic
corpus and records, per input, whether the reference accepts it and what it
decodes to. The result is a TSV committed to the repo and replayed in CI by
`lake exe correspondence-check <family>`, so CI needs neither Python nor
network.

WHY A COMMITTED TSV: generating it requires the reference implementation, which
for some families is an external PyPI package that CI does not install. The
checked-in TSV is what CI gates on; regeneration is a local step. That trade
only works if regeneration is byte-for-byte reproducible, hence: no `random`
module (an explicit LCG instead), a fixed corpus, and deterministic ordering.

A family supplies a `Family` (see below) and nothing else; everything here —
pins, staleness stamps, TSV format, `--out`/`--check`, dedup — is shared.
"""

from __future__ import annotations

import argparse
import pathlib
from dataclasses import dataclass
from typing import Callable, Iterable, Sequence

from . import pins

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent.parent


# --------------------------------------------------------------------------
# Deterministic randomness
# --------------------------------------------------------------------------

def lcg(seed: int):
    """Deterministic LCG (glibc constants), yielding the HIGH bits.

    The high-bit tap is load-bearing, not stylistic. The low bits of a
    power-of-two-modulus LCG have periods as short as 2 (bit 0 simply
    alternates), so `state % 256` produces a handful of distinct byte patterns
    and a generated corpus collapses under dedup — observed here as 4000
    generated cases deduplicating to ~200. Taking `state >> 15` restores the
    full period.

    (The three hand-rolled LCGs elsewhere in EvmAsm/Tests/ all sample the low
    bits and have not been audited for this.)
    """
    state = seed
    while True:
        state = (state * 1103515245 + 12345) & 0x7FFFFFFF
        yield state >> 15


# --------------------------------------------------------------------------
# Family contract
# --------------------------------------------------------------------------

@dataclass(frozen=True)
class Family:
    """One family's side of an oracle.

    `corpus` yields the inputs; `oracle` maps one input to
    `(verdict, detail, aux)` where verdict is `accept`/`reject`, detail is the
    rendered decoded value (for `accept`) or an error class (for `reject`), and
    aux is the family's optional second axis (`same`/`differs`/`-`).

    `render_input` turns an input into the TSV's first column; the Lean subject
    must parse that same form. Byte families use hex.
    """
    name: str
    corpus: Callable[[], Iterable[object]]
    oracle: Callable[[object], tuple[str, str, str]]
    reference: pins.Reference
    render_input: Callable[[object], str] = lambda b: b.hex()
    aux_label: str = "aux"


# --------------------------------------------------------------------------
# TSV
# --------------------------------------------------------------------------

def header(family: Family, version: str, specs_sha: str) -> list[str]:
    return [
        "# Generated by scripts/spec-oracle.py — DO NOT EDIT BY HAND.",
        f"# Family: {family.name}. Method: docs/agents/spec-correspondence.md",
        f"# Reference: {family.reference.describe()}",
        # The two stamps below are what make staleness detectable. The gitlink
        # SHA is readable in CI WITHOUT the submodule checked out, so the Lean
        # replay can tell that execution-specs moved and this corpus was never
        # re-validated against the new pin.
        f"# oracle-version: {version}",
        f"# execution-specs: {specs_sha}",
        "# Columns: input <TAB> accept|reject <TAB> detail <TAB> aux",
        "#   detail = rendered decoded value, or ErrorClass:message.",
        f"#   aux    = {family.aux_label}: same|differs, or - when rejected.",
    ]


def generate(family: Family) -> list[str]:
    seen: set[str] = set()
    lines: list[str] = []
    for item in family.corpus():
        key = family.render_input(item)
        if key in seen:
            continue
        seen.add(key)
        verdict, detail, aux = family.oracle(item)
        lines.append(f"{key}\t{verdict}\t{detail}\t{aux}")
    return lines


def render(family: Family) -> str:
    """Full TSV text, with pins verified. Refuses to build a corpus against a
    reference version the repo does not pin — making a wrong-version corpus
    impossible to produce rather than merely detectable afterwards."""
    version = family.reference.verify_and_describe_version()
    specs_sha = pins.execution_specs_sha(REPO_ROOT)
    return "\n".join(header(family, version, specs_sha) + generate(family)) + "\n"


# --------------------------------------------------------------------------
# CLI
# --------------------------------------------------------------------------

def default_path(family_name: str) -> pathlib.Path:
    return REPO_ROOT / "tests" / "correspondence" / f"{family_name}.tsv"


def main(registry: Sequence[Family], argv: list[str] | None = None) -> int:
    names = ", ".join(f.name for f in registry)
    ap = argparse.ArgumentParser(
        prog="spec-oracle.py",
        description="Generate a spec-correspondence oracle corpus. "
                    "Method: docs/agents/spec-correspondence.md")
    ap.add_argument("--family", required=True, help=f"one of: {names}")
    ap.add_argument("--out", type=pathlib.Path,
                    help="write the TSV here (default: tests/correspondence/<family>.tsv)")
    ap.add_argument("--check", action="store_true",
                    help="verify the committed TSV is up to date; write nothing")
    args = ap.parse_args(argv)

    match = next((f for f in registry if f.name == args.family), None)
    if match is None:
        ap.error(f"unknown family `{args.family}`; known: {names}")

    path = args.out or default_path(match.name)
    text = render(match)
    body = [line for line in text.splitlines() if not line.startswith("#")]

    if args.check:
        if not path.exists():
            print(f"error: {path} does not exist — generate it first")
            return 1
        if path.read_text(encoding="utf-8") != text:
            print(f"error: {path} is stale — regenerate with\n"
                  f"    scripts/spec-oracle.py --family {match.name} --out {path}")
            return 1
        print(f"{path}: up to date ({len(body)} records)")
        return 0

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    accepts = sum(1 for line in body if "\taccept\t" in line)
    print(f"wrote {path}: {len(body)} records "
          f"({accepts} accept, {len(body) - accepts} reject)")
    return 0
