#!/usr/bin/env python3
"""Generate v0.6.2 root-construction completeness probes.

The inputs are structurally valid, re-hashed NewPayloadRequests.  They change
one root-bearing surface while retaining the otherwise canonical witness and
BAL.  execution-specs therefore rejects each input; the guest must do so too.

This is initially a P0 red KAT generator for evm-asm-lukr5.  Keep the typed
construction here rather than byte-offset mutation: all SSZ offsets and the
payload block hash are regenerated by execution-specs.
"""

from __future__ import annotations

import argparse
import json
from dataclasses import replace
from pathlib import Path

from ethereum.crypto.hash import keccak256
from ethereum.forks.amsterdam.execution_engine.requests import ExecutionRequests
from ethereum.forks.amsterdam.execution_engine.validation_helpers import _payload_header
from ethereum.forks.amsterdam.stateless_guest import (
    deserialize_stateless_input,
    run_stateless_guest,
)
from ethereum.forks.amsterdam.stateless_host import serialize_stateless_input
from ethereum.merkle_patricia_trie import Trie, root
from ethereum_rlp import rlp
from ethereum_types.bytes import Bytes
from ethereum.state import Root


DEFAULT_FIXTURE_ROOT = (
    Path(__file__).resolve().parents[2]
    / "gen-out/eest-fixtures/tests-zkevm@v0.6.2/fixtures/fixtures"
)
WITHDRAWALS = Path(
    "blockchain_tests/for_amsterdam/shanghai/eip4895_withdrawals/withdrawals/"
    "multiple_withdrawals_same_address.json"
)
REQUESTS = Path(
    "blockchain_tests/for_amsterdam/prague/eip7685_general_purpose_el_requests/"
    "multi_type_requests/valid_multi_type_requests.json"
)


def first_valid(root: Path, rel: Path, *, wants_requests: bool = False) -> Bytes:
    for case in json.loads((root / rel).read_text()).values():
        for block in case.get("blocks", []):
            raw = block.get("statelessInputBytes")
            if raw is None:
                continue
            blob = Bytes(bytes.fromhex(raw.removeprefix("0x")))
            if bytes(run_stateless_guest(blob))[32] != 1:
                continue
            requests = deserialize_stateless_input(blob).new_payload_request.execution_requests
            if wants_requests and not any(
                len(getattr(requests, field))
                for field in (
                    "deposits", "withdrawals", "consolidations",
                    "builder_deposits", "builder_exits",
                )
            ):
                continue
            return blob
    raise ValueError(f"no suitable valid input in {root / rel}")


def with_payload(inp, payload, requests=None) -> Bytes:
    npr = inp.new_payload_request
    reqs = npr.execution_requests if requests is None else requests
    header = _payload_header(payload, npr.parent_beacon_block_root, reqs)
    payload = replace(payload, block_hash=keccak256(rlp.encode(header)))
    return serialize_stateless_input(
        replace(inp, new_payload_request=replace(
            npr, execution_payload=payload, execution_requests=reqs
        ))
    )


def cases(fixtures_root: Path) -> dict[str, tuple[Bytes, bool]]:
    request_input = deserialize_stateless_input(
        first_valid(fixtures_root, REQUESTS, wants_requests=True)
    )
    request_payload = request_input.new_payload_request.execution_payload
    assert len(request_payload.transactions) == 1
    receipt_drop = with_payload(
        request_input,
        replace(request_payload, receipts_root=root(Trie(secured=False, default=None))),
    )
    requests_drop = with_payload(
        request_input, request_payload, ExecutionRequests((), (), (), (), ())
    )

    withdrawal_input = deserialize_stateless_input(
        first_valid(fixtures_root, WITHDRAWALS)
    )
    withdrawal_payload = withdrawal_input.new_payload_request.execution_payload
    assert len(withdrawal_payload.withdrawals) >= 2
    withdrawal_drop = with_payload(
        withdrawal_input,
        replace(withdrawal_payload, withdrawals=withdrawal_payload.withdrawals[:-1]),
    )
    return {
        # This no-transaction EIP-4895 block is the positive control for the
        # body-driven withdrawal path.  It must continue to be accepted.
        "withdrawals_control_multiple_same_address": (
            serialize_stateless_input(withdrawal_input), True
        ),
        "receipt_drop_all_root_repinned": (receipt_drop, False),
        "requests_drop_all_root_repinned": (requests_drop, False),
        "withdrawal_drop_one_root_repinned": (withdrawal_drop, False),
    }


def record(blob: Bytes, expected_accept: bool) -> dict[str, str]:
    output = bytes(run_stateless_guest(blob))
    assert (output[32] == 1) == expected_accept, (
        "execution-specs disagreed with the expected root-construction verdict"
    )
    return {
        "statelessInputBytes": "0x" + bytes(blob).hex(),
        "statelessOutputBytes": "0x" + output.hex(),
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--fixtures-root", type=Path, default=DEFAULT_FIXTURE_ROOT)
    parser.add_argument("--out", type=Path, default=Path("/tmp/root-construction-forgery-probe.json"))
    parser.add_argument(
        "--forgeries-only",
        action="store_true",
        help="omit the expected-valid withdrawal control",
    )
    args = parser.parse_args()
    selected = cases(args.fixtures_root)
    if args.forgeries_only:
        selected = {name: case for name, case in selected.items() if not case[1]}
    blocks = [record(blob, expected_accept) for blob, expected_accept in selected.values()]
    args.out.write_text(json.dumps({
        "tests/kat_root_construction_forgery/probe[fork_Amsterdam-blockchain_test]": {
            "network": "Amsterdam", "blocks": blocks
        }
    }, indent=2) + "\n")
    print(f"wrote {len(blocks)} execution-specs-derived root-construction probes to {args.out}")


if __name__ == "__main__":
    main()
