/-
  EvmAsm.Tests.RlpOracleCheck

  Differential check of `EvmAsm.EL.RLP.decodeFully` against the *reference*
  RLP implementation used by execution-specs (`ethereum_rlp`, pinned by
  `execution-specs/uv.lock` at 0.1.6).

  This is the executable backing for the RLP verdicts in
  `docs/rlp-ssz-spec-correspondence.md`. Those verdicts answer "is our decoder
  stricter or looser than the reference?", and a hand-derived answer to that
  question is exactly the kind of unaudited measurement that produced the
  stale findings in #10779/#10782 — so the answer is replayed from an oracle
  instead.

  The oracle corpus is generated by `scripts/rlp-python-oracle.py` and
  committed at `tests/rlp-vectors/python-oracle.tsv`; CI replays the committed
  file and never needs Python. See the correspondence doc for why the Python
  side cannot be vendored (`ethereum_rlp` is an external PyPI package, so
  `scripts/check-spec-refs.sh` cannot reach it).

  IMPORTANT — what is and is not compared:
    * accept/reject agreement: compared, and any disagreement is a finding.
    * decoded value: compared on mutual accept.
    * rejection *reason*: NOT compared. The reference's messages describe its
      own control flow (e.g. it reports a bare byte with trailing data as
      "negative length"), which carries no obligation for a different
      implementation. Requiring reason equality would manufacture failures.

  This module deliberately imports only `EvmAsm.EL.RLP.FullDecode`, whose
  transitive closure is `Decode` and `Basic` — no Mathlib — so the check
  builds in seconds and can be gated in CI cheaply.

  Usage:
    lake exe rlp-oracle-check [path/to/python-oracle.tsv]
    lake exe rlp-oracle-check --self-test
-/

import EvmAsm.EL.RLP.FullDecode

namespace EvmAsm.Tests.RlpOracleCheck

open EvmAsm.EL.RLP

/-! ## Hex and rendering -/

private def hexDigit? (c : Char) : Option Nat :=
  if '0' ≤ c && c ≤ '9' then some (c.toNat - '0'.toNat)
  else if 'a' ≤ c && c ≤ 'f' then some (c.toNat - 'a'.toNat + 10)
  else if 'A' ≤ c && c ≤ 'F' then some (c.toNat - 'A'.toNat + 10)
  else none

/-- Parse an even-length hex string into bytes. `none` on any bad character
or an odd length. -/
def parseHex (s : String) : Option (List Byte) :=
  let cs := s.toList
  let rec go : List Char → Option (List Byte)
    | [] => some []
    | [_] => none
    | hi :: lo :: rest => do
      let h ← hexDigit? hi
      let l ← hexDigit? lo
      let tl ← go rest
      some (BitVec.ofNat 8 (h * 16 + l) :: tl)
  go cs

private def hexDigitChar (n : Nat) : Char :=
  if n < 10 then Char.ofNat ('0'.toNat + n) else Char.ofNat ('a'.toNat + (n - 10))

private def hexOfByte (b : Byte) : String :=
  let n := b.toNat
  String.ofList [hexDigitChar (n / 16), hexDigitChar (n % 16)]

private def hexOfBytes (bs : List Byte) : String :=
  bs.foldl (fun acc b => acc ++ hexOfByte b) ""

/-- Render an `RLPItem` in the same S-expression form the Python oracle emits:
bytes as `"<hex>"`, lists as `(<item> ...)`. Keeping both renderers textually
identical means the comparison needs no parser on either side. -/
partial def render : RLPItem → String
  | .bytes data => "\"" ++ hexOfBytes data ++ "\""
  | .list items => "(" ++ String.intercalate " " (items.map render) ++ ")"

/-! ## Records -/

structure Record where
  inputHex : String
  accepted : Bool
  detail : String
  /-- Reference answer to "does re-encoding the decoded value reproduce the
  input?". `some true`/`some false`; `none` when the input was rejected. -/
  reencodeSame : Option Bool := none
deriving Inhabited

private def isBlank (s : String) : Bool :=
  s.all (fun c => c == ' ' || c == '\t' || c == '\r')

/-- Parse one TSV line. Comments and blank lines yield `none`. -/
def parseLine (rawLine : String) : Option Record :=
  -- Drop CRs so a CRLF checkout does not corrupt the last field.
  let line := String.ofList (rawLine.toList.filter (· != '\r'))
  if line.startsWith "#" || line.isEmpty || isBlank line then none
  else
    -- NOTE: an empty input renders as an empty first field, so splitting must
    -- keep leading empties (`String.splitOn` does).
    let reenc (s : String) : Option Bool :=
      if s == "same" then some true else if s == "differs" then some false else none
    match line.splitOn "\t" with
    | [h, v, d, r] =>
        some { inputHex := h, accepted := v == "accept", detail := d, reencodeSame := reenc r }
    | [h, v, d] => some { inputHex := h, accepted := v == "accept", detail := d }
    | [h, v] => some { inputHex := h, accepted := v == "accept", detail := "" }
    | _ => none

inductive Outcome where
  /-- Both sides agree (reject, or accept with the same value). -/
  | agree
  /-- We reject what the reference accepts: false-rejects on valid data. -/
  | stricter (input : String) (expected : String)
  /-- We accept what the reference rejects: a soundness finding. -/
  | looser (input : String) (got : String) (why : String)
  /-- Both accept, different decoded values. -/
  | valueMismatch (input : String) (expected got : String)
  /-- Both accept and agree on the value, but the encoders disagree about
  whether re-encoding reproduces the input. -/
  | encodeMismatch (input : String) (expected got : Bool)
deriving Inhabited

def classify (r : Record) : Outcome :=
  match parseHex r.inputHex with
  | none => .agree  -- unparseable line; counted separately by the caller
  | some bs =>
    match decodeFully bs, r.accepted with
    | none, false => .agree
    | some item, true =>
      let got := render item
      if got != r.detail then .valueMismatch r.inputHex r.detail got
      else
        -- Encoder direction: does `EL.RLP.encode` round-trip exactly where the
        -- reference's `rlp.encode` does?
        match r.reencodeSame with
        | none => .agree
        | some expected =>
          let ours := encode item == bs
          if ours == expected then .agree
          else .encodeMismatch r.inputHex expected ours
    | none, true => .stricter r.inputHex r.detail
    | some item, false => .looser r.inputHex (render item) r.detail

structure Tally where
  total : Nat := 0
  agree : Nat := 0
  stricter : Nat := 0
  looser : Nat := 0
  valueMismatch : Nat := 0
  encodeMismatch : Nat := 0
deriving Inhabited

/-! ## Driver -/

def runRecords (rs : List Record) (maxReport : Nat := 12) : Tally × List String := Id.run do
  let mut t : Tally := {}
  let mut msgs : List String := []
  for r in rs do
    t := { t with total := t.total + 1 }
    match classify r with
    | .agree => t := { t with agree := t.agree + 1 }
    | .stricter inp exp =>
        t := { t with stricter := t.stricter + 1 }
        if t.stricter ≤ maxReport then
          msgs := msgs ++ [s!"  STRICTER  input={inp}  reference accepted {exp}, we rejected"]
    | .looser inp got why =>
        t := { t with looser := t.looser + 1 }
        if t.looser ≤ maxReport then
          msgs := msgs ++ [s!"  LOOSER    input={inp}  reference rejected ({why}), we accepted {got}"]
    | .valueMismatch inp exp got =>
        t := { t with valueMismatch := t.valueMismatch + 1 }
        if t.valueMismatch ≤ maxReport then
          msgs := msgs ++ [s!"  VALUE     input={inp}  reference={exp}  ours={got}"]
    | .encodeMismatch inp exp got =>
        t := { t with encodeMismatch := t.encodeMismatch + 1 }
        if t.encodeMismatch ≤ maxReport then
          msgs := msgs ++ [s!"  ENCODE    input={inp}  reference re-encode-same={exp}  ours={got}"]
  return (t, msgs)

def loadRecords (path : System.FilePath) : IO (List Record) := do
  let contents ← IO.FS.readFile path
  return contents.splitOn "\n" |>.filterMap parseLine

/-! ## Staleness guard

A committed corpus can silently keep describing a reference version the repo no
longer uses: every leg of the check would keep passing while measuring the wrong
thing — this checker's own failure mode, one level up. The generator stamps the
`ethereum-rlp` version and the `execution-specs` gitlink SHA into the header;
here we verify the SHA still matches the superproject.

Why the SHA and not `uv.lock`: the gitlink is readable from the superproject
tree **without the submodule checked out**, which is the situation in CI. Since
the `ethereum-rlp` pin lives in `execution-specs/uv.lock`, any change to it
necessarily moves this SHA — so an unchanged SHA is sufficient evidence that the
pinned reference has not moved under the corpus. -/

private def headerValue (lines : List String) (key : String) : Option String :=
  lines.findSome? fun l =>
    let pfx := "# " ++ key ++ ": "
    if l.startsWith pfx then some ((l.drop pfx.length).trimAscii.toString) else none

/-- The `execution-specs` gitlink SHA recorded in the superproject tree. -/
def recordedSpecsSha : IO (Option String) := do
  let out ← IO.Process.output { cmd := "git", args := #["ls-tree", "HEAD", "execution-specs"] }
  if out.exitCode != 0 then return none
  -- Format: "160000 commit <sha>\texecution-specs"
  match (out.stdout.splitOn " ").getLast? with
  | none => return none
  | some tl => return some ((tl.splitOn "\t").headD "" |>.trimAscii.toString)

/-- Verify the corpus still describes the pinned reference. Returns an error
message, or `none` when the pins agree (or cannot be read here). -/
def checkPins (path : System.FilePath) : IO (Option String) := do
  let contents ← IO.FS.readFile path
  let lines := contents.splitOn "\n" |>.take 12
  let some oracleVer := headerValue lines "oracle-version"
    | return some "corpus header has no `# oracle-version:` stamp — regenerate it"
  let some stampedSha := headerValue lines "execution-specs"
    | return some "corpus header has no `# execution-specs:` stamp — regenerate it"
  IO.println s!"  pinned reference {oracleVer}, execution-specs {stampedSha.take 12}"
  match ← recordedSpecsSha with
  | none =>
      IO.println "  note: could not read the execution-specs gitlink; pin not verified here"
      return none
  | some actual =>
      if actual == stampedSha then return none
      else return some s!"execution-specs moved: corpus was generated at {stampedSha.take 12}, \
repo now pins {actual.take 12}. The `ethereum-rlp` pin lives in that submodule's uv.lock, so the \
committed corpus may describe a reference this repo no longer uses. Regenerate it \
(scripts/rlp-python-oracle.py) and re-check."

/-- Planted-violation self-check. A gate that cannot demonstrate catching a
violation is itself unaudited (same discipline as
`scripts/check_spec_refs.py --self-test`). -/
def selfTest : IO UInt32 := do
  -- `820102` is a valid 2-byte string; `8100` is non-canonical and rejected.
  let planted : List Record :=
    [ { inputHex := "820102", accepted := true,  detail := "\"0102\"" }   -- agrees
    , { inputHex := "8100",   accepted := true,  detail := "\"00\"" }     -- we are stricter
    , { inputHex := "820102", accepted := false, detail := "Planted" }    -- we are looser
    , { inputHex := "820102", accepted := true,  detail := "\"ffff\"" }   -- value mismatch
      -- valid + correct value, but claims re-encoding does NOT reproduce it
    , { inputHex := "820102", accepted := true,  detail := "\"0102\"",
        reencodeSame := some false }
    ]
  let (t, msgs) := runRecords planted
  for m in msgs do IO.println m
  let comparisonOk :=
    t.stricter == 1 && t.looser == 1 && t.valueMismatch == 1
      && t.encodeMismatch == 1 && t.agree == 1
  unless comparisonOk do
    IO.println s!"self-test: FAILED (comparison) — {repr (t.agree, t.stricter, t.looser, t.valueMismatch, t.encodeMismatch)}"
    return 1
  -- The staleness guard gets the same treatment: plant a moved gitlink SHA and
  -- a missing stamp, and require both to be caught. A guard that silently
  -- passes on a stale corpus would let every other leg keep reporting
  -- agreement while measuring the wrong reference.
  let tmp ← IO.FS.createTempDir
  let good := "# oracle-version: ethereum-rlp==0.1.6\n\
               # execution-specs: " ++ (← recordedSpecsSha).getD "unknown" ++ "\n\
               820102\taccept\t\"0102\"\tsame\n"
  let stale := "# oracle-version: ethereum-rlp==0.1.6\n\
                # execution-specs: 0000000000000000000000000000000000000000\n\
                820102\taccept\t\"0102\"\tsame\n"
  let noStamp := "# execution-specs: deadbeef\n820102\taccept\t\"0102\"\tsame\n"
  let write (name content : String) : IO System.FilePath := do
    let p := tmp / name; IO.FS.writeFile p content; return p
  let goodOk := (← checkPins (← write "good.tsv" good)).isNone
  let staleCaught := (← checkPins (← write "stale.tsv" stale)).isSome
  let noStampCaught := (← checkPins (← write "nostamp.tsv" noStamp)).isSome
  IO.FS.removeDirAll tmp
  if goodOk && staleCaught && noStampCaught then
    IO.println "self-test: OK — planted stricter/looser/value/encode findings all detected, \
and the staleness guard catches a moved execution-specs pin and a missing stamp \
without flagging a current corpus"
    return 0
  else
    IO.println s!"self-test: FAILED (pin guard) — \
{repr (goodOk, staleCaught, noStampCaught)} (expected (true, true, true))"
    return 1

def defaultOraclePath : System.FilePath := "tests/rlp-vectors/python-oracle.tsv"

def main (args : List String) : IO UInt32 := do
  if args.contains "--self-test" then
    return (← selfTest)
  let path : System.FilePath :=
    match args.filter (!·.startsWith "--") with
    | p :: _ => p
    | [] => defaultOraclePath
  unless ← path.pathExists do
    IO.eprintln s!"error: oracle corpus not found at {path}"
    IO.eprintln "Generate it with:"
    IO.eprintln "  scripts/rlp-python-oracle.py --out tests/rlp-vectors/python-oracle.tsv"
    return 2
  let rs ← loadRecords path
  if rs.isEmpty then
    IO.eprintln s!"error: no records parsed from {path}"
    return 2
  IO.println s!"rlp-oracle-check: {rs.length} records from {path}"
  -- Staleness guard runs before the comparison: a corpus that describes the
  -- wrong reference makes the agreement figure meaningless, so a green
  -- comparison must not be reported alongside a stale pin.
  match ← checkPins path with
  | some err =>
      IO.eprintln s!"error: {err}"
      return 1
  | none => pure ()
  let (t, msgs) := runRecords rs
  IO.println s!"  agree          {t.agree}"
  IO.println s!"  stricter       {t.stricter}   (reference accepts, EL.RLP rejects)"
  IO.println s!"  looser         {t.looser}   (reference rejects, EL.RLP accepts)"
  IO.println s!"  value mismatch {t.valueMismatch}"
  IO.println s!"  encode mismatch {t.encodeMismatch}   (EL.RLP.encode vs reference rlp.encode)"
  unless msgs.isEmpty do
    IO.println ""
    IO.println "findings (first few of each class):"
    for m in msgs do IO.println m
  if t.stricter == 0 && t.looser == 0 && t.valueMismatch == 0 && t.encodeMismatch == 0 then
    IO.println ""
    IO.println "RESULT: EL.RLP.decodeFully/encode agree with ethereum_rlp 0.1.6 on every record."
    return 0
  else
    IO.println ""
    IO.println "RESULT: divergence — see docs/rlp-ssz-spec-correspondence.md before changing either side."
    return 1

end EvmAsm.Tests.RlpOracleCheck
